AppFlowy-IO/AppFlowy

Brewfile, Makefile, scripts/makefile/env.toml
unpinned the protobuf version, need to make sure that's OK
=> Use brewfile

backend/scripts/database/init_database.sh
sqlx-cli 0.5.5 can not be installed on latest nightly Rust, which outputs errors like:
```
error: cannot find derive macro `Clap` in this scope
error: cannot find attribute `clap` in this scope
```
sqlx-cli 0.5.6 fixed it.
The PR use `^0.5.6` to retrive 0.5.6 <= ver < 0.6.0, while there should not be a very very tight requirement over sqlx-cli version.
=> Bump sqlx-cli version to fix its compiling error when installing

backend/Dockerfile, backend/src/entities/token.rs, backend/src/service/user/logged_user.rs
solving ticket #13, https://github.com/AppFlowy-IO/appflowy/issues/62
docker backend should be built with that arguments:
```bash
docker build -f backend/Dockerfile
```
=> fix backend build

doc/BUILD_ON_WINDOWS.md, frontend/Makefile.toml, frontend/app_flowy/.vscode/tasks.json, frontend/scripts/build_sdk.cmd, frontend/scripts/makefile/desktop.toml, frontend/scripts/makefile/env.toml
1. doc\BUILD_ON_WINDOWS.md
- add command for building development version
2. .vscode\tasks.json
- Enable vscode to launch debug session on windows
3. frontend\scripts\makefile\env.toml
- Fix "Command : dart not found." on windows
4. frontend\Makefile.toml
- Change profile name "env.development-windows" to "env.development-desktop-windows-x86"
=> [Build] Enhance windows build instruction and cargo make scripts

doc/BUILD_ON_LINUX.md
When running Step 3 `flutter channel dev` got:
```
Missing "unzip" tool. Unable to extract Dart SDK.
Consider running "sudo apt-get install unzip".
```
Building on Ubuntu 20.04
=> Add unzip to requirements

doc/BUILD_ON_WINDOWS.md, frontend/scripts/makefile/env.toml
1. doc\BUILD_ON_WINDOWS.md
2. frontend\scripts\makefile\env.toml
- break down install_targets task into 3 platform specific tasks
- only install necessary targets for specfic platform
=> [Instruction] Enhance BUILD_ON_WINDOWS.md to remove choco dependency

README.md
Fixes a typo found in license badge.
=> docs: s/APGL/AGPL/

README.md
Added temporary instructions for how to install on Linux and Windows
Added references to the Linux and Windows build instructions
Please note that these instructions refer to a AppFlowy-Linux.tar.gz file in the Releases section. This file is not available in that section yet. I have created the file, but do not have the rights to add it to that section. Please tell me how to proceed.
P.S. The file that I created had the latest bug fixes and is in Debug mode. Remind me when we talk about this to create a Release file when the 0.0.2 tag.
=> Improved the main README.md

frontend/app_flowy/.vscode/tasks.json, frontend/scripts/build_sdk.sh
Build system will now detect OS and pass it down to build_sdk.sh.
build_sdk.sh will now automatically choose the correct cargo-make command line based on
=> Automate build sdk sh

frontend/app_flowy/lib/workspace/presentation/widgets/pop_up_action.dart
Fixes #153 , the ActionCell height was too short and resulted in portions of a character getting cut-off
=> Increased height of ActionCell

frontend/app_flowy/packages/flowy_infra_ui/lib/src/flowy_overlay/list_overlay.dart
removed the SizedBox. Leaving the size to adjust automatically depending on the footer's content.
Fixes #141
=> Fix application menu size

frontend/app_flowy/pubspec.lock, frontend/app_flowy/pubspec.yaml
This PR just updates the pubspec files to use device_info_plus version 3.2.1, which has been fixed to support Linux and Windows so that the debug info button can work on those platforms.
=> Update device_info_plus to version 3.2.1

frontend/rust-lib/dart-ffi/Cargo.toml, frontend/rust-lib/dart-ffi/src/lib.rs
Reverts AppFlowy-IO/appflowy#282. Because of the FLOWY_SDK.get() may return None.
=> Revert "feat: use once_cell for perf."

frontend/scripts/docker-buildfiles/Dockerfile
Hi, based on #296, I debugged and found that the path is using the `0.0.2` version while the last tag is `0.0.3`. So this PR aims to fix that. 
Signed-off-by: Lays Rodrigues <laysrodriguessilva@gmail.com>
=> fix appflowy version in dockerfile

commitlint.config.js
My previous PR have a commit prefix (`chore: ...`) that doesn't follow `commitlint`, so I add some more (based on https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) and sort the list alphabetically.
=> Add some more commit prefixes

frontend/scripts/docker-buildfiles/Dockerfile, frontend/scripts/docker-buildfiles/docker-compose.yml
Fix error:
```
❌ The protoc-gen-dart was not installed correctly.
✅ You can fix that by adding "dart pub global activate protoc_plugin" to your shell's config file.(.bashrc, .bash, etc.)
```
Also mount other required volumes in docker-compose
=> Fix docker build

frontend/scripts/docker-buildfiles/Dockerfile, frontend/scripts/docker-buildfiles/docker-compose.yml
Previous image was 7.69GB which is somewhat heavy. Now the resulting image is 1.20GB thanks to multi-stage builds.
=> Reduce docker image size by using docker multi-stage build

frontend/app_flowy/lib/workspace/presentation/stack_page/doc/widget/banner.dart
Fixed DocBanner widget overflow reported in issue #354 
I used the FittedBox with a BoxFit.scaleDown to preserve the aspect of the feature. Now the FittedBox by the Center Alignment, removing the necessity of Alignment inside of Row.
=> fix: DocBanner overflow issue: #354

commitlint.config.js
Added types: build, feature
no longer checks subject's case
now forces a leading blank before body (This is required by Github)
Increased body length to 200
=> Adjust commitlint config

frontend/app_flowy/lib/workspace/domain/page_stack/page_stack.dart, frontend/app_flowy/lib/workspace/infrastructure/markdown/src/delta_markdown_decoder.dart, frontend/app_flowy/lib/workspace/infrastructure/markdown/src/inline_parser.dart, frontend/app_flowy/lib/workspace/presentation/widgets/emoji_picker/src/config.dart, frontend/app_flowy/lib/workspace/presentation/widgets/emoji_picker/src/emoji_picker.dart, frontend/app_flowy/lib/workspace/presentation/widgets/emoji_picker/src/emoji_picker_builder.dart, frontend/app_flowy/lib/workspace/presentation/widgets/menu/menu.dart, frontend/app_flowy/packages/flowy_infra_ui/flowy_infra_ui_platform_interface/lib/flowy_infra_ui_platform_interface.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/src/flowy_overlay/flowy_overlay.dart, frontend/app_flowy/web/index.html
Found via `codespell -q 3 -S *.svg,./frontend/app_flowy/assets/translations -L bloc,crate,homestate,nd,ot,ser`
=> Fix various typos

.github/workflows/ci.yaml, .github/workflows/dart_test.yml, .github/workflows/release.yml, .github/workflows/rust_lint.yml, .github/workflows/rust_test.yml
1. Speed up dart and rust test workflows. And update the rust cache key.
2. Specify the rust version at all workflows.
=> chore: use actions-cache to speed up dart & rust test.

frontend/app_flowy/lib/workspace/application/view/view_bloc.dart
Fixes the bug outlined here: https://github.com/AppFlowy-IO/AppFlowy/issues/143#issue-1079095055
Added call to update view after the page has been deleted (line 54)
=> fixes #143: consecutive deletes to a doc

frontend/app_flowy/lib/core/frameless_window.dart, frontend/app_flowy/lib/workspace/application/home/home_bloc.dart, frontend/app_flowy/lib/workspace/application/menu/menu_bloc.dart, frontend/app_flowy/lib/workspace/presentation/home/home_stack.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/menu.dart, frontend/app_flowy/lib/workspace/presentation/home/navigation.dart, frontend/app_flowy/macos/Runner/MainFlutterWindow.swift
This PR is implementing a frameless window for AppFlowy on macOS.
**Before**
Normal State:
Collapsed State:
**After**
Normal State:
Collapsed State:
- Hide the title bar of WindowDelegate in Swift
- Implement movable area in Flutter
- Send messages through **MethodChannel** to Cocoa to move the window
- Handle collapsing state in Flutter by moving the state from *MenuBloc* to *HomeBloc*
=> feat: frameless window for mac

frontend/app_flowy/lib/workspace/presentation/home/menu/app/header/add_button.dart, frontend/app_flowy/lib/workspace/presentation/plugins/doc/src/widget/toolbar/toolbar_icon_button.dart, frontend/app_flowy/packages/flowy_infra/lib/text_style.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/widget/buttons/primary_button.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/widget/buttons/secondary_button.dart
This quick PR just fixes a few issues that I noticed when I built and ran AppFlowy on my computer. These include:
- Setting the color of the add page icon to the theme `iconColor`, which changes with light mode/dark mode.
- Setting the color of the toolbar buttons in the workspace to the theme `iconColor`, which changes with light mode/dark mode.
- Changing the background of the toolbar buttons in the workspace to the theme `hover`, which changes with light mode/dark mode.
- Setting the font style of the primary and secondary button text to the `Btn` text style.
- Changing the size of the `Btn` text style to `s16` from `s14`, as the text seemed a little small compared with the button size.
=> Fix various small issues

.github/workflows/ci.yaml, .github/workflows/release.yml, frontend/Makefile.toml, frontend/app_flowy/macos/Runner.xcodeproj/project.pbxproj, frontend/scripts/build_sdk.sh
This PR is changing the build script for the people who use the M1 mac to build the native arm64 app on their MacBook.
**Notice:**
If you have built the x86 version of AppFlowy on your M1 mac, please follow these steps to clean your environment:
- Uninstall the CocoaPods installed by gem:
```
sudo gem uninstall cocoapods
```
- Install the CocoaPods with HomeBrew:
```
brew install cocoapods
```
- Run `flutter clean` in `AppFlowy/frontend/app_flowy`
- Rebuild the AppFlowy with the [official doc](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-macos)
=> feat: native support for m1 mac

frontend/.vscode/launch.json, frontend/.vscode/tasks.json
Fixed the "AF: Build Dart Only" launch configuration.
Renamed the "Flutter Pub" task to "Flutter Pub Get" so it's clearer
Fixed the default build task
=> fix: Fix the launch configuration and tasks

frontend/.vscode/launch.json, frontend/Makefile.toml, frontend/app_flowy/macos/Runner.xcodeproj/project.pbxproj
1. fix the error when building the `app_flowy(profile)` task.
2. build the active arch only when building the `Profile scheme`.
=> fix: fail to execute profile task in VSCode

.github/workflows/ci.yaml, .github/workflows/dart_lint.yml, .github/workflows/dart_test.yml, .github/workflows/release.yml, .github/workflows/rust_lint.yml, frontend/Makefile.toml
fix: Fix Linux build on x86_64.  The build script currently uses 'uname -m' which on most Linux systems returns 'x86_64'.
=> fix : fix linux build on x86_64

.githooks/commit-msg, .githooks/pre-commit, .githooks/pre-push, .husky/commit-msg, package.json
Our current implementation of githooks and Husky did not work. They did nothing.
My research showed that Husky is a JS script tool, and didn't really fit for our needs. So I removed it.
Native githooks will work fine, but require one line of code to be executed, I will document this in the Environment Setup documentation.
I enabled all of the hooks that @appflowy had setup, they all work now.  However, I think that the pre-push hook might be too much and might need to be removed.
CommitLint also now works, I will add the documentation for that too.
=> Fix githooks and remove Husky

frontend/app_flowy/lib/workspace/presentation/home/home_screen.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/menu.dart
AppFlowy will open the view that the last time the user opened it. But the _buildHomeMenu  function will get called when AppFlowy's screen resizes. So we only set the latestOpenView when it's null.
=> fix: open the latest view when AppFlowy launch.

frontend/app_flowy/pubspec.yaml
when I launch build_runner, it displays this :
``` 
*  Executing task: flutter pub run build_runner build --delete-conflicting-outputs 
[INFO] Generating build script...
[INFO] Generating build script completed, took 414ms
[INFO] Precompiling build script......
[WARNING] ../../../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/freezed-2.0.4/lib/src/tools/type.dart:27:16: Error: The getter 'imports' isn't defined for the class 'PrefixElement'.
- 'PrefixElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/analyzer-3.4.1/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'imports'.
return e.imports.any((l) {
^^^^^^^ …
```
=> fix:  flutter build error - The getter 'imports' isn't defined for the class 'PrefixElement' 

.github/workflows/rust_lint.yml, frontend/rust-lib/flowy-grid/src/entities/cell_entities.rs, frontend/rust-lib/flowy-grid/src/entities/field_entities.rs, frontend/rust-lib/flowy-grid/src/entities/row_entities.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/date_type_option/date_type_option_entities.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/selection_type_option/select_option.rs, frontend/rust-lib/flowy-grid/tests/grid/block_test/script.rs
Quick fix for the rust_lint GitHub workflow, since I noticed that the tests were failing due to invalid YAML syntax.
=> Fix YAML syntax in rust_lint workflow

frontend/scripts/docker-buildfiles/docker-compose.yml
When I run `docker-compose up` command I'm getting the following error:
```
app_1  | (app_flowy:1): dbind-WARNING **: 20:06:32.776: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
app_1  | libGL error: MESA-LOADER: failed to retrieve device information
app_1  | [xcb] Unknown sequence number while processing queue
app_1  | [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
app_1  | [xcb] Aborting, sorry about that.
app_1  | app_flowy: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
appflowy_app_1 exited with code 139 …
```
=> Small fixes for `docker-compose up` command's error and warning

frontend/app_flowy/lib/plugins/grid/presentation/widgets/footer/grid_footer.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/grid_header.dart
Both New Column and New Row buttons now have the same background shade as other column headers on hover
=> fix: fixed hover color #685

.github/workflows/ci.yaml, .github/workflows/dart_lint.yml, .github/workflows/dart_test.yml
Noticed #359 issue, and try to fix. Then, it comes here.
Since #391 uses actions-caches, it speed up a lot. Even better, we could respect the cache of the dependency, it may save a lot of time.
|  **Before**   | **After**  |
|  ----  | ----  |
| ![image](https://user-images.githubusercontent.com/7845507/184188918-b89f0e2b-015d-4a42-b349-81ffeda70767.png)  | ![image](https://user-images.githubusercontent.com/7845507/184189027-e69bce77-f347-4be1-8a6b-a4f4a634ec02.png) |
| ![image](https://user-images.githubusercontent.com/7845507/184189327-963fbfa1-66df-4c09-b860-a474a8534e1f.png) | ![image](https://user-images.githubusercontent.com/7845507/184190124-a96013ac-8c40-4263-b554-e0912c67a189.png) |
Hope it may help. If the ci & dart job works well, I could optimize others deeply.
=> chore: speed up ci by respecting the cargo deps cache

frontend/app_flowy/packages/appflowy_editor/README.md, frontend/app_flowy/packages/appflowy_editor/documentation/customizing.md, frontend/app_flowy/packages/appflowy_editor/documentation/testing.md
Initial update as part of an editorial review of the content of the readme files of this project.  Some notes:
• I would suggest adding a short example as to what you might do with an empty editor once it's been instantiated and also showing an actual sample json structure for instantiating the editor, even if it's very simple.
• The Glossary Heading that says to refer to the API documents should provide a link, but I wasn't sure where this location should be.
=> doc: Editorial updates to the ReadMe for AppFlowyEditor

frontend/app_flowy/lib/plugins/grid/application/cell/select_option_editor_bloc.dart
An empty create option sometimes appears in grid and kanban select/multi-select. To reproduce, type something into the text box, clear it, and then choose an option.
https://user-images.githubusercontent.com/71320345/189468722-56fbebab-7b61-457f-9bd6-263d391f82ec.mp4
=> fix: empty create option in select/multi-select properties

frontend/app_flowy/lib/plugins/grid/application/field/type_option/multi_select_type_option.dart, frontend/app_flowy/lib/plugins/grid/application/field/type_option/single_select_type_option.dart
When using the edit property menu (from the grid header or the grid settings buttons at the top) to edit single or multi-select properties, identical options can be created, as shown below:
https://user-images.githubusercontent.com/71320345/189540529-cf73f8f2-aa7d-4316-8647-29376186cf1d.mp4
=> fix: prevent select property from having identical options

frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/number.dart
=> fix: add missing padding between number format list and filter bar

frontend/app_flowy/lib/workspace/application/appearance.dart
#700 
If case before in `readLocaleWhenAppLaunch` and `setLocale` stopped `AppearanceSettingModel` from loading the saved locale during opening load.
1. Go to `Settings` and then `Language`
2. Pick any language, let's say `Bahasa`
3. Close and reopen the app
4. The app should now load with `Bahasa` as the starting language
=> fix: Fixed locale bug when oppening - 

frontend/app_flowy/lib/workspace/presentation/home/home_layout.dart, frontend/app_flowy/lib/workspace/presentation/home/home_screen.dart
This PR modifies the home layout to show the sidebar menu as an overlapping drawer on screens at the tabletPortrait breakpoint.
Fixes #796
=> feat: show menu as overlapping drawer on small screens

frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/assets/translations/es-VE.json, frontend/app_flowy/assets/translations/fr-FR.json, frontend/app_flowy/assets/translations/id-ID.json, frontend/app_flowy/assets/translations/ru-RU.json, frontend/app_flowy/assets/translations/zh-CN.json, frontend/app_flowy/assets/translations/zh-TW.json, frontend/app_flowy/lib/plugins/grid/application/cell/date_cal_bloc.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/date_cell/date_editor.dart, frontend/rust-lib/flowy-grid/src/services/field/type_options/date_type_option/date_tests.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/date_type_option/date_type_option.rs
- I think one o'clock is better than noon for time format hinting
- the cell's time should show/hide immediately according to the switch
- I added autofocus to the text field when the switch is toggled
- prevent the date from disappearing when the time input is invalid. (see below)
- prevent the time field from showing a whitespace at the front after submitting (see below). The cell's date and time spacing is actually reduced by one space as well, but it can be re-added separately.
https://user-images.githubusercontent.com/71320345/190865573-0af932d2-135b-47ea-9139-f450d9bbaecc.mp4
=> fix: some improvements for when including time in a date cell

frontend/app_flowy/packages/flowy_infra/lib/theme.dart
This fixes the blue tint, which is used in single/multi-select option labels and is currently the same color as aqua.The design doc seems to have made a mistake. I used a screen color picker to get the color, and have tested on the other colors beforehand to make sure that the code is correct.
=> Fix blue tint

frontend/app_flowy/lib/plugins/grid/application/cell/select_option_editor_bloc.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/text_field.dart
https://user-images.githubusercontent.com/71320345/191922686-d486dcaf-893e-4f8a-9974-92237ed05092.mp4
The new logic is as follows:
If there aren't any matches, then create it.
If there is an unselected option that matches, then select it and clear filter.
If there is a selected option that matches, then clear filter.
The logic works as intended, but it seems messy. How can I make it better?
=> grid: fix pressing enter on an option that already exists recreates it

frontend/scripts/install_dev_env/install_macos.sh
It's natural for me to hit ENTER at a prompt when I assume that the default response is to do the less-dangerous thing (which in this case, I would assume to be tied to the `N` response).  But if I do that, the script gets lots of errors.
So I'm adding a default of `N` to the prompt for installing Rust.
Also, adding an `|| exit 1` to the `cd` so that IDE/shellcheck warnings go away.
=> feat: make Rust installation prompt default to No

frontend/app_flowy/lib/workspace/presentation/home/home_screen.dart, frontend/app_flowy/lib/workspace/presentation/home/home_stack.dart
This PR changes `_buildHomeMenu` to check if the plugin is blank before setting the view to the last opened view.
Fixes #856
=> fix: only open the last opened view if plugin is blank

frontend/scripts/docker-buildfiles/Dockerfile
When running in Docker, the error described in #1022 appeared. This commit fixes that by adding libkeybinder3 as a dependency installed in the final container.
=> Add libkeybinder3 to Dockerfile

frontend/app_flowy/lib/workspace/presentation/settings/widgets/settings_appearance_view.dart
Fix the toggle not updating live in the settings UI when switching between Light/Dark mode
=> fix: Theme toggle not updating UI

frontend/app_flowy/lib/plugins/doc/document.dart, frontend/app_flowy/lib/workspace/presentation/widgets/pop_up_action.dart
This patch does three things: 1. remove the padding between the icon and the text if there is no icon, 2. align the content of each row at the center along the crossaxis, and 3. align the dropdown menu with the right edge of the share button. The extra spacing to the right is not fixed yet and is tracked at #1206. Oh and changed the color of the button too!
Before:
After:
=> fix: improve look of share button dropdown menu

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_cell.dart
This fixes #1186 .
`spacing` attribute of the `Wrap` being used in `SelectOptionWrap` seems to be causing the issue. I have just removed the use of the `spacing` from the wrap and instead I have used a `Padding` to provide spacing to the children of the `Wrap`.
=> fix: Extra spacing in multiselect cell

.github/workflows/ci.yaml, .github/workflows/dart_lint.yml, .github/workflows/dart_test.yml, .github/workflows/release.yml, .github/workflows/rust_coverage.yml, .github/workflows/rust_lint.yml, .github/workflows/rust_test.yml, frontend/rust-lib/lib-log/src/lib.rs, frontend/rust-lib/rust-toolchain.toml, frontend/scripts/makefile/tests.toml, shared-lib/rust-toolchain.toml
Implements #1169.
- Bumped `rustc` to `2022-04-07`, that is version `1.60.0` as that version introduces coverage instrumentation. These bumps are in the `rust-toolchain.toml` files in the projects and also in the CI workflow files.
- In `frontend/scripts/makefile/tests.toml`, created two `cargo make` tasks (among other supporting ones):
- `get_test_coverage` - Tests both projects with `-C instrument-coverage` flag with `rustc`. Further, runs `grcov` to create an HTML report of the total coverage. The report is stored in each project's directory under `target/coverage-html/`, main HTML file being `index.html`.
- `get_ci_test_coverage` - Tests the same way as above, but generates `lcov` test reports instead of human readable HTML. These can be integrated in CI using various actions on the …
=> Code coverage for Rust

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/date_cell/date_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/date.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/number.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/select_option.dart
- Add separator in edit property for date and number properties
- Hide "Add option button" when the input field is shown. Also changed text color of "Options"
- Increase size of appflowy popover for date editor because it gets cut off when "include time" is enabled
=> fix: several grid ui improvements

.github/workflows/release.yml
This PR adds the ability to create easy to install .deb packages for Linux as mentioned in the issue https://github.com/AppFlowy-IO/AppFlowy/issues/1303.
Following changes adds app_flowy symlink to /usr/bin for opening the app via terminal or command line and as well as a desktop entry in applications drawer using postinst script.
All of the associated libraries, files, symlinks and desktop entry is removed using postrm script.
=> feat: create deb package for linux (#1303)

frontend/app_flowy/lib/plugins/grid/presentation/widgets/common/text_field.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/select_option.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/widget/rounded_input_field.dart
fixes [#1368](https://github.com/AppFlowy-IO/AppFlowy/issues/1368)
=> Close popover on text field tap

frontend/app_flowy/lib/core/network_monitor.dart, frontend/app_flowy/pubspec.lock, frontend/app_flowy/pubspec.yaml, frontend/rust-lib/flowy-net/src/entities/network_state.rs
Networktype returns nulls when the connectivity result is vpn resulting to null safety issues. Implemented a case for when the connectivity result is vpn to resolve this issue.
=> fix: NetworkType null safety issues

frontend/app_flowy/windows/runner/Runner.rc
Name of the application was displayed as ``A new flutter project`` in Windows Taskbar when right clicking on the app.
This PR fixes issue #1416 by setting the ``FileDescription`` property to application name.
In any case the description doesn't change for any existing users even after reinstalling. Manually deleting the app_flowy windows registry keys from ``HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\Shell\MuiCache`` fixes the issue.
=> fix: Application name in Windows taskbar.

frontend/app_flowy/lib/plugins/document/document.dart, frontend/app_flowy/lib/user/presentation/sign_up_screen.dart, frontend/app_flowy/lib/user/presentation/skip_log_in_screen.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/app/create_button.dart, frontend/app_flowy/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/style_widget/button.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/style_widget/icon_button.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/widget/rounded_button.dart
The difference is subtle, but notice how the hover color only flashes when the mouse is exiting the button. This patch also defers default font properties of the TextButtons from the child FlowyText if needed.
main:
https://user-images.githubusercontent.com/71320345/202879622-02dfcbd7-7125-497d-b436-915283832b67.mp4
this patch:
https://user-images.githubusercontent.com/71320345/202879633-fa40799e-4054-4044-be8c-1a9c0f53751b.mp4
=> fix: fix colors for buttons and allow more customization

frontend/app_flowy/lib/workspace/presentation/home/home_stack.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/app/create_button.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/style_widget/extension.dart
(sidebar color changed in the screenshot so outlines are visible) 
main:
this patch:
=> fix: divider colors for top and bottom border widgets

frontend/app_flowy/packages/flowy_infra/lib/theme.dart
The button text in a widget that has the blue fill color should be white instead of black in dark mode.
Also, sorry for the typo on the commit message
=> fix: onPrimary and onPrimaryContainer colors

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/extension.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/text_field.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/common/text_field.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/select_option.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/widget/rounded_input_field.dart
UI changes: 
|before | after |
|--- | --- |
| ![image](https://user-images.githubusercontent.com/71320345/203902419-764b61de-a9d9-4048-925d-210b0f86b8e6.png) | ![image](https://user-images.githubusercontent.com/71320345/203901281-33eef71b-f938-4bdc-b0b6-b82001073bd3.png) |
| ![image](https://user-images.githubusercontent.com/71320345/203902659-6d4c9a59-28ed-47e9-8936-22f459d98a9e.png) | ![image](https://user-images.githubusercontent.com/71320345/203901443-65b70941-f8df-4bce-9509-77e5638de9c1.png) |
| ![image](https://user-images.githubusercontent.com/71320345/203902482-7ccd514f-405b-4ea0-a905-550387704ff9.png) | ![image](https://user-images.githubusercontent.com/71320345/203902276-6407d956-ea4c-4f1b-8d33-ad912f5c7715.png) |
Lastly, there is no longer an unpleasant extra padding when the …
=> chore: select option cell & header editor UI + move to theme.of(context).texttheme

frontend/app_flowy/lib/plugins/grid/presentation/widgets/filter/choicechip/text.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/select_option_editor.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/style_widget/text_field.dart
overview of changes:
- get text length from controller (avoids having to create an extra member, initialize it in `initState`, and update it in `onChanged`)
- call `setstate` in `onChanged` handler to update suffix text
- add a space at the front of suffix text to better visually break up the 2 pieces of text 
- fix autofocus typo
- adjusted hint text style (from which suffix text style is also inferred)
- add some margins vertically (a.k.a added vertical padding on the text)
=> fix: flowy text field bugs

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/checklist_cell/checklist_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_cell.dart
| before | after |
| :---:| :-----:|
|![before](https://user-images.githubusercontent.com/71320345/206192780-caf1af89-7ec3-4cba-91d6-bfc0de37abdf.png) | ![image](https://user-images.githubusercontent.com/71320345/206192618-c55584dc-5f2d-4293-bd1f-9e6959fafe78.png) |
=> fix: location of popover wrt the grid cell (select and checklist)

frontend/app_flowy/lib/plugins/trash/menu.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/menu.dart
Hello AppFlowy. I am creating this PR to solve issue on this [link](https://github.com/AppFlowy-IO/AppFlowy/issues/834).
1. Remove `padding(horizontal: Insets.l),` in line 103 so the hover effect width can match the container.
2. Add `ValueListneableBuilder` so MenuTrash widget can update their state when clicked or unclicked.
The video of the result is [here](https://drive.google.com/file/d/1qDIW75iBAvYm42zlHyRYxr7m-LSKSS1G/view?usp=share_link)
This is the updated PR from previous attempt on this [link](https://github.com/AppFlowy-IO/AppFlowy/pull/1486).
=> feat: add hover effect when trash icon is selected or hovered.

.github/workflows/release.yml, frontend/scripts/linux_installer/control, frontend/scripts/linux_installer/postinst, frontend/scripts/linux_installer/postrm
Following PR aims to fix #1503 by refactoring the linux build workflow in CI to be less verbose by moving ``postrm`` and ``postinst`` package scripts from CI workflow to ``scripts/linux_installer`` as all of the other OSes installer assets and scripts live there.
It also includes an additional workflow named ``build-linux-x86-alt`` with ``ubuntu-18.04`` runner image to build an alternate deb package. The following workflow should only be used temporarily as a workaround to support older debian based distributions where ``GLIBC < 2.34``, see #1503.
=> Refactor linux workflow & fix 1503

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/date_cell/date_cell.dart
Fixes #1414
Added a focus border to date cells if the popup is open:
=> fix: no focus border on date cells

frontend/app_flowy/lib/plugins/grid/presentation/layout/sizes.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/date_cell/date_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/common/type_option_separator.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/field_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/field_cell_action_sheet.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/field_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/field_type_option_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/date.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/number.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/select_option.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/select_option_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/row/row_detail.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/toolbar/grid_property.dart, frontend/app_flowy/lib/workspace/application/appearance.dart
This PR shows the scrollbars in the menus again, but some other changes have to be made to the menus since the padding on the scrollviews also insets the scrollbars. Also, with this patch, nested popovers now sit side by side properly, rather than overlapping a small portion near the edge of the parent
|Field Type||
|:-:|:-:|
|Text and Number|<video width=100 height=50% src="https://user-images.githubusercontent.com/71320345/209442410-c2acf085-ee2d-4620-b44a-3d32f132b15a.mp4"></video>|
|Date|<video src="https://user-images.githubusercontent.com/71320345/209442572-3bbd8f14-59db-43cb-85e2-877a667ff519.mp4"></video>|
|Select|<video src="https://user-images.githubusercontent.com/71320345/209442696-c066c6ab-10b0-4056-a742-13b3093867d8.mp4"></video>|
=> feat: show the scrollbars again

frontend/rust-lib/flowy-grid/tests/grid/field_test/test.rs
@appflowy could you please help me review this unit test,
somehow, the ".name" method doesn't return the name of options in multi selection type. So i use the ".id" method, then the test case was passed.
=> test: grid switch from multi select to text test

frontend/app_flowy/packages/appflowy_popover/lib/src/layout.dart, frontend/app_flowy/packages/appflowy_popover/lib/src/popover.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
Flutter doesn't currently allow popups to go outside the application window. Because of this, popovers have an unpolished look when they are about go off-canvas. This PR adds a spacing between the popover and the edge of the window.
We can improve this even further by automatically switching to the other side if there isn't enough space on side where the popover is supposed to spawn.
=> chore: add spacing between a popover and the edge of the window

frontend/app_flowy/lib/plugins/grid/application/cell/cell_service/cell_controller.dart, frontend/app_flowy/lib/plugins/grid/application/cell/date_cal_bloc.dart, frontend/app_flowy/lib/plugins/grid/application/cell/number_cell_bloc.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/number_cell.dart, frontend/rust-lib/flowy-grid/src/services/field/type_options/number_type_option/number_type_option_entities.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/type_option_cell.rs, frontend/rust-lib/flowy-user/src/services/database.rs
If the initial input content is: "", then after entering an invalid number string, the cell content will be empty. The cellDataNofitier doesn't notify the listener because the new value is the same as the old one. aka, "", the empty string.
Add `listenWhenOnCellChanged` callback to let the caller design how to handle the value change notification.
=> fix: update the cell content if input is not valid data

frontend/rust-lib/flowy-grid/src/services/field/type_options/number_type_option/number_type_option.rs, frontend/rust-lib/flowy-grid/src/services/grid_editor.rs
@appflowy could you please help me review this change
i tried to modify the code to achieve the same behaviours like Notion app for Number type.
the only problem is when i fill in the text under Number type, the backend in Rust processes as an empty string which is correct, But the frontend still display the string on the cell instead of empty the cell.
=> feat: handling same as Notion when user fills in the mixing of number and text

frontend/rust-lib/flowy-folder/src/manager.rs
As written in title. It just removes `use PhantomSnapshotPersistence` as it is not used (anymore).
=> CleanUp: removed unused PhantomSnapshotPersistence-import

frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/lib/plugins/calendar/calendar.dart, frontend/app_flowy/lib/startup/plugin/plugin.dart, frontend/app_flowy/lib/startup/tasks/load_plugin.dart, frontend/app_flowy/lib/workspace/application/view/view_ext.dart, frontend/app_flowy/test/bloc_test/home_test/create_page_test.dart, frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs, frontend/rust-lib/flowy-folder/src/entities/view.rs, frontend/rust-lib/flowy-grid/src/entities/field_entities.rs, frontend/rust-lib/flowy-grid/src/entities/setting_entities.rs, frontend/rust-lib/flowy-grid/src/services/group/group_util.rs, frontend/rust-lib/flowy-grid/src/util.rs, frontend/rust-lib/flowy-grid/tests/grid/grid_editor.rs, frontend/rust-lib/flowy-test/src/helper.rs, shared-lib/folder-rev-model/src/view_rev.rs, shared-lib/grid-rev-model/src/grid_view.rs
This PR builds on #1555 to add the initial bits and pieces of the new calendar view to AppFlowy
​
- Added test for creating a calendar page on the flutter side
​
=> chore: add calendar view plugin along with backend data

frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/field_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/field_cell_action_sheet.dart
Implements vision of #1673
- different widths for general field actions and type options
- unbounded maxHeight
- fix extra padding
- in the future, if necessary, move SizedBox to FieldEditor to use different widths for each FieldType
=> chore: grid field action sheet layout improvement

frontend/app_flowy/lib/plugins/board/presentation/card/board_checklist_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/cell_accessory.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/cell_container.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/checklist_cell/checklist_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/checklist_cell/checklist_cell_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/checklist_cell/checklist_progress_bar.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/row/grid_row.dart
- As a result of a previous change to fix cell accessories on URL cells, the 'open as a page' accessory for primary field cells no longer appear when hovering over the row, add it back!
- `ChangeNotifierProvider` doesn't recreate the notifier when `CellContainer` is rebuilt, which causes the bug. Therefore, make the notifier also rebuild with `CellContainer`.
- remove unnecessary extra `Stack` and `Inkwell` widgets used to detect mouse presses in select option and checklist cells by porting to `GridCellState`.
resolves #1543
=> chore: improve grid focus and hover event handling

frontend/app_flowy/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart
The `ShortcutEvent` did not fire on my keyboard layout (de-at)
=> fix: command of double tilde to strikethrough

frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/field_editor.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/style_widget/text_field.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/widget/rounded_input_field.dart
Introduces `onFieldSubmitted` on `RoundedInputField` type that will get used as `TextFormField` property.
Closes #1295.
=> feat: on enter exit editing property field #1295

frontend/app_flowy/packages/flowy_infra_ui/lib/style_widget/button.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/widget/ignore_parent_gesture.dart
Just a workaround to prevent the `MoveWindowDetector` from accepting the events.
Reference
* https://docs.flutter.dev/development/ui/advanced/gestures#gesture-disambiguation
* https://github.com/flutter/flutter/issues/67255
=> fix: #1290 [Bug] 300ms delay on buttons in titlebar

frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/checkbox_event_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/format_style_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart, frontend/app_flowy/packages/appflowy_editor/test/infra/test_raw_key_event.dart, frontend/app_flowy/packages/appflowy_editor/test/service/internal_key_event_handlers/checkbox_event_handler_test.dart
Solves #1762
Users can now use the key combination: **Ctrl+Enter** on Windows and Linux to quickly on/off a checkbox in AppFlowy. Mac Users have to press **Meta+Enter** in order to achieve the same.
This also works with multiple checkboxes. Thus as a user, you can select multiple todos and then press Ctrl+Enter to toggle them.
=> [FR] Shortcut for toggling checkbox 

frontend/app_flowy/lib/main.dart, frontend/app_flowy/lib/startup/tasks/app_widget.dart, frontend/app_flowy/linux/flutter/generated_plugin_registrant.cc, frontend/app_flowy/linux/flutter/generated_plugins.cmake, frontend/app_flowy/macos/Flutter/GeneratedPluginRegistrant.swift, frontend/app_flowy/pubspec.lock, frontend/app_flowy/pubspec.yaml
Resolves #762
Resolves #1559
Fixes being unable to resize the tiny default window on Linux.
Having `window_manager` available also gives us the ability to do [many window-related operations](https://pub.dev/packages/window_manager#api) in the future if desired.
If this is merged I'd next suggest we look at the ability to remember window size & position between launches.
=> fix: use window_manager to set minimum window size

frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/tab_handler.dart, frontend/app_flowy/packages/appflowy_editor/test/service/internal_key_event_handlers/tab_handler_test.dart
Solves #1684 
**Impact:**
Users can now press the tab key to create a sub todo or a sub checkbox.
Pressing tab here:
will result in:
=> Pressing tab on a todo creates a sub-todo

frontend/app_flowy/lib/main.dart, frontend/app_flowy/packages/appflowy_backend/lib/log.dart
Adds handling for platform errors that are not caught by the
Flutter framework. Doing so will log the error properly and
prevent the app from crashing.
=> Catch platform errors

frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/arrow_keys_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/backspace_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart, frontend/app_flowy/packages/appflowy_editor/test/service/internal_key_event_handlers/arrow_keys_handler_test.dart
Solves #75 #1825 
Adds the following functionalities:
=> Improve Editing and Navigating shortcuts with Ctrl/Meta

frontend/rust-lib/flowy-document/src/editor/mod.rs
=> fix: error happens when parsing readme content

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart
- Added option of shortcuts in help menu
- Clicking on the shortcut leads to the `Shortcuts.md` file
Fix for Issue: #1761
=> feat(shortcuts): Add Shortcuts to Help Menu

frontend/appflowy_flutter/lib/workspace/presentation/home/home_screen.dart
When menuIsDrawer = true, homeMenuResizer is still positioned at homeStack left. 
In this case, homeMenuResizer will located at homeMenu left, so we must drag home menu left area to resize home menu.
So I create this PR to fix this case.
=> fix: homeMenuResizer position when menu is drawer.

frontend/appflowy_flutter/README.md
Added basic information so that new contributors can easily get started with contributions.
Issue: #1908
=> docs(appflowy_flutter) : Update Documentation

frontend/appflowy_flutter/packages/appflowy_editor/lib/src/render/selection_menu/selection_menu_widget.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/markdown_syntax_to_styled_text.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/infra/test_raw_key_event.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/render/selection_menu/selection_menu_widget_test.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/service/internal_key_event_handlers/markdown_syntax_to_styled_text_test.dart
Add the following two features which were removed due to license reason
1. double asterisk to bold text
2. remove the slash '/'  after clicking the selection menu item  
Related to #1900 
Resolves #1881
=> feat(appflowy_editor):  double asterisk to bold text and remove slash after clicking selection menu item  

frontend/appflowy_flutter/lib/workspace/presentation/widgets/left_bar_item.dart
Double-click the title to select all the text on it.
Fix #1324
=> fix(appflowy_flutter): fix double click title issue #1324

frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart
Solves #1977 
Now clicking on the shortcuts button points the user to [this](https://appflowy.gitbook.io/docs/essential-documentation/shortcuts).
=> chore: changed the link of shortcuts page

frontend/appflowy_flutter/packages/appflowy_editor/lib/src/core/document/node_iterator.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/core/document/node_iterator_test.dart
When we have more than two level nodes nested (as children) the node iterator misses the first parent, because it goes as deep as possible at first.
Faced this while working on Table.
=> fix: bug on node iterator with nested nodes

frontend/appflowy_flutter/packages/appflowy_editor/lib/src/render/selection_menu/selection_menu_service.dart
On small window sizes, the width of the slash menu becomes greater and the menu overflows the right boundary. The user was hence not able to access all the menu items.
This PR fixes this issue. Now Selection menu scrolls in case of overflow, otherwise it behaves as it used to originally.
The following video illustrates the change I have made :
https://user-images.githubusercontent.com/79906086/226300367-5ff771d5-fa8b-4474-b022-916beaa30b73.mov
fixes #2019
=> fix: scrolling selection-menu when it goes out of bound, fixes #2019

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/sort/create_sort_list.dart
This pull request fixes the bug reported in issue #2044 where the hint text under the sort feature was misplaced. The expected behavior was to display "Sort by" in the hint text, but instead, it was displaying "Filter by".
I fixed the bug by simply correcting the code, replacing "filterBy" with "sortBy" which references the correct hint text.
fixes #2044
=> fix: sort hint text typo

frontend/appflowy_flutter/packages/appflowy_editor/lib/src/render/selection_menu/selection_menu_widget.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/render/selection_menu/selection_menu_widget_test.dart
The slash menu responded to the tab and arrow keys however the user should be able to control the slash menu simultaneously with the tab and arrow keys. This PR fixes the issue.
Tab key now moves the currently highlighted selection to the right by one. User can move to the first element in the next row if the selection is at the button furthest to the right. Using the arrow keys, the selection moves in the direction specified by the arrow key.
https://user-images.githubusercontent.com/84044317/226590005-b5e1aae8-cc6d-4e63-85ec-80bb401e46c4.mp4
fixes #2030
=> fix: slash menu responds to multiple key events

frontend/appflowy_flutter/packages/appflowy_editor/lib/src/core/transform/transaction.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/core/transform/transaction_test.dart
Replacing lesser number of available multi-line text nodes with higher number of incoming multi-line nodes lead to inconsistencies such as overwriting and unexpected line skips, this PR fixes the issue.
fixes #2092
=> fix: open-ai replace does not work in certain use-cases

frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart
Now, when you type text between two asterisks (e.g., \*bold text\*), it will appear in bold in the editor.
https://user-images.githubusercontent.com/98649066/227230689-0a7b00d6-4f99-4bf2-a4a8-911fd0e49e3e.mp4
Please note that I tested this feature on Windows, but I haven't had the chance to test it on MacOS yet. Therefore, I kindly ask all MacOS users to test this feature and report any issues they encounter.
Fixes #2080
=> fix: double asterisk to bold fixes #2080

frontend/.vscode/launch.json, frontend/rust-lib/flowy-database/src/manager.rs, frontend/rust-lib/flowy-database/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database/src/services/database_view/editor.rs, frontend/rust-lib/flowy-database/src/services/database_view/editor_manager.rs
Duplicating view including duplicating the setting and data of the view. Currently,  only duplicate the data of the view.  Duplicating the setting of the view will be done in another PR.
=> fix: modify same database by duplicate view

frontend/appflowy_flutter/packages/appflowy_editor/lib/src/render/toolbar/toolbar_item.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/src/render/toolbar/toolbar_item_widget.dart
The tooltip for the toolbar item didn't contain the description of its connected shortcut. This PR adds this functionality for all those items which have shortcut.
It is hardcoded at the moment, as discussed in the PR description.
fix for issue #2053
=> feat: improved tooltip of toolbar items to include the connected shortcut commands, fixes #2053

frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/board/board_menu_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/grid/grid_menu_item.dart
Fixed the issue with Referenced Board/Referenced Grid not appearing when using the slash menu command "/referenced". The keywords for these items have been rewritten and now they can be inserted using either the slash menu `/referenced`, `/board`, `/grid`, or `/kanban` command.
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/2139
=> Fix: referenced board and grid keywords

frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart
Fixes https://github.com/AppFlowy-IO/AppFlowy/issues/2062
The shortcut option in the help menu is misaligned. This is due to the emoji being smaller in size compared to other emojis.
Click on the `?` icon on the bottom right section of the app.
> Screenshot
Replaced current emoji with clipboard emoji which is more appropriate in size as suggested [here](https://github.com/AppFlowy-IO/AppFlowy/issues/2062#issuecomment-1480461543)
> Screenshot
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.
=> fix: Replace `Shortcuts` icon in the help menu option to fix misalignment 

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/accessory/cell_accessory.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart
I added a `SizedBox.shrink()` when there is no child in the `FlowyHoverContainer` in order to prevent the null check error happen again. Meanwhile, I delete the `_background` widget since it doesn't show any UI effect anyway. 
Fixes #2147 
https://user-images.githubusercontent.com/14248245/228919011-4dea812b-4356-4d75-b573-cb9ca5d04d12.mov
=> Fix: Null check error in FlowyHoverContainer

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/user/presentation/folder/folder_widget.dart, frontend/appflowy_flutter/lib/user/presentation/skip_log_in_screen.dart
Closes: #2105
- Additionally added Moveable Window so that on Mac we can drag the window around.
<details>
<summary>Windows</summary>
100% Text Size (OS Accessibility)
225% Text Size (OS Accessibility)
</details>
<details>
<summary>MacOS</summary>
Default Text Size (OS Accessbility)
Large Text Size (OS Accessbility)
</details>
=> fix: improve quick start layout

frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/image.dart
Looks like there are analyzer warnings that snuck into `main` somewhere along the way. The[ integration test revert is failing CI](https://github.com/AppFlowy-IO/AppFlowy/pull/2201#pullrequestreview-1373633257) due to these errors. Submitting a separate PR instead of adding those changes to this PR.
Here are the analyzer errors:
```
Run flutter analyze
Analyzing appflowy_flutter...                                   
info • 'toggleableActiveColor' is deprecated and shouldn't be used. No longer used by the framework, please remove any reference to it. For more information, consult the migration guide at https://flutter.dev/docs/release/breaking-changes/toggleable-active-color#migration-guide. This feature was deprecated after v3.4.0-19.0.pre • lib/workspace/application/appearance.dart:256:7 …
```
=> fix analyzer warnings

.github/workflows/integration_test.yml
Integration tests fail after upgrading Flutter from `3.3.10` to `3.7.5` because Flutter dropped OpenGL support. IIUC, the CI runners don't render using metal, so until https://github.com/flutter/flutter/issues/118469 is fixed, we will need to run the integration tests on a different OS.
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/2200
---
=> fix: run integration tests on Linux

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/assets/translations/eu-ES.json, frontend/appflowy_flutter/assets/translations/fr-FR.json, frontend/appflowy_flutter/assets/translations/ko-KR.json, frontend/appflowy_flutter/assets/translations/pt-BR.json, frontend/appflowy_flutter/assets/translations/ru-RU.json, frontend/appflowy_flutter/assets/translations/sv.json, frontend/appflowy_flutter/assets/translations/zh-CN.json, frontend/appflowy_flutter/assets/translations/zh-TW.json, frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/toolbar/board_setting.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/toolbar/board_toolbar.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/layout/sizes.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/grid_header.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/number.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/select_option.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/toolbar/grid_group.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/toolbar/sort_button.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/checklist_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/checklist_progress_bar.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/url_cell/cell_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/url_cell/url_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_detail.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/toast.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
This PR is the third part of the dark mode improvement https://github.com/AppFlowy-IO/AppFlowy/issues/1671. It update the UI in the Kanban board view page.
Updated the following UI:
1. Item detail dialogue: Change the text from 'New column' to 'New property' to avoid potential confusion.
2. CheckList in the item detail dialogue
3. Setting button
4. Update NumberTypeOptionWidget's UI to avoid text overflow
5. Minor update in grid view: Keep GridToolbar has the same button style
No test added. UI changes only.
=> feat: Improve dark mode in board page

frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/board_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_detail.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/size.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_input.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/dialog/styled_dialogs.dart
This PR is to fix multiple UI issues as followings:
1. Put original borderRadius back to FieldCellButton
Header
Property Cell
Fix https://github.com/AppFlowy-IO/AppFlowy/pull/2193#discussion_r1162550363
2. Remove the border of card when it is in dark mode
3. Change the `NavigatorTextFieldDialog` style to center aligned with wider padding. It will be used in the pop-up dialog in https://github.com/AppFlowy-IO/AppFlowy/pull/2224 later.
Impacted Widgets:
Rename Page/Title
Create/name new page
---
=> fix: fix multiple UI issues

frontend/Makefile.toml, frontend/scripts/makefile/tests.toml
TEST_COMIPLE_TARGET variable was being set to `x86_64-apple-darwin` for macos irrespective of the architecture, resulting in error when trying to run tests on mac m1. Now TEST_COMPILE_TARGET is being set according to the architecture. 
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/2264
=> fix: seperating env for mac test depending upon archs

frontend/appflowy_flutter/lib/plugins/document/editor_styles.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/cover/cover_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/cover/emoji_popover.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/cover/icon_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/auto_completion_node_widget.dart, frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/emoji_picker/src/config.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/emoji_picker/src/default_emoji_picker_view.dart, frontend/appflowy_flutter/packages/appflowy_editor_plugins/lib/src/code_block/code_block_node_widget.dart, frontend/appflowy_flutter/packages/appflowy_editor_plugins/lib/src/extensions/theme_extension.dart
This PR is to replace PR #2141 to improve UIs in the documents page(Editor). 
The following UIs have been updated. 
1. Emoji Picker
2. Selection menu
3. AI writer dialog button
4. Dropdown menu item style in code block
5. Callout tint color list
---
=> feat: Improve dark mode in document page

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/grid_header.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_detail.dart
Removes the extra padding on the popover shown below
---
=> fix: remove padding on popovers of newly-created fields

.github/workflows/flutter_ci.yaml
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/2073
---
Changing ```frontend/appflowy_tauri/src-tauri/src/main.rs``` before these changes caused the following workflows to be triggered:
After these changes:
=> ci: dont run flutter ci on commits that only change tauri sources

frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_language_view.dart
This PR is to change the current language picker UI along with fix #2291.
https://user-images.githubusercontent.com/14248245/233741806-04d02ea7-a4f3-43c5-a489-5709e66315a2.mov
Initially, I attempted to change the text color when it is hovered, but I realized that it was difficult to achieve due to the limitations of the DropdownButton. I considered importing a dropdownbutton related package(just for changing the text color?) or creating a customized DropdownButton(time-consuming). Instead, I think the best approach at the moment is to use the same popup-style widget in the theme setting, which would maintain consistency throughout the application setting page too.
=> feat: change the UI of language selector

frontend/appflowy_flutter/lib/plugins/trash/src/sizes.dart, frontend/appflowy_flutter/lib/plugins/trash/src/trash_cell.dart, frontend/appflowy_flutter/lib/plugins/trash/trash_page.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_customize_location_view.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart
This PR is to follow up PR #2345 and fix #2298. 
I added a `foregroundColorOnHover` in the `HoverStyle`,so we can modify the icon and text color when it is hovered. Then I used it in `FlowyIconButton` to change the icon color when it is hovered. 
1. Update the hover effect in file location setting. I used the same hover style in setting(like theme and language) 
2. Update the hover effect on trash page. 
https://user-images.githubusercontent.com/14248245/234407831-6309f053-190b-4506-abdb-34377cdf9638.mov
---
=> fix: fix icon hover color in dark mode

frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/TextBlock.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/utils/slate/hotkey.ts, frontend/appflowy_tauri/src/appflowy_app/utils/slate/text.ts
=> Support to break wrap the text block when triggering shift+enter

frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/emoji_picker/src/default_emoji_picker_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/emoji_picker/src/default_emoji_picker_view.dart
This PR fixes distorted/shrunk emojis in `Document` page's Callout option, closes [Issue #2284](https://github.com/AppFlowy-IO/AppFlowy/issues/2284).
> Issue screenshot
The parent wrapper container now has `BoxFit.scaleDown` option instead of `BixFit.fill`.
> [Fix] Screenshot
> [Fix] Recording
https://user-images.githubusercontent.com/13991373/233542336-18f4b74a-33a5-478d-baa5-e3e50c8fb961.mov
---
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
=> Fix: Fix distorted/shrunken emojis in Callout option in the`Document` page

frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart, frontend/appflowy_flutter/pubspec.lock
This PR addresses several UI issues of the calendar view in dark mode.
- The color of the days' texts
- The color of month forward/backward navigation icons
- Hover color of the new event button
- Bump calendar_view package to 1.0.3 to remove extra trailing whitespace below calendar
- Adjust padding in day cell
---
=> chore: calendar dark mode UI fixes

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_editor.dart
The original commit has some visible regressions. See the video below:
https://user-images.githubusercontent.com/71320345/233851095-733b3c3a-621c-437b-aa9c-58fd41cf3b56.mp4
- when switching from one popover to another, notice that the text field is stealing focus
- the select option editor popover isn't opening at all
=> revert: "Fix: #2028 auto enter edit mode for text field."

frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart
This is a band-aid fix for the below issue. Ideally, the time should disappear completely before the date string starts getting ellided. But I've been playing with this since yesterday but to no avail.
https://user-images.githubusercontent.com/71320345/235703319-e107bdd6-cfcd-474a-a6cd-2b8aa9ff2f32.mp4
ref: #2403
---
=> fix: text overflow on time in event card

frontend/appflowy_flutter/lib/plugins/database_view/application/database_controller.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/application/calendar_bloc.dart, frontend/rust-lib/flowy-database/src/services/field/type_options/date_type_option/date_type_option.rs
Use the local timezone to calculate the formatted date string. We can use the timezone specified by the user in the future.
=> feat: use user local timezone

frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_user_view.dart
[Screencast from 21-03-2023 09:15:59.webm](https://user-images.githubusercontent.com/84413505/226550394-67c0316f-8362-445d-b9e2-a7710c936ad1.webm)
This pull request fixes issue #2033, which was related to the auto-save functionality for changing the workspace name in the Settings section. The current behavior required the user to press Enter in order to save the changes. However, with this fix, the change will be automatically saved without the need to press Enter. For example, if the user changes the workspace name from "Me" to "Destiny", closing the Settings by clicking on the gray area outside the Settings window will now result in the name being changed to "Destiny".
Implemented auto-save functionality for the workspace name in the Settings section. (used onChanged in place of …
=> Feat: sync name on change

frontend/appflowy_flutter/assets/translations/en.json
=> fix: adjust layout setting string

frontend/appflowy_flutter/lib/plugins/database_view/application/cell/cell_data_persistence.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_cal_bloc.dart
Regardless of whether a date has previously been selected, clicking toggle include time in a cell that previously did not have time will enter the current time for you.
fix: #1800
fix: #2440
---
=> fix: default include time

frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart
Notice how there is extra whitespace when the visibility of the select option field is being toggled
https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/365c9535-1e40-491f-9bd8-d7d0821d833f
---
=> fix: don't show whitespace when no options are selected

frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_tests.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option_entities.rs
- Split off a portion of repeated logic into a separate function in `apply_changeset`.
- Improve readability in some parts
- early escape from timezone parsing if the timezone_id string is empty
---
=> chore: clean up code

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/auto_completion_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/auto_completion_plugins.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/smart_edit_node_widget.dart
`integration test` has been flaky for a while, and I'm fixing it. I noticed that integration tests for `open_ai_smart_menu_test` have been failing consistently lately. I ran a `git bisect` and tracked it to this PR.
**Issue** https://github.com/AppFlowy-IO/AppFlowy/issues/2346
Link to the workflow to show that tests failed when this PR was introduced
> https://github.com/AppFlowy-IO/AppFlowy/pull/2528/checks
PR that introduced `open_ai_smart_menu_test` (passed when introduced).
> https://github.com/AppFlowy-IO/AppFlowy/actions/runs/4869490828/jobs/8684057865
=> Revert "Support regenerating ai results #2012" (fix broken integration tests).

frontend/appflowy_flutter/integration_test/board_test.dart, frontend/appflowy_flutter/integration_test/empty_document_test.dart, frontend/appflowy_flutter/integration_test/open_ai_smart_menu_test.dart, frontend/appflowy_flutter/integration_test/util/data.dart
**Issue** https://github.com/AppFlowy-IO/AppFlowy/issues/2346
Tests on a workspace with an empty document flakes. It [succeeds in certain runs](https://github.com/AppFlowy-IO/AppFlowy/actions/runs/5086697721/jobs/9141396746#step:11:3083), but [fails in others](https://github.com/AppFlowy-IO/AppFlowy/actions/runs/5059606445/jobs/9081384873#step:11:3069).
Here are the two exceptions that I caught for the flaky test.
```
1. Tests on a workspace with only an empty document /grid shortcut creates a new grid and view of the grid (failed)
The following TestFailure was thrown running a test:
Expected: at least 2 matching nodes in the widget tree
Actual: _WidgetTypeFinder:<zero widgets with type "SelectionMenuItemWidget" (ignoring offstage
widgets)>
Which: means none were found but some were …
```
=> [Fix] Integration test flakes.

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/auto_completion_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/auto_completion_plugins.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/smart_edit_node_widget.dart
`integration test` has been flaky for a while, and I'm fixing it. I noticed that integration tests for `open_ai_smart_menu_test` have been failing consistently lately. I ran a `git bisect` and tracked it to this PR.
**Issue** https://github.com/AppFlowy-IO/AppFlowy/issues/2346
Link to the workflow to show that tests failed when this PR was introduced
> https://github.com/AppFlowy-IO/AppFlowy/pull/2528/checks
PR that introduced `open_ai_smart_menu_test` (passed when introduced).
> https://github.com/AppFlowy-IO/AppFlowy/actions/runs/4869490828/jobs/8684057865
=> Revert "Support regenerating ai results #2012"

frontend/appflowy_flutter/lib/core/config/kv_keys.dart, frontend/appflowy_flutter/lib/startup/tasks/app_window_size_manager.dart, frontend/appflowy_flutter/lib/startup/tasks/windows.dart
This commit addresses the feature request to save the window size settings. The application will now remember the user's preferred window size, allowing for a more personalized and seamless user experience.
Fixes: #2544
---
=> feat: Implement window size settings saving

.github/workflows/flutter_ci.yaml, .github/workflows/integration_test.yml, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
=> chore: retry codecov

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/emoji_popover.dart
This is the same fix as #2518, I think the commit got lost during merging somewhere in the commit history.
---
=> fix: remove icon button not working in popover

frontend/appflowy_flutter/integration_test/document/cover_image_test.dart, frontend/appflowy_flutter/integration_test/util/editor_test_operations.dart, frontend/appflowy_flutter/integration_test/util/expectation.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_editor.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/custom_cover_picker.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart
Title says all. In addition, this PR also fixes the following UI issue:
- The hover color isn't completely opaque, and so when two layers of the hover color stack it seems as though the button has a different hover color.
- The add icon isn't located at the very center of the button
=> test: add more cover integration tests

frontend/.vscode/tasks.json
Restore the default build task to AF: Code Gen instead of both AF: Generate Freezed Files and Code Gen
---
=> chore: restore default vscode build task

frontend/appflowy_flutter/integration_test/hotkeys_test.dart, frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
Solves: #2304 
https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/aa91911a-bede-4c61-a8ff-c9f9ffb8474e
---
=> feat: toggle theme mode shortcut

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src/appflowy_app/components/auth/auth.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/user/user_bd_svc.ts
=> fix: tauri check user failed

frontend/appflowy_flutter/lib/workspace/presentation/home/home_layout.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/size.dart
resolves #2637
Title says all. I personally think that this is fine since we already set a minimum width on the window size.
However, if there are usability problems, please do let me know and I'll find another solution
---
=> fix: use same base width for all screen sizes

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/choicechip/text.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/condition_button.dart
fixes [#2476](https://github.com/AppFlowy-IO/AppFlowy/issues/2476)
This PR fixes pixels overflow issue using by `Expandable` and text overflow rule `overflow: TextOverflow.ellipsis`.
https://www.loom.com/share/007bae93eabb4d819fc169d0239a15ff
https://www.loom.com/share/0246a6cdc88f42558716c7364279b4aa
---
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
=> fix: Filter UI popover pixels overflow with dynamic width and height

frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart
=> fix: add newlines after device info entries for debug info

frontend/appflowy_flutter/.gitignore, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/accessory/cell_shortcuts.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cell_builder.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/number_cell/number_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/text_cell/text_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/url_cell/url_cell.dart, frontend/appflowy_flutter/pubspec.lock
closes #2965 
- remove the paste shortcut, use the built-in paste function of the text field instead.
---
=> fix: pasting a link in a URL grid crashes the app

frontend/appflowy_flutter/integration_test/database_sort_test.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/field/field_controller.dart, frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/checklist_type_option/checklist.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/multi_select_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/single_select_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option_cell.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/url_type_option/url_type_option.rs, frontend/rust-lib/flowy-database2/src/services/sort/controller.rs, frontend/rust-lib/flowy-database2/tests/database/sort_test/checkbox_and_text_test.rs, frontend/rust-lib/flowy-database2/tests/database/sort_test/multi_sort_test.rs, frontend/rust-lib/flowy-database2/tests/database/sort_test/single_sort_test.rs
The logic for date sorting is already there. This PR primarily addreses the problem of empty cells being included in the sort. They should now be placed at the very bottom
TODO: fix regression: checkbox field not being sorted properly. The cell data is initially empty when created so it's automatically moved to the bottom, which isn't the desired behavior when the sort is Ascending (edit: done)
TODO: fix multi-sort logic (edit: done)
resolves #2775
---
=> feat: enable sort by date + sort fix

frontend/scripts/code_generation/language_files/generate_language_files.sh
Previously, the entire translation folder would be moved to `assets/translations` (i.e. `assets/translations/translations/en.json`) if the folder exists. This creates the folder if needed then moves the individual JSON files over instead.
---
=> fix: move translation jsons to right folder

frontend/appflowy_flutter/lib/workspace/application/favorite/favorite_bloc.dart
Error log
https://github.com/AppFlowy-IO/AppFlowy/actions/runs/5740386657/job/15558096157
---
=> fix: dispose the listener when the favorite bloc dispose

frontend/rust-lib/flowy-test/src/lib.rs, frontend/rust-lib/flowy-test/src/user_event.rs, frontend/rust-lib/flowy-test/tests/user/migration_test/mod.rs, frontend/rust-lib/flowy-test/tests/user/migration_test/util.rs, frontend/rust-lib/flowy-user/src/services/user_session.rs
Need to remove the shared KV before enable historical document test
=> ci: disable historical document test

frontend/resources/translations/de-DE.json
Solves: #3037 
I use 'Eigenschaft' which means property instead of the other suggestion: 'Spalte' which means column.
---
=> chore: german translation for new property and shortcuts

.github/workflows/release.yml, frontend/Makefile.toml, frontend/appflowy_flutter/macos/Podfile, frontend/appflowy_flutter/macos/Runner.xcodeproj/project.pbxproj, frontend/scripts/flutter_release_build/build_universal_package_for_macos.sh, frontend/scripts/makefile/flutter.toml
```sh
cd frontend
sh scripts/flutter_release_build/build_universal_package_for_macos.sh
```
```sh
cargo make --profile production-mac-arm64 appflowy
```
```sh
cargo make --profile production-mac-x86_64 appflowy
```
It doesn't support building the arm64 package only on Intel mac. The error log: https://github.com/LucasXu0/AppFlowy/actions/runs/5771555525/job/15645635129
```yaml
build-for-macOS-arm64:
name: ${{ matrix.job.target }} (${{ matrix.job.os }}) [${{ matrix.job.extra-build-args }}]
runs-on: ${{ matrix.job.os }}
needs: create-release
env:
MACOS_APP_RELEASE_PATH: frontend/appflowy_flutter/product/${{ github.ref_name }}/macos/Release
MACOS_AARCH64_ZIP_NAME: AppFlowy_${{ github.ref_name }}_macos-aarch64.zip
MACOS_DMG_NAME: AppFlowy_${{ github.ref_name }}_macos-aarch64
strategy: …
```
=> chore: Support CI build universal macOS package

frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_tests.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option_entities.rs
This PR saves the number as the unformatted decimal string, instead of the formatted string. This was causing problems because
`1000` becomes `€1.000` when stored in the backend. Then upon parsing, since `.` is the decimal deparator in euros, this becomes one euro and zero euro cents, which then gets formatted to `€1,00`.
fixes #3096
---
=> fix: euro currency number format

.github/workflows/release.yml, frontend/scripts/flutter_release_build/build_flowy.dart, frontend/scripts/flutter_release_build/tool.dart
On Windows, the dart script can't invoke `cargo make` to build the release application because the dart script owns a file that `cargo build` needs. As a result, `cargo build` hangs, which caused the timeout seen here: https://github.com/AppFlowy-IO/AppFlowy/issues/3161
As a fix, allowed calling the two parts of the script that clean the pubspec.yaml to exclude/include test dependencies.
---
=> Fix windows release build

frontend/appflowy_flutter/macos/Runner.xcodeproj/project.pbxproj
```log
dyld[95533]: Library not loaded: @rpath/HotKey.framework/Versions/A/HotKey
Referenced from: <9EAE1F08-63E5-37C6-9DFD-90E6FC44FEE3> /Users/lucas.xu/Desktop/AppFlowy/frontend/appflowy_flutter/build/macos/Build/Products/Debug/AppFlowy.app/Contents/MacOS/AppFlowy
Reason: tried: '/usr/lib/swift/HotKey.framework/Versions/A/HotKey' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/HotKey.framework/Versions/A/HotKey' (no such file), '/usr/lib/swift/HotKey.framework/Versions/A/HotKey' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/HotKey.framework/Versions/A/HotKey' (no such file), '/Users/lucas.xu/Desktop/AppFlowy/frontend/appflowy_flutter/build/macos/Build/Products/Debug/AppFlowy.app/Contents/Frameworks/HotKey.fra …
```
=> fix: macOS build error(Library not loaded) in debug mode

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_editor.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
resolves #3158
Also makes the cursor begin at the end of the text in a FlowyTextField if an initial value is provided.
---
=> fix: arrow keys on field name text field

frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
CJK IME preview
https://www.loom.com/share/60449cc32e1d4897a2b7e2f6e68e62b1
https://www.loom.com/share/292f65c1fd9240b389f881388b6bb871
closes #3227
closes #3193
closes #3173
closes #3155
closes #3132
closes #3060
closes #2896
closes #2909
closes #2769
closes #2768 
closes #2666
closes #2331
closes #2222
---
=> feat: improve CJK IME support

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/sort/sort_editor.dart
=> fix: one-frame glitch when deleting all sorts

frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/bloc/date_card_cell_bloc.dart
This pull request fixes the time visibility for date properties in Kanban cards.
closes #3188
---
=> fix: DateCardCellState date formatting

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/row/row.dart
Closes: #3208
I checked on the issue that the temporary disable of Reorderable on Windows was supposed to fix, but even after undoing those changes, I wasn't able to reproduce according to #2794 - We might have to take note of if this bug reappears, and solve it in another manner.
=> fix: reorder rows on windows

frontend/rust-lib/flowy-database2/src/entities/field_entities.rs, frontend/rust-lib/flowy-database2/src/services/cell/type_cell_data.rs, frontend/rust-lib/flowy-database2/src/services/database_view/layout_deps.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/timestamp_type_option/timestamp_type_option.rs
=> fix: don't use timestamp fields to make calendar

frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_tests.rs
fixes a test that's failing locally for users not in GMT time zone. CI has always passed since the VM is configured to be in GMT
---
=> test: fix convert text to date cell test

frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
Fix macOS window controls overlapping with tabbar when side menu is closed.
Closes #3316 
---
=> fix: add left padding to TabsManager widget

frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart
The popovers in settings (Theme, Language, perhaps more) cannot trigger by clicking. This is a major regression from this PR: https://github.com/AppFlowy-IO/AppFlowy/pull/3380
---
=> fix: cannot open popovers

frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/brightness_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/color_scheme.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/direction_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/theme_setting_entry_template.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_language_view.dart
=> fix: close popover after item selection in settings view

frontend/appflowy_flutter/integration_test/document/document_test_runner.dart, frontend/appflowy_flutter/integration_test/document/document_text_direction_test.dart, frontend/appflowy_flutter/integration_test/util/settings.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/font/customize_font_toolbar_item.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/direction_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/theme_setting_entry_template.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/resources/translations/en.json
closes https://github.com/AppFlowy-IO/AppFlowy/issues/3499
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/a9690876-474b-4f03-afe6-e381fe12315b
---
=> Fix 032 launch review issues

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_cal_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_editor.dart
- color of the unselected days in darkmode. It should blend into the background now
- a day selected -> toggle end date -> click on another one . This should immediately set the range
- reorganized the editor to not rebuild everything in the top-level bloc builder. Without this, toggling include time will reset the focused day to this month. (sorry Mathias)
---
=> fix: some issues with the end date

frontend/appflowy_flutter/integration_test/document/document_option_action_test.dart, frontend/appflowy_flutter/integration_test/document/document_test_runner.dart, frontend/appflowy_flutter/integration_test/util/editor_test_operations.dart, frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option_action.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/appflowy_flutter/test/unit_test/editor/transaction_adapter_test.dart
- support parsing the marked html text 
- option + click doesn't work sometimes.
- image block drag gesture.
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/ab3c2733-aac6-4dd0-a36c-5de03becd34d
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/5a01e844-601d-4200-9b3a-5a7cb41de9a7
---
=> fix: unable to parse html text which contains <mark> tag

CHANGELOG.md, frontend/appflowy_flutter/integration_test/document/document_with_database_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/database_view_block_component.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
- fix: undo issues https://github.com/AppFlowy-IO/appflowy-editor/pull/503
- fix: the cursor will flicker one frame to its previous position https://github.com/AppFlowy-IO/appflowy-editor/pull/506
- closes https://github.com/AppFlowy-IO/AppFlowy/issues/3533
---
=> chore: update editor version to b422187

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_property.dart
refer to the video in https://github.com/AppFlowy-IO/AppFlowy/pull/3328 the drag icon disappears when the drag starts.
---
=> fix: still show drag icon while dragging

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/emoji_menu_item.dart
To fix #2897 
1. Fix the overlay location for the emoji picker menu 
2. Add border decoration for the emoji picker menu 
---
=> fix: emoji picker menu issue

frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_new_page_button.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/color_scheme.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/dandelion.dart, frontend/resources/translations/en.json
To close #3268  and improve the following UI. 
1. Add a tooltip and set the hover color in the upload theme button as same as other icon buttons around.
2. Set new page icon color to primary color
---
3. I modified the following part from the draft design under the issue discussion. 
For light mode:
- I set all the hover colors to yellow style rather than green or yellow in different parts. 
- Only the sidebar background has a green color, the rest part uses a yellow style color. 
- I didn't change the border color(divider color) because it is also linked to the divider in the settings page, which looks weird if we add a colorful color there. 
https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/e41a4dd2-ac5f-4f6e-8d28-b91c093c4950
There are two options for the sidebar color I feel it …
=> feat: dandelion theme improvement

frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml
**flathub**
https://github.com/flathub/io.appflowy.AppFlowy/pull/63/files
**snap**
https://github.com/LucasXu0/appflowy-snap/commit/ea980685b1746fe5c38e435363ee16c133c8e284
**appimage**
this PR.
**tar.gz**
```
sudo apt-get install libnotify4
```
or 
```
sudo dnf install libnotify
```
---
=> fix: missing dependency in appimage

frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/colorscheme.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lemonade.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/theme.dart, frontend/appflowy_flutter/test/unit_test/theme/theme_test.dart
I made option B in #3550 become a new color theme called `Lemonade`. 
I changed the sidebar color to a deep green color in the dandelion theme to distinguish the dark mode for dandelion and lemonade. It is the only difference between these two dark modes so far. 
Lemonade theme in light mode:
Lemonade theme in dark mode:
Dandelion theme in light mode(no change in this PR):
Dandelion theme in dark mode(only sidebar color changed)
---
=> feat: add lemonade theme color

frontend/resources/translations/ja-JP.json
closes #3702 
brief explanations.
```
L.9 "youCanAlso" 
old: "あなたもすることができます"
=> this means If I can do it, you can do it too.
new: "他にもこんなことができます"
L.57 "import"
old: "輸入"
=> this means importation from abroad 
new: "取り込む"
L.151 "markdown"
old: "マークダウンにエクスポートされたノート",
=> not natural
new: "マークダウン形式のノート",
L.152 "path"
old: "ドキュメント/フローティ"
=> flowy is 'フローウィー' not 'フローティ', and this path should not be translated 
new: "Documents/flowy"
L.211 "supabaseSetting"
old: "スーパーベースの設定"
=> the name 'Supabase' is the same in Japanese
new: "Supabaseの設定"
L.219 "label"
old: "Theme Mode"
=> unfamiliar English
new: "外観テーマ"
L.222 "system"
old: "Adapt to System"
=> unfamiliar English
new: "システムと同期"
L.235 "builtInsLabel"
old: "内蔵テーマ"
=> not natural
new: "組み込みテーマ"
L.272 "export"
old: "輸出"
=> This means exportation …
```
=> feat: improve translations ja_JP

frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_customize_shortcuts_view.dart
bug: #3710
Fixed missing bottom margin of "Reset to default" button in  Shortcut settings.
---
- [:heavy_check_mark:] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [:heavy_check_mark: ] I've listed at least one issue that this PR fixes in the description above.
=> fix: Shortcut settings Reset to default is missing bottom margin #3710

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/checklist_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/checklist_cell_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/checklist_progress_bar.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_property.dart
- hide completed items in lemonade theme
- press enter to create a new item
- make the add new task item control less intrusive
- completed checklists' progress bars are green
https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/4c2cbecb-4368-4ad9-ba74-5c274abebd4c
---
=> chore: improve checklist ui

README.md
I just swapped an http link with an https link. The link previously led to the nginx default page.
=> Change http to https in README

frontend/appflowy_flutter/test/bloc_test/board_test/create_card_test.dart, frontend/appflowy_flutter/test/bloc_test/board_test/group_by_multi_select_field_test.dart
the ungrouped-item-stack is now positioned last, so tests need to be adjusted
---
=> fix: board unit test fix

frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_new_page_button.dart
Fixes #3389 
The divider is now starting from the window and stretching to the edge of the Sidebar without hindering with rest of the Sidebar UI.
---
=> fix: removed the parent padding and instead applied padding individually.

frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart
This PR makes the text color uniform with the one for database views
---
=> chore: share button text color in document

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/extension.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
`FlowyText` has a special behavior with the `TextHeightBehavior`. Also bump the vertical padding from 1.5 to 2.0
Before
After
---
=> fix: padding issue with the select tags

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/layout/sizes.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/mobile_grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/footer/grid_footer.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/grid_header.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/mobile_field_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/tab_bar/tab_bar_view.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrolling/styled_scroll_bar.dart
- the border height of the the new property field is smaller than others. now it's lined up correctly
- use click gesture instead of long pressing to rename field. now fixed. long press to reorder
- small adjustments to icon color, text color, and padding throughout
---
=> chore: some mobile grid issues

frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_url_cell.dart
- When you press on a URL cell, no matter where in the internal padding of the cell, the textfield will be focused
=> fix: mobile url cell focusnode fix

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/cells/number_cell.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_checkbox_cell.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_number_cell.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_text_cell.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_timestamp_cell.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_url_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/application/grid_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/create_filter_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/footer/grid_footer.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/grid_header.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/mobile_field_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/row/mobile_row.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/sort/create_sort_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/tab_bar/tab_bar_view.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/mobile_cell_container.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/select_option_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/url_cell/url_cell.dart, frontend/resources/translations/en.json
1. In mobile, only clicking the primary field cell will trigger the card detail page
2. Fix a bug where if there is more fields than can fit on the list when creating a filter or a sort, the field doesnt overlap the search box
3. Allow reordering rows when there's an active filter
4. There are user complaints about the excessive  animations in database tab bar view.
5. Add a tooltip for url cells in grid and row detail page on desktop.
6. Only show number keypad when editing a number cell on mobile.
---
=> chore: various database UI fixes

frontend/appflowy_flutter/linux/flutter/dart_ffi/binding.h, frontend/rust-lib/flowy-database2/src/services/group/controller_impls/date_controller.rs
initially discovered in `flowy-database2::tests::database::group_test::date_group_test::group_by_date_test` in California timezone any time around 5 PM local time.
Group building and determining the group of a row should only be done w.r.t the local time zone, not the time zone of the field.
---
=> fix: date group_id generation logic

frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_content/mobile_card_content.dart
This commit fixes a bug in mobile board views where even when the title of the card is not empty (i.e. after editing the title in row detail page), it still shows the "Untitled" placeholder.
---
=> fix: mobile board card title not updating

frontend/appflowy_flutter/packages/appflowy_backend/pubspec.yaml, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/scripts/docker-buildfiles/Dockerfile, frontend/scripts/makefile/protobuf.toml
makes it compatible with protoc_plugin 21.x.x
before testing, run 
```shell
dart pub global activate protoc_plugin
```
and see that the version has changed to 21.x.x (currently latest at 21.1.2)
---
=> chore: bump dart protobuf version

frontend/.vscode/tasks.json
1. fix and add back `AF: Dart Clean`. This task runs cargo make clean and also clears out the dart files generated by `protoc`
2. reorganize tasks in tasks.json
3. don't run `flutter pub get` twice.
4. make the tauri task use pnpm and sync i18n files before build
---
=> chore: reorganize vscode tasks

frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_menu_item.dart
=> fix: close emoji menu by ESC key

frontend/appflowy_flutter/lib/core/config/kv_keys.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/more/cubit/document_appearance_cubit.dart, frontend/appflowy_flutter/lib/util/color_to_hex_string.dart, frontend/appflowy_flutter/lib/workspace/application/appearance_defaults.dart, frontend/appflowy_flutter/lib/workspace/application/settings/appearance/appearance_cubit.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/brightness_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/color_scheme.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/create_file_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/date_format_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/direction_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/document_color_setting_button.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/document_cursor_color_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/document_selection_color_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/settings_appearance.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/theme_setting_entry_template.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/time_format_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_notifications_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/utils/hex_opacity_string_extension.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart, frontend/resources/translations/en.json, frontend/rust-lib/flowy-user/src/entities/user_setting.rs
**Customized document cursor and selection color**
To close #3972 
- When users enter 'return' on the text field, the preview area will get updated. Thus, users can get a brief preview of how it will look like. If users type an invalid value of color, it will show the error message below the text field.
- When users click 'Apply', it will validate all the values and save the value only if it is validated. 
- When users reset the color, the value will be `null` and the UI will use the corresponding theme color from `DefaultAppearanceSettings. get**Color. `
- The color values are saved both in the backend and shared preference. 
https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/1ce1e188-0b16-4a2b-828a-a819117729c7
https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/d5b2b628-4e9e-47 …
=> feat: customized cursor and selection color

frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_checklist_cell.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_number_cell.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_text_cell.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_timestamp_cell.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_url_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/cells/text_card_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cell_builder.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/select_option_cell.dart
- grid cells are now constant height and don't wrap
- remove arrows in row detail page
---
=> chore: adjust mobile grid cell design

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_copy_command.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_cut_command.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
renamed the duplicated 
Copy, Paste, and Cut commands
this PR closes #4193 
---
=> fix: renamed duplicate shortcut commands

frontend/.vscode/launch.json
The `Build Dart Only` config caters to desktop, ios, ios-simulator android and android-simulator. If you have ios-simulator selected as active device, it will launch AppFlowy on the simulator.
Actually, most of the launch configs are kind of misleading. The `<platform>: Build All` and `<platform>: Clean and Rebuild All` builds the libraries for the specific platform. But which platform AppFlowy will open still depends on which device you have as active at the bottom right.
---
=> chore: remove misleading vscode launch task

frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_edit_field_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_picker_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_type_option_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_field_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/field/field_backend_service.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/application/grid_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/mobile_grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/mobile_fab.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/mobile_select_option_editor.dart, frontend/resources/translations/en.json
Whereas before lots of user flows require clicking on a Done or Save button to apply changes, now changes are updated instantaneously.
Also fixes a bug where field editor for hidden fields still show the hide option rather than show.
---
=> fix: bottom sheet updates apply immediately

frontend/rust-lib/flowy-database2/src/event_handler.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_operation.rs, frontend/rust-lib/flowy-database2/src/services/field/field_operation.rs, frontend/rust-lib/flowy-database2/tests/database/field_test/script.rs, frontend/rust-lib/flowy-database2/tests/database/group_test/script.rs
This is a hot-fix for a bug where if a new option is inserted in a grid, a relevant stack isn't being created in a linked kanban board.
---
=> fix: notify all views of field type option changes

frontend/appflowy_flutter/lib/startup/startup.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml
Every request to AppFlowy cloud will carry the client api version
=> chore: bump client api

frontend/appflowy_flutter/integration_test/document/document_alignment_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/align_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/custom_text_align_command.dart
This fix is related to the feature request issue:
> [FR] have a shortcut for text alignment: #3351
Added a feature that addresses the requirements of the issue, allowing users to align text in the document using shortcut keys. The implemented keyboard shortcuts are:
- `Ctrl+Shift+L`: Align left
- `Ctrl+Shift+E`: Align center
- `Ctrl+Shift+R`: Align  right
Additionally, included tests to ensure the functionality works as expected.
https://github.com/AppFlowy-IO/AppFlowy/assets/68953739/2de99899-5e58-4f9d-915a-c30efe73ca53
=> feat: support aligning the text block using shortcuts

frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/theme_upload/theme_upload_learn_more_button.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/buttons/secondary_button.dart
- ### Feature Preview
- Restored the outline color for the secondary button prior to #4317.  
- Add an outline color field in the secondary button to build the learn more button in the customized theme dialog. 
---
=> fix: fix secondary button outline color

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/util.dart
- fix: When pressing on the Text formatting for RTL/LTR, the menu disappears
---
=> fix: the aa menu disappear after clicking the inactive indent itemg

frontend/appflowy_flutter/android/app/build.gradle
I tested the sign-in feature on Android versions 23 to 34 and found that it only works on devices with Android version 10 or higher. Therefore, I recommend setting the minimum supported version to Android 10 unless the sign-in feature is adapted for the version <= 29.
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4396
---
=> chore: set minimum supported android version to android 10

frontend/rust-lib/build-tool/flowy-codegen/src/protobuf_file/proto_gen.rs
Fix a bug that sometimes occur during development where a rogue .DS_Store file is parsed while generating protobuf files.
---
=> fix: don't parse unexpected files while generating protobuf

frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/_restart_app_button.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_appflowy_cloud.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_cloud.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_local_cloud.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_supabase_cloud.dart
=> feat: optimize cloud settings on mobile

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_font_item.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4477
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4476
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/ec590cd9-246e-4f32-8a60-1f6e7da1921e
---
=> fix: font shown in AA has _r as a suffix & copy & paste menu did not dismiss when navigating to the font page

frontend/appflowy_flutter/lib/plugins/database/widgets/row/cells/select_option_cell/select_option_editor.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/row/cells/select_option_cell/text_field.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/appflowy_flutter/test/unit_test/select_option_split_text_input.dart, frontend/appflowy_flutter/test/widget_test/select_option_text_field_test.dart
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/4326
The package doesn't do much so I removed it.
@LucasXu0 Do you know how I can cancel composing with Esc without also closing the Popover?
EDIT: fixed.
https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/a25d16ef-405c-4677-832d-5c0610eae91f
---
=> fix: composing in select option text field doesn't work

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
=> fix: the text and icon in + menu are not aligned in the same baseline

frontend/appflowy_flutter/lib/plugins/database/board/application/board_bloc.dart
=> fix: don't show ungrouped column when the field type is checkbox

frontend/appflowy_flutter/integration_test/sidebar/rename_current_item_test.dart, frontend/appflowy_flutter/lib/startup/deps_resolver.dart, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/lib/workspace/application/sidebar/rename_view/rename_view_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/rename_view_popover.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
Closes: #3490 
Using `CMD+SHIFT+R` to quickly rename current page.
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/01b9dafe-6a81-4259-88f8-6a4964a81aad
---
Focus is not returned to the Editor after renaming, possible future improvement.
=> feat: f2 to rename current view

frontend/appflowy_flutter/lib/mobile/presentation/base/app_bar_actions.dart
clicking on the white space around the `FlowySvg` doesn't register.
Affects back button, close button, cancel button and more buttons.
---
=> fix: size of hitbox in app bar button

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_item_body.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_quick_actions.dart, frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_mobile_quick_action_button.dart
- change the height of each item to be 52px, less padding of 4px vertically to have 44px height for the inkwell widget
- change the thickness of divider to 0.5px
- used in:
- view actions in homepage after sliding
- view actions in the more appbar button
- database card detail actions
- database view actions.
https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/5536ce68-84a0-4761-8c2f-21f61e7996f5
---
=> chore: inkwell mobile quick action sheets

frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs, frontend/rust-lib/flowy-database2/src/services/sort/entities.rs
=> fix: deleting a sorting field doesn't delete existing sorts

frontend/appflowy_flutter/lib/plugins/database/application/field/field_controller.dart
resolves #3444
Steps to reproduce:
1. Create a sort on a field
2. Switch to a different document/database and come back
3. Delete that sort
4. Attempt to create a sort on that same field.
---
=> fix: deleting a sort doesn't allow creating a new sort on that field

frontend/appflowy_flutter/integration_test/document/document_with_outline_block_test.dart, frontend/appflowy_flutter/integration_test/util/editor_test_operations.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_button.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option_action.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option_action_button.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_shortcut_event.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/pop_up_action.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/language.dart, frontend/resources/translations/en.json
**Closes:** #4355 
**Changes Made:**
Added dynamic depth control to the `OutlineBlockWidget` component.
When a depth **H1** is selected, the app now displays headings up to level 1.
For depth **H2**, it shows headings up to level 2, extending upto subsequent **H3** headings.
**Demo:**
https://github.com/AppFlowy-IO/AppFlowy/assets/68953739/948a6e88-89d8-49c7-b58c-7ef3f5f899af
=> feat: Implement outline block component depth control

frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/checkbox_cell_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_controller_builder.dart, frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_data_loader.dart, frontend/appflowy_tauri/src/appflowy_app/application/database/cell/cell_types.ts, frontend/appflowy_tauri/src/appflowy_app/application/database/field/type_option/type_option_types.ts, frontend/appflowy_tauri/src/appflowy_app/components/database/components/cell/CheckboxCell.tsx, frontend/rust-lib/event-integration/tests/database/local_test/test.rs, frontend/rust-lib/flowy-database2/src/entities/type_option_entities/checkbox_entities.rs, frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_filter.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_tests.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_type_option_entities.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/multi_select_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_type_option.rs, frontend/rust-lib/flowy-database2/src/services/group/controller_impls/checkbox_controller.rs
Currently, the checkbox cell data is parsed to a single-String tuple struct. It works, there are no bugs, but can be more intuitive.
There are three states. When grouping, calculating, filtering, sorting or what have you, we need to check whether a cell is checked or not.
Evidently, `is_uncheck()` may cause bugs in the future. We don't run into this issue now because we negate `is_check()` instead of using `is_uncheck()`, but it would be so much simpler if we just use a bool instead. We also get to remove the dependency on these consts "Yes" and "No" on the frontend-frontend.
---
=> refactor: checkbox field type

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/date_picker/mobile_date_picker_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_picker_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_full_field_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/edit_database_view_screen.dart, frontend/appflowy_flutter/lib/plugins/base/drag_handler.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_checklist_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_date_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_select_option_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_checklist_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_date_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_select_cell_option.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_checklist_cell_editor.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_select_option_editor.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/setting/mobile_database_controls.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/mobile_appflowy_date_picker.dart
This is a precursor to the mobile transition PR for easier review.
- adjust top corner radius from 12px to 16px
- remove unnecessary provided `padding = EdgeInsets.zero` in some `showMobileBottomSheet` calls
- remove `resizeToAvoidBottomInsets` since default padding is already added later down, if I understand it correctly
- rename `DragHandler` to `DragHandle`
---
=> chore: adjust show mobile bottom sheet

frontend/rust-lib/flowy-database2/src/entities/filter_entities/date_filter.rs, frontend/rust-lib/flowy-database2/src/entities/filter_entities/number_filter.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_filter.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_filter.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/timestamp_type_option/timestamp_type_option.rs
- match the condition in the `<type>FilterPB` first, not the arguments given. e.g. before, it first sees that the timestamp on a `DateFilterPB` is `None`, then deduces that the condition will be either `IsEmpty` or `IsNotEmpty`.
- this improves readability, and especially in`DateFilterPB` where the logic for `DateConditionPB::IsWithin` isn't immediately apparent.
- this also tests that the arguments are correct, catching when appropriate arguments aren't present in the passed-in `<type>FilterPB`.
---
=> refactor: improve type option filter logic

frontend/appflowy_flutter/lib/plugins/database/application/cell/date_cell_service.dart, frontend/appflowy_tauri/src/appflowy_app/application/database/cell/cell_service.ts, frontend/rust-lib/event-integration/src/database_event.rs, frontend/rust-lib/event-integration/tests/database/local_test/test.rs, frontend/rust-lib/flowy-database2/src/entities/type_option_entities/date_entities.rs, frontend/rust-lib/flowy-database2/src/event_handler.rs, frontend/rust-lib/flowy-database2/src/event_map.rs, frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/checklist_type_option/checklist_entities.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option_entities.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/mod.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option_cell.rs, frontend/rust-lib/flowy-database2/src/services/group/controller_impls/date_controller.rs, frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/util.rs, frontend/rust-lib/flowy-database2/tests/database/cell_test/script.rs, frontend/rust-lib/flowy-database2/tests/database/cell_test/test.rs, frontend/rust-lib/flowy-database2/tests/database/database_editor.rs, frontend/rust-lib/flowy-database2/tests/database/field_test/util.rs, frontend/rust-lib/flowy-database2/tests/database/group_test/script.rs
- also rename `DateChangesetPB` to `DateCellChangesetPB`
---
=> refactor: use BoxAny for dynamically-typed cell changesets

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart, frontend/resources/translations/en.json
- display the error message if upload failed
---
=> feat: error message should persist on the image block

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_field_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_list.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/sort/create_sort_list.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_select_option_editor.dart
bottom overflow
not enough padding
misc
- change delete text and icon color for select option editor to red
- improve code style in field name filter
---
=> fix: mobile view and field list bottom sheets

frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/group_card_header.dart, frontend/resources/translations/en.json
Closes: #4770 
We have a lot of different sheets on Mobile, but I've made it uniform to the database options sheet.
=> fix: edit column sheet uniform ui

frontend/rust-lib/flowy-database2/src/entities/filter_entities/select_option_filter.rs, frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs, frontend/rust-lib/flowy-database2/src/services/cell/type_cell_data.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_tests.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_type_option_entities.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option_entities.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option_entities.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/multi_select_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_ids.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/url_type_option/url_type_option_entities.rs
- `TypeCellData` is dead code. We use `AnyMap`s for serialization and deserialization when dealing with data storage and `BoxAny`s for generic in-memory storage instead now. 
- The `DecodedCellData` trait has been replaced with `TypeOptionCellData` whose contents are the same but is more thoroughly implemented (and actively used, in `TypeOptionCellDataCompare`)
- `FromCellString` isn't required for the `TypeOption::CellData` type. We have replaced it with `for<'a> From<&'a Cell>`. As such, I've decided to remove this trait completely and let the individual cell data types that need this functionality implement the `FromStr` trait
---
=> chore: type option cell data trait cleanup

frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/checklist_cell_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/checklist_card_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/checklist.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_checklist_cell_editor.dart, frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart
Add keyboard navigation to checklist cell editor. `text field` refers to the place where the name of the task is changed. `item` refers to the entire checklist task, comprised of the checkbox, text field and delete button.
- Space when item is focused to select/unselect
- Delete when item is focused to delete
- Enter when item is focused to start editing (give focus to the text field)
- Cmd/Ctrl + Enter when item is focused OR text field is focused to select/unselect
- Esc when text field is focused to stop editing
---
=> feat: checklist UX improvement

frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
- use warning instead of assert to prevent panic during local sqlite workspace deletion
=> fix: delete workspace no panic

frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_checklist_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart, frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
This PR fixes the traversal issue in the checlist editor.
- Disabled button receiving focus if the onPressed is null _(Default behavior for Flutter, onPressed == null means disabled)_
- Added skipTraversal to the Popover itself so it doesn't get included in the traversal order
- Only clear the new item text field if a new item was actually created
- Disable create button when it doesn't do anything. If you only added spaces you could click on the button, but it would only clear the text field, not create a new item
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/1b7adff0-9f11-419a-abdd-2e910b775aa9
=> fix: focus traversal in checklist popover

frontend/appflowy_flutter/lib/core/helpers/url_launcher.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
Remove the logic that automatically adds the HTTP(S) scheme, because the `launchUrl` function will return **false** even when it successfully opens a URL the `file://` scheme.
---
=> fix: only adding http(s) scheme if needed

frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_editor.dart, frontend/appflowy_flutter/lib/plugins/database/grid/application/calculations/field_type_calc_ext.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/calculations/calculate_cell.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/calculations/calculations_row.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/view_meta_info.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrolling/styled_scroll_bar.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrolling/styled_scrollview.dart, frontend/resources/translations/en.json, frontend/rust-lib/flowy-database2/src/entities/calculation/calculation_entities.rs, frontend/rust-lib/flowy-database2/src/services/calculations/service.rs
- Floating calculations so that they're always visible / available _(see preview)_
- Wrapped Calculate cell in a Horizontal ScrollView to avoid overflow, for reference see Notions implementation _(see preview)_
- Fixed issues with count (not) empty calculations
- Made some changes to the duplicate calendar event icon button
- Improved readability of the View Meta Info _(see preview)_
- Hid the "arrow down" on calculation cells that already have a chosen calculation _(UI Gimmick, you can still select another calculation type by pressing on the cell)_
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/1a356725-b1c8-481b-96b9-c464aff2d242
The tooltip is only showing if some of the calculate cell is hidden/obscured, notice that you _can't_ scroll in the calculate cell, it's purely a UI …
=> fix: launch review 0.5.1

frontend/appflowy_flutter/lib/plugins/database/application/row/row_service.dart, frontend/appflowy_tauri/src/appflowy_app/application/database/row/row_service.ts, frontend/rust-lib/event-integration/src/database_event.rs, frontend/rust-lib/flowy-database2/src/entities/row_entities.rs, frontend/rust-lib/flowy-database2/src/event_handler.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_filter.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_group.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_operation.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_sort.rs, frontend/rust-lib/flowy-database2/src/services/filter/controller.rs, frontend/rust-lib/flowy-database2/src/services/group/configuration.rs, frontend/rust-lib/flowy-database2/src/services/group/controller.rs, frontend/rust-lib/flowy-database2/src/services/group/controller_impls/default_controller.rs, frontend/rust-lib/flowy-database2/src/services/group/group_builder.rs, frontend/rust-lib/flowy-database2/src/services/sort/controller.rs, frontend/rust-lib/flowy-database2/tests/database/block_test/script.rs, frontend/rust-lib/flowy-database2/tests/database/group_test/date_group_test.rs, frontend/rust-lib/flowy-database2/tests/database/group_test/script.rs, frontend/rust-lib/flowy-database2/tests/database/sort_test/script.rs
requires https://github.com/AppFlowy-IO/AppFlowy/pull/4688
- Move some fragmented create row logic from event handler to database editor
- Streamline row duplication logic
- Remove unnecessary Arc\<Field>. The filter, sort and group controllers already are Arcs, and in the instances where we use the struct field, we are just referencing it. So we probably don't need to put it in an Arc.
---
=> refactor: create row workflow

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/editor_state_paste_node_extension.dart
=> fix: apply formatting to pasted text only when the block is a paragraph

frontend/resources/translations/ja-JP.json
Sorry, I’m just learning to contribute. :)
The kanji for  `"ゴミ箱を殻にする"` is incorrect and may not convey the correct meaning.
before: `"ゴミ箱を殻にする"`("殻" means grain's Hull)
after: `"ゴミ箱を空にする"`("空" means empty)
Please pay attention!
---
=> chore: typo fix

README.md
Solves: #4987 
- replaces broken links with the docs.appflowy.io domain which is the working domain for the docs.
---
=> docs: replace broken links with working ones

frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/select_option_loader.dart
Fix a case where selecting an option in the single select filter popup doesn't select that option and deselect the others.
---
=> fix: single select option filter ui

frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/select_option_cell_editor_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/select_option_filter_list_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/option_list.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_cell_editor.dart, frontend/appflowy_flutter/test/bloc_test/grid_test/cell/select_option_cell_test.dart
- fix regression on select option logic, where if multiple selected options are selected in one go when an active filter is present, hidden select options can't be selected
- allow backspace to deselect a selected option
- improvements to option filtering and arrow navigation
---
=> chore: more select option cell editor improvements

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_web/wasm-libs/Cargo.lock, frontend/appflowy_web/wasm-libs/Cargo.toml, frontend/appflowy_web_app/src-tauri/Cargo.lock, frontend/appflowy_web_app/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/dart-ffi/Cargo.toml, frontend/rust-lib/flowy-folder-pub/src/cloud.rs, frontend/rust-lib/flowy-server/src/af_cloud/impls/folder.rs, frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs, frontend/rust-lib/flowy-server/src/local_server/impls/user.rs, frontend/rust-lib/flowy-server/src/supabase/api/user.rs, frontend/rust-lib/flowy-user-pub/src/cloud.rs, frontend/rust-lib/flowy-user/src/anon_user/sync_supabase_user_collab.rs
We're currently enhancing AppFlowy Cloud to include team collaboration features. However, integrating these features with Supabase as the server option is proving to be more complex and requires additional work. As a result, we've decided to temporarily disable the option to use Supabase until we can fully support team collaboration functionalities with it.
=> chore: bump collab and client api

frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart, frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/relation_cell_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_controller.dart, frontend/appflowy_flutter/lib/plugins/database/application/field/field_controller.dart, frontend/appflowy_flutter/lib/plugins/database/application/field/field_editor_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/application/row/row_banner_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/domain/field_listener.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_detail.dart, frontend/appflowy_flutter/test/bloc_test/board_test/create_or_edit_field_test.dart, frontend/appflowy_flutter/test/bloc_test/board_test/group_by_unsupport_field_test.dart, frontend/appflowy_flutter/test/bloc_test/board_test/util.dart, frontend/appflowy_flutter/test/bloc_test/grid_test/field/edit_field_test.dart, frontend/appflowy_flutter/test/bloc_test/grid_test/util.dart
Remove `SingleFieldListener` and replace usage with `FieldController`'s `addSingleFieldListener` callback which gets triggered on `FieldInfo` changes instead of only `FieldPB` changes
---
=> chore: remove single field listener

frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
This PR is for issue #4968, to edit side panel title with double click. 
I directly used GestureDetector of SingleInnerViewItem, I could have also passed it as function call back but it will require having MultiBlocProvider.
I am new here, any feedback @annieappflowy ?
---
=> feat: double tab edit side panel 

CHANGELOG.md, frontend/appflowy_flutter/lib/shared/feature_flags.dart
- Improved the display of code blocks with line numbers
- Added support for signing in using Magic Link
- Fixed the database synchronization indicator issue
- Resolved the issue with opening the mentioned page on mobile
- Cleared the collaboration status when the user exits AppFlowy
---
=> chore: release 0.5.5

frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/4912
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/4911
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/3765
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/3174
- row icon not being displayed
---
=> fix: kanban row icon

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_floating_toolbar/custom_mobile_floating_toolbar.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
depends on https://github.com/AppFlowy-IO/appflowy-editor/pull/776
https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/71d5845e-8bef-4d11-9e4a-a0a10f9e08f6
This isn't conform to either of the platforms' default appearance, but I couldn't find the right parameters and curves. For now, both platforms will see a subtle fade and slide effect.
---
=> feat: mobile floating toolbar animation

frontend/appflowy_flutter/android/app/src/main/Classes/binding.h, frontend/appflowy_flutter/integration_test/desktop/board/board_add_row_test.dart, frontend/appflowy_flutter/integration_test/desktop/board/board_group_test.dart, frontend/appflowy_flutter/ios/Podfile.lock, frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_controller.dart, frontend/appflowy_flutter/lib/plugins/database/application/field/field_cell_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart, frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart, frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_card.dart, frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_page.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/layout/layout.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/calculations/calculations_row.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/footer/grid_footer.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/grid_header.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/row.dart, frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/tab_bar_header.dart, frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_style_maps/desktop_board_card_cell_style.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/setting/setting_property_list.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
- When not editing the title, wrap the title into two lines. When editing, show all the contents
- improve text editing behavior. Titles will be forced to be single line
- expand kanban board to full width
- allow auto-scrolling when dragging a card to the edge of the kanban board.
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/4979
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/4666
---
=> fix: kanban UX bugs

frontend/appflowy_flutter/lib/plugins/database/application/database_controller.dart, frontend/appflowy_flutter/lib/plugins/database/application/row/related_row_detail_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_detail.dart, frontend/rust-lib/flowy-database2/src/event_handler.rs, frontend/rust-lib/flowy-database2/src/event_map.rs
1. In collaborative sessions, the row property will now be displayed almost instantaneously upon expanding a row as a full page.
2. Fix a case where using the breadcrumbs to navigate back to the original database view didn't bring the user to the correct database view.
3. Fix the row detail actions to the top of the row detail dialog.
4. Move the expand icon to the top-right corner of the row detail dialog.
---
=> fix: open row as full page launch review issues

frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_picker_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_setting.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_font_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/lib/shared/google_fonts_extension.dart, frontend/appflowy_flutter/lib/workspace/application/settings/appearance/base_appearance.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart
"Font not found" exception will be thrown if setting San Francisco font for a document on iOS and then opening the same document on Android. 
Attempt to downgrade the font to the system one if unable to load the specified font.
---
=> fix: google fonts not found exception

frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5220
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/d33b45c1-086d-4084-93a4-a271fba8215a
---
=> fix: korean IME issue on Windows

frontend/rust-lib/flowy-user/src/user_manager/manager_user_awareness.rs, frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
=> chore: drop old user awarenss when open workspace

frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_recent_view.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/desktop_cover.dart, frontend/appflowy_flutter/lib/util/string_extension.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/theme_extension.dart
In the older versions, the cover color used a hex string as its value. Now, we use a tint color that adjusts based on the theme. Therefore, I added compatible logic for the hex string.
---
=> fix: color selection compatible with older versions

frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/5301
---
=> fix: kanban board card text input inconsistency

frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_web/wasm-libs/Cargo.toml, frontend/appflowy_web_app/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml
This PR is a follow up on https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/218 - we have updated yrs to v0.18.8 and enable full awareness state passing within awareness update callbacks.
=> chore: udpated yrs to v0.18.8

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_floating_toolbar/custom_mobile_floating_toolbar.dart
Android (translate + fade)
https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/57826565-f7e2-4244-b30b-e4645e4d85bd
iOS (scale with curve)
https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/053702a1-df3c-4c74-887c-e69de826e2aa
---
=> chore: improve floating mobile toolbar animation for iOS

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_shortcuts.dart
Pressing `Enter` in a callout block will insert a newline (\n) within the callout, while pressing `Shift+Enter` in a callout will insert a new paragraph next to the callout.
---
=> feat: support pressing enter key to insert new line within callout block

frontend/appflowy_flutter/lib/plugins/document/application/document_data_pb_extension.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/error/error_block_component_builder.dart, frontend/resources/translations/en.json
- Add a missing delta value for heading blocks if their delta is empty.
- Fix error block overflow on mobile.
---
=> fix: heading node validate failed

frontend/appflowy_flutter/integration_test/desktop/board/board_field_test.dart, frontend/appflowy_flutter/integration_test/shared/database_test_op.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/mobile_card_content.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/card/card_bloc.dart
Before this changing any field from CellController<String, String> to a CellController<SomeCellDataPB, String> caused an exception. The root of the problem was that _CardContent wasn't getting rebuilt when field type got changed. In CardState it was storing a list of CellContext which contains only field id and row id so on changing field type the state wasn't changing.
I made a new type CellMeta which stores field type alongside row id and field id and now CardState stores list of CellMeta.
Fixes #5360
=> fix: chaning field type #5360

frontend/rust-lib/flowy-database2/src/manager.rs
Importing CSV files may fail if the file contains too many rows.
=> chore: add limitation when importing csv file

frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart, frontend/appflowy_flutter/lib/plugins/document/application/document_collab_adapter.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_cover_image.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_icon.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_layout.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
=> fix: unable to remove the remote selection when the user close the page on mobile

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/workspace/application/settings/shortcuts/settings_shortcuts_cubit.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_customize_shortcuts_view.dart
#5413 
Partially solves: #5355 
https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/90961fcc-8d20-4684-8784-e20ba2f72d3d
---
=> fix: accept multi-key combination for customizing shortcuts & removes duplicates

frontend/rust-lib/flowy-document/src/event_handler.rs, frontend/rust-lib/flowy-document/src/manager.rs
When switching to or creating a new workspace, there is a possibility that it will attempt to retrieve the previous workspace document using the current new workspace ID.
For example, SET_DOCUMENT_AWARENESS_LOCAL_STATE will get document async.
```text
{"msg":"[🟢 SET_DOCUMENT_AWARENESS_LOCAL_STATE - START]","time":"06-03 15:54:40","target":"flowy_document::manager"}
{"msg":"[🟢 GET_DOCUMENT - START]","time":"06-03 15:54:40","target":"flowy_document::manager"}
2024-06-03 15:54:40 ERROR flowy_document::manager: error: Internal: "Call open document first"
at flowy-document/src/manager.rs:138
in flowy_document::managerget_document with doc_id: "949be6c4-3804-480b-aa5a-278358d06371"
in flowy_document::managerset_document_awareness_local_state
```
=> fix: workspace id not match

frontend/appflowy_flutter/lib/workspace/application/favorite/favorite_service.dart, frontend/appflowy_flutter/lib/workspace/application/recent/cached_recent_service.dart, frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart, frontend/appflowy_flutter/lib/workspace/application/view_title/view_title_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/header/sidebar_top_menu.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/create_space_popup.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/manage_space_popup.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon_popup.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart, frontend/resources/translations/en.json, frontend/rust-lib/flowy-folder/src/manager.rs
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5530
---
=> Fix space issues

frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart, frontend/resources/translations/en.json
=> feat: collapse space and switch space by shortcuts

CHANGELOG.md, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> chore: bump version 0.6.0

frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
Closes: #5332 
I wasn't able to figure out the concluding reason why, but due to the ReminderBloc acting as a Singleton (basically as a cached service for Reminders throughout our application), on application startup the Startup event would be triggered, but due to eg. window resizing/rendering or similar, it would not be able to finish and thus the reminders in state would not be properly initialized.
I've moved the Started event respectively to Mobile and Desktop first points of contact (their home screens). This is a fix for the immediate problem.
The long-term solution is finding a way to return the Reminder itself along with the DateCell, so that it does not rely on other lazy operations or futures.
=> fix: reminder race condition

frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/theme_upload/theme_upload_view.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/colorscheme.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/plugins/bloc/dynamic_plugin_bloc.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/plugins/service/models/flowy_dynamic_plugin.dart, frontend/appflowy_flutter/test/unit_test/settings/theme_missing_keys_test.dart
If there are missing keys in the light or dark theme file, we simply replace them with default values.
This is not a good way of handling errors, but it's better than failing indiscriminately without any proper feedback.
I've added a `getMissingKeys` to compare and see which values are missing, and written some quick unit tests for it. We should find a way to use it so we can let users know if their theme has missing values.
Relates: #5359
=> fix: make theme uploads more tolerant

frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5601
In some keyboards, the system returns equal as + keycode, while others may return add as + keycode, so add them both as zoom in key.
---
=> feat: add key + as zoom-in key

frontend/rust-lib/flowy-chat/src/chat.rs
=> chore: show ai service error

CHANGELOG.md, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/rust-lib/flowy-folder/src/manager.rs
=> fix: filter chat page when duplicating

frontend/appflowy_flutter/lib/env/env.dart, frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart, frontend/appflowy_flutter/lib/plugins/document/application/document_data_pb_extension.dart, frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart
- set INTERNAL_BUILD = 1 to enable debug logs when building internal package.
---
=> feat: enable debug logs in internal build

frontend/appflowy_flutter/ios/Podfile.lock, frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_home_recent_views.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/recent_space.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_text_cell.dart, frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/inline_page_reference.dart, frontend/appflowy_flutter/lib/workspace/application/recent/cached_recent_service.dart, frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/recent_views_list.dart, frontend/rust-lib/flowy-folder/src/entities/view.rs, frontend/rust-lib/flowy-folder/src/event_handler.rs, frontend/rust-lib/flowy-folder/src/event_map.rs, frontend/rust-lib/flowy-folder/src/manager.rs
fetch the recent views batch and limit the result count.
---
=> feat: optimize the read recent views speed

frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
In https://github.com/AppFlowy-IO/AppFlowy-Cloud/pull/690 , the pg advisory lock has been removed. As a result, if there are concurrent requests to verify a new user's token, only the first request will succeed. In practice, this should rarely happen, and if they do, it's good to throw an error in such case, as concurrent requests like this could be a sign
that there is a bug on the client end.
However, this scenario can happen in test. Cargo execute tests in parallel. Even though unique users and emails are created for most cases, all of them still rely on the admin client to send a request to appflowy cloud in order to generate a sign in url. And all admin client instances share the same user name and email.
This can be resolved if we retry the admin sign in attempt once.
---
=> fix: Add retry for admin client sign in for test

frontend/appflowy_web_app/src/application/database-yjs/selector.ts, frontend/appflowy_web_app/src/application/services/js-services/cache/index.ts, frontend/appflowy_web_app/src/application/services/js-services/index.ts
=> fix: can not display rows when rows overthan 1000

frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart, frontend/rust-lib/flowy-core/src/deps_resolve/user_deps.rs
In some cases, the delete workspace API may return an error even though the deletion actually succeeded. Verify by checking the workspace list again to cover this case.
---
=> fix: try to reopen the first workspace if the workspace deletion failed

frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart, frontend/appflowy_flutter/lib/workspace/application/view_title/view_title_bar_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
Basically, it can reduce the update time cost of a section item from 20-30ms to 2-5ms.
---
=> chore: optimize recent section performance

frontend/appflowy_flutter/lib/plugins/document/document_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_image.dart
ignore case sensitive of image name when dragging image to document
---
=> fix: ignore case sensitive of image name when dragging image to document

frontend/appflowy_flutter/linux/my_application.cc, frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml
fixes #3536
fixes #5306
related thread: https://github.com/flutter/flutter/issues/111453
Tested on KDE Tumbleweed for x11 and Wayland sessions. AppImage recipe was referencing Ubuntu 22.04 sources (Jammy), while the CI builds on Ubuntu-latest (24.04, Noble Numbat)
Before: ![image](https://github.com/user-attachments/assets/ea8dfd69-aa82-4dd5-aa7c-870bcebc1930)
After: ![image](https://github.com/user-attachments/assets/85388cae-aa30-4e2b-9c13-163e59365cf1)
(I don't think there're tests regarding the configs)
=> Fix(Linux): Fixed AppImage build, removed Wayland Header

frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
```
Launching lib/main.dart on macOS in debug mode...
CocoaPods' output:
↳
-- snip --
-> Installing Sentry (8.33.0)
> Git download
> Git download
$ /usr/bin/git clone https://github.com/getsentry/sentry-cocoa.git /var/folders/pj/jl4sz3pj2mv_7ycqnnn7pvjr0000gn/T/d20240903-13323-joyk9s --template= --single-branch --depth 1 --branch 8.33.0
[!] Error installing Sentry
[!] /usr/bin/git clone https://github.com/getsentry/sentry-cocoa.git /var/folders/pj/jl4sz3pj2mv_7ycqnnn7pvjr0000gn/T/d20240903-13323-joyk9s --template= --single-branch --depth 1 --branch 8.33.0
Cloning into '/var/folders/pj/jl4sz3pj2mv_7ycqnnn7pvjr0000gn/T/d20240903-13323-joyk9s'...
warning: Could not find remote branch 8.33.0 to clone.
fatal: Remote branch 8.33.0 not found in upstream origin …
```
=> chore(flutter): bump sentry version to fix building

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_web_app/src-tauri/Cargo.lock, frontend/appflowy_web_app/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml
https://github.com/AppFlowy-IO/AppFlowy-Builder/actions/runs/10679813798/job/29599893581
---
=> fix: build error in release mode

frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/magic_link_sign_in_buttons.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
=> chore(mobile): dismiss the keyboard when tap outside on login

frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart, frontend/appflowy_flutter/macos/Podfile.lock
from 0.6.8 and most recent review, due to introduction of multi-line checklist tasks
- cannot create multi-line tasks from the "add new task" text field
- cannot quickly create checklist tasks in the row detail page
---
=> fix(flutter_desktop): more checklist multiline issues

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/custom_cover_picker_bloc.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/widgets/upload_image_file_widget.dart, frontend/appflowy_flutter/lib/util/default_extensions.dart
Closes: https://github.com/AppFlowy-IO/AppFlowy/issues/5760
Adds webp, gif, and bmp file formats to the default allows.
=> fix: more default image extensions

frontend/appflowy_flutter/integration_test/desktop/board/board_row_test.dart, frontend/appflowy_flutter/lib/plugins/database/application/field/field_info.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/action.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/row.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart, frontend/resources/translations/en.json
Inform the user why inserting a new row before or after a row, or reordering rows is not allowed when there are sorts configured for the current grid view; and give an option to remove sorting in order to continue.
---
=> fix: reordering or creating a row while sorts are active

frontend/appflowy_flutter/integration_test/shared/database_test_op.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_document.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
Closes: #6042 
Missing EditorDropManager caused file block to break Row Detail Document due to this being required to wrap the AppFlowyEditorPage on Desktop. An oversight on my part originally.
=> fix: provider issue in row document

frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
We keep using the old rowMeta even though it's been updated. Please refer to screen recording below to reproduce.
https://github.com/user-attachments/assets/2c26f99a-1fd6-4e60-b9c9-4a481e2174b5
---
=> fix(flutter_desktop): incorrect row meta in row detail page

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
I haven't been able to reproduce the issues with line numbers shifting vertically compared to the lines. Right now the way we have built the Code Block using the Markdown makes the layout of the line numbers reliant on having the same font size and line height as the text to the right of it, I'm assuming the issue might be related to accessibility or something else that shifts the font size.
This PR simply hides line numbers in a code block.
=> fix: hide line numbers in code block

frontend/appflowy_flutter/packages/flowy_svg/lib/src/flowy_svg.dart
As an example, hintColor on mobile is not a fully-opaque gray color, but black with its opacity toned down. When passed to FlowySvg, this color's opacity is cranked back up to 1.0. In the sort panel, both the "no active sorts" text and the sort icon specify this hint color but look completely different. In the second example, notice the plus sign next to the words "new row".
Before:
After:
---
=> fix: semi-transparent colors being forced to full opacity in FlowySvg

frontend/appflowy_flutter/integration_test/desktop/database/database_row_cover_test.dart, frontend/appflowy_flutter/integration_test/desktop/database/database_row_page_test.dart, frontend/appflowy_flutter/integration_test/desktop/document/document_with_cover_image_test.dart, frontend/appflowy_flutter/integration_test/shared/database_test_op.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/board/mobile_board_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/mobile_card_content.dart, frontend/appflowy_flutter/lib/plugins/database/application/row/related_row_detail_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/application/row/row_banner_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_card.dart, frontend/appflowy_flutter/lib/plugins/database/grid/application/row/row_detail_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_media_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart, frontend/appflowy_flutter/lib/plugins/database_document/database_document_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/desktop_cover.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart, frontend/appflowy_flutter/lib/plugins/shared/cover_type_ext.dart, frontend/appflowy_flutter/lib/shared/af_image.dart, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_web_app/src-tauri/Cargo.toml, frontend/resources/translations/en.json, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-database2/src/entities/row_entities.rs, frontend/rust-lib/flowy-database2/src/entities/type_option_entities/media_entities.rs, frontend/rust-lib/flowy-database2/src/event_handler.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/media_type_option/media_type_option.rs, frontend/rust-lib/flowy-database2/tests/database/mock_data/grid_mock_data.rs
Requires: https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/294
TBD
=> fix: row cover improvements

frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_filter.rs
handle the case where the condition is something other than empty and not-empty, and content is empty.
---
=> fix: edge case for text filters

frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_block_action_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/custom_link_preview.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/link_preview_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/shared.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5426
---
=> feat: keep link format when converting preview block to text

frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/filter_editor_bloc.dart, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
https://github.com/user-attachments/assets/bf0b0e74-5489-443b-b34b-4e7b3999365f
---
=> fix: hide editing rows from groups when filters are applied

frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart, frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart, frontend/appflowy_flutter/test/unit_test/editor/transaction_adapter_test.dart
depends on https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/305
If the paragraph in the document wasn't already associated with an external ID and external type, when editing it, the adapter should assign it a new external ID and external type using the existing data.
---
=> fix: potential text empty when editing doc

frontend/appflowy_flutter/lib/plugins/database/calendar/application/unschedule_event_bloc.dart, frontend/rust-lib/flowy-database2/src/entities/calendar_entities.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs, frontend/rust-lib/flowy-database2/tests/database/layout_test/script.rs, frontend/rust-lib/flowy-database2/tests/database/layout_test/test.rs
also revert incorrect test modification. The get_all_calendar_events function should return all events, even those that are unscheduled.
---
=> fix: fetch all calendar events

frontend/appflowy_flutter/integration_test/desktop/grid/grid_row_test.dart, frontend/appflowy_flutter/test/bloc_test/grid_test/field/field_editor_bloc_test.dart, frontend/rust-lib/flowy-database2/src/services/database/database_observe.rs
The database row observe should only edit one view when handling one databaseviewchange. Otherwise, we have a bug like the following
https://github.com/user-attachments/assets/4185313c-182f-49d2-9d4b-c1c5a18723d7
---
=> fix: don't process on every view while only handling one view

frontend/appflowy_web_app/src/application/slate-yjs/command/index.ts, frontend/appflowy_web_app/src/application/slate-yjs/plugins/withYjs.ts, frontend/appflowy_web_app/src/application/slate-yjs/utils/applyToSlate.ts, frontend/appflowy_web_app/src/application/slate-yjs/utils/applyToYjs.ts, frontend/appflowy_web_app/src/application/slate-yjs/utils/convert.ts, frontend/appflowy_web_app/src/application/slate-yjs/utils/positions.ts, frontend/appflowy_web_app/src/application/slate-yjs/utils/yjsOperations.ts, frontend/appflowy_web_app/src/components/_shared/more-actions/MoreActions.tsx, frontend/appflowy_web_app/src/components/editor/__tests__/shortcuts/Markdown.cy.tsx, frontend/appflowy_web_app/src/components/editor/components/blocks/link-preview/LinkPreview.tsx, frontend/appflowy_web_app/src/components/editor/components/blocks/numbered-list/NumberListIcon.tsx, frontend/appflowy_web_app/src/components/editor/components/blocks/quote/Quote.tsx, frontend/appflowy_web_app/src/components/editor/components/leaf/formula/FormulaLeaf.tsx, frontend/appflowy_web_app/src/components/editor/components/toolbar/selection-toolbar/actions/Formula.tsx, frontend/appflowy_web_app/src/components/editor/editor.scss, frontend/appflowy_web_app/src/components/editor/plugins/withDelete.ts, frontend/appflowy_web_app/src/components/editor/utils/markdown.ts
=> fix: supported incremental updates

frontend/rust-lib/flowy-folder/src/manager.rs
=> chore: update logs

frontend/appflowy_flutter/integration_test/desktop/document/document_option_action_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/appflowy_flutter/test/unit_test/document/turn_into/turn_into_test.dart
https://github.com/user-attachments/assets/165c1b4b-bc9f-4abb-9838-b72a9786cdea
---
=> feat: turn into multiple lines

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/emoji_picker_button.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
Calculate the emoji size and emoji button size based on the font size settings for the doc.
https://github.com/user-attachments/assets/e40f28e1-19d6-49ea-a1c6-a440e4628c78
---
=> fix: callout emoji size should follow the document font size

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
=> fix: display paragraph mark only if the block content is empty

frontend/appflowy_flutter/lib/mobile/application/notification/notification_reminder_bloc.dart, frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart, frontend/appflowy_flutter/lib/plugins/document/document_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/insert_page_command.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_block_component.dart, frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/inline_page_reference.dart, frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart, frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/recent_view_tile.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/tab_bar_item.dart
=> fix: show default view name

frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/more_bottom_sheet.dart, frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
I identified an issue where the iOS app would crash due to a GoRouter error when attempting to return to the home screen after deleting a workspace. This pull request includes a fix for the bloc to handle the navigation correctly, ensuring a smooth transition back to the home screen without errors.
IOS app is being released and needs to be resolved as soon as possible!
https://github.com/user-attachments/assets/2b3c793f-5033-4c84-946f-6cf4d24bb42c
```sh
FlutterError (Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.)
``` …
=> fix: crash on delete button press caused by GoRouter

frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
closes: #6444 
I added condition which check if the current user is owner of the workspace then, the owner is eligible to delete spaces created by any of the members, but members only have permission to delete the spaces created by them.
---
=> fix: owner can delete spaces created by other users

frontend/appflowy_web_app/src/application/slate-yjs/command/index.ts, frontend/appflowy_web_app/src/application/slate-yjs/utils/applyToYjs.ts, frontend/appflowy_web_app/src/application/slate-yjs/utils/yjsOperations.ts, frontend/appflowy_web_app/src/components/editor/__tests__/shortcuts/Markdown.cy.tsx, frontend/appflowy_web_app/src/components/editor/components/blocks/toggle-list/ToggleIcon.tsx, frontend/appflowy_web_app/src/components/editor/components/blocks/toggle-list/ToggleList.tsx, frontend/appflowy_web_app/src/components/editor/editor.scss, frontend/appflowy_web_app/src/components/editor/plugins/withInsertText.ts, frontend/appflowy_web_app/src/components/editor/utils/markdown.ts
=> feat: support toggle heading

frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_media_cell_editor.dart
=> fix: mobile media cleanup

frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
- tapping on ai response doesn't hide keyboard
- increase mobile input contentpadding even more
- messages arriving out of order
- input box losing focus after clicking on sample questions
---
=> chore: more ai ui fixes

frontend/scripts/windows_installer/inno_setup_config.iss
The reason windows users see wrong version number, is because our installer doesn't override the .exe file (which has the wrong version number).
=> chore: inno setup ignore version on .exe

README.md, frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_ai_message_bloc.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_entity.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_service.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_stream.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_loading.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
=> chore: parse chat response

frontend/appflowy_flutter/integration_test/desktop/document/document_with_toggle_list_test.dart, frontend/appflowy_flutter/lib/plugins/document/document_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart, frontend/resources/translations/en.json
closes #6776
closes #6737 
---
=> feat: support click to create content inside empty toggle list

frontend/appflowy_flutter/lib/plugins/database/application/tab_bar_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_group.rs, frontend/rust-lib/flowy-database2/src/services/database_view/views.rs, frontend/rust-lib/flowy-database2/src/services/group/action.rs, frontend/rust-lib/flowy-database2/src/services/group/controller.rs, frontend/rust-lib/flowy-database2/src/services/group/controller_impls/date_controller.rs, frontend/rust-lib/flowy-database2/src/services/group/controller_impls/default_controller.rs, frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/multi_select_controller.rs, frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/single_select_controller.rs, frontend/rust-lib/flowy-database2/src/services/group/group_builder.rs, frontend/rust-lib/flowy-database2/tests/database/group_test/url_group_test.rs
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/6816
~~This fix introduces a regression to the calculation feature. Therefore, another solution needs to be found~~
Sometimes a bug fix is dirty. But sometimes a dirty bug fix works.
The test doesn't pass on main
---
=> fix: RwLock race condition during group controller instantiation

frontend/appflowy_flutter/integration_test/desktop/uncategorized/tabs_test.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/chat.dart, frontend/appflowy_flutter/lib/plugins/blank/blank.dart, frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart, frontend/appflowy_flutter/lib/plugins/database_document/database_document_plugin.dart, frontend/appflowy_flutter/lib/plugins/document/document.dart, frontend/appflowy_flutter/lib/plugins/trash/trash.dart, frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/flowy_tab.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/tabs_manager.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/tab_bar_item.dart, frontend/resources/translations/en.json
=> fix: tabs lr 0.7.6

frontend/appflowy_flutter/lib/workspace/application/home/home_setting_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_layout.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/size.dart
illustration of bug:
https://github.com/user-attachments/assets/afe00f43-cbb2-4ed4-9732-497f3000810d
cause: negative resize offsets are no longer allowed
---
=> fix(desktop): resize sidebar menu regression

frontend/appflowy_flutter/integration_test/desktop/document/document_with_date_reminder_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/child_page_transaction_handler.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/date_transaction_handler.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_block.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_transaction_handler.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/editor_transaction_handler.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/editor_transaction_service.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/mention_transaction_handler.dart
resolve #6913
~~TODO: fix, test~~ (done)
---
=> fix(flutter): implement mention date transaction handler

frontend/appflowy_flutter/integration_test/desktop/uncategorized/code_block_language_selector_test.dart, frontend/appflowy_flutter/integration_test/desktop_runner_9.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/selectable_item_list_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_language_selector.dart
solves #6905
https://github.com/user-attachments/assets/8efcba00-211e-4977-98b4-840de312af9e
---
=> feat: able to select language for the code block by arrow keys (#6905)

frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/grid_header.dart
Relates: #3503 - I fixed an issue related to this as well, resizing window shouldn't displace the two scrollviews anymore, not sure if this solves the bug described in 3503 though.
Added scrollbar to the inline grid
=> fix: inline grid launch review

frontend/appflowy_flutter/integration_test/desktop/uncategorized/code_block_language_selector_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/selectable_item_list_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_language_selector.dart
---
- Using `ClampingScrollPhysics` to standardize the scroll animation when selecting language with arrow keys
- Fix the index error when deleting text and then using the up or down arrow key
=> fix: the index error when deleting text and then using the up or down arrow key

frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart, frontend/appflowy_flutter/integration_test/desktop/document/document_find_menu_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/context_menu/custom_context_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_plain_text.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart, frontend/resources/translations/en.json
To fix #7023 
- add `Paste as plain text` item to ContextMenu
- pasting the original Markdown data will automatically convert it
=> feat: add option to paste plain text

frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_editor_style.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/numbered_list/numbered_list_icon.dart
also add more decimal places to line height in chat message text
Editor:
Chat:
---
=> fix: numbered list misalignment

frontend/resources/translations/fr-FR.json
Hi AppFlowy team,
I'm a native French speaker. 
I've added several translations in French (fr-FR).
Feel free to review and merge.
Love AppFlowy, keep up the good work! 📝
Preview the messages on https://inlang.com/github.com/alxdrcirilo/AppFlowy .
=> Update translations (fr-FR)

frontend/scripts/docker-buildfiles/Dockerfile
Specify the `cargo-binstall` version as 1.10.17.
```log
#30 94.55 error: failed to compile `cargo-binstall v1.10.18`, intermediate artifacts can be found at `/tmp/cargo-installOmw6K4`.
#30 94.55 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
#30 94.55 
#30 94.55 Caused by:
#30 94.55   rustc 1.80.1 is not supported by the following package:
#30 94.55     home@0.5.11 requires rustc 1.81
#30 94.55      Summary Successfully installed cargo-make! Failed to install cargo-binstall (see error(s) above).
#30 94.55 error: some crates failed to install
#30 ERROR: process "/bin/sh -c source ~/.cargo/env && cargo install cargo-make cargo-binstall --locked" did not complete successfully: exit code: 101
------
> [builder 18/23] RUN …
```
=> fix: docker ci

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
Related to #7049
> last one is embedded link on a text, every after using the feature once, i can't open the menu again, i need to close the keyboard first to use it again
=> fix: toolbar menu not showing beacase keyboard height is not updated in time

frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_metadata.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/message_util.dart, frontend/resources/translations/en.json
requires https://github.com/AppFlowy-IO/AppFlowy/pull/7083
1. error toast when trying to open a page that no longer exists
2. success toast when finished saving a message to a page
---
=> chore: add toast messages for ai chat interactions

frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/collaborative_workspace_test.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
https://github.com/user-attachments/assets/cf452d98-b740-4978-ac85-e7c0c67e023c
https://github.com/user-attachments/assets/98b7740d-18f2-4390-8e08-c324777943ed
https://github.com/user-attachments/assets/1baf3d5c-687a-4b77-9c15-9223034503c3
https://github.com/user-attachments/assets/01ba8615-a4e7-45d2-b52b-cfc2d98df15e
---
=> fix(flutter_desktop): workspace menu ui issues

frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_select_sources_cubit.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_bottom_sheet.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_menu.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart, frontend/resources/translations/en.json
[chore: expand current space in select sources or when saving to a page](https://github.com/AppFlowy-IO/AppFlowy/commit/3bccd592f23ea37d6802851e2b179f2eac233515)
[chore: hide non-document views while saving to page](https://github.com/AppFlowy-IO/AppFlowy/commit/4ed830c78395b09b7810b9ab3ef4f15aa3386984)
[chore: add buttons when saving to page](https://github.com/AppFlowy-IO/AppFlowy/commit/0f1e6c1ca600e2ff6047c35b741a2ea623d8f0af)
---
=> feat(flutter_desktop): save ai message to page improvements

frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart, frontend/appflowy_flutter/test/unit_test/editor/transaction_adapter_test.dart
if the value in Delta's attributes is false, we should set the value to null instead. Because on Yjs or YDelta, canceling format must use the null value. If we use false, the update will be rejected.
---
=> fix: convert false value in attributes to null

frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/date_time_text_field.dart
Closes: #6788 
This just adds some loose restrictions to the Date and Time text fields in the Date Picker.
This is done to help the user write the correct format. It's not completely enforced according to the date format, but does limit the user a bit more.
24-hours - Can only enter 5 characters (12:34) and only enter numbers and `:`
12-hours - Can enter `AM` and `PM` as well (12:34 AM) 8 characters
Date field - Can only enter 12 characters (Unsure if should limit it to 10) and allows `.`, `-`, and `/` characters other than numbers.
=> chore: add loose restrictions to date time text field

frontend/appflowy_flutter/integration_test/desktop/cloud/cloud_runner.dart, frontend/appflowy_flutter/integration_test/desktop/cloud/sidebar/sidebar_icon_test.dart, frontend/appflowy_flutter/integration_test/desktop/document/document_sub_page_test.dart, frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_icon_test.dart, frontend/appflowy_flutter/integration_test/mobile/document/page_style_test.dart, frontend/appflowy_flutter/integration_test/shared/base.dart, frontend/appflowy_flutter/integration_test/shared/common_operations.dart, frontend/appflowy_flutter/integration_test/shared/emoji.dart, frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_page_card.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_icon.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_block_component.dart, frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon.dart, frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart, frontend/appflowy_flutter/lib/shared/icon_emoji_picker/recent_icons.dart, frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart, frontend/appflowy_flutter/test/unit_test/util/recent_icons_test.dart
Fix issue #7101
- fix: error displaying in Page style
- fix: complete the filter logic of icon picker
- fix: error displaying in Favorite/Recent page
- fix: the color picker showed when tapping down
- fix: icons are not supported in subpage blocks
---
=> Fix icon picker issues on mobile 

frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
https://github.com/AppFlowy-IO/AppFlowy/issues/7145
---
=> fix: context menu should not auto show when collaborating

frontend/appflowy_flutter/lib/env/cloud_env.dart, frontend/appflowy_flutter/lib/env/env.dart, frontend/appflowy_flutter/lib/plugins/shared/share/constants.dart, frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart, frontend/appflowy_flutter/lib/workspace/application/command_palette/command_palette_bloc.dart, frontend/rust-lib/flowy-core/src/deps_resolve/search_deps.rs, frontend/rust-lib/flowy-search/src/document/handler.rs
- Enable AI search
- Remove 'www' in the default web url
---
=> chore: enable AI seach

frontend/rust-lib/flowy-search/src/document/handler.rs
the iterator was consumed by `find()`, it can't be reused in next loop.
---
=> fix: search results were filtered accidentally

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/custom_image_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/resizeable_image.dart, frontend/appflowy_flutter/lib/shared/appflowy_network_image.dart, frontend/appflowy_flutter/test/unit_test/image/appflowy_network_image_test.dart
When the maximum retry count exceeds the `maxRetries`, it should be reset to avoid affecting the next round of image loading, such as when the page is reopened.
---
=> fix: retry count should be clear if the value exceeds max retries

frontend/appflowy_flutter/integration_test/desktop/cloud/sidebar/sidebar_icon_test.dart, frontend/appflowy_flutter/integration_test/desktop/command_palette/folder_search_test.dart, frontend/appflowy_flutter/integration_test/desktop/document/document_callout_test.dart, frontend/appflowy_flutter/integration_test/shared/common_operations.dart, frontend/appflowy_flutter/integration_test/shared/emoji.dart, frontend/appflowy_flutter/integration_test/shared/expectation.dart, frontend/appflowy_flutter/lib/plugins/base/icon/icon_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart, frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
Remove `iconContent` from `IconsData` to avoid unnecessary data cost
---
=> chore: remove iconContent from IconsData

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
=> fix: pass alwaysDistributeColumnWidths to simple table block

frontend/appflowy_flutter/lib/mobile/presentation/setting/appearance/appearance_setting_group.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/appearance/text_scale_setting.dart, frontend/resources/translations/en.json
=> chore: rename [Font Scale Factor] to [Display Size]

frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_shortcuts_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_alert_dialog.dart
Fix the issue: #7171
Before the fix: 
After the fix:
dark | light
---|---
---
=> chore: cancel button not visible in [Reset to Default] for shortcuts(#7171)

frontend/appflowy_flutter/integration_test/desktop/cloud/cloud_runner.dart, frontend/appflowy_flutter/integration_test/desktop/cloud/database/database_image_test.dart, frontend/appflowy_flutter/integration_test/desktop/cloud/database/database_test_runner.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/resizeable_image.dart, frontend/appflowy_flutter/lib/shared/appflowy_network_image.dart
Regression from https://github.com/AppFlowy-IO/AppFlowy/pull/7128/files#diff-28074cd2d3a105117d3b2d12feeced5be3a8ed37e62e088eabfd38d3b5b96c3dL56. 
> It can't fetch the user profile in the kanban board, so the image keeps loading in this case.
---
=> fix: editor stuck on image loading loop when uploading image in row document

frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_text_message.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
NB: the selectable field of `FlowyText` has been removed. The recommendation from Flutter is that we use Text + SelectableArea instead of SelectableText.
~~Also, this PR would work better with a newer version of flutter as this method doesn't work with double tap to select a word and triple tap to select paragraph in the current flutter version~~ (EDIT: Updated to 3.27.4)
---
=> fix(flutter_desktop): selection going missing while scrolling

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/layouts/image_browser_layout.dart
The issue is caused by non-limited height of `ImageBrowserLayout`
After adding specific height:
---
=> fix: gallery not rendering in row page

frontend/appflowy_flutter/integration_test/desktop/uncategorized/share_markdown_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ask_ai_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/util/ask_ai_node_extension.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/multi_image_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/custom_image_node_parser.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/custom_paragraph_node_parser.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/database_node_parser.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/document_markdown_parsers.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/sub_page_node_parser.dart, frontend/appflowy_flutter/lib/plugins/shared/share/export_tab.dart, frontend/appflowy_flutter/lib/plugins/shared/share/share_bloc.dart, frontend/appflowy_flutter/lib/shared/markdown_to_document.dart, frontend/appflowy_flutter/lib/workspace/application/export/document_exporter.dart, frontend/appflowy_flutter/test/unit_test/markdown/markdown_parser_test.dart
To fix #3343
- support exporting multiple images
- support exporting database as csv file
- support exporting date or reminder
- support exporting subpage and page reference as link
- export markdown-related files as a zip file
---
=> fix: support exporting more content to markdown

frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart
=> fix: default page name should be empty when creating

frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_setting_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/ai/ai_settings_group.dart, frontend/appflowy_flutter/lib/workspace/application/favorite/favorite_bloc.dart, frontend/appflowy_flutter/lib/workspace/application/settings/ai/settings_ai_bloc.dart
=> feat: switch ai mode on mobile

frontend/appflowy_flutter/integration_test/desktop/document/document_alignment_test.dart, frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_math_equation_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/custom_text_align_command.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_shortcut.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_shortcuts_view.dart, frontend/resources/translations/en.json
To fix #7331 
- Insert inline math eqaution : ctrl + shift + e
- Align text center: ctrl + shift + e -> ctrl + shift + c
---
=> fix: add shortcut to create Inline Math Equation

frontend/appflowy_flutter/lib/shared/version_checker/version_checker.dart, frontend/appflowy_flutter/lib/startup/tasks/auto_update_task.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/7424
The auto updater should not block the launch process. It can be run without await.
---
=> fix: auto updater should not block the launch process

frontend/appflowy_flutter/lib/workspace/presentation/widgets/user_avatar.dart
Fix the issue of the `UserAvatar` component not displaying network images as circular.
---
=> fix: potential issues with displaying CircleAvatar

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/7433
- Added the callout block type to convertibleBlockTypes to support converting it to paragraph when using backspace.
---
=> fix: unable to delete the callout block when it's in the first line

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
=> fix: title position working incorrectly with document width setting

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/bulleted_list/bulleted_list_icon.dart
Center the bulleted icon in the column block.
---
=> fix: bulleted list icon does not center in the columns

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_gesture_detector.dart
1. When generating, disable scrolling along with any mouse interaction. Such interactions will pop a confirmation dialog to cancel and remove
2. When not generating, enable scrolling, but don't allow any other sort of mouse interaction, including but not limited to:
- tapping
- tap and hold
- tap and drag
- three finger drag
---
=> fix: ai writer gestures

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/callout_node_parser.dart
There isn't a call out block in markdown, so we convert to quote instead. We also include the icon (emoji) in the first line to preserve the information. Icons, however, can't be converted.
---
=> fix: don't include icon while exporting callout to md

frontend/rust-lib/flowy-folder/src/manager.rs
Currently, if the trash's parent and child hierarchy forms a cycle, the app will fail to launch due to segmentation fault, caused by infinite recursion. There is already a method in AppFlowy Collab which address this, so we just need to reuse the same method.
---
=> fix: prevent segfault due to infinite recursion in trash view

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_plain_text.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/7514
If the HTML can't be parsed during pasting, fall back to the plain text option.
---
=> fix: unable to paste iframe in editor

frontend/appflowy_flutter/lib/plugins/document/document_page.dart
The BlocProvider seems to determine that it isn't necessary to instantiate, leading to the state's view not being correct.
---
=> fix: continue writing edge case

frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/quote/quote_block_component.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
https://github.com/user-attachments/assets/87402a67-9059-4e2b-9dd7-5c8257fb572e
- Keep the same node id on the AI chat page when generating an answer.
---
=> fix: quote block flashes on the AI chat page while generating an answer.

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_shortcuts.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/quote/quote_block_shortcuts.dart
- Use padding instead of positioned in cover title and cover icon
- Ingore shift+enter in callout/quote and fallback to system behavior
---
=> fix: optimize cover title position offset calculation

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_format_toolbar_items.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_hightlight_color_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_link_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_placeholder_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_text_align_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_text_color_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/more_option_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/text_heading_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/text_suggestions_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/toolbar_id_enum.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/resources/translations/en.json
- The tooltip text should only upper case the first letter of the first word
- The tooltip text on windows should not have `\`
- Add shortcut hint for some of the `more option` menu buttons
---
=> fix: some toolbar text display error

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/appflowy_date_picker_base.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/desktop_date_picker.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/date_picker_dialog.dart
- Firstly,  change the `include time`
- Then click the reminder, I got an errror
```
======== Exception caught by gesture library =======================================================
The following assertion was thrown while dispatching a pointer event:
A _PopoverStateNotifier was used after being disposed.
Once you have called dispose() on a _PopoverStateNotifier, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:183:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:190:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:416:27)
#3 …
```
=> fix: using date picker with @ menu get some errors

frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_handler.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_settings_manager.dart, frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_stream_manager.dart
Separate chat_bloc logic into multiple files
=> refactor: chat bloc

frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml
---
Update collab version in order to address the issue solved by this PR: https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/381
=> chore: update collab version for row deserialization fix
