README.md
Added this command in step 3 of rust install process 
source $HOME/.cargo/env
=> [DOCS] Added Command line source update command

backend/Dockerfile
use source from github repo
solving ticket https://github.com/AppFlowy-IO/appflowy/issues/13
=> fix the docker build

backend/doc/database_setup.md
=> add install sqlx-cli

backend/doc/database_struct.md
=> add Table Struct

.github/workflows/ci.yaml
This will save flutter clone time & bandwidth.
=> ci: flutter git clone depth 1

doc/BUILD_ON_LINUX.md, doc/BUILD_ON_WINDOWS.md, frontend/scripts/makefile/protobuf.toml
1. doc\BUILD_ON_WINDOWS.md
- rustup.exe with parameter to install rust without prompt
2. frontend/scripts/makefile/protobuf.toml
- add a sub task to check if protoc is presented in PATH
=> [Instruction] Slightly update steps of BUILD_ON_WINDOWS.md

README.md
https://github.com/Homebrew/homebrew-cask/pull/115114
=> Add brew install instructions

doc/TRANSLATION.md
Documentation for contributors to contribute translations
=> Add translation documentation

doc/BUILD_ON_LINUX.md
Marked Arch Linux as being verified (however protobuf isn't working yet)
Restructured the steps to better separate concerns
Added instructions for Arch Linux
Highlighted some steps that may be overlooked by someone who already has Flutter installed (or that I found confusing during installation
Moved environment settings to Step 5
=> Updated Linux build document

doc/BUILD_ON_LINUX.md, frontend/scripts/build_sdk.sh
Fixed a typo (aarch64 -> x86)
Since I was here : Capitalized the OS names
=> Fix build sdk sh

doc/BUILD_ON_LINUX.md
Fixed the numbering (Github doesn't do numbering correctly...)
Added step showing how to start coding in VS Code
Changed server step from Optional to TBD
=> Edited Linux Instructions

frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/lib/generated/codegen_loader.g.dart
=> Changed string "Untitles" to "Untitled"

doc/BUILD_ON_WINDOWS.md
=> build on windows 10 X86_64 verified

frontend/app_flowy/assets/translations/zh_CN.json, frontend/app_flowy/lib/generated/codegen_loader.g.dart, frontend/app_flowy/lib/startup/tasks/application_widget.dart
=> Add i18n/zh-CN support

README.md, doc/TRANSLATION.md
Put the steps for existing translations first, this will be the most used case.
Simplified the wording of the 'add new language' case.
@irfanbacker See if you approve of how I did this :)
=> Modify translation.md

README.md, doc/DOMAIN_DRIVEN_DESIGN.md, doc/TRANSLATION.md
=> Modify domain driven design.md

doc/BUILD_ON_DOCKER.md, doc/docker-buildfiles/Dockerfile, doc/docker-buildfiles/docker-compose.yml
FR: https://github.com/AppFlowy-IO/appflowy/issues/163
=> Added support for docker image in docs/docker-buildfiles

frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/assets/translations/it_IT.json, frontend/app_flowy/assets/translations/zh_CN.json, frontend/app_flowy/lib/generated/codegen_loader.g.dart, frontend/app_flowy/lib/generated/locale_keys.g.dart, frontend/app_flowy/lib/workspace/presentation/stack_page/home_stack.dart, frontend/app_flowy/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart, frontend/app_flowy/macos/Flutter/GeneratedPluginRegistrant.swift, frontend/app_flowy/pubspec.lock, frontend/app_flowy/pubspec.yaml
This pull request adds a menu item button to the question mark button in the lower right corner of the application, which will copy system info to the clipboard when pressed.
This is my first PR to AppFlowy, so please let me know if I forgot to do something or did something wrong.
fixes #145
=> Add debug info button

frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/assets/translations/it_IT.json, frontend/app_flowy/assets/translations/zh_CN.json, frontend/app_flowy/lib/startup/tasks/application_widget.dart, frontend/app_flowy/lib/workspace/presentation/theme/theme_model.dart, frontend/app_flowy/lib/workspace/presentation/widgets/menu/widget/menu_user.dart
[Note: I am submitting a PR for @rileyhawk1417 as I rebased the commit that these changes were based on.]
* Theme toggle allows the user to switch between light and dark theme with ease.
=> Theme Toggle Button for AppFlowy. Created by @rileyhawk1417

frontend/app_flowy/assets/translations/it_IT.json
Reverts AppFlowy-IO/appflowy#265
=> Revert "Update it_IT.json"

frontend/app_flowy/assets/translations/it_IT.json
settings were not in the correct json group.
=> Fix Italian translation

frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/assets/translations/fr-CA.json, frontend/app_flowy/assets/translations/it-IT.json, frontend/app_flowy/assets/translations/zh-CN.json, frontend/app_flowy/lib/startup/tasks/application_widget.dart, frontend/app_flowy/lib/workspace/application/appearance.dart, frontend/app_flowy/lib/workspace/presentation/settings/settings_dialog.dart, frontend/app_flowy/lib/workspace/presentation/settings/widgets/settings_appearance_view.dart, frontend/app_flowy/lib/workspace/presentation/settings/widgets/settings_language_view.dart, frontend/app_flowy/lib/workspace/presentation/stack_page/doc/doc_stack_page.dart, frontend/app_flowy/lib/workspace/presentation/stack_page/doc/widget/toolbar/color_picker.dart, frontend/app_flowy/lib/workspace/presentation/stack_page/doc/widget/toolbar/header_button.dart, frontend/app_flowy/lib/workspace/presentation/widgets/menu/widget/menu_trash.dart, frontend/app_flowy/lib/workspace/presentation/widgets/menu/widget/menu_user.dart, frontend/app_flowy/macos/Runner/Info.plist, frontend/app_flowy/packages/flowy_infra/lib/language.dart
**NOT READY TO MERGE**
I've set it up in a similar way to theme, however the app is not rebuilding when language is changed. raising PR to get help
=> Language switcher

README.md
Removed the last `.` after **Twitter**.
Closing #291
=> Improved the project's README

Makefile.toml
=> fix: makefile for commitlint

frontend/app_flowy/lib/startup/tasks/application_widget.dart
set EasyLocalization to not save language locally.
=> fix: put back Russian language

.github/workflows/notify_on_strings_update.yml, .github/workflows/release.yml
Added automatic notifications:
- When file with english UI strings updated
- When new release is published
Sends notifications to discord by webhook
Didn't make any tests
=> Add automatic notifications

frontend/app_flowy/assets/translations/en.json
Reverts AppFlowy-IO/AppFlowy#321
=> Revert "ci: test web hook"

.github/workflows/release.yml, .github/workflows/release_docker.yml
Fixes #344 
NOTE: For it to work, we need an admin to configure an account in Docker Hub and set the credentials in environment variables in GithUb as explained in https://docs.docker.com/ci-cd/github-actions/#set-up-a-docker-project
=> Push docker image to Docker Hub

README.md, frontend/scripts/docker-buildfiles/Dockerfile, frontend/scripts/docker-buildfiles/README.md
I made other improvements to the docker image:
* Reduce image size again, to 894MB
* Adjust permissions and remove need to run xhost
* Run appflowy as unprivileged user
* Add README file for more information
=> Multiple improvements in docker image

frontend/app_flowy/assets/translations/pt-BR.json, frontend/app_flowy/lib/startup/tasks/app_widget.dart, frontend/app_flowy/packages/flowy_infra/lib/language.dart
Note: It should be added to the docs that the file `frontend/app_flowy/packages/flowy_infra/lib/language.dart` also need to be updated, so the translation can appear on the app.
=> Add portuguese translation

frontend/app_flowy/assets/translations/ca-ES.json, frontend/app_flowy/lib/startup/tasks/app_widget.dart, frontend/app_flowy/packages/flowy_infra/lib/language.dart
I have added support for the Catalan language, used in some parts of Spain.
=> Add catalan translation

frontend/app_flowy/assets/translations/hu-HU.json, frontend/app_flowy/lib/startup/tasks/app_widget.dart, frontend/app_flowy/packages/flowy_infra/lib/language.dart
Added support for the Hungarian language.
=> Add Hungarian translation

frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/cell/select_option_cell/select_option_editor.dart
=> Clicking on option capsule will now create and select the new opt value

frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/cell/select_option_cell/select_option_editor.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/cell/select_option_cell/text_field.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/header/type_option/select_option_editor.dart
The PR is meant to address the issue #523
=> fix: Close renaming window when creating another new option

frontend/app_flowy/lib/workspace/presentation/widgets/emoji_picker/src/emoji_button.dart
This PR is meant to resolve issue #502
=> Close emoji picker window on page switch

frontend/app_flowy/assets/translations/pt-BR.json, frontend/app_flowy/assets/translations/pt-PT.json
Hi, I translated your project into European Portuguese and while at it I fixed some of the spelling and grammar mistakes on the Brazilian Portuguese version. See if this is all right with you guys, thanks!
=> Added European Portuguese (pt-PT) translation and fixed Brazilian Portuguese translation

frontend/app_flowy/lib/workspace/application/grid/block/block_listener.dart, frontend/app_flowy/lib/workspace/application/grid/block/block_service.dart, frontend/app_flowy/lib/workspace/application/grid/cell/cell_service/cache.dart, frontend/app_flowy/lib/workspace/application/grid/cell/cell_service/cell_service.dart, frontend/app_flowy/lib/workspace/application/grid/cell/cell_service/context_builder.dart, frontend/app_flowy/lib/workspace/application/grid/grid_bloc.dart, frontend/app_flowy/lib/workspace/application/grid/grid_header_bloc.dart, frontend/app_flowy/lib/workspace/application/grid/grid_service.dart, frontend/app_flowy/lib/workspace/application/grid/row/row_bloc.dart, frontend/app_flowy/lib/workspace/application/grid/row/row_detail_bloc.dart, frontend/app_flowy/lib/workspace/application/grid/row/row_service.dart, frontend/app_flowy/lib/workspace/application/grid/setting/property_bloc.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/grid_page.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/cell/cell_builder.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/row/grid_row.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/row/row_detail.dart, frontend/rust-lib/flowy-grid/src/entities/row_entities.rs
1. Move GridRowCacheService to GridBlockCacheService
2. Move GridCellCacheService to GridRowCacheService
=> refactor: grid block cache

frontend/app_flowy/packages/flowy_editor/example/lib/plugin/image_node_widget.dart, frontend/app_flowy/packages/flowy_editor/example/lib/plugin/text_node_widget.dart, frontend/app_flowy/packages/flowy_editor/lib/document/attributes.dart, frontend/app_flowy/packages/flowy_editor/lib/document/node.dart, frontend/app_flowy/packages/flowy_editor/lib/document/state_tree.dart, frontend/app_flowy/packages/flowy_editor/lib/document/text_delta.dart, frontend/app_flowy/packages/flowy_editor/lib/editor_state.dart, frontend/app_flowy/packages/flowy_editor/lib/operation/operation.dart, frontend/app_flowy/packages/flowy_editor/test/delta_test.dart
This PR is implementing the inverting operation of `TextDelta`.
=> Feat: invert delta

frontend/app_flowy/lib/workspace/application/grid/field/field_editor_bloc.dart, frontend/app_flowy/lib/workspace/application/grid/field/field_service.dart, frontend/app_flowy/lib/workspace/application/grid/field/field_type_option_edit_bloc.dart, frontend/app_flowy/lib/workspace/application/grid/field/type_option/multi_select_type_option.dart, frontend/app_flowy/lib/workspace/application/grid/field/type_option/single_select_type_option.dart, frontend/app_flowy/lib/workspace/application/grid/field/type_option/type_option_service.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/header/field_cell.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/header/field_editor.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/header/field_type_option_editor.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/header/grid_header.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/header/type_option/builder.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/row/row_detail.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/widgets/toolbar/grid_property.dart
Refactor some classes according to the grid_field.plantuml. 
https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/architecture/frontend/grid
=> refactor: field editor bloc

frontend/app_flowy/packages/flowy_editor/example/lib/plugin/image_node_widget.dart, frontend/app_flowy/packages/flowy_editor/example/lib/plugin/text_node_widget.dart, frontend/app_flowy/packages/flowy_editor/lib/document/node.dart, frontend/app_flowy/packages/flowy_editor/lib/document/state_tree.dart, frontend/app_flowy/packages/flowy_editor/lib/editor_state.dart, frontend/app_flowy/packages/flowy_editor/lib/flowy_editor.dart, frontend/app_flowy/packages/flowy_editor/lib/operation/operation.dart, frontend/app_flowy/packages/flowy_editor/lib/operation/transaction.dart, frontend/app_flowy/packages/flowy_editor/lib/operation/transaction_builder.dart
This PR is implementing a builder of `Transaction` to help the widget to build the transactions from the editor state.
=> Feat: transaction builder

frontend/app_flowy/packages/flowy_editor/assets/document.json, frontend/app_flowy/packages/flowy_editor/lib/document/node.dart, frontend/app_flowy/packages/flowy_editor/lib/document/state_tree.dart, frontend/app_flowy/packages/flowy_editor/lib/document/text_delta.dart, frontend/app_flowy/packages/flowy_editor/test/delta_test.dart
This PR is implementing the conversation between `Delta` and JSON.
=> Feat: delta to json

frontend/scripts/install_dev_env/install_linux.sh, frontend/scripts/install_dev_env/install_macos.sh
Also fixed colors for Linux.
Now displays messages in yellow so that they stick out more.
=> fix: colors and brew install for mac

frontend/app_flowy/packages/flowy_editor/example/lib/plugin/text_node_widget.dart, frontend/app_flowy/packages/flowy_editor/lib/editor_state.dart, frontend/app_flowy/packages/flowy_editor/lib/operation/transaction_builder.dart, frontend/app_flowy/packages/flowy_editor/lib/undo_manager.dart
This PR is implementing a simple UndoManager for the FlowyEditor.
Known issue:
- Wrong cursor after redo(Will be fixed in another PR)
=> Feat: undo manager

frontend/app_flowy/packages/flowy_editor/example/lib/plugin/text_node_widget.dart, frontend/app_flowy/packages/flowy_editor/lib/editor_state.dart, frontend/app_flowy/packages/flowy_editor/lib/undo_manager.dart
=> Feat: redo

frontend/app_flowy/lib/workspace/presentation/settings/widgets/settings_appearance_view.dart, frontend/app_flowy/lib/workspace/presentation/widgets/toggle/toggle.dart, frontend/app_flowy/lib/workspace/presentation/widgets/toggle/toggle_style.dart
https://github.com/AppFlowy-IO/AppFlowy/issues/697
=> feat: implement new toggle

frontend/app_flowy/lib/workspace/presentation/settings/widgets/settings_language_view.dart
=> feat: Initial implementation of updated language selector ui based on figma

frontend/app_flowy/packages/flowy_editor/lib/document/node.dart, frontend/app_flowy/packages/flowy_editor/lib/operation/operation.dart, frontend/app_flowy/packages/flowy_editor/lib/operation/transaction_builder.dart, frontend/app_flowy/packages/flowy_editor/test/operation_test.dart
This PS is implementing operation transforming for `TransactionBuilder` to avoid index error in index/delete operations.
- Fix issue of the parent of Node
=> Feat: operation transform

frontend/rust-lib/Cargo.lock, shared-lib/Cargo.lock
https://github.com/Freaky/faccess/pull/1
=> fix: update faccess version from 0.2.3 to 0.2.4 for fixing linux-arm64 building

frontend/app_flowy/.gitignore, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/grid_page.dart, frontend/app_flowy/lib/workspace/presentation/plugins/grid/src/layout/sizes.dart
=> fixes #698 display the number of rows

frontend/app_flowy/packages/flowy_infra_ui/lib/src/flowy_overlay/list_overlay.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/src/flowy_overlay/overlay_container.dart
=> fix: ProviderNotFound exception in overlay demo example

frontend/scripts/install_dev_env/install_macos.sh
Case insensitive to accepting the installation of Rust
Use Source to refresh the current window
=> chore: fix install script errors

frontend/app_flowy/assets/translations/pl-PL.json, frontend/app_flowy/lib/startup/tasks/app_widget.dart, frontend/app_flowy/packages/flowy_infra/lib/language.dart
This PR adds a Polish translation to the App.
Changes include:
- Add pl-PL.json including the new translation.
- Updated app_widget.dart with the new language entry
- Updated language.dart with the new language entry
Build and run the project.
Open settings choose Polski and the app should show the correct translations.
=> feat: Add Polish translation

frontend/app_flowy/packages/flowy_editor/lib/service/selection_service.dart
https://github.com/AppFlowy-IO/AppFlowy/issues/570
Selecting the paragraph when triple tapping the text.
=> Feat: handle triple tap for flowy editor

frontend/app_flowy/packages/flowy_editor/lib/src/document/node.dart, frontend/app_flowy/packages/flowy_editor/lib/src/document/text_delta.dart, frontend/app_flowy/packages/flowy_editor/lib/src/extensions/text_node_extensions.dart, frontend/app_flowy/packages/flowy_editor/lib/src/infra/html_converter.dart, frontend/app_flowy/packages/flowy_editor/lib/src/operation/transaction_builder.dart, frontend/app_flowy/packages/flowy_editor/lib/src/render/rich_text/flowy_rich_text.dart, frontend/app_flowy/packages/flowy_editor/lib/src/service/internal_key_event_handlers/arrow_keys_handler.dart, frontend/app_flowy/packages/flowy_editor/lib/src/service/internal_key_event_handlers/copy_paste_handler.dart, frontend/app_flowy/packages/flowy_editor/lib/src/service/internal_key_event_handlers/delete_text_handler.dart, frontend/app_flowy/packages/flowy_editor/test/delta_test.dart
=> Fix: emoji position and unicode issues

frontend/app_flowy/packages/flowy_editor/lib/src/service/internal_key_event_handlers/copy_paste_handler.dart, frontend/app_flowy/packages/flowy_editor/lib/src/service/internal_key_event_handlers/default_key_event_handlers.dart, frontend/app_flowy/packages/flowy_editor/lib/src/service/internal_key_event_handlers/delete_text_handler.dart, frontend/app_flowy/packages/flowy_editor/lib/src/service/internal_key_event_handlers/page_up_down_handler.dart, frontend/app_flowy/packages/flowy_editor/lib/src/service/internal_key_event_handlers/select_all_handler.dart
=> Feat: handle edit keys

frontend/app_flowy/packages/flowy_infra_ui/lib/widget/dialog/styled_dialogs.dart
=> fix: closing rename dialog on escape key press

frontend/app_flowy/lib/workspace/presentation/home/home_layout.dart, frontend/app_flowy/lib/workspace/presentation/home/home_screen.dart, frontend/app_flowy/lib/workspace/presentation/home/home_stack.dart
=> [PR] Layout of window's icon

frontend/app_flowy/packages/flowy_editor/lib/src/document/selection.dart, frontend/app_flowy/packages/flowy_editor/lib/src/infra/html_converter.dart, frontend/app_flowy/packages/flowy_editor/lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
Copy the style as HTML, inlcluding:
- italic
- underline
- strikethrough
=> Feat: copy styles

frontend/app_flowy/packages/flowy_editor/lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
Parse the link from the pasting text.
=> Feat: paste url from plain text

frontend/app_flowy/packages/appflowy_editor/example/lib/main.dart, frontend/app_flowy/packages/appflowy_editor/lib/appflowy_editor.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/editor_state.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/infra/log.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/checkbox_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/input_service.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/copy_paste_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/delete_text_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/slash_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/keyboard_service.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/render_plugin_service.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/scroll_service.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/selection_service.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/undo_manager.dart, frontend/app_flowy/packages/appflowy_editor/pubspec.yaml, frontend/app_flowy/packages/appflowy_editor/test/infra/log_test.dart
https://github.com/AppFlowy-IO/AppFlowy/issues/876
=> feat: [improvements] integrate logging library in AppFlowyEditor

frontend/app_flowy/packages/appflowy_editor/lib/src/operation/operation.dart, frontend/app_flowy/packages/appflowy_editor/test/legacy/operation_test.dart, frontend/rust-lib/Cargo.lock, shared-lib/Cargo.lock, shared-lib/lib-ot/Cargo.toml, shared-lib/lib-ot/src/core/document/attributes.rs, shared-lib/lib-ot/src/core/document/document.rs, shared-lib/lib-ot/src/core/document/document_operation.rs, shared-lib/lib-ot/src/core/document/mod.rs, shared-lib/lib-ot/src/core/document/node.rs, shared-lib/lib-ot/src/core/document/position.rs, shared-lib/lib-ot/src/core/document/transaction.rs, shared-lib/lib-ot/src/core/mod.rs, shared-lib/lib-ot/src/errors.rs, shared-lib/lib-ot/tests/main.rs
This PR is implementing the document model in Rust.
Missing:
- Unit tests
- Documentations
- Operation transforming.
=> Feat: document model in rust

frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/lib/plugins/grid/presentation/widgets/row/grid_row.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/menu.dart, frontend/app_flowy/lib/workspace/presentation/home/navigation.dart
=> fix: added tooltip for grid row action buttons

frontend/app_flowy/packages/appflowy_editor/lib/src/extensions/editor_state_extensions.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/extensions/text_node_extensions.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/rich_text_style.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/toolbar/toolbar_item.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/toolbar/toolbar_item_widget.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/toolbar/toolbar_widget.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/default_text_operations/format_rich_text_style.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/toolbar_service.dart, frontend/app_flowy/packages/appflowy_editor/test/render/toolbar/toolbar_item_widget_test.dart, frontend/app_flowy/packages/appflowy_editor/test/service/internal_key_event_handlers/update_text_style_by_command_x_handler_test.dart, frontend/app_flowy/packages/appflowy_editor/test/service/toolbar_service_test.dart
=> feat: #931 highlight the status of the currently selected style in toolbar

frontend/scripts/docker-buildfiles/Dockerfile
=> Fix: docker build

frontend/app_flowy/packages/appflowy_board/lib/src/utils/log.dart, frontend/rust-lib/flowy-grid/src/services/field/type_options/selection_type_option/select_option.rs, frontend/rust-lib/flowy-grid/src/services/grid_view_manager.rs, frontend/rust-lib/flowy-grid/src/services/group/configuration.rs, frontend/rust-lib/flowy-grid/src/services/group/controller.rs
Save the card status after moving to 'No status' column
=> chore: save move to no status card

.github/workflows/flowy_editor_test.yml, frontend/app_flowy/pubspec.lock
=> fix: #955 upgrade build_resolvers to 2.0.9

frontend/app_flowy/packages/appflowy_editor/lib/src/document/selection.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/default_selectable.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/flowy_rich_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/arrow_keys_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/copy_paste_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/default_key_event_handlers.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/legacy/arrow_keys_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/slash_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/selection_service.dart, frontend/app_flowy/packages/appflowy_editor/test/infra/test_raw_key_event.dart, frontend/app_flowy/packages/appflowy_editor/test/service/internal_key_event_handlers/arrow_keys_handler_test.dart
=> feat: #953 improve arrow keys handler

frontend/app_flowy/packages/appflowy_editor/example/lib/plugin/image_node_widget.dart, frontend/app_flowy/packages/appflowy_editor/example/lib/plugin/network_image_node_widget.dart, frontend/app_flowy/packages/appflowy_editor/example/lib/plugin/youtube_link_node_widget.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/document/node_iterator.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/document/text_delta.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/extensions/node_extensions.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/image/image_node_widget.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/bulleted_list_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/checkbox_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/default_selectable.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/flowy_rich_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/heading_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/number_list_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/quoted_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/rich_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/selection/selectable.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/selection_service.dart, frontend/app_flowy/packages/appflowy_editor/pubspec.yaml
https://pub.dev/packages/appflowy_editor/score
=> Fix analysis issues

frontend/app_flowy/packages/appflowy_editor/README.md, frontend/app_flowy/packages/appflowy_editor/lib/appflowy_editor.dart
https://pub.dev/packages/appflowy_editor/score
=> chore: fix link error in readme

.github/workflows/flowy_editor_test.yml, frontend/app_flowy/packages/appflowy_editor/README.md, frontend/app_flowy/packages/appflowy_editor/test/render/toolbar/toolbar_widget_test.dart
=> feat: support codecov

.github/workflows/dart_lint.yml, .github/workflows/dart_test.yml, .github/workflows/rust_lint.yml, .github/workflows/rust_test.yml
https://github.com/AppFlowy-IO/AppFlowy/issues/973
=> chore: set paths in github actions to reduce the ci time

shared-lib/lib-ot/src/codec/markdown/markdown_encoder.rs, shared-lib/lib-ot/src/codec/markdown/mod.rs, shared-lib/lib-ot/src/rich_text/attributes.rs
=> refactor: Migrate the markdown feature from Dart to Rust

frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/page_up_down_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart
=> fix: splited shortcut event functions

frontend/app_flowy/packages/appflowy_editor/lib/src/operation/transaction_builder.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/number_list_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/backspace_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/copy_paste_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/enter_without_shift_in_text_node_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/number_list_helper.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/whitespace_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/undo_manager.dart, frontend/app_flowy/packages/appflowy_editor/test/legacy/undo_manager_test.dart, frontend/app_flowy/packages/appflowy_editor/test/service/internal_key_event_handlers/enter_without_shift_in_text_node_handler_test.dart
Merge after #903
This PR is implementing the number list in AppflowyEditor.
1. Insert a line with numbered subtype(User press `Enter` to break a line):
1. Make the number of this line is the successor of the previous line.
2. Make the following lines’s number incremental.
2. Delete a line with numbered subtype(User press `Backspace` to delete a line):
1. Make the following lines’s number incremental.
3. The user input number and press `.`:
1. If the number provided by the user is the successor of the previous line:
1. Turn this line into numbered subtype.
2. Make the following lines’s number incremental.
2. Otherwise, ignore it.
4. The user press `Backspace` after the number:
1. Make the following lines incremental from number `1`
Indent/detent is not implemented yet.
=> Feat: number list

frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/grid_header.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/toolbar/grid_toolbar.dart
=> fix: Icon theme on setting and new column icon

frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/field_type_list.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/date.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/multi_select.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/number.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/select_option.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/single_select.dart, frontend/app_flowy/packages/appflowy_popover/lib/popover.dart
=> Fix: UI issues of popover

frontend/app_flowy/assets/translations/pt-BR.json
- Updated a missing string in English;
- Removed some anglicism to proper Portuguese;
- Fixed some terms, typo in general for Brazilian Portuguese language.
=> chore: Update Brazilian Portuguese Localization

frontend/app_flowy/assets/translations/pt-BR.json
- Added missings strings;
- Cleaned up my latter changes;
- Fixed some indentations and spaces
Translation 100% completed 🇧🇷 !
=> chore: Update 2: Brazilian Portuguese Localization

frontend/rust-lib/flowy-grid/src/event_handler.rs, frontend/rust-lib/flowy-grid/src/macros.rs, frontend/rust-lib/flowy-grid/src/services/cell/cell_operation.rs, frontend/rust-lib/flowy-grid/src/services/grid_editor.rs, frontend/rust-lib/flowy-grid/src/services/grid_view_manager.rs, frontend/rust-lib/flowy-grid/tests/grid/group_test/test.rs
=> fix: switch field type in board

frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/assets/translations/es-VE.json, frontend/app_flowy/assets/translations/fr-FR.json, frontend/app_flowy/assets/translations/id-ID.json, frontend/app_flowy/assets/translations/ja-JP.json, frontend/app_flowy/assets/translations/pt-BR.json, frontend/app_flowy/assets/translations/ru-RU.json, frontend/app_flowy/assets/translations/zh-CN.json, frontend/app_flowy/assets/translations/zh-TW.json, frontend/rust-lib/flowy-grid/src/services/field/type_options/date_type_option/date_tests.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/date_type_option/date_type_option_entities.rs
=> fix: duplicate time format str

frontend/app_flowy/lib/plugins/doc/document.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/app/header/add_button.dart, frontend/app_flowy/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart, frontend/app_flowy/lib/workspace/presentation/widgets/pop_up_action.dart, frontend/app_flowy/packages/flowy_infra_ui/example/lib/overlay/overlay_screen.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/src/flowy_overlay/list_overlay.dart
=> fix: auto resize Action list

frontend/app_flowy/packages/appflowy_board/lib/src/utils/log.dart, frontend/app_flowy/packages/appflowy_board/lib/src/widgets/board_data.dart, frontend/app_flowy/packages/appflowy_board/lib/src/widgets/board_group/group.dart, frontend/app_flowy/packages/appflowy_board/lib/src/widgets/board_group/group_data.dart, frontend/app_flowy/packages/appflowy_board/lib/src/widgets/reorder_flex/drag_state.dart, frontend/app_flowy/packages/appflowy_board/lib/src/widgets/reorder_flex/drag_target.dart, frontend/app_flowy/packages/appflowy_board/lib/src/widgets/reorder_flex/drag_target_interceptor.dart, frontend/app_flowy/packages/appflowy_board/lib/src/widgets/reorder_flex/reorder_flex.dart, frontend/app_flowy/packages/appflowy_board/lib/src/widgets/reorder_phantom/phantom_controller.dart, frontend/app_flowy/packages/appflowy_board/lib/src/widgets/reorder_phantom/phantom_state.dart
=> fix: calculate overlap

frontend/app_flowy/assets/translations/fr-FR.json
I worked on translating the new words added recently to French !
This PR closes #462
=> feature: Translate new words to French

frontend/app_flowy/packages/appflowy_editor/lib/src/commands/edit_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/commands/format_built_in_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/commands/format_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/commands/text_command_infra.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/document/selection.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/editor_state.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/link_menu/link_menu.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/checkbox_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/flowy_rich_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/toolbar/toolbar_item.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/default_text_operations/format_rich_text_style.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/editor_service.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/input_service.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/space_on_web_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart, frontend/app_flowy/packages/appflowy_editor/test/service/internal_key_event_handlers/space_on_web_handler_test.dart
=> feat: add commands and update checkbox logic

frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/assets/translations/zh-CN.json, frontend/app_flowy/lib/plugins/grid/presentation/widgets/footer/grid_footer.dart
fix the grid footer button  for use  LocaleKeys instead of 'New row' .
add some chinese translation.
=> locale fix

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/extension.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_editor.dart
=> fix: improve look of select option list

frontend/app_flowy/assets/translations/fr-FR.json
As usually, I worked on translating the new English UI strings to French.
=> fix : added French translations

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/date_cell/date_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/date.dart
=> feat: use appflowy styled toggle widget in date settings

frontend/app_flowy/lib/workspace/presentation/home/menu/app/header/header.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/app/section/item.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/menu_user.dart
=> feat: elide sidebar text

frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/markdown_syntax_to_styled_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart
uses traditional markdown format.
requires the prefix of http or https
=> feat: added markdown links

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/date_cell/date_editor.dart
Added some padding around the header and daysOfWeek, and changed the selected decoration to a more boxy-design
Before:
After:
=> fix: improve look of calendar

.github/workflows/ci.yaml
=> feat: support windows platform in ci.yaml

frontend/app_flowy/lib/workspace/presentation/home/menu/app/section/item.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/style_widget/hover.dart, frontend/app_flowy/pubspec.lock
https://user-images.githubusercontent.com/71320345/194712292-40abd405-abe7-4dc4-8e81-1e54d86812c3.mp4
=> fix: regression on hover effect persisting after closing menu

frontend/app_flowy/assets/translations/ko-KR.json, frontend/app_flowy/lib/startup/tasks/app_widget.dart, frontend/app_flowy/packages/flowy_infra/lib/language.dart
Added translation for Korean (ko_KR)
=> Feat: Translation for Korean ko_KR

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/cell_container.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/checkbox_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/date_cell/date_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/number_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/text_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/url_cell/url_cell.dart
=> fix: grid cell abnormal on click behaviour

.github/workflows/release.yml
Resolved https://github.com/AppFlowy-IO/AppFlowy/issues/1279
=> fix: #1279 macOS package size

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/text_field.dart
=> horizontal scroll on multiselect options

frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/exit_editing_mode_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart, frontend/app_flowy/packages/appflowy_editor/test/service/internal_key_event_handlers/exit_editing_mode_handler_test.dart
https://user-images.githubusercontent.com/11863087/196391615-3be87f09-213e-4b61-94c6-9a3d4dc7cb83.mov
=> feat: implement new shortcut: press Escape to exit editing mode

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/text_cell.dart
=> fix: half hidden textfield in name field

frontend/app_flowy/lib/plugins/grid/application/cell/select_option_editor_bloc.dart, frontend/app_flowy/lib/plugins/grid/application/cell/select_option_service.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/text_field.dart, frontend/app_flowy/test/bloc_test/grid_test/select_option_bloc_test.dart, frontend/app_flowy/test/widget_test/select_option_text_field_test.dart
=> feat: alter some select option editor bloc events and add tests

frontend/app_flowy/assets/translations/sv.json, frontend/app_flowy/lib/startup/tasks/app_widget.dart, frontend/app_flowy/packages/flowy_infra/lib/language.dart
Hi,
Here's Swedish translation if wanted.
=> Add Swedish translation

frontend/app_flowy/lib/plugins/doc/application/share_bloc.dart, frontend/app_flowy/lib/plugins/doc/document.dart, frontend/app_flowy/lib/workspace/application/markdown/src/delta_markdown_encoder.dart, frontend/app_flowy/packages/flowy_infra_ui/example/pubspec.lock, frontend/app_flowy/packages/flowy_infra_ui/flowy_infra_ui_platform_interface/pubspec.lock, frontend/app_flowy/packages/flowy_infra_ui/flowy_infra_ui_web/pubspec.lock, frontend/app_flowy/packages/flowy_infra_ui/pubspec.lock, frontend/app_flowy/packages/flowy_sdk/example/pubspec.lock, frontend/app_flowy/packages/flowy_sdk/pubspec.lock, frontend/app_flowy/pubspec.lock, frontend/app_flowy/pubspec.yaml
=> feat: support markdown export and customize save path

frontend/rust-lib/flowy-grid/src/services/field/type_options/selection_type_option/select_type_option.rs
=> fix: avoid overlapping option colors

frontend/app_flowy/packages/appflowy_editor/lib/src/service/default_text_operations/format_rich_text_style.dart, frontend/app_flowy/packages/appflowy_editor/test/service/default_text_operations/format_rich_text_style_test.dart
I tried to tackle this issue https://github.com/AppFlowy-IO/AppFlowy/issues/1325.
Hopefully it is the correct way to fix it.
=> fix: remove attribute if it already exists on the node

frontend/app_flowy/lib/plugins/board/application/board_bloc.dart, frontend/app_flowy/lib/plugins/board/application/board_data_controller.dart, frontend/app_flowy/lib/plugins/doc/application/doc_bloc.dart, frontend/app_flowy/lib/plugins/doc/document_page.dart, frontend/app_flowy/lib/plugins/grid/application/grid_bloc.dart, frontend/app_flowy/lib/plugins/grid/application/grid_data_controller.dart, frontend/app_flowy/lib/plugins/grid/application/grid_service.dart, frontend/app_flowy/lib/startup/deps_resolver.dart, frontend/app_flowy/lib/user/application/user_listener.dart, frontend/app_flowy/lib/user/presentation/router.dart, frontend/app_flowy/lib/user/presentation/skip_log_in_screen.dart, frontend/app_flowy/lib/user/presentation/splash_screen.dart, frontend/app_flowy/lib/workspace/application/home/home_bloc.dart, frontend/app_flowy/lib/workspace/presentation/home/home_screen.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/menu.dart, frontend/app_flowy/test/bloc_test/grid_test/util.dart, frontend/app_flowy/test/bloc_test/menu_test/app_bloc_test.dart, frontend/rust-lib/flowy-folder/src/entities/workspace.rs, frontend/rust-lib/flowy-folder/src/event_map.rs, frontend/rust-lib/flowy-folder/src/services/workspace/controller.rs, frontend/rust-lib/flowy-folder/src/services/workspace/event_handler.rs
=> test: add app bloc test

CHANGELOG.md
=> chore: Improved Changelog.md

frontend/app_flowy/lib/plugins/grid/presentation/widgets/common/text_field.dart
fixes [#1369](https://github.com/AppFlowy-IO/AppFlowy/issues/1369)
Hello ! you can find bellow the fix in the video in order to have an idea.
[fix_input_focus.webm](https://user-images.githubusercontent.com/98823356/198847816-731eef2f-3e2a-4035-a1c6-63ad15186cdd.webm)
=> fix request focus when InputTextField is added

frontend/app_flowy/packages/appflowy_popover/lib/src/popover.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/style_widget/hover.dart
=> fix: disappearing hover effect on popover trigger

frontend/app_flowy/lib/plugins/grid/application/grid_data_controller.dart, frontend/app_flowy/lib/plugins/grid/application/row/row_cache.dart, frontend/app_flowy/test/bloc_test/grid_test/grid_bloc_test.dart, frontend/app_flowy/test/bloc_test/grid_test/util.dart, frontend/rust-lib/flowy-revision/src/rev_persistence.rs
1. add documentation for grid_bloc_test.dart
2. try to fix unstable test result
=> fix: grid_bloc_test.dart

frontend/app_flowy/lib/workspace/application/appearance.dart, frontend/app_flowy/packages/flowy_infra/lib/theme.dart, frontend/rust-lib/flowy-user/src/entities/user_setting.rs
~requires: #1432 to avoid test errors due to removal of the `fromType` constructor~
=> feat: initial steps to allow changing the app font

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/cell_accessory.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/date_cell/date_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/extension.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/footer/grid_footer.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/field_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/grid_header.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/row/row_detail.dart, frontend/app_flowy/lib/user/presentation/welcome_screen.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/app/section/item.dart, frontend/app_flowy/lib/workspace/presentation/widgets/toggle/toggle.dart, frontend/app_flowy/packages/flowy_infra/lib/color_extension.dart, frontend/app_flowy/packages/flowy_infra/lib/size.dart, frontend/app_flowy/packages/flowy_infra/lib/text_style.dart, frontend/app_flowy/packages/flowy_infra/lib/theme.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/style_widget/scrolling/styled_scroll_bar.dart
=> chore: add textTheme to AppTheme

frontend/app_flowy/lib/plugins/board/presentation/card/board_text_cell.dart, frontend/app_flowy/lib/plugins/board/presentation/card/board_url_cell.dart
=> chore: use theme.of(context).texttheme in board

frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/lib/plugins/grid/application/field/field_controller.dart, frontend/app_flowy/lib/plugins/grid/application/filter/filter_create_bloc.dart, frontend/app_flowy/lib/plugins/grid/application/filter/filter_menu_bloc.dart, frontend/app_flowy/lib/plugins/grid/application/filter/text_filter_editor_bloc.dart, frontend/app_flowy/lib/plugins/grid/application/row/row_cache.dart, frontend/app_flowy/lib/plugins/grid/application/row/row_list.dart, frontend/app_flowy/lib/plugins/grid/presentation/grid_page.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/filter/choicechip/choicechip.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/filter/choicechip/text.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/filter/create_filter_list.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/filter/menu.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/toolbar/filter_button.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/style_widget/button.dart, frontend/app_flowy/pubspec.lock, frontend/app_flowy/pubspec.yaml, frontend/app_flowy/test/bloc_test/home_test/app_bloc_test.dart, frontend/rust-lib/flowy-document/src/services/migration.rs, frontend/rust-lib/flowy-grid/src/services/filter/controller.rs, frontend/rust-lib/flowy-grid/src/services/group/controller_impls/select_option_controller/util.rs, frontend/rust-lib/flowy-grid/src/services/view_editor/editor.rs, frontend/rust-lib/flowy-grid/tests/grid/filter_test/script.rs, frontend/rust-lib/flowy-grid/tests/grid/filter_test/select_option_filter_test.rs
1. Show the filters after creating the default filter
2. Insert/Delete rows one by one in order to keep the index right
3. Show the filter's condition in filter item
=> Fix/filter UI bugs

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/date_cell/date_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/date_cell/date_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/date.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/widget/rounded_input_field.dart
| main | this patch |
| ------- | --------------- |
| ![image](https://user-images.githubusercontent.com/71320345/203263680-e81b632e-2d12-4eba-afa3-6bcc2d34df14.png)| ![image](https://user-images.githubusercontent.com/71320345/203262601-949a433f-8d95-41a9-878c-df94bc322fd9.png) |
| ![image](https://user-images.githubusercontent.com/71320345/203262917-3fa98007-002e-4db8-b591-b69e475a12cd.png) | ![image](https://user-images.githubusercontent.com/71320345/203263868-784cdc25-1f14-4499-92dc-55556740eeea.png) |
=> chore: date cell & header editor UI + move to theme.of(context).texttheme

frontend/app_flowy/lib/plugins/grid/application/row/row_cache.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/row/row_detail.dart, frontend/rust-lib/flowy-grid/src/entities/block_entities.rs, frontend/rust-lib/flowy-grid/src/services/block_manager.rs, shared-lib/grid-rev-model/src/grid_block.rs
=> fix: options don't refresh after moving the card

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/text_cell.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/filter/choicechip/select_option/select_option.dart
=> fix: click enter to submit the text content

frontend/app_flowy/packages/appflowy_editor/lib/src/render/toolbar/toolbar_widget.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/selection_service.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/toolbar_service.dart
=> fix: [Bug] Text formatting toolbar disappear under layout 

frontend/app_flowy/assets/translations/ca-ES.json, frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/assets/translations/es-VE.json, frontend/app_flowy/assets/translations/fr-CA.json, frontend/app_flowy/assets/translations/fr-FR.json, frontend/app_flowy/assets/translations/hu-HU.json, frontend/app_flowy/assets/translations/id-ID.json, frontend/app_flowy/assets/translations/it-IT.json, frontend/app_flowy/assets/translations/ja-JP.json, frontend/app_flowy/assets/translations/pl-PL.json, frontend/app_flowy/assets/translations/pt-BR.json, frontend/app_flowy/assets/translations/ru-RU.json, frontend/app_flowy/assets/translations/sv.json, frontend/app_flowy/assets/translations/tr-TR.json, frontend/app_flowy/assets/translations/zh-CN.json, frontend/app_flowy/assets/translations/zh-TW.json, frontend/app_flowy/lib/startup/tasks/app_widget.dart, frontend/app_flowy/lib/workspace/application/appearance.dart, frontend/app_flowy/lib/workspace/presentation/settings/widgets/settings_appearance_view.dart, frontend/app_flowy/packages/flowy_infra/lib/theme.dart, frontend/app_flowy/packages/flowy_infra_ui/lib/style_widget/button.dart, frontend/rust-lib/flowy-user/src/entities/user_setting.rs
=> feat: switch between light and dark theme based on system settings

frontend/app_flowy/packages/appflowy_editor/example/lib/pages/simple_editor.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/image/image_node_widget.dart
=> fix: #1586 deleting an image causes the editor to enter a bad state

frontend/rust-lib/flowy-grid/src/services/field/type_options/text_type_option/text_tests.rs
=> test: UnitTest Switching from Multi to text

frontend/app_flowy/packages/appflowy_board/lib/src/widgets/reorder_flex/reorder_flex.dart
=> Fix scrollToBottom for macos see #1609

frontend/rust-lib/flowy-grid/src/event_handler.rs, frontend/rust-lib/flowy-grid/src/services/cell/cell_operation.rs, frontend/rust-lib/flowy-grid/src/services/cell/type_cell_data.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/checkbox_type_option/checkbox_type_option.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/date_type_option/date_tests.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/date_type_option/date_type_option.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/date_type_option/date_type_option_entities.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/number_type_option/number_type_option.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/selection_type_option/checklist_type_option.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/selection_type_option/multi_select_type_option.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/selection_type_option/select_type_option.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/selection_type_option/single_select_type_option.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/text_type_option/text_type_option.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/type_option.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/type_option_cell.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/url_type_option/url_tests.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/url_type_option/url_type_option.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/url_type_option/url_type_option_entities.rs, frontend/rust-lib/flowy-grid/src/services/sort/controller.rs, frontend/rust-lib/flowy-grid/src/services/view_editor/editor.rs, frontend/rust-lib/flowy-grid/tests/grid/field_test/test.rs, frontend/rust-lib/flowy-sync/src/client_grid/grid_revision_pad.rs, shared-lib/Cargo.lock, shared-lib/grid-rev-model/src/grid_rev.rs
Fix the number value of cell that doesn't refresh after typing the value.
=> fix: number cell format

frontend/rust-lib/flowy-grid/src/services/field/type_options/checkbox_type_option/checkbox_type_option.rs
@appflowy please help me review, as mentioned on Discord, i was ran into the error while trying to execute individual unit-test :
=> feat: switching from text type to checkbox type

frontend/app_flowy/lib/plugins/board/presentation/toolbar/board_setting.dart, frontend/app_flowy/lib/plugins/board/presentation/toolbar/board_toolbar.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/toolbar/filter_button.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/toolbar/grid_group.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/toolbar/grid_property.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/toolbar/setting_button.dart
- padding improvements similar to #1605
- combine show/hide button with field editor button
=> chore: grid/kanban toolbar UI improvements

frontend/rust-lib/flowy-grid/src/services/field/type_options/checkbox_type_option/checkbox_tests.rs
=> test: add more cases for checkout_box_description_test

frontend/app_flowy/lib/workspace/presentation/home/menu/app/section/section.dart
Regression caused by upgrading the Flutter version
fixes #1402
=> fix: menu section scrollcontroller not attached

frontend/app_flowy/lib/workspace/application/settings/settings_location_cubit.dart, frontend/app_flowy/lib/workspace/presentation/settings/widgets/settings_file_customize_location_view.dart
=> fix: the settings view of path configuration is not displayed completely

frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/extension.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/select_option_editor.dart, frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/select_option_cell/text_field.dart, frontend/app_flowy/test/widget_test/select_option_text_field_test.dart
=> chore: add close button in select option tags for select option textfield

frontend/app_flowy/lib/workspace/application/settings/settings_location_cubit.dart, frontend/app_flowy/lib/workspace/presentation/settings/widgets/settings_file_customize_location_view.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/default_selectable.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/rich_text/flowy_rich_text.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/render/selection/selectable.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/arrow_keys_handler.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/selection_service.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart, frontend/app_flowy/packages/appflowy_editor/test/service/internal_key_event_handlers/arrow_keys_handler_test.dart
https://user-images.githubusercontent.com/11863087/210517210-a0f181aa-2599-44dd-9b07-9610cfc13597.mov
=> #1624 Support Shift + Option + Left/Right Arrow

frontend/app_flowy/packages/appflowy_editor/README.md, frontend/app_flowy/packages/appflowy_editor/documentation/importing.md, frontend/app_flowy/packages/appflowy_editor/example/lib/home_page.dart, frontend/app_flowy/packages/appflowy_editor/example/macos/Podfile.lock, frontend/app_flowy/packages/appflowy_editor/lib/appflowy_editor.dart, frontend/app_flowy/packages/appflowy_editor/lib/src/plugins/quill_delta/delta_document_encoder.dart, frontend/app_flowy/packages/appflowy_editor/test/plugins/quill_delta/delta_document_encoder_test.dart
NOT support font size, text align, and nested numbered list yet.
=> feat: #1649 [FR] Convert quill delta to appflowy document

frontend/rust-lib/flowy-database/migrations/2023-01-06-032859_folder_rev_snapshot/down.sql, frontend/rust-lib/flowy-database/migrations/2023-01-06-032859_folder_rev_snapshot/up.sql, frontend/rust-lib/flowy-database/src/schema.rs, frontend/rust-lib/flowy-folder/src/manager.rs, frontend/rust-lib/flowy-folder/src/services/persistence/rev_sqlite/folder_snapshot_sqlite_impl.rs, frontend/rust-lib/flowy-folder/src/services/persistence/rev_sqlite/mod.rs, frontend/rust-lib/flowy-revision/src/rev_snapshot.rs
Generate snapshot for AppFlowy folder after user editor
=> chore: save folder snapshot with custom config

frontend/app_flowy/assets/translations/en.json, frontend/app_flowy/lib/plugins/calendar/calendar.dart, frontend/app_flowy/lib/plugins/calendar/presentation/calendar_page.dart, frontend/app_flowy/lib/plugins/calendar/presentation/layout/sizes.dart, frontend/app_flowy/lib/plugins/calendar/presentation/toolbar/calendar_toolbar.dart, frontend/app_flowy/pubspec.lock, frontend/app_flowy/pubspec.yaml
Adds the [calendar_view](https://pub.dev/packages/calendar_view) package and use it in the calendar plugin. Does not support displaying events yet.
=> chore: add calendar_view package

.github/workflows/release.yml, frontend/Makefile.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/flowy-database/Cargo.toml
Need help fixing the cross-platform build config.
=> ci: support aarch64

frontend/app_flowy/packages/appflowy_editor_plugins/lib/src/emoji_picker/src/default_emoji_picker_view.dart
before:
https://user-images.githubusercontent.com/8122139/212498641-94840ff9-f9f0-4bb5-9dbd-213435492882.mp4
after:
https://user-images.githubusercontent.com/8122139/212498643-810c693c-4c05-4f4b-9424-39a58e942341.mp4
=> perf(emoji picker): use Gridview.builder

frontend/app_flowy/lib/workspace/application/appearance.dart, frontend/app_flowy/lib/workspace/application/home/home_setting_bloc.dart, frontend/app_flowy/lib/workspace/presentation/home/home_layout.dart, frontend/app_flowy/lib/workspace/presentation/home/home_screen.dart, frontend/app_flowy/lib/workspace/presentation/home/home_stack.dart, frontend/app_flowy/lib/workspace/presentation/home/hotkeys.dart, frontend/app_flowy/lib/workspace/presentation/home/menu/menu.dart, frontend/app_flowy/lib/workspace/presentation/home/navigation.dart, frontend/rust-lib/flowy-user/src/entities/user_setting.rs
solves #690
extended `AppearanceSettingsPB` with
- `is_menu_collapsed` - the current visibility state of the menu
- `menu_offset` - the current offset of the default menu width
=> feat: save menu appearance

frontend/app_flowy/lib/plugins/grid/application/field/field_controller.dart, frontend/rust-lib/flowy-grid/src/services/field/type_options/type_option_cell.rs, frontend/rust-lib/flowy-grid/src/services/field/type_options/url_type_option/url_type_option.rs, frontend/rust-lib/flowy-grid/src/services/group/configuration.rs, frontend/rust-lib/flowy-grid/src/services/group/controller_impls/mod.rs, frontend/rust-lib/flowy-grid/src/services/group/controller_impls/select_option_controller/util.rs, frontend/rust-lib/flowy-grid/src/services/group/controller_impls/url_controller.rs, frontend/rust-lib/flowy-grid/src/services/group/group_util.rs, frontend/rust-lib/flowy-grid/tests/grid/cell_test/test.rs, frontend/rust-lib/flowy-grid/tests/grid/grid_editor.rs, frontend/rust-lib/flowy-grid/tests/grid/group_test/script.rs, frontend/rust-lib/flowy-grid/tests/grid/group_test/test.rs, shared-lib/grid-rev-model/src/group_rev.rs
=> feat: support group by url in kanban board

frontend/app_flowy/packages/appflowy_editor_plugins/assets/images/delete.svg, frontend/app_flowy/packages/appflowy_editor_plugins/lib/src/code_block/code_block_node_widget.dart, frontend/app_flowy/packages/appflowy_editor_plugins/lib/src/infra/svg.dart, frontend/app_flowy/packages/appflowy_editor_plugins/lib/src/math_ equation/math_equation_node_widget.dart, frontend/app_flowy/packages/appflowy_editor_plugins/pubspec.yaml
=> fix: #1732 the actions of an image look different than the ones of a code block

frontend/app_flowy/packages/appflowy_board/example/lib/multi_board_list_example.dart, frontend/app_flowy/packages/appflowy_board/lib/src/widgets/board.dart, frontend/app_flowy/packages/appflowy_board/lib/src/widgets/board_group/group.dart
=> chore: add config to allow groups to take minimal vertical space if possible

frontend/rust-lib/flowy-client-sync/src/client_database/block_revision_pad.rs, frontend/rust-lib/flowy-database/src/event_handler.rs, frontend/rust-lib/flowy-database/src/services/block_editor.rs, frontend/rust-lib/flowy-database/src/services/mod.rs, frontend/rust-lib/flowy-database/src/services/retry.rs, shared-lib/lib-infra/src/retry/future.rs, shared-lib/lib-ws/src/ws.rs
potential failure to read the data of the row while some one hold the writer
=> fix: potential failure to read the data of the row

frontend/app_flowy/lib/core/helpers/helpers.dart, frontend/app_flowy/lib/core/helpers/target_platform.dart, frontend/app_flowy/lib/main.dart, frontend/app_flowy/lib/window/app_window.dart, frontend/app_flowy/lib/window/window.dart
This is much cleaner and better encapsulated. Sets up an area for further window management in the future.
Does not try to initialize on mobile or web, which would crash.
=> Refactor app window logic

frontend/app_flowy/lib/core/network_monitor.dart, frontend/app_flowy/pubspec.lock
Missing case causing static analysis error that is blocking the build.
=> fix(network_monitor): add missing case for `other` network type

frontend/appflowy_flutter/lib/plugins/document/document_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/smart_edit_toolbar_item.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/src/commands/command_extension.dart
* replace the smart edit icon.
* fix the smart edit text range is wrong in some cases.
=> fix: smart edit bugs

frontend/appflowy_flutter/packages/appflowy_editor/test/core/document/path_test.dart
issue #1120 
- Add test for appflowy_editor/lib/src/core/document/path.dart
=> feat: add test for appflowy_editor path

frontend/appflowy_flutter/packages/appflowy_editor/test/core/document/attributes_test.dart
- Add tests for attributes.dart present in appflowy_editor/lib/core/document
=> feat: add test for appflowy_editor attributes

frontend/appflowy_flutter/assets/translations/pt-BR.json
Hi there AppFlowy team 👋🏽 
- Fix typos;
- Fix inconsistencies;
- Removed duplicated block strings.
Note: There are some word by word translated texts that I still need to figure out how to adapt properly; though, do believe most of strings are good to go! Please review!
=> chore: Update 3: Brazilian Portuguese Localization

frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/selection_service.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/toolbar_service.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/render/rich_text/toolbar_rich_text_test.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/service/internal_key_event_handlers/format_style_handler_test.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/service/toolbar_service_test.dart
=> fix: #1778

frontend/appflowy_flutter/lib/plugins/database_view/calendar/application/calendar_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_cal_bloc.dart, frontend/appflowy_flutter/lib/plugins/trash/src/trash_cell.dart
=> fix: #1942 utc timestamp being parsed as local time

frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/cover/cover_node_widget.dart
Fix cover image overflow issue. Fix #1916
=> fix(appflowy_flutter): fix cover image overflow #1916

frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/util/learn_more_action.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/auto_completion_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/smart_edit_node_widget.dart
=> feat: open gitbook openAI link when tapping learn more button

frontend/Makefile.toml, frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/service/openai_client.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/auto_completion_plugins.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/smart_edit_action.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/smart_edit_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/smart_edit_toolbar_item.dart, frontend/appflowy_flutter/lib/user/application/user_listener.dart, frontend/appflowy_flutter/lib/util/debounce.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_user_view.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/src/commands/command_extension.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/src/core/transform/transaction.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/command/command_extension_test.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/core/transform/transaction_test.dart, frontend/rust-lib/flowy-folder/src/services/workspace/controller.rs, frontend/scripts/windows_installer/inno_setup_config.iss
=> release 0.1.1

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/integration_test/switch_folder_test.dart, frontend/appflowy_flutter/lib/plugins/document/document_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/grid/grid_menu_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/grid/grid_view_menu_item.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/appflowy_editor.dart
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/2047
=> feat: create a new grid from the document slash menu

frontend/appflowy_flutter/lib/plugins/document/application/share_bloc.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/parsers/code_block_node_parser.dart, frontend/appflowy_flutter/test/unit_test/editor/share_markdown_test.dart
Code block parser implementation to support markdown code format
Fixes #1834
=> fix : Code block parser implementation  

frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/keyboard_service.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/shortcut_event/shortcut_event.dart, frontend/appflowy_flutter/pubspec.lock
* Define a new parameter called `character` to `shortcut_event`.
* Trigger the shortcut by checking whether the character is the same as the character of the `RawKeyEvent` in `onKey` callback,
=> feat: trigger shortcut event by character

frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
=> fix: allow # in links when pasting

frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_language_view.dart
=> fix: dropdown state unchanging after file reset

frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart, frontend/appflowy_flutter/pubspec.yaml
- Updated App Version from `1.0.0` to `0.1.1` as mentioned.
Resolves Issue #2074
=> fix: Update app version in `pubspec.yaml`

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_customize_location_view.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/flowy_dialog.dart
Relates: #2056 
<details>
<summary>Screen recording of how it looks</summary>
</details>
=> fix: settings dialog files path copy snackbar

frontend/appflowy_flutter/assets/translations/zh-TW.json, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/language.dart
=> feat: Add more translations in Chinese(Traditional)

frontend/appflowy_flutter/packages/appflowy_editor/lib/src/render/toolbar/toolbar_item.dart, frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/default_text_operations/format_rich_text_style.dart, frontend/appflowy_flutter/packages/appflowy_editor/test/render/rich_text/toolbar_rich_text_test.dart
Fixes #1069.
I added number list to the toolbar and wrote test for it
https://user-images.githubusercontent.com/103382847/226871569-21aad6ac-c577-452a-9e38-8a3057cd9c8b.mp4
=> Feat: adding number feature to toolbar

frontend/appflowy_flutter/packages/flowy_infra/lib/image.dart
hot fix nested path in svgWidget
=> fix: fix nested path

frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_customize_location_view.dart
Adds a theme for `SnackBar` in AppFlowy. There is no specification in any of the Figma files, so the theme is the same as the `SettingsMenuOptions` in the left panel of the settings menu.
**Light, Default**
**Dark, Default**
**Light, Dandelion**
**Dark, Dandelion**
**Light, Lavender**
**Dark, Lavender**
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/2127
---
=> [feat] add theme for snackbar

frontend/appflowy_flutter/macos/Podfile, frontend/appflowy_flutter/macos/Runner.xcodeproj/project.pbxproj
=> fix: sometimes build error in macOS x86_64

frontend/rust-lib/Cargo.lock, frontend/rust-lib/flowy-core/src/lib.rs, frontend/rust-lib/flowy-document2/Cargo.toml
=> chore: add tracing to document2

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src/appflowy_app/components/document/DocumentTitle/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/Node/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/Root/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/SubscribeNode.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/TextInput.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/layout/NavigationPanel/FolderItem.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/interfaces/document.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/document/document_bd_svc.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/document/document_controller.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/document/document_observer.ts, frontend/appflowy_tauri/src/appflowy_app/views/DocumentPage.hooks.ts, frontend/rust-lib/Cargo.lock, frontend/rust-lib/flowy-document2/src/document.rs, frontend/rust-lib/flowy-document2/src/entities.rs, frontend/rust-lib/flowy-document2/src/event_handler.rs, frontend/rust-lib/flowy-document2/src/event_map.rs, frontend/rust-lib/flowy-document2/src/manager.rs
=> Split create document and open document

frontend/appflowy_flutter/assets/translations/ru-RU.json
The PR is not related to any of opened issues, since it updates existing localization
---
=> feat: update ru-RU localization

frontend/appflowy_flutter/lib/core/helpers/helpers.dart, frontend/appflowy_flutter/lib/core/helpers/url_validator.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/url_cell/cell_editor.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/snap_bar.dart
=> feat: add url validation in cell_editor

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart
The PR works on this issue https://github.com/AppFlowy-IO/AppFlowy/issues/2026
and replace the emoji next to What's New as it doesn't show properly on Windows
---
=> feat: add a new entry to the question bubble

frontend/appflowy_tauri/src/appflowy_app/components/document/HeadingBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/ListBlock/ColumnListBlock.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/ListBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/TextBlock.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/TextInput.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/interfaces/document.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/document/document_controller.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/backspace.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/insert.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/set_cursor.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/split.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/update.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/slice.ts, frontend/appflowy_tauri/src/appflowy_app/utils/block.ts, frontend/rust-lib/flowy-document2/src/event_handler.rs, frontend/rust-lib/flowy-document2/src/manager.rs
=> Need to set the cursor to the correct position, after the DOM node is updated

frontend/appflowy_tauri/src/appflowy_app/stores/effects/document/document_controller.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/backspace.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/delete.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/indent.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/insert.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/outdent.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/set_cursor.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/split.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/update.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/slice.ts, frontend/appflowy_tauri/src/appflowy_app/utils/block.ts, frontend/appflowy_tauri/src/appflowy_app/views/DocumentPage.hooks.ts
=> Make it unidirectional data flow by listening to document updates

frontend/appflowy_tauri/.eslintrc.cjs, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockMenu/MenuItem.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/interfaces/document.ts, frontend/appflowy_tauri/src/appflowy_app/utils/tool.ts
=> Modify some eslint rules

frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/TextBlock.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/TextInput.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/backspace.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async_actions/set_cursor.ts, frontend/appflowy_tauri/src/appflowy_app/utils/block.ts, frontend/appflowy_tauri/src/appflowy_app/utils/slate/hotkey.ts, frontend/appflowy_tauri/src/appflowy_app/utils/slate/text.ts
=> Support pressing keyboard event to move cursor

frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart
title says all
resolves #2386
https://user-images.githubusercontent.com/71320345/235165639-f153406f-46fa-4893-8205-145657f9eccb.mp4
---
=> feat: open the event details page when a new one is create

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src/appflowy_app/components/_shared/EditRow/DateFormatPopup.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/EditRow/DatePickerPopup.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/EditRow/DateTimeFormat.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/_shared/EditRow/DateTypeOptions.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/EditRow/EditCellText.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/EditRow/EditCellWrapper.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/EditRow/EditFieldPopup.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/EditRow/EditRow.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/EditRow/NumberFormat.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/_shared/EditRow/NumberFormatPopup.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/EditRow/TimeFormatPopup.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/database-hooks/loadField.ts, frontend/appflowy_tauri/src/appflowy_app/components/_shared/database-hooks/useCell.ts, frontend/appflowy_tauri/src/appflowy_app/components/board/BoardCard.tsx, frontend/appflowy_tauri/src/appflowy_app/components/board/BoardGroup.tsx, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/database/slice.ts, frontend/rust-lib/Cargo.lock
closes https://github.com/AppFlowy-IO/AppFlowy/issues/2271
closes https://github.com/AppFlowy-IO/AppFlowy/issues/2272
=> feat: tauri kanban fixes

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/database_view/application/cell/cell_controller.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/database_controller.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/view/view_cache.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/application/board_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/board_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/application/calendar_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/application/grid_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/application/row/row_detail_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/card.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/card_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/card_cell_builder.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/cells/card_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/cells/checkbox_card_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/cells/date_card_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/cells/select_option_card_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/cells/text_card_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/container/card_container.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_detail.dart, frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/rust-lib/flowy-database/src/event_handler.rs, frontend/rust-lib/flowy-database/src/services/cell/cell_operation.rs, frontend/rust-lib/flowy-database/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database/src/services/field/type_options/date_type_option/date_type_option_entities.rs, frontend/rust-lib/flowy-database/src/services/row/row_builder.rs
This PR introduces a new design of the UI of opening grid row/kanban board card/calendar event as page.
- Add a right sidebar to include row actions. For now, there is only the ability to delete the row.
- Removed the thick scroll bar for a more subtle version. Also increase the scrollbar margin in the main axis to account for the rounded corners (doesn't seem to cause regressions on other popovers)
- Reorganized the layout of the page to allow future implementation of #2183.
fixes #1993
https://user-images.githubusercontent.com/71320345/234302277-b7fee5d4-cda2-4360-8374-db9dd5ee716b.mp4
---
=> chore: grid row page detail redesign

frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_detail.dart
- adjusted padding
- fixed day badge for first day of month
- use default mouse cursor unless hovering over an event
- fix bug regarding divider poking through the corners of the overlay
https://user-images.githubusercontent.com/71320345/235388649-0a086f59-60fe-4860-b18b-0f32046601d4.mp4
https://user-images.githubusercontent.com/71320345/235388654-90496c0a-a6de-453e-bf21-29b61acd42b1.mp4
---
=> fix: calendar ui adjustments

frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_user_view.dart
fixes: #2297
https://user-images.githubusercontent.com/72064462/235370527-2d3176f2-b24a-40c5-b54a-db2116dfeb7d.mov
=> fix: hover state issue in icon picker for dark mode workspace name.

.github/workflows/translation_notify.yml
This pr adds a link to the changes made in the commits that caused workflow to send a message about changes in English localization to discord
=> feat: add link to changes to message

frontend/appflowy_flutter/lib/plugins/database_view/calendar/application/calendar_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/cells/card_cell.dart
=> fix: sort the events in each day cell by time

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/text_cell/text_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_detail.dart
Title says all
fixes #2428
---
=> feat: show title in row detail page

frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart
=> feat: double click day cell to create event

frontend/appflowy_tauri/src/appflowy_app/components/document/Node/NodeChildren.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/Node/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/TextBlock.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/useMarkDown.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/TodoListBlock/TodoListBlock.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/TodoListBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/constants/document/config.ts, frontend/appflowy_tauri/src/appflowy_app/interfaces/document.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/text/backspace.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/text/index.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/text/split.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/text/update.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/todo_list.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/turn_to.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/blocks/common.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/blocks/heading.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/blocks/todo_list.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/slate/markdown.ts, frontend/appflowy_tauri/src/appflowy_app/views/DocumentPage.hooks.ts, frontend/appflowy_tauri/tailwind.config.cjs, frontend/rust-lib/flowy-document2/src/manager.rs
=> feat: checkbox block

frontend/appflowy_tauri/src/appflowy_app/components/_shared/database-hooks/loadField.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/DocumentTitle/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/Node/NodeChildren.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/Node/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/QuoteBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/useMarkDown.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/TodoListBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/constants/document/config.ts, frontend/appflowy_tauri/src/appflowy_app/interfaces/document.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/quote.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/blocks/common.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/blocks/heading.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/blocks/quote.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/slate/markdown.ts
This PR is based on [2413](https://github.com/AppFlowy-IO/AppFlowy/pull/2413) and needs to be merged with [2413](https://github.com/AppFlowy-IO/AppFlowy/pull/2413) first
---
=> Support quote block

.github/workflows/release.yml
This PR removes CI job based on Ubuntu 18.04, closes [#2341](https://github.com/AppFlowy-IO/AppFlowy/issues/2341).
Shows only 1 job under `build-for-linux`
---
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
=> feat: Remove CI job based on Ubuntu 18.04

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/toolbar/calendar_layout_setting.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/toolbar/calendar_toolbar.dart
fixes #2408
https://user-images.githubusercontent.com/71320345/235433501-56651106-c71e-4d9f-8511-186981e67bf5.mp4
---
=> feat: show unscheduled events in calendar toolbar

frontend/appflowy_tauri/src/appflowy_app/components/document/BulletedListBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/Node/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/NumberedListBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/events/TurnIntoEvents.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TodoListBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/ToggleListBlock/ToggleListBlock.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/ToggleListBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/constants/document/config.ts, frontend/appflowy_tauri/src/appflowy_app/interfaces/document.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/text/split.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/blocks/common.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/blocks/index.ts
This branch is based on https://github.com/AppFlowy-IO/AppFlowy/pull/2453
---
=> Support toggle list block

frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/toolbar/calendar_layout_setting.dart
=> fix: wrong day of week

frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/section/section.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/menu.dart
resolves #1777
https://user-images.githubusercontent.com/71320345/236682041-e9b0218f-fb14-435b-bd4a-0c5c7516eb68.mp4
https://user-images.githubusercontent.com/71320345/236682052-9905dfb3-7259-4531-bd02-0646c875bf36.mp4
---
=> feat: improve sidebar item dragged appearance

frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/cover/emoji_popover.dart
=> fix: show delete icon for document icon properly

frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/card.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/container/card_container.dart
This PR is to add a hover effect on an event card and close #2417 
https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/c0c18cb6-92e7-4532-8104-02e495d95145
https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/2153cccb-9be7-407f-bcf0-3c612e087d53
---
=> feat: add hover effect on an event card

frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/rust-lib/flowy-document/src/editor/READ_ME.json
=> chore: update editor v0.1.12 and format the readme

.github/workflows/tauri_ci.yaml, frontend/appflowy_tauri/pnpm-lock.yaml
=> chore: update node version to 18.16.0 and update pnpm version to 8.5.0

frontend/rust-lib/flowy-database/src/services/field/type_options/number_type_option/number_type_option.rs, frontend/rust-lib/flowy-database/tests/database/mock_data/grid_mock_data.rs, frontend/rust-lib/flowy-database/tests/database/sort_test/single_sort_test.rs
=> fix: number sort

.github/workflows/release.yml, frontend/Makefile.toml, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/card.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/container/card_container.dart, frontend/appflowy_flutter/lib/plugins/document/document_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/emoji_picker/emoji_menu_item.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart, frontend/appflowy_flutter/pubspec.yaml, frontend/scripts/windows_installer/inno_setup_config.iss
=> bump version 0.1.5

frontend/appflowy_tauri/.eslintrc.cjs, frontend/appflowy_tauri/package.json, frontend/appflowy_tauri/pnpm-lock.yaml, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockMenu/BlockMenu.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSelection/BlockSelection.hooks.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSelection/NodesRect.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSideToolbar/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/CodeBlock/CodeBlock.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/CodeBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/Node/Node.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/TextBlock.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/VirtualizedList/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/SubscribeNode.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/Text/TextInput.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/interfaces/document.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/document/document_controller.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/text/merge.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/text/update.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/cursor.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/rect_selection.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/slice.ts, frontend/appflowy_tauri/src/appflowy_app/stores/store.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/blocks/common.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/subscribe.ts, frontend/appflowy_tauri/src/appflowy_app/utils/region_grid.ts, frontend/appflowy_tauri/src/appflowy_app/utils/tool.ts
This branch is based on https://github.com/AppFlowy-IO/AppFlowy/pull/2464
---
=> Support rectangular selection box

frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/cover/emoji_popover.dart
=> fix: remove icon button not working in popover

.github/workflows/release.yml, CHANGELOG.md, README.md, frontend/Makefile.toml, frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/database_view/calendar/application/calendar_setting_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/toolbar/calendar_layout_setting.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/toolbar/calendar_setting.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/toolbar/calendar_toolbar.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/container/card_container.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_cal_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_editor.dart, frontend/appflowy_flutter/lib/plugins/document/document_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/cover/emoji_popover.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/emoji_picker/emoji_menu_item.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/section/section.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/menu.dart, frontend/appflowy_flutter/macos/Runner.xcodeproj/project.pbxproj, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/rust-lib/flowy-database/src/services/field/type_options/number_type_option/number_type_option.rs, frontend/rust-lib/flowy-database/tests/database/mock_data/grid_mock_data.rs, frontend/rust-lib/flowy-database/tests/database/sort_test/single_sort_test.rs, frontend/rust-lib/flowy-document/src/editor/READ_ME.json, frontend/scripts/flutter_release_build/build_flowy.dart, frontend/scripts/flutter_release_build/tool.dart, frontend/scripts/windows_installer/inno_setup_config.iss
Submitting this PR since there are some messy conflicts due to diversion in the date calculation logic. I've tried my best to make sure that there aren't mitigations, but more testing is welcome.
=> chore: merge remote-tracking branch 'main' into develop

frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_type_option_entities.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option_entities.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_ids.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option_cell.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/url_type_option/url_type_option_entities.rs
=> chore: fix typo

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/database_view/application/database_controller.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/database_view_service.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/row/row_cache.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/application/board_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/application/grid_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/row/row.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cell_builder.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/cell_container.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_sizes.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/left_bar_item.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/extension.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart, frontend/appflowy_flutter/test/bloc_test/grid_test/grid_bloc_test.dart
Allows reordering of rows in a Grid where no current filter and sorting is applied
Closes: #1123
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/a562c29a-e6cd-4bc1-9262-df23d29e0be8
---
=> feat: reorder rows in grid

frontend/rust-lib/Cargo.lock, frontend/rust-lib/flowy-sqlite/Cargo.toml, frontend/rust-lib/flowy-sqlite/src/kv/kv.rs, frontend/rust-lib/flowy-sqlite/src/kv/schema.rs, frontend/rust-lib/flowy-user/src/services/user_session.rs
=> refactor: kv

frontend/appflowy_flutter/lib/main.dart, frontend/appflowy_flutter/lib/startup/entry_point.dart, frontend/appflowy_flutter/lib/startup/startup.dart, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/lib/startup/tasks/hot_key.dart, frontend/appflowy_flutter/lib/startup/tasks/load_plugin.dart, frontend/appflowy_flutter/lib/startup/tasks/localization.dart, frontend/appflowy_flutter/lib/startup/tasks/platform_error_catcher.dart, frontend/appflowy_flutter/lib/startup/tasks/platform_service.dart, frontend/appflowy_flutter/lib/startup/tasks/prelude.dart, frontend/appflowy_flutter/lib/startup/tasks/rust_sdk.dart, frontend/appflowy_flutter/lib/startup/tasks/windows.dart, frontend/appflowy_flutter/lib/user/presentation/skip_log_in_screen.dart, frontend/appflowy_flutter/lib/window/window.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_customize_location_view.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/appflowy_flutter/test/util.dart
=> Optimize startup tasks

frontend/appflowy_flutter/lib/plugins/database_view/application/sort/sort_service.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/rust-lib/flowy-database2/src/manager.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs, frontend/rust-lib/flowy-database2/src/services/sort/controller.rs
fix #2534. Snapshot cause unexpected panic. Disable for now
=> chore: disable snapshot for now

frontend/rust-lib/Cargo.lock, frontend/rust-lib/flowy-database2/src/entities/row_entities.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/filter/controller.rs
=> fix: implement move row in backend

frontend/appflowy_flutter/lib/plugins/document/application/document_data_pb_extension.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_shortcut_event.dart
Closes: #2320
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/2398706a-0208-4814-937b-2c9a1d30b341
---
=> fix: select all in code block handler

frontend/appflowy_flutter/lib/plugins/document/application/doc_bloc.dart
=> fix: always open the readme file

frontend/appflowy_flutter/lib/plugins/document/application/doc_bloc.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_add_button.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_list.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_button.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option_action_button.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/board/board_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/divider/divider_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/grid/grid_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/appflowy_flutter/test/util.dart, frontend/rust-lib/flowy-core/src/deps_resolve/folder2_deps.rs
Optimize the hover block action component.
---
=> feat: optimzie the hover block action

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/selectable_svg_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/board/board_menu_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/board/board_view_menu_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/divider/divider_character_shortcut_event.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/emoji_menu_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/grid/grid_menu_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/grid/grid_view_menu_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/header/add_button.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/header/header.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/header/import/import_panel.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> fix: slash menu background color

.github/workflows/flutter_ci.yaml
title says all, we want the green checkmark
---
=> fix: flutter windows ci

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/auto_completion_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/auto_completion_plugins.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/plugins/openai/widgets/smart_edit_node_widget.dart
Reverts AppFlowy-IO/AppFlowy#2622
=> Revert "Revert "Support regenerating ai results #2012" (fix broken integration tests)."

frontend/rust-lib/Cargo.lock, frontend/rust-lib/flowy-database/Cargo.toml, frontend/rust-lib/flowy-database/src/entities/database_entities.rs, frontend/rust-lib/flowy-database/src/event_handler.rs, frontend/rust-lib/flowy-database/src/event_map.rs, frontend/rust-lib/flowy-database/src/services/export.rs, frontend/rust-lib/flowy-database/src/services/field/type_options/date_type_option/date_type_option_entities.rs, frontend/rust-lib/flowy-database/src/services/field/type_options/number_type_option/format.rs, frontend/rust-lib/flowy-database/src/services/field/type_options/text_type_option/text_type_option.rs, frontend/rust-lib/flowy-database/src/services/mod.rs, frontend/rust-lib/flowy-database/tests/database/export_test.rs, frontend/rust-lib/flowy-database/tests/database/mod.rs
=> chore: implement export handler

frontend/rust-lib/flowy-database2/src/entities/field_entities.rs, frontend/rust-lib/flowy-database2/src/event_handler.rs, frontend/rust-lib/flowy-database2/src/manager.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option_entities.rs, frontend/rust-lib/flowy-database2/src/services/share/csv/export.rs, frontend/rust-lib/flowy-database2/src/services/share/csv/import.rs, frontend/rust-lib/flowy-database2/tests/database/database_editor.rs, frontend/rust-lib/flowy-database2/tests/database/share_test/export_test.rs
=> chore: import history database

frontend/appflowy_flutter/lib/plugins/database_view/grid/application/row/row_detail_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_detail.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/header/import/import_panel.dart
=> feat: enable hide the grid property in row detail page

frontend/appflowy_flutter/lib/plugins/database_view/grid/application/row/row_detail_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cell_builder.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_detail.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/header/import/import_panel.dart, frontend/appflowy_flutter/pubspec.lock
=> fix: disable edit update or create field

frontend/appflowy_flutter/lib/plugins/database_view/application/field/field_editor_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/field/type_option/type_option_context.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/field/type_option/type_option_data_controller.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_cell_action_sheet.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/toolbar/grid_property.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_detail.dart, frontend/appflowy_flutter/test/bloc_test/board_test/util.dart, frontend/appflowy_flutter/test/bloc_test/grid_test/util.dart
=> feat: add default text when create a new field

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/database_view/application/database_controller.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/database_view_service.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/row/row_cache.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/application/board_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/application/grid_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/row/row.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cell_builder.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/cell_container.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_sizes.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/left_bar_item.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/extension.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart, frontend/appflowy_flutter/test/bloc_test/grid_test/grid_bloc_test.dart
Reverts AppFlowy-IO/AppFlowy#2533
=> Revert "feat: reorder rows in grid"

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
=> chore: bump version 0.1.6

frontend/appflowy_flutter/lib/workspace/application/settings/share/export_service.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_exporter_widget.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/rust-lib/flowy-database2/src/entities/mod.rs, frontend/rust-lib/flowy-database2/src/entities/share_entities.rs, frontend/rust-lib/flowy-database2/src/event_handler.rs, frontend/rust-lib/flowy-database2/src/event_map.rs
=> feat:expport csv data to local file

frontend/appflowy_flutter/lib/plugins/database_view/application/database_view_service.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/insert_page_command.dart, frontend/rust-lib/flowy-database2/src/entities/database_entities.rs, frontend/rust-lib/flowy-database2/src/event_handler.rs, frontend/rust-lib/flowy-database2/src/event_map.rs, frontend/rust-lib/flowy-database2/src/manager.rs, frontend/rust-lib/flowy-document2/src/manager.rs
=> feat: hide ref database view

frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_tauri/src/appflowy_app/components/_shared/LanguageSelectPopup.tsx, frontend/appflowy_tauri/src/appflowy_app/stores/i18n/initializeI18n.ts
=> fix: update ar language not found issue.

frontend/appflowy_flutter/lib/plugins/database_view/application/database_view_service.dart, frontend/appflowy_flutter/lib/plugins/database_view/database_view.dart, frontend/appflowy_flutter/lib/plugins/document/application/doc_service.dart, frontend/appflowy_flutter/lib/util/json_print.dart, frontend/appflowy_flutter/lib/workspace/application/menu/menu_bloc.dart, frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart, frontend/appflowy_flutter/lib/workspace/application/workspace/workspace_service.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart, frontend/appflowy_flutter/test/bloc_test/home_test/home_bloc_test.dart, frontend/appflowy_flutter/test/util.dart, frontend/appflowy_tauri/src/appflowy_app/stores/effects/folder/workspace/workspace_bd_svc.ts, frontend/rust-lib/dart-ffi/src/env_serde.rs, frontend/rust-lib/flowy-folder2/src/entities/view.rs, frontend/rust-lib/flowy-folder2/src/event_handler.rs, frontend/rust-lib/flowy-folder2/src/event_map.rs, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-folder2/src/test_helper.rs, frontend/rust-lib/flowy-folder2/tests/workspace/script.rs, frontend/rust-lib/flowy-test/src/folder_event.rs
=> fix: ref view in document

frontend/rust-lib/flowy-core/src/deps_resolve/folder2_deps.rs, frontend/rust-lib/flowy-document2/src/document_data.rs, frontend/rust-lib/flowy-document2/src/event_handler.rs, frontend/rust-lib/flowy-document2/src/manager.rs, frontend/rust-lib/flowy-document2/tests/document/document_insert_test.rs, frontend/rust-lib/flowy-document2/tests/document/document_test.rs, frontend/rust-lib/flowy-folder2/src/user_default.rs, frontend/rust-lib/flowy-folder2/src/view_operation.rs
=> fix: create build in document

frontend/appflowy_flutter/lib/startup/tasks/rust_sdk.dart, frontend/rust-lib/flowy-core/assets/read_me.json, frontend/rust-lib/flowy-core/src/deps_resolve/folder2_deps.rs, frontend/rust-lib/flowy-document2/src/document_block_keys.rs, frontend/rust-lib/flowy-document2/src/document_data.rs, frontend/rust-lib/flowy-document2/src/entities.rs, frontend/rust-lib/flowy-document2/src/event_handler.rs, frontend/rust-lib/flowy-document2/src/event_map.rs, frontend/rust-lib/flowy-document2/src/lib.rs, frontend/rust-lib/flowy-document2/src/manager.rs, frontend/rust-lib/flowy-document2/tests/document/document_insert_test.rs, frontend/rust-lib/flowy-document2/tests/document/document_test.rs, frontend/rust-lib/flowy-document2/tests/document/event_handler_test.rs, frontend/rust-lib/flowy-document2/tests/document/mod.rs
=> feat: public the json to document data pb api

frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-database2/src/entities/field_entities.rs, frontend/rust-lib/flowy-database2/src/event_handler.rs, frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/database/util.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option_entities.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs, frontend/rust-lib/flowy-database2/tests/database/block_test/row_test.rs, frontend/rust-lib/flowy-database2/tests/database/cell_test/test.rs, frontend/rust-lib/flowy-database2/tests/database/database_editor.rs, frontend/rust-lib/flowy-document2/src/event_handler.rs, frontend/rust-lib/flowy-document2/src/parser/json/parser.rs, frontend/rust-lib/flowy-folder2/src/user_default.rs
refactor:
The updatedAt and createdAt  are reading the timestamp from the row instead of inserting a cell data. 
fix #2643
=> refactor: updated at and created at

frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-core/src/deps_resolve/folder2_deps.rs, frontend/rust-lib/flowy-database2/src/manager.rs, frontend/rust-lib/flowy-database2/src/notification.rs, frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_group.rs, frontend/rust-lib/flowy-document2/src/event_handler.rs, frontend/rust-lib/flowy-document2/src/manager.rs, frontend/rust-lib/flowy-document2/tests/document/document_test.rs, frontend/rust-lib/flowy-folder2/src/event_handler.rs, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-folder2/src/view_operation.rs
=> feat: delete the view from the db when the view is deleted

.github/workflows/flutter_ci.yaml
=> chore: speed up flutter_ci

.github/workflows/flutter_ci.yaml, .github/workflows/rust_ci.yaml, .github/workflows/tauri_ci.yaml
=> ci: cache workspace

frontend/appflowy_flutter/lib/workspace/application/settings/share/import_service.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/header/add_button.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/header/import/import_panel.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/rust-lib/flowy-core/src/deps_resolve/folder2_deps.rs, frontend/rust-lib/flowy-database2/src/services/share/csv/import.rs, frontend/rust-lib/flowy-folder2/src/entities/import.rs, frontend/rust-lib/flowy-folder2/src/lib.rs, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-folder2/src/share/import.rs, frontend/rust-lib/flowy-folder2/src/view_operation.rs
=> chore: implement import csv ui

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/checklist_cell_editor_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/checklist_progress_bar.dart
=> chore: auto focus checklist editing

frontend/appflowy_flutter/lib/workspace/application/app/app_bloc.dart, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-core/src/deps_resolve/collab_deps.rs, frontend/rust-lib/flowy-database2/src/manager.rs, frontend/rust-lib/flowy-folder2/src/entities/view.rs, frontend/rust-lib/flowy-folder2/src/event_handler.rs, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-sqlite/migrations/2023-06-05-135652_collab_snapshot/up.sql, frontend/rust-lib/flowy-sqlite/src/schema.rs, frontend/rust-lib/flowy-test/src/lib.rs, frontend/rust-lib/flowy-test/tests/folder/test.rs
=> fix: reorder view when sibling view was deleted

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/url_cell/url_cell.dart
=> fix:http:// prefix issue fix

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/grid_header.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrolling/styled_scroll_bar.dart
Closes: #2633 
---
CC @LucasXu0 @appflowy
=> fix: add new row issue

.github/workflows/integration_test.yml, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> Update editor 1.0.0

frontend/appflowy_flutter/assets/translations/fr-FR.json
=> Spanish and french translations

frontend/appflowy_flutter/assets/translations/zh-CN.json
https://github.com/AppFlowy-IO/AppFlowy/issues/2049
---
=> fix: update cn translate

.github/workflows/rust_ci.yaml, frontend/.vscode/launch.json, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-folder2/src/user_default.rs, frontend/scripts/makefile/tests.toml
=> chore: update workspace id from nanoid to uuid

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSelection/RangeKeyDown.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/CodeBlock/useKeyDown.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/Overlay/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/useKeyDown.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/CopyPasteHooks/useCopy.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/CopyPasteHooks/usePaste.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/EditorHooks/useCommonKeyEvents.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/SlateEditor/useEditor.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/SlateEditor/useSlateYjs.ts, frontend/appflowy_tauri/src/appflowy_app/constants/document/copy_paste.ts, frontend/appflowy_tauri/src/appflowy_app/constants/document/keyboard.ts, frontend/appflowy_tauri/src/appflowy_app/interfaces/document.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/document/document_controller.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/merge.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/copyPaste.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/format.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/range.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/action.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/copy_paste.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/delta.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/format.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/node.ts
=> Copy and paste appflowy editor data

frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-core/src/deps_resolve/collab_deps.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_type_option.rs, frontend/rust-lib/flowy-folder2/src/event_handler.rs, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-test/tests/database/test.rs
=> chore: bump up collab version

frontend/appflowy_flutter/lib/core/config/kv.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-error/src/code.rs, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-user/src/services/database.rs
=> chore: bump up collab

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/url_cell/url_cell.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/lib/user/presentation/folder/folder_widget.dart, frontend/appflowy_flutter/lib/user/presentation/skip_log_in_screen.dart, frontend/appflowy_flutter/lib/workspace/application/settings/settings_file_exporter_cubit.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_export_file_widget.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_customize_location_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_exporter_widget.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/color_picker.dart, frontend/rust-lib/flowy-sqlite/src/kv/kv.rs
=> fix: can't input url in Grid

frontend/appflowy_flutter/lib/plugins/database_view/application/cell/cell_data_persistence.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/group/group_service.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/setting/group_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/application/board_bloc.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/test/bloc_test/board_test/group_by_multi_select_field_test.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_tauri/src/appflowy_app/stores/effects/database/cell/data_persistence.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/database/group/group_controller.ts, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-database2/src/entities/calendar_entities.rs, frontend/rust-lib/flowy-database2/src/entities/database_entities.rs, frontend/rust-lib/flowy-database2/src/entities/group_entities/group.rs, frontend/rust-lib/flowy-database2/src/entities/row_entities.rs, frontend/rust-lib/flowy-database2/src/entities/type_option_entities/checklist_entities.rs, frontend/rust-lib/flowy-database2/src/entities/type_option_entities/date_entities.rs, frontend/rust-lib/flowy-database2/src/event_handler.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs, frontend/rust-lib/flowy-database2/src/services/group/configuration.rs, frontend/rust-lib/flowy-database2/tests/database/group_test/script.rs, frontend/rust-lib/flowy-database2/tests/database/group_test/test.rs, frontend/rust-lib/flowy-test/src/lib.rs, frontend/rust-lib/flowy-test/tests/database/test.rs
=> test: add database event tests

frontend/scripts/docker-buildfiles/Dockerfile
=> ci: fix docker ci

frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/cells/checklist_card_cell.dart
=> fix: adding vertical padding for progress bar

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/accessory/cell_accessory.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/url_cell/url_cell.dart
=> feat: hide url cell accessory when the content is empty

.github/workflows/integration_test.yml, CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
=> chore: bump version 0.2.1

frontend/appflowy_flutter/lib/workspace/application/app/app_bloc.dart, frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart, frontend/appflowy_flutter/test/bloc_test/board_test/util.dart, frontend/appflowy_flutter/test/bloc_test/grid_test/filter/filter_util.dart, frontend/appflowy_flutter/test/bloc_test/grid_test/util.dart
=> refactor: create view interface

frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/header/add_button.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/header/import/import_panel.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/header/import/import_type.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/flowy_dialog.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/flowy_overlay.dart
=> feat: support importing multiple md files all at once

frontend/appflowy_flutter/integration_test/share_markdown_test.dart, frontend/appflowy_flutter/integration_test/util/common_operations.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart, frontend/appflowy_flutter/lib/startup/tasks/windows.dart
=> fix: the markdown file name doesn't update after renaming the document

frontend/appflowy_flutter/integration_test/cover_image_test.dart, frontend/appflowy_flutter/integration_test/switch_folder_test.dart, frontend/appflowy_flutter/integration_test/util/common_operations.dart, frontend/appflowy_flutter/integration_test/util/expectation.dart, frontend/appflowy_flutter/integration_test/util/util.dart
=> chore: optimize the integration test APIs

frontend/appflowy_flutter/assets/images/login/language.svg, frontend/appflowy_flutter/integration_test/document_test.dart, frontend/appflowy_flutter/integration_test/language_test.dart, frontend/appflowy_flutter/integration_test/util/common_operations.dart, frontend/appflowy_flutter/integration_test/util/expectation.dart, frontend/appflowy_flutter/lib/user/presentation/skip_log_in_screen.dart, frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_language_view.dart
Close #2789 
1. Add `LanguageSelectorOnWelcomePage` and its hover effect. 
https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/f1565725-2300-4aef-903f-bdea2e323e17
2. Add test code and catch error code
While using the 'setLocale' function in 'EasyLocalization', it threw the error message 'Unable to load asset' and searched for the incorrect JSON file path. To prevent this from disrupting the process, I added some catch error code.
---
=> feat: language selector on welcome page

frontend/appflowy_flutter/integration_test/cover_image_test.dart, frontend/appflowy_flutter/integration_test/document_with_database_test.dart, frontend/appflowy_flutter/integration_test/runner.dart, frontend/appflowy_flutter/integration_test/util/base.dart, frontend/appflowy_flutter/integration_test/util/common_operations.dart, frontend/appflowy_flutter/integration_test/util/editor_test_operations.dart, frontend/appflowy_flutter/integration_test/util/util.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_document.dart, frontend/appflowy_flutter/lib/plugins/document/document_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/link_to_page_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/cover_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/emoji_menu_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> fix: unable insert a reference database

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
=> chore: bump version 0.2.2

frontend/appflowy_flutter/integration_test/database_filter_test.dart, frontend/appflowy_flutter/integration_test/util/base.dart, frontend/appflowy_flutter/integration_test/util/database_test_op.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/database_controller.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/field/field_controller.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/application/board_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/choicechip/checklist/checklist.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/choicechip/select_option/option_list.dart, frontend/scripts/makefile/protobuf.toml
=> test: filter integration

frontend/appflowy_flutter/assets/translations/ru-RU.json
=> update russian localization

.github/workflows/flutter_ci.yaml, .github/workflows/integration_test.yml
=> chore: use retry action v1.0.36

frontend/appflowy_tauri/src-tauri/tauri.conf.json, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSideToolbar/BlockMenu.tsx
We encountered the problem mentioned in this issue, so made a modification to `tauri.conf.json`
https://github.com/tauri-apps/tauri/issues/5961
---
=> Build app failed in macOS

frontend/appflowy_flutter/lib/plugins/document/document.dart
=> fix: export markdown file

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/board_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_document.dart, frontend/appflowy_flutter/lib/plugins/document/document_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/insert_page_command.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/link_to_page_widget.dart, frontend/appflowy_flutter/lib/user/presentation/welcome_screen.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/error_page.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/pubspec.yaml, frontend/rust-lib/dart-ffi/Cargo.toml
This is to style the error widget per @appflowy's request and fix my remaining TODO comment.
---
=> [feat] make error widget sexy

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_shortcut_event.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> feat: upgrade editor version to latest 0.1.4

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/integration_test/util/base.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/board_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/layout/sizes.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/cover_image_picker_bloc.dart, frontend/appflowy_flutter/lib/startup/deps_resolver.dart, frontend/appflowy_flutter/lib/startup/startup.dart, frontend/appflowy_flutter/lib/startup/tasks/rust_sdk.dart, frontend/appflowy_flutter/lib/user/presentation/folder/folder_widget.dart, frontend/appflowy_flutter/lib/workspace/application/settings/settings_location_cubit.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_customize_location_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart
=> feat: put all user data into a folder when choosing a custom storage path

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
=> chore: bump version 0.2.3

frontend/appflowy_flutter/integration_test/database_sort_test.dart, frontend/appflowy_flutter/integration_test/runner.dart, frontend/appflowy_flutter/integration_test/switch_folder_test.dart, frontend/appflowy_flutter/integration_test/util/database_test_op.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/sort/create_sort_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/sort/order_panel.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/sort/sort_editor.dart, frontend/appflowy_flutter/lib/workspace/application/settings/settings_location_cubit.dart
=> chore: add database sort integration test

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/plugins/database_view/tar_bar/tar_bar_add_button.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_banner.dart
=> chore: adjust ui

frontend/appflowy_flutter/integration_test/database_cell_test.dart, frontend/appflowy_flutter/integration_test/util/database_test_op.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_editor.dart
=> test: more integration tests

frontend/appflowy_flutter/windows/runner/main.cpp
=> feat: only allow one windows instance

frontend/appflowy_flutter/integration_test/database_calendar_test.dart, frontend/appflowy_flutter/integration_test/database_row_page_test.dart, frontend/appflowy_flutter/integration_test/util/base.dart, frontend/appflowy_flutter/integration_test/util/database_test_op.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_editor.dart
=> test: add more calendar integration tests

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_list.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/header/header.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/section/item.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/scripts/makefile/flutter.toml
#2873
#2854
#2853
#2852
#2843
#2842
#2839
#2807
#2768
---
=> fix: 0.2.3 known issues

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
=> chore: bump version 0.2.4

frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-document2/src/manager.rs, frontend/rust-lib/flowy-folder2/src/entities/view.rs, frontend/rust-lib/flowy-folder2/src/event_handler.rs, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-folder2/src/notification.rs, frontend/rust-lib/flowy-folder2/src/user_default.rs, frontend/rust-lib/flowy-folder2/src/view_operation.rs
=> feat: using cached view

frontend/appflowy_flutter/assets/translations/hu-HU.json
Fixed typos and added missing items in Hungarian translation.
---
=> Fixed typos and added missing items in Hungarian translation

frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/error_page.dart, frontend/rust-lib/dart-ffi/Cargo.toml
No issue, just per review comment.
---
=> [feat] Add actions to error widget.

frontend/appflowy_flutter/assets/translations/zh-CN.json
I just updated the zh-CN.json based on en.json. After replace the original file, the app has able to run succeefully.
It seems still a lot of entries<sub>(Is that word correct?)</sub> are not translated[^1]. Is that even en.json are not coverd all entries?
No matter what, it‘s still increased about 200+ entries in Simplified Chinese translation. Hopes that would helpful.
[^1]: ![1687678884567](https://github.com/AppFlowy-IO/AppFlowy/assets/36128030/f5f8fd82-f8c2-495c-8555-b54a893d5afd)
=> zh-CN update

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSideToolbar/BlockMenu.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSideToolbar/BlockMenuTurnInto.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSideToolbar/BlockSideToolbar.hooks.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSideToolbar/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSlash/index.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSlash/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/EquationBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/EquationBlock/useEquationBlock.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/Node/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TextActionMenu/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TextActionMenu/menu/TurnIntoSelect.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/shortchut.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/useTurnIntoBlockEvents.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/TodoListBlock/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/InlineBlock/InlineContainer.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/KatexMath/index.css, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/KatexMath/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/TemporaryInput/EquationEditContent.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/TurnInto/TurnInto.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/TurnInto/index.tsx, frontend/appflowy_tauri/src/appflowy_app/constants/document/config.ts, frontend/appflowy_tauri/src/appflowy_app/interfaces/document.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/duplicate.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/rect_selection.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/turn_to.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/slice.ts, frontend/appflowy_tauri/src/appflowy_app/utils/document/block.ts
https://github.com/AppFlowy-IO/AppFlowy/assets/108015703/f8d905c3-abe8-471d-9eea-2c4e4769f2d0
---
=> Support equation block

frontend/appflowy_flutter/integration_test/database_calendar_test.dart, frontend/appflowy_flutter/integration_test/database_cell_test.dart, frontend/appflowy_flutter/integration_test/util/database_test_op.dart
The integration test in Github Actions have only passed from time to time, and has recently completely given up running on my local machine. This PR aims to fix that.
resolves #2919
=> test: fix calendar integration test #2919

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/integration_test/document/edit_document_test.dart, frontend/appflowy_flutter/lib/plugins/document/application/doc_bloc.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_selection_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/more/cubit/document_appearance_cubit.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
* support inserting local image.
* add image menu
* align
* copy link
* delete
---
=> feat: support inserting local image

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
- Added support for uploading the local image
- Added support for inserting an inline page reference
- Added support for inserting an outline block
- Added support for aligning the image by image menu
- Some UI issues
---
=> chore: bump version 0.2.5

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_selection_menu.dart
=> chore: add ref

frontend/rust-lib/flowy-document2/src/entities.rs, frontend/rust-lib/flowy-test/src/document/document_event.rs, frontend/rust-lib/flowy-test/src/document/mod.rs, frontend/rust-lib/flowy-test/src/document/text_block_event.rs, frontend/rust-lib/flowy-test/src/document/utils.rs, frontend/rust-lib/flowy-test/src/lib.rs, frontend/rust-lib/flowy-test/tests/document/block_test.rs, frontend/rust-lib/flowy-test/tests/document/document_test.rs, frontend/rust-lib/flowy-test/tests/document/mod.rs
=> chore: add document test

frontend/appflowy_flutter/assets/translations/en.json, frontend/appflowy_flutter/lib/core/config/kv_keys.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_document.dart, frontend/appflowy_flutter/lib/plugins/document/document.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/more/cubit/document_appearance_cubit.dart, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/menu_user.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/levenshtein.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance_view.dart, frontend/appflowy_flutter/test/bloc_test/app_setting_test/document_appearance_test.dart, frontend/appflowy_flutter/test/unit_test/algorithm/levenshtein_test.dart, frontend/appflowy_flutter/test/unit_test/editor/editor_style_test.dart, frontend/appflowy_flutter/test/widget_test/theme_font_family_setting_test.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/44445638/bcd8d676-954b-4e64-a36e-4bcd4e4108bc
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/2795
---
=> [feat] Allow user to select any Google Font

frontend/appflowy_flutter/integration_test/database_calendar_test.dart
Recent runs of the integration test on Github CI have been largely unstable, and the cause is seemingly random. This PR combines many of the tests in the calendar integration test group in hopes of ironing out these stability issues. Fingers crossed 🤞.
EDIT: Well look at that, isn't that ironic.
---
=> test: improve stability of calendar integration test

frontend/appflowy_flutter/integration_test/document/document_with_inline_math_equation_test.dart, frontend/appflowy_flutter/integration_test/open_ai_smart_menu_test.dart, frontend/appflowy_flutter/integration_test/util/editor_test_operations.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/inline_math_equation/inline_math_equation_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/migration/editor_migration.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/scripts/makefile/flutter.toml
closes #2969
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/d2318286-8771-4d91-b737-c78993021798
---
=> fix: unable to cancel the inline math equation format

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
- Dynamic load themes
- Inline math equation
---
=> chore: bump version 0.2.6

install.sh
With this installation script, AppFlowy can be installed using the curl command,
```
curl -sSL https://github.com/roopeshsn/AppFlowy/raw/installation-script/install.sh | bash
```
Here are the logs,
```
roopesh@roopesh-mi-notebook-14:~$ curl -sSL https://github.com/roopeshsn/AppFlowy/raw/installation-script/install.sh | bash
AppFlowy-IO/AppFlowy info checking GitHub for latest tag
AppFlowy-IO/AppFlowy info found version: 0.2.5 for 0.2.5/linux/amd64
._AppFlowy
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
AppFlowy/
AppFlowy/._appflowy.desktop.temp
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
AppFlowy/appflowy.desktop.temp …
```
=> feat: wrote an installation script for Linux users to install AppFlowy (#2951)

frontend/scripts/docker-buildfiles/Dockerfile
=> chore: fix typo in Dockerfile

frontend/appflowy_flutter/integration_test/tabs_test.dart, frontend/appflowy_flutter/integration_test/util/common_operations.dart, frontend/appflowy_flutter/lib/plugins/blank/blank.dart, frontend/appflowy_flutter/lib/plugins/database_view/tar_bar/tab_bar_view.dart, frontend/appflowy_flutter/lib/plugins/document/document.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/built_in_page_widget.dart, frontend/appflowy_flutter/lib/plugins/trash/menu.dart, frontend/appflowy_flutter/lib/plugins/trash/trash.dart, frontend/appflowy_flutter/lib/startup/deps_resolver.dart, frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart, frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_event.dart, frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_state.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_screen.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_sizes.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/section/item.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/app/section/section.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/menu.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/flowy_tab.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/tabs_manager.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/tab_bar_item.dart, frontend/resources/translations/en.json
Closes: #2942 Relates: #2312
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/c070cf3f-5187-4ea9-84cf-5eddfe689146
---
=> feat: open apps in tabs

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_editor.dart
=> fix: field hide/delete icon color in dark mode

frontend/appflowy_flutter/integration_test/database_field_test.dart, frontend/appflowy_flutter/integration_test/util/common_operations.dart, frontend/appflowy_flutter/integration_test/util/database_test_op.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/select_option.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/2985
---
=> test: add an option test

frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance_view.dart
[fixes](https://github.com/AppFlowy-IO/AppFlowy/issues/3012)
=> chore: added a tooltip to theme mode  for toggling theme

frontend/appflowy_flutter/integration_test/database_row_page_test.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_banner.dart
Fixed issue #2937
| Previous | Now |
| --- | ----------- |
| <img width="720" alt="Screenshot 2023-07-15 at 6 15 02 AM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/62821607/d3401213-163f-41e1-aacf-415f0e044bad"> | <img width="720" alt="Screenshot 2023-07-15 at 6 56 21 AM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/62821607/316534b4-e618-4388-abfd-a5d9425bfb66"> |
---
=> fix: row banner overlay

frontend/appflowy_flutter/integration_test/document/edit_document_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart
=> chore: clean unnecessary todos

frontend/appflowy_flutter/integration_test/appearance_settings_test.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance_view.dart
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/2975
---
=> fix: focus is clickable if text field is being edited

frontend/.vscode/launch.json, frontend/.vscode/tasks.json, frontend/Makefile.toml, frontend/appflowy_flutter/integration_test/util/mock/mock_file_picker.dart, frontend/appflowy_flutter/ios/Flutter/AppFrameworkInfo.plist, frontend/appflowy_flutter/ios/Podfile, frontend/appflowy_flutter/ios/Podfile.lock, frontend/appflowy_flutter/ios/Runner.xcodeproj/project.pbxproj, frontend/appflowy_flutter/ios/Runner/Info.plist, frontend/appflowy_flutter/lib/startup/tasks/hot_key.dart, frontend/appflowy_flutter/packages/appflowy_backend/ios/Classes/binding.h, frontend/appflowy_flutter/packages/flowy_infra_ui/android/src/main/kotlin/com/example/flowy_infra_ui/FlowyInfraUiPlugin.kt, frontend/appflowy_flutter/packages/flowy_infra_ui/ios/Classes/FlowyInfraUiPlugin.h, frontend/appflowy_flutter/packages/flowy_infra_ui/ios/Classes/FlowyInfraUiPlugin.m, frontend/appflowy_flutter/packages/flowy_infra_ui/ios/Classes/SwiftFlowyInfraUiPlugin.swift, frontend/scripts/install_dev_env/install_ios.sh, frontend/scripts/makefile/flutter.toml, frontend/scripts/makefile/mobile.toml
```sh
cd frontend/
cargo make --profile development-ios-arm64(-sim) appflowy-core-dev-ios # use development-ios-arm64-sim if running on simulator.
cd appflowy_flutter
sh scripts/code_generation/generate.sh
flutter run
```
```sh
cd frontend
cargo make --profile development-ios-arm64 appflowy-ios-dev # for real device
cargo make --profile development-ios-arm64-sim appflowy-ios-dev # for simulator
```
AF-iOS-Simulator: Clean + Rebuild All. After building successfully, you can use 'build dart only' if there are no Rust code changes.    
Please make sure your iPhone is registered on Xcode when debugging on a real device.
---
=> feat: support building on iOS platform

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_button.dart
=> fix: cursor for block options on Windows

frontend/scripts/code_generation/language_files/generate_language_files.cmd
Error message
```bash
'Generating language files'
Copying resources/translations to appflowy_flutter/assets/translations
Invalid path
0 File(s) copied
```
https://github.com/AppFlowy-IO/AppFlowy/actions/runs/5587216069/job/15131387072
Notes: The CI jobs passed when there's a `\` after the path, but it failed on the release job.
---
=> fix: windows release job

.github/workflows/rust_ci.yaml, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_tauri/src/appflowy_app/components/_shared/BlockDraggable/BlockDragDropContext.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/BlockDraggable/BlockDraggable.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/_shared/BlockDraggable/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSideToolbar/BlockSideToolbar.hooks.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSideToolbar/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/Node/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/VirtualizedList/index.tsx, frontend/appflowy_tauri/src/appflowy_app/components/layout/NestedPage/NestedPage.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/layout/NestedPage/index.tsx, frontend/appflowy_tauri/src/appflowy_app/stores/effects/database/database_bd_svc.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/workspace/page/page_bd_svc.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/workspace/page/page_controller.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/workspace/workspace_observer.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/pages/slice.ts, frontend/resources/translations/en.json, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-folder2/src/entities/view.rs, frontend/rust-lib/flowy-folder2/src/event_handler.rs, frontend/rust-lib/flowy-folder2/src/event_map.rs, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-folder2/tests/workspace/folder_test.rs, frontend/rust-lib/flowy-folder2/tests/workspace/script.rs, frontend/rust-lib/flowy-test/tests/folder/local_test/test.rs
https://github.com/AppFlowy-IO/AppFlowy/assets/108015703/bb663839-48ca-437d-ae71-d177b791f7f8
---
=> fix: implement the interface of move nested views

README.md
AppFlowy has a lot of missing translations. 
I thought you could use your community for the missing translation.
---
I added the inlang Badge to the readme. 
that makes it easier for the community to see how much of the app needs to be translated. The idea behind the badge is to leverage the power of the community :) 
For AppFlowy
[![translation badge](https://inlang.com/badge?url=github.com/AppFlowy-IO/AppFlowy)](https://inlang.com/editor/github.com/AppFlowy-IO/AppFlowy?ref=badge)
=> Add Transaltion section README.md

frontend/rust-lib/flowy-database2/src/manager.rs, frontend/rust-lib/flowy-database2/src/services/database_view/layout_deps.rs
=> fix: date field created when reference a calendar

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/37607224/8124948b-3949-4e62-a256-d16bd250e7fc
Fixes: #3063 
---
=> fix: improve readability in callout

frontend/appflowy_flutter/ios/Podfile.lock, frontend/appflowy_flutter/packages/appflowy_backend/ios/appflowy_backend.podspec
Add the C++ library dependency to the appflowy_backend.podspec to avoid the undefined symbol errors.
<details>
<summary><b>Error Log</b></summary>
```log
Running Xcode build...                                                  \
\uc0\u9492 \u9472 Compiling, linking and signing...                        36.6s\
Xcode build done.                                           66.0s\
Failed to build iOS app\
Error (Xcode): Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::at(unsigned\
long) const\
\
\
Error (Xcode): Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find(char,\
unsigned long) const\
\
\
Error (Xcode): Undefined symbol: std::__1::basic_string<char, …
```
=> fix: missing c++ library when building iOS

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_component.dart
=> chore: add c cpp auto options in langauges

.github/workflows/flutter_ci.yaml, .github/workflows/integration_test.yml, frontend/appflowy_flutter/integration_test/document/document_with_database_test.dart, frontend/appflowy_flutter/ios/Podfile.lock, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/link_to_page_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/database_view_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/inline_database_menu_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/inline_page/inline_page_reference.dart, frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart, frontend/appflowy_flutter/packages/appflowy_backend/ios/appflowy_backend.podspec
- Could not create an inline Grid/Board/Calendar inside the document after supporting the nested folder
---
=> Fix insert reference page

.github/workflows/release.yml, frontend/appflowy_flutter/lib/env/env.dart, frontend/appflowy_flutter/lib/startup/deps_resolver.dart, frontend/appflowy_flutter/lib/startup/tasks/supabase_task.dart, frontend/appflowy_flutter/lib/user/application/auth/appflowy_auth_service.dart, frontend/appflowy_flutter/lib/user/application/auth/auth_service.dart, frontend/appflowy_flutter/lib/user/application/auth/supabase_auth_service.dart, frontend/appflowy_flutter/lib/user/application/sign_in_bloc.dart, frontend/appflowy_flutter/lib/user/presentation/sign_in_screen.dart, frontend/appflowy_flutter/lib/user/presentation/splash_screen.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_user_view.dart, frontend/rust-lib/flowy-server/src/supabase/api/collab_storage.rs, frontend/scripts/code_generation/env/generate_env.cmd, frontend/scripts/code_generation/env/generate_env.sh, frontend/scripts/code_generation/generate.cmd, frontend/scripts/code_generation/generate.sh
=> feat: implement magic link login

frontend/appflowy_flutter/lib/user/application/user_service.dart, frontend/rust-lib/flowy-user/src/services/session_serde.rs
=> chore: fix historical user open issue

frontend/appflowy_flutter/integration_test/sidebar/sidebar_test.dart, frontend/appflowy_flutter/integration_test/util/common_operations.dart, frontend/appflowy_flutter/lib/workspace/application/menu/menu_bloc.dart, frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/personal_folder.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_new_page_button.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/draggable_view_item.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart, frontend/appflowy_flutter/test/bloc_test/home_test/menu_bloc_test.dart
- show · before the view name if the view is a database view.
- adjust the UI padding.
- disable moving the page into the database view.
- disable drag and drop in the database view.
---
=> feat: disable moving page into the database

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
- Nestable personal folder that supports drag and drop
- Support for favorite folders.
- Support for sorting by date in Grid view.
- Add a duplicate button in the Board context menu.
- Improve readability in Callout
- Some UI issues
---
=> chore: bump version 0.2.8

frontend/appflowy_flutter/macos/Runner.xcodeproj/project.pbxproj
=> fix: macos release build

frontend/rust-lib/flowy-config/src/event_handler.rs, frontend/rust-lib/flowy-config/src/event_map.rs, frontend/rust-lib/flowy-core/src/integrate/server.rs, frontend/rust-lib/flowy-core/src/lib.rs, frontend/rust-lib/flowy-core/src/module.rs, frontend/rust-lib/flowy-sqlite/src/kv/kv.rs, frontend/rust-lib/flowy-test/src/lib.rs, frontend/rust-lib/flowy-test/tests/user/migration_test/document_test.rs, frontend/rust-lib/flowy-test/tests/user/migration_test/mod.rs, frontend/rust-lib/flowy-user/src/event_handler.rs, frontend/rust-lib/flowy-user/src/event_map.rs, frontend/rust-lib/flowy-user/src/migrations/historical_document.rs, frontend/rust-lib/flowy-user/src/services/user_session.rs
=> refactor: remove shared instance KV

frontend/appflowy_flutter/integration_test/sidebar/sidebar_favorites_test.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/favorite_folder.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/personal_folder.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/84044317/872e1cd4-9562-43e7-8fab-f898a4b3d774
fixes #3113 
---
=> fix:  favorite selection and context menu doesn't work

frontend/appflowy_flutter/lib/startup/tasks/supabase_task.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
- support opening AppFlowy both in develop mode and production mode.
For now, the default supabase auth directory is `ApplicationDataStorage + supabase_auth`.
---
=> feat: support customizing the supabase auth path

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/number_cell/number_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/url_cell/url_cell.dart
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3119
---
just make the **maxLines** to null of what text cell does
=> fix issue 3119 to auto wrapper the date, number and url cell

frontend/appflowy_flutter/lib/user/presentation/sign_in_screen.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/personal_folder.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_user_view.dart, frontend/resources/translations/en.json, frontend/scripts/windows_installer/inno_setup_config.iss
=> fix: deeplink doesn't work in windows exe installer

frontend/appflowy_flutter/integration_test/util/database_test_op.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/toolbar/board_setting_bar.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/layout/sizes.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/toolbar/calendar_setting_bar.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/layout/sizes.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/toolbar/filter_button.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/toolbar/grid_setting_bar.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/toolbar/sort_button.dart, frontend/appflowy_flutter/lib/plugins/database_view/tar_bar/setting_menu.dart, frontend/appflowy_flutter/lib/plugins/database_view/tar_bar/tab_bar_header.dart, frontend/appflowy_flutter/lib/plugins/database_view/tar_bar/tab_bar_view.dart, frontend/appflowy_flutter/lib/plugins/database_view/tar_bar/tar_bar_add_button.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/setting/setting_button.dart, frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/size.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart, frontend/rust-lib/dart-ffi/Cargo.toml
| Before | After |
| :--: | :--: |
| ![image](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/9b54eca7-6925-4f93-ad73-ae197a227154) | ![image](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/0a4f7d1d-b97b-407b-bc69-f3d311a69179) |
---
=> chore: database tab bar ui improvements

frontend/appflowy_flutter/integration_test/document/document_copy_and_paste_test.dart, frontend/appflowy_flutter/integration_test/document/document_test_runner.dart, frontend/appflowy_flutter/integration_test/share_markdown_test.dart, frontend/appflowy_flutter/integration_test/util/editor_test_operations.dart, frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
CHANGELOG
- https://pub.dev/packages/appflowy_editor/changelog
---
=> chore: update editor version to 1.2.3

frontend/appflowy_flutter/lib/startup/tasks/supabase_task.dart
=> chore: remove the unused value in supabase_task

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
- Improve tab and shortcut, click with alt/option to open a page in new tab.
- Improve database tab bar UI.
- Add button and more action button of the favorite section doesn't work.
- Fix euro currency number format.
- Some UI issues
---
=> chore: bump version 0.2.9

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/sort/sort_editor.dart
=> fix: replace svgWidget by FlowySvg

frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_user.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_user_view.dart, frontend/appflowy_flutter/packages/flowy_svg/lib/src/flowy_svg.dart
this was a silly oversight
fixes: https://github.com/AppFlowy-IO/AppFlowy/issues/3211
---
=> [fix] transparent svgs

frontend/appflowy_flutter/integration_test/document/document_with_toggle_list_test.dart, frontend/appflowy_flutter/lib/plugins/document/application/doc_bloc.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_add_button.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_shortcut_event.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_shortcut_event.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> feat: improve the functionality of pasting from html

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/extension.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/select_option_editor.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/built_in_page_widget.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/flowy_tab.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart
- Update the hover color on information and setting button
- Remove the hover effect on 'x' button in `SelectOptionTag`
- Update the hover color of `_SelectOptionCell`
- Update the hover color on add icon button.
Fix #2790 
- Fix #3172 
---
=> fix: color issues related to hover effect

frontend/appflowy_flutter/lib/user/application/auth/supabase_auth_service.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/error_page.dart, frontend/rust-lib/flowy-core/src/integrate/server.rs, frontend/rust-lib/flowy-core/src/lib.rs, frontend/rust-lib/flowy-database2/src/manager.rs, frontend/rust-lib/flowy-document2/src/manager.rs, frontend/rust-lib/flowy-error/src/code.rs, frontend/rust-lib/flowy-error/src/errors.rs, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-server/src/supabase/api/database.rs, frontend/rust-lib/flowy-server/src/supabase/api/document.rs, frontend/rust-lib/flowy-server/src/supabase/api/request.rs, frontend/rust-lib/flowy-server/src/supabase/server.rs, frontend/rust-lib/flowy-user-deps/src/cloud.rs, frontend/rust-lib/flowy-user/src/entities/user_setting.rs, frontend/rust-lib/flowy-user/src/event_handler.rs, frontend/rust-lib/flowy-user/src/event_map.rs, frontend/rust-lib/flowy-user/src/manager.rs, frontend/rust-lib/flowy-user/src/services/cloud_config.rs, frontend/rust-lib/flowy-user/src/services/user_encryption.rs
=> fix: only encrypt if enable

frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/color_scheme.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/theme_setting_entry_template.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_customize_location_view.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart, frontend/appflowy_flutter/packages/flowy_svg/lib/src/flowy_svg.dart
=> [fix] svg sizes

frontend/rust-lib/flowy-encrypt/src/encrypt.rs, frontend/rust-lib/flowy-server/src/supabase/api/util.rs, frontend/rust-lib/flowy-server/tests/supabase_test/user_test.rs, frontend/rust-lib/flowy-test/tests/user/supabase_test/auth_test.rs, frontend/rust-lib/flowy-user/src/services/cloud_config.rs, frontend/rust-lib/flowy-user/src/services/user_encryption.rs
=> docs: documentation for encryption functions

.github/workflows/rust_ci.yaml, frontend/appflowy_flutter/integration_test/auth/auth_test.dart, frontend/appflowy_flutter/integration_test/runner.dart, frontend/appflowy_flutter/integration_test/util/auth_operation.dart, frontend/appflowy_flutter/integration_test/util/settings.dart, frontend/appflowy_flutter/integration_test/util/util.dart, frontend/appflowy_flutter/lib/env/env.dart, frontend/appflowy_flutter/lib/startup/deps_resolver.dart, frontend/appflowy_flutter/lib/startup/startup.dart, frontend/appflowy_flutter/lib/startup/tasks/rust_sdk.dart, frontend/appflowy_flutter/lib/user/application/auth/appflowy_auth_service.dart, frontend/appflowy_flutter/lib/user/application/auth/auth_service.dart, frontend/appflowy_flutter/lib/user/application/auth/device_id.dart, frontend/appflowy_flutter/lib/user/application/auth/mock_auth_service.dart, frontend/appflowy_flutter/lib/user/application/auth/supabase_auth_service.dart, frontend/appflowy_flutter/lib/user/presentation/sign_in_screen.dart, frontend/appflowy_flutter/lib/user/presentation/skip_log_in_screen.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_customize_location_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_user_view.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart, frontend/rust-lib/dart-ffi/.cargo/config.toml
https://github.com/AppFlowy-IO/AppFlowy/assets/86001920/de4a1b09-5d34-407f-b308-8f29e82294cb
https://github.com/AppFlowy-IO/AppFlowy/assets/86001920/8686b3e2-6ead-4a36-9b57-045f6a231171
=> test: add supabase auth tests

frontend/appflowy_flutter/integration_test/document/document_copy_and_paste_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_plain_text.dart
- copy a URL.
- selected some texts.
- click cmd/ctrl+v to paste the url.
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/8997024c-7a05-4d60-9ef3-4a15d5e8cd2c
---
=> feat: format the selected text to url if available

frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/language.dart, frontend/resources/translations/fa.json
In this pull request, I've integrated the Persian language translation files into the Appflowy repository, enabling comprehensive support for Persian language users. By merging this pull request, Appflowy's user base will be expanded to Persian-speaking individuals.
cc @richardshiue @MayurSMahajan
[fixes issue #2836](https://github.com/AppFlowy-IO/AppFlowy/issues/2836)
"fixes #2836"
---
=> feat: add the Persian language translations

frontend/appflowy_flutter/lib/user/presentation/sign_in_screen.dart, frontend/appflowy_flutter/lib/user/presentation/skip_log_in_screen.dart
=> chore: enable continue last session after logout

frontend/.vscode/launch.json, frontend/.vscode/tasks.json, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/test/bloc_test/app_setting_test/appearance_test.dart
=> fix: reopen the application lost the theme

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/integration_test/document/document_copy_and_paste_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/clipboard_service.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_cut_command.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/editor_state_paste_node_extension.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_user_view.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
- Improve paste features:
- Paste HTML content from website.
- Paste image from clipboard.
- Support Group by Date in Kanban Board.
- Notarize the macOS package, which is now verified by Apple.
- Add Persian language translations.
- Some UI issues
=> chore: bump version 0.3.0

frontend/rust-lib/flowy-error/Cargo.toml, frontend/rust-lib/flowy-server/Cargo.toml
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/742
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/566
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3195
=> chore: use vendored openssl

frontend/appflowy_flutter/lib/startup/tasks/supabase_task.dart, frontend/appflowy_flutter/linux/CMakeLists.txt, frontend/appflowy_flutter/linux/my_application.cc, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/scripts/linux_distribution/deb/AppFlowy.desktop, frontend/scripts/linux_distribution/deb/build_deb.sh
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/c90ed978-863c-4874-99f9-1621203779d4
---
=> chore: update supabase version and setup new deeplink for linux

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/default_emoji_picker_view.dart
=> fix: nightmode support for no recents text on the emoji menu

frontend/appflowy_flutter/lib/plugins/database_view/application/share_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/tar_bar/tab_bar_view.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/share_button.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/resources/translations/en.json, frontend/rust-lib/flowy-document2/src/manager.rs
=> chore: share database via csv

frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/44445638/6f7b4bbf-1988-41fb-b7ab-0e1d157cad77
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3219
---
=> feat: add hover color to question bubble like mockup

frontend/appflowy_flutter/lib/env/env.dart, frontend/appflowy_flutter/lib/startup/tasks/rust_sdk.dart, frontend/appflowy_flutter/packages/appflowy_backend/lib/env_serde.dart, frontend/appflowy_flutter/packages/appflowy_backend/lib/env_serde.i.dart, frontend/rust-lib/flowy-server-config/src/supabase_config.rs
=> chore: remove jwt secret env variable

frontend/rust-lib/flowy-core/src/integrate/server.rs, frontend/rust-lib/flowy-server-config/src/supabase_config.rs
=> fix: disable sync if keys aren't provided

frontend/Makefile.toml, frontend/rust-lib/Cargo.toml, frontend/scripts/makefile/desktop.toml
=> chore: update cargo build profile

frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-database2/src/manager.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs, frontend/rust-lib/flowy-document2/src/manager.rs, frontend/rust-lib/flowy-user/src/migrations/migrate_to_new_user.rs, frontend/rust-lib/flowy-user/src/migrations/sync_new_user.rs
=> chore: update collab libs rev

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_component.dart
Solves: #3360 
Adds CSharp or C# support to codeblock.
In the Codeblock Language Options, click on CS to get syntax highlighting for CSharp.
=> feat: add csharp in codeblock

frontend/resources/translations/pt-BR.json, frontend/resources/translations/pt-PT.json
New translations for pt-PT & pt-BR
=> pt-PT & pt-BR translation updated 

.github/workflows/tauri_ci.yaml, frontend/appflowy_tauri/src-tauri/Cargo.lock
This pull request addresses an important aspect of maintaining our Rust projects—keeping Cargo.toml and Cargo.lock synchronized. When changes are made to the project's dependencies, it is crucial to ensure that Cargo.lock is also updated to accurately reflect these changes. This PR helps us maintain consistency and stability in our Rust project builds.
- **Dependency Consistency**: The Cargo.toml file defines the high-level dependencies for our project. However, Cargo.lock contains detailed information about specific versions and dependencies used in the build. Keeping them in sync ensures that all team members and our continuous integration process build the project with identical dependencies.
- **Reproducibility**: A synchronized Cargo.lock enables us to reproduce exact builds …
=> Ensure Cargo.lock Is Updated Alongside Changes to Cargo.toml

frontend/appflowy_flutter/linux/CMakeLists.txt
=> fix: downgrade the folder path to io.appflowy.appflowy

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_editor.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
=> chore: date editor ui polish

frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
=> chore: update version to 0.3.2

frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_event_card.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/create_filter_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/filter_menu.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/sort/create_sort_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/cells/card_cell.dart
=> fix: some UI issues

frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart, frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_buttons.dart, frontend/appflowy_flutter/lib/user/presentation/widgets/auth_form_container.dart
In #3217, I used the wrong size(screen size) as the button size to render the button. This PR is to fix that problem. It should stay in the central position no matter how we resize the screen. 
Desktop
Mobile
---
=> fix: fix alignment issue in login page

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/align_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/create_file_setting.dart, frontend/resources/translations/en.json
=> Fix launch review issues

frontend/resources/translations/it-IT.json
* This pull request fixes an incorrect Italian translation
=> Italian translation fix

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml
=> chore: update collab rev id

frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
=> fix: do not rebuild hover on item selection

frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
=> fix: tests for interacting with viewitem

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/row/row.dart
=> fix: add bottom border to new property column

frontend/appflowy_flutter/integration_test/appearance_settings_test.dart, frontend/appflowy_flutter/integration_test/util/mock/mock_openai_repository.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/board_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/database_view_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/config.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/default_emoji_picker_view.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/emoji_picker.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/extensions/flowy_tint_extension.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/font/customize_font_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/lib/util/google_font_family_extension.dart, frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/theme_setting_entry_template.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance_view.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/resources/flowy_icons/16x/font_family.svg, frontend/resources/translations/en.json
=> feat: customize text font

frontend/appflowy_flutter/lib/plugins/database_view/application/field/field_cell_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_cell.dart, frontend/appflowy_flutter/test/bloc_test/grid_test/field/field_cell_bloc_test.dart
fixes [3388](https://github.com/AppFlowy-IO/AppFlowy/issues/3388)
=> fix: set minimum width for grid fields to 100px

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_editor.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_editor_bloc.dart
Closes: #2057 
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/164e1a0c-5518-48b0-859a-a5646158e4c4
=> feat: select cover image on upload

.github/workflows/release.yml
The new package names should be in this format: `AppFlowy-<version>-<os>-<arch>`
- replace `ubuntu` in the name of linux package with `linux`
- automatically release the RPM.
---
=> chore: rename package name

frontend/appflowy_flutter/lib/plugins/database_view/widgets/field/grid_property.dart
---
fixes [#3457 ](https://github.com/AppFlowy-IO/AppFlowy/issues/3457)
=> fix: right icon size same as left one

frontend/appflowy_flutter/integration_test/database_calendar_test.dart, frontend/appflowy_flutter/integration_test/util/database_test_op.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/application/calendar_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/application/calendar_event_editor_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/application/unschedule_event_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_day.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_event_card.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_event_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/layout/sizes.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/toolbar/calendar_setting_bar.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/select_option.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cell_builder.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/text_cell/text_cell.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart, frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/colorscheme.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/dandelion.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lavender.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/theme_extension.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart, frontend/resources/translations/en.json
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3046
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/2383
=> chore: calendar UI polish

frontend/appflowy_flutter/integration_test/util/database_test_op.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/workspace/application/appearance.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/colorscheme.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/dandelion.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lavender.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/theme_extension.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/94619783/feae9ad2-2194-4976-a943-d35d98c39e85
---
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3447
=> fix: grid theming to bottom row count number

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
=> chore: bump version 0.3.3

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/align_toolbar_item.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/64174995/37ff9b43-fe8f-4aa3-b368-8d334c1a2799
---
fixes #3475
=> fix: Missing the hand gesture icon in the text alignment options

frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart
=> fix: on hover/enter issue for view items

frontend/resources/translations/ar-SA.json, frontend/resources/translations/ca-ES.json, frontend/resources/translations/de-DE.json, frontend/resources/translations/es-VE.json, frontend/resources/translations/eu-ES.json, frontend/resources/translations/fa.json, frontend/resources/translations/fr-CA.json, frontend/resources/translations/fr-FR.json, frontend/resources/translations/hu-HU.json, frontend/resources/translations/id-ID.json, frontend/resources/translations/it-IT.json, frontend/resources/translations/ja-JP.json, frontend/resources/translations/ko-KR.json, frontend/resources/translations/pl-PL.json, frontend/resources/translations/pt-BR.json, frontend/resources/translations/pt-PT.json, frontend/resources/translations/ru-RU.json, frontend/resources/translations/sv.json, frontend/resources/translations/tr-TR.json, frontend/resources/translations/zh-CN.json, frontend/resources/translations/zh-TW.json
Describe the changes you have conducted here.
I have edited id-ID part only in the inlang.com 
Preview the messages on https://inlang.com/github.com/linkb15/AppFlowy .
=> chore: update translations for id-ID

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/94619783/c0fda096-aa81-4bba-979b-680df48dbab3
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3543
=> fix: on hover change_cover button correct mouse cursor

.githooks/commit-msg
fixes : https://github.com/AppFlowy-IO/AppFlowy/issues/3561
This PR updated the git hook link, for the git commit message
---
- [# ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [ #] I've listed at least one issue that this PR fixes in the description above.
- [ #] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ #] All existing tests are passing.
=> fix:updated githook helper link

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/find_and_replace/find_and_replace_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_input.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/resources/flowy_icons/16x/arrow_down.svg, frontend/resources/flowy_icons/16x/arrow_up.svg, frontend/resources/translations/en.json
=> feat: integrate find and replace into AppFlowy

frontend/appflowy_flutter/integration_test/runner.dart, frontend/appflowy_flutter/integration_test/settings/user_language_test.dart
This PR add integration tests for user language settings.
Solve #3416 
---
=> chore: add integration tests for user language settings

frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/errors/workspace_failed_screen.dart, frontend/resources/translations/en.json
=> fix: avoid non-null promise on null value on home screen

frontend/appflowy_flutter/lib/plugins/document/document_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_toolbar_item.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/toast.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/color_scheme.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_exporter_widget.dart
Fixes SnackBar theme across the application, and creates a single function that can be used across the app. 
- Fixes: https://github.com/AppFlowy-IO/AppFlowy/issues/3365
---
=> feat: fix snackbar themeing issues

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml, frontend/scripts/docker-buildfiles/Dockerfile, frontend/scripts/install_dev_env/install_linux.sh
- Added support for creating a reminder.
- Added support for finding and replacing in the document page.
- Added support for showing the hidden fields in row detail page.
- Adjust the toolbar style in RTL mode.
- Improve snackbar UI design.
- Improve dandelion theme.
- Improve id-ID and pl-PL language translations.
=> chore: bump version 0.3.4

README.md
=> Updated Link to OS Specific Development in README.md

frontend/appflowy_flutter/README.md
=> docs: update links in readme

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/inline_page_reference.dart
=> fix: remove current page link option in page reference

.github/PULL_REQUEST_TEMPLATE.md, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/text_cell/text_cell.dart
<h1>Before</h1>
<h1>After</h1>
Fixes #3390
---
=> Fix: Missing WhiteSpace b/w Primary Field Text and Row Icon

README.md
---
Updated the location mentioned the project readme.
=> Updated translation part in project readme

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_editor.dart
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3526
=> Fix updated the image to use Image Image.file instead of FileImage, because it wasn't working for macOs

frontend/appflowy_flutter/lib/plugins/document/presentation/banner.dart
=> fix: restore page banner ui improvement

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/font/customize_font_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/embed_image_url_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_selection_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/unsplash_image_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_file_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_toolbar_item.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_language_view.dart, frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/theme_extension.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/resources/flowy_icons/16x/image_placeholder.svg, frontend/resources/translations/en.json
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/f665c6e8-984c-4621-8bcf-589f8d94ee16
---
=> feat: image block revamp

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
=> chore: bump version 0.3.5

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/url_cell/url_cell.dart
=> fix: url underline issue

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_cal_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_editor.dart
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3614
---
=> fix: wrong date selected in CDT

frontend/appflowy_flutter/lib/workspace/presentation/notifications/notification_button.dart
=> fix: notification button delayed tooltip

frontend/appflowy_flutter/integration_test/document/document_test_runner.dart, frontend/appflowy_flutter/integration_test/document/document_with_image_block_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/unsplash_image_widget.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/brightness_setting.dart, frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> fix: image block issues

frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/language.dart, frontend/resources/translations/uk-UA.json
feat: 3625
Added Ukrainian Language
- [:white_check_mark:] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [:white_check_mark:] I've listed at least one issue that this PR fixes in the description above.
=> feat: 3625 Added Ukrainian Language

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/open_ai_image_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/stability_ai_image_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/service/openai_client.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/stability_ai/stability_ai_client.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/stability_ai/stability_ai_error.dart, frontend/appflowy_flutter/lib/startup/deps_resolver.dart, frontend/appflowy_flutter/lib/user/application/user_service.dart, frontend/appflowy_flutter/lib/workspace/application/user/settings_user_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_user_view.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/resources/translations/en.json, frontend/rust-lib/flowy-server/src/af_cloud/impls/user.rs, frontend/rust-lib/flowy-server/src/supabase/api/user.rs, frontend/rust-lib/flowy-server/tests/supabase_test/user_test.rs, frontend/rust-lib/flowy-sqlite/migrations/2023-10-09-094834_user_stability_ai_key/down.sql, frontend/rust-lib/flowy-sqlite/migrations/2023-10-09-094834_user_stability_ai_key/up.sql, frontend/rust-lib/flowy-sqlite/src/schema.rs, frontend/rust-lib/flowy-test/tests/user/local_test/user_profile_test.rs, frontend/rust-lib/flowy-user-deps/src/entities.rs, frontend/rust-lib/flowy-user/src/entities/parser/mod.rs, frontend/rust-lib/flowy-user/src/entities/parser/user_stability_ai_key.rs, frontend/rust-lib/flowy-user/src/entities/user_profile.rs, frontend/rust-lib/flowy-user/src/services/user_sql.rs
=> feat: generate image by Stability AI / openAI

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/number.dart
This PR fixes the issue https://github.com/AppFlowy-IO/AppFlowy/issues/3452
---
=> Solved the Issue #3452

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/error/error_block_component_builder.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_shortcut_event.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/resources/translations/en.json
=> fix: openAI image expiration

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/row/row.dart
Closes: #3450
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3450
---
=> fix: correct svg for row actions

frontend/appflowy_flutter/lib/workspace/application/home/home_setting_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/home_layout.dart
[FR] #1674 
https://github.com/AppFlowy-IO/AppFlowy/assets/114166000/88dab107-c489-4786-bdff-7e93f34eb81d
Sidebar will automatically collapse if the window size is small and will reappear when the window is large enough
---
=> feat: 1674 Auto-hide sidebar when re-sizing the window

frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/date_picker_dialog.dart
---
- ~~[ ] I've listed at least one issue that this PR fixes in the description above.~~ _Review change_
=> fix: esc to close date picker dialog

frontend/appflowy_flutter/lib/workspace/application/home/home_setting_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
=> fix: fix integration tests

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/event-integration/tests/document/supabase_test/file_test.rs, frontend/rust-lib/flowy-document2/tests/document/util.rs, frontend/rust-lib/flowy-error/src/impl_from/cloud.rs, frontend/rust-lib/flowy-server/src/af_cloud/impls/file_storage.rs, frontend/rust-lib/flowy-server/tests/supabase_test/file_test.rs, frontend/rust-lib/flowy-storage/src/lib.rs
=> feat: implement file storage using appflowy cloud

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
=> chore: bump version 0.3.6

frontend/appflowy_flutter/lib/workspace/presentation/notifications/notification_grouped_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/notifications/notification_item.dart
=> fix: build app

frontend/appflowy_flutter/lib/startup/startup.dart, frontend/appflowy_flutter/lib/startup/tasks/appflowy_cloud_task.dart, frontend/appflowy_flutter/lib/user/application/supabase_realtime.dart, frontend/appflowy_flutter/lib/user/application/user_auth_listener.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-error/Cargo.toml, frontend/rust-lib/flowy-error/src/impl_from/mod.rs, frontend/rust-lib/flowy-error/src/impl_from/tokio.rs, frontend/rust-lib/flowy-server/src/af_cloud/impls/user.rs, frontend/rust-lib/flowy-server/src/af_cloud/server.rs, frontend/rust-lib/flowy-server/src/local_server/impls/user.rs, frontend/rust-lib/flowy-server/src/supabase/api/user.rs, frontend/rust-lib/flowy-user-deps/src/cloud.rs, frontend/rust-lib/flowy-user/src/entities/auth.rs, frontend/rust-lib/flowy-user/src/manager.rs
Fix:
1. reconnect ws
2. force login when user token is invalid
3. sync database data using ws
=> feat: af cloud database

frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/board_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/cells/checkbox_card_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checkbox_cell/checkbox_cell.dart
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3620
---
=> fix: 3620 unchecked checkbox color

.github/workflows/flutter_ci.yaml, .github/workflows/integration_test.yml, frontend/appflowy_flutter/integration_test/switch_folder_test.dart
https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
---
=> fix: the disk space of CI machines always runs out

frontend/appflowy_flutter/integration_test/document/document_with_image_block_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_selection_menu.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/a698b4ba-de52-4a47-8288-9282fd36d144
closes #3692
---
=> feat: auto pop up upload image menu

frontend/resources/translations/id-ID.json, frontend/resources/translations/ru-RU.json
Update translation Indonesia. #3649
=> feat: Update translations id_ID

frontend/resources/translations/pt-PT.json, frontend/resources/translations/ru-RU.json
Updated pt-PT translations
Preview the messages on https://inlang.com/github.com/pedroldk/AppFlowy .
=> Update pt-PT translations

frontend/appflowy_flutter/lib/plugins/database_view/widgets/share_button.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/dandelion.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lavender.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lemonade.dart
- Share button color improvement: I found a dark text color actually matches all the theme's primary color
- Improve the shadow color in light mode.
- Use the same hover color in dark mode for any theme: 
---
=> fix: fix lemonade theme issues

frontend/appflowy_flutter/integration_test/share_markdown_test.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/callout_node_parser.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/code_block_node_parser.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/divider_node_parser.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/document_markdown_parsers.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/markdown_parsers.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/math_equation_node_parser.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/toggle_list_node_parser.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart, frontend/appflowy_flutter/lib/workspace/application/export/document_exporter.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/appflowy_flutter/test/unit_test/editor/share_markdown_test.dart
=> feat: add toggle list and callout node parser

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/code_block_node_parser.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/custom_image_node_parser.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/divider_node_parser.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/document_markdown_parsers.dart, frontend/appflowy_flutter/lib/workspace/application/export/document_exporter.dart, frontend/appflowy_flutter/test/unit_test/editor/share_markdown_test.dart
=> fix: unable to export image to markdown

frontend/appflowy_flutter/lib/plugins/database_view/calendar/application/calendar_event_editor_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_event_editor.dart
=> fix: calendar eventcard not displaying as intended

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSlash/BlockSlashMenu.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSlash/index.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/useTurnIntoBlockEvents.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/InlineBlock/PageInline.tsx, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/SubscribeNode.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/usePanelSearchText.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/workspace/page/page_controller.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/insert.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/update.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/mention.ts, frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/turn_to.ts, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml
=> fix: slash command panel bugs

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrolling/styled_scrollview.dart
[BUG] #3750 
Fixed the issue where the horizontal scrollbar was disappearing in the grid view, when scrolling horizontally using trackpad or `shift + mouse scroll wheel`
---
https://github.com/AppFlowy-IO/AppFlowy/assets/114166000/e96ed8da-8fde-4099-acc2-a9cee874660e
=> fix: fixed the horizontal scrollbar disappearing in grid view

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/event-integration/src/lib.rs, frontend/rust-lib/event-integration/tests/database/supabase_test/helper.rs, frontend/rust-lib/event-integration/tests/user/supabase_test/auth_test.rs, frontend/rust-lib/flowy-core/src/deps_resolve/document_deps.rs, frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs, frontend/rust-lib/flowy-core/src/lib.rs, frontend/rust-lib/flowy-database-deps/src/cloud.rs, frontend/rust-lib/flowy-database2/src/manager.rs, frontend/rust-lib/flowy-document-deps/src/cloud.rs, frontend/rust-lib/flowy-document2/src/manager.rs, frontend/rust-lib/flowy-document2/tests/document/util.rs, frontend/rust-lib/flowy-server/src/af_cloud/impls/database.rs, frontend/rust-lib/flowy-server/src/af_cloud/impls/document.rs, frontend/rust-lib/flowy-server/src/af_cloud/impls/file_storage.rs, frontend/rust-lib/flowy-server/src/af_cloud/impls/folder.rs, frontend/rust-lib/flowy-server/src/af_cloud/impls/user.rs, frontend/rust-lib/flowy-server/src/local_server/impls/database.rs, frontend/rust-lib/flowy-server/src/local_server/impls/document.rs, frontend/rust-lib/flowy-server/src/supabase/api/database.rs, frontend/rust-lib/flowy-server/src/supabase/api/document.rs, frontend/rust-lib/flowy-server/tests/supabase_test/database_test.rs, frontend/rust-lib/flowy-user/src/manager.rs, frontend/scripts/makefile/env.toml
=> chore: update client api commit id

frontend/appflowy_flutter/integration_test/database_calendar_test.dart, frontend/appflowy_flutter/integration_test/util/database_test_op.dart
=> fix: integration tests failing on Sundays

frontend/appflowy_flutter/lib/workspace/application/settings/notifications/notification_settings_cubit.dart, frontend/rust-lib/flowy-user/src/entities/user_setting.rs
=> fix: notification settings initial state

frontend/appflowy_flutter/lib/plugins/document/presentation/more/font_size_switcher.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/more/more_button.dart
Fix [issue 3749](https://github.com/AppFlowy-IO/AppFlowy/issues/3749). By following changes:
1. Increase PopupMenuButton maximum width to adapt to sub widget width display.
2. Use SegmentedButton to replace ToggleButton for better display.
fix [#3749 ](https://github.com/AppFlowy-IO/AppFlowy/issues/3749)
---
=> fix: font size text being displayed out of range.

frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/language.dart, frontend/resources/translations/am-ET.json
[fixes](https://github.com/AppFlowy-IO/AppFlowy/issues/3728)
---
=> Add amharic translation

.github/workflows/flutter_ci.yaml, frontend/appflowy_flutter/lib/plugins/document/presentation/more/font_size_switcher.dart, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> chore: remove the unit tests of Windows and macOS

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/slash_menu_items.dart
=> feat: insert date from slash menu

frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart
=> fix: what is new button broken link

frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
=> feat: save card orders

frontend/resources/translations/de-DE.json
fix around #3784
I have updated the German translation so that the text is fully visible and conveys the correct meaning. 
I also checked all other languages, and none are causing any text overflow.
Special Thanks to MacMeikel#6875 from discord.
---
=> chore: update german translation for select option

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
=> feat: set the default font family to Poppins on mobile

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_action_widget.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/personal_folder/mobile_home_personal_folder.dart, frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/draggable_view_item.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/draggable_item/draggable_item.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/6734e75b-7c3d-4a62-a92c-21eb88cf4089
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/bc6f22b5-9f41-4b07-879f-780d02a78b86
---
=> feat: enable mobile view item drag-and-drop reordering

frontend/appflowy_flutter/lib/plugins/database_view/board/application/board_bloc.dart
=> fix: edit card title not working

frontend/appflowy_flutter/lib/plugins/database_view/board/application/board_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/widgets/board_column_header.dart
=> fix: more board fixes

frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/cells/select_option_card_cell.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> chore: bump af board ver

frontend/appflowy_flutter/integration_test/board/board_add_row_test.dart, frontend/appflowy_flutter/integration_test/board/board_test_runner.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/database_controller.dart, frontend/appflowy_flutter/lib/plugins/database_view/application/database_view_service.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/application/board_bloc.dart
=> fix: add card at the beginning

CHANGELOG.md, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
- Support showing checklist items inline in row page.
- Support inserting date from slash menu.
- Support renaming a stack directly by clicking on the stack name.
- Show the detailed reminder content in the notification center.
- Save card order in Board view.
- Allow to hide the ungrouped stack.
- Segmented the checklist progress bar.
- Optimize side panel animation.
- Fix calendar with hidden date or title doesn't show options correctly.
- Fix the horizontal scroll bar disappears in Grid view.
- Improve setting tab UI in Grid view.
- Improve theme of the code block.
- Fix some UI issues.
=> chore: bump version 0.3.7

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/link_to_page_widget.dart
Closes: #3839 
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/faba520a-e0d0-4258-87b2-1d5e8351c796
=> fix: link to page dialog offset

.github/workflows/release.yml, frontend/appflowy_flutter/macos/Runner.xcodeproj/project.pbxproj, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> fix: unable to build macOS universal package on x86 machine

frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_item.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart
=> fix: notification actions lemonade darkmode

frontend/appflowy_flutter/lib/plugins/database_view/tar_bar/tab_bar_view.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/share_button.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/dandelion.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lavender.dart, frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lemonade.dart
Change the share button text to white color in the default theme. The other themes keep the same as used to be.
---
=> chore: improve share button text color

frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_event_editor.dart
=> fix: calendar event editor field name overflow

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_document.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/resources/translations/en.json
**REQUIRES APPFLOWY_EDITOR 1.5.2**
Closes: #3582
=> feat: add placeholder to card editor

frontend/appflowy_flutter/integration_test/runner.dart, frontend/appflowy_flutter/integration_test/settings/notifications_settings_test.dart, frontend/appflowy_flutter/integration_test/settings/settings_runner.dart, frontend/appflowy_flutter/lib/startup/deps_resolver.dart, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/lib/user/application/reminder/reminder_bloc.dart
Closes: #3846 
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/f5c82f4d-af6f-41ad-ad32-a2e366788894
=> fix: notifications setting

CHANGELOG.md, frontend/Makefile.toml, frontend/appflowy_flutter/pubspec.yaml
=> chore: update to version 0.3.8

frontend/appflowy_flutter/lib/plugins/database_view/board/application/board_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/board_page.dart
=> fix: integration tests

frontend/appflowy_flutter/lib/plugins/database_view/board/application/board_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/widgets/board_hidden_groups.dart
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3951
---
=> chore: fix ungroupedsection being shown

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_property.dart, frontend/resources/translations/am-ET.json, frontend/resources/translations/ar-SA.json, frontend/resources/translations/ca-ES.json, frontend/resources/translations/de-DE.json, frontend/resources/translations/en.json, frontend/resources/translations/es-VE.json, frontend/resources/translations/eu-ES.json, frontend/resources/translations/fa.json, frontend/resources/translations/fr-CA.json, frontend/resources/translations/fr-FR.json, frontend/resources/translations/hin.json, frontend/resources/translations/hu-HU.json, frontend/resources/translations/id-ID.json, frontend/resources/translations/it-IT.json, frontend/resources/translations/ja-JP.json, frontend/resources/translations/ko-KR.json, frontend/resources/translations/pl-PL.json, frontend/resources/translations/pt-BR.json, frontend/resources/translations/pt-PT.json, frontend/resources/translations/ru-RU.json, frontend/resources/translations/sv-SE.json, frontend/resources/translations/tr-TR.json, frontend/resources/translations/uk-UA.json, frontend/resources/translations/ur.json, frontend/resources/translations/vi-VN.json, frontend/resources/translations/zh-CN.json, frontend/resources/translations/zh-TW.json
Sorry, I’m just learning to contribute. :)
I didn't understand why **snake_case** is used for the variable `create_new_card` and not **lowerCamelCase**.
So I decided it was a typo and corrected it.
🤦🏼‍♂️ And I also added **part** of Russian translation from [prev PR](https://github.com/AppFlowy-IO/AppFlowy/pull/3933), excuse the inaccuracy 😿 
Please pay attention!
=> chore: update Russian, fix naming conventions and typos

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart, frontend/resources/translations/en.json
=> Fix: checkbox power toggle missing configuration

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/row/row.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cell_builder.dart, frontend/appflowy_flutter/pubspec.lock
=> fix: card detail regression on desktop

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cell_builder.dart
I set Grid**CellStyle to nullable to avoid this error popup in mobile.
---
=> fix: fix mobile grid cell error

frontend/appflowy_flutter/lib/user/presentation/widgets/folder_widget.dart
=> fix: login page hint text overflow

frontend/resources/translations/tr-TR.json
Existing translation strings are reviewed and missing ones  are completed.
=> Turkish translation update

frontend/resources/translations/pl-PL.json
=> chore: updated polish translations

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_action_widget.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_edit_link_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_item/mobile_text_decoration_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_item/utils.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/packages/appflowy_backend/ios/Classes/binding.h, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/20255862-6658-4375-aa15-6a9fc5d3bea9
---
=> feat: improve editing link user experience

frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml, frontend/appflowy_flutter/android/app/src/main/Classes/binding.h, frontend/appflowy_flutter/lib/startup/tasks/supabase_task.dart, frontend/appflowy_flutter/lib/user/application/auth/supabase_auth_service.dart, frontend/appflowy_flutter/lib/user/application/supabase_realtime.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> fix: unable to login on android when building in release mode

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/choicechip/select_option/option_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/multi_select.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/select_option.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/single_select.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/extension.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/select_option_editor.dart
fixes #4002 
also includes some code cleanup
---
=> chore: fix the select option mouse event conflict

frontend/appflowy_flutter/macos/Podfile
before
```log
/Users/lucas.xu/Desktop/development/AppFlowy/frontend/appflowy_flutter/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'FMDB' from project 'Pods')
/Users/lucas.xu/Desktop/development/AppFlowy/frontend/appflowy_flutter/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'HotKey' from project 'Pods')
/Users/lucas.xu/Desktop/development/AppFlowy/frontend/appflowy_flutter/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of …
```
=> chore: set mininum macos target development target supported to 10.14

frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_picker_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/language/language_picker_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/widgets/show_flowy_mobile_bottom_sheet.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_language_screen.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_editor.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/unsplash_image_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart
=> fix: mobile UI issues

frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_property_edit/mobile_field_editor.dart
=> fix: changing visibility of property

frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4009
---
=> fix: sv.json missing

.github/workflows/flutter_ci.yaml
=> chore: disable codecov

frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart, frontend/resources/translations/en.json
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/f19da479-5d8a-436c-804a-9487634910d7
=> feat: mobile no date optimization

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/edit_select_field.dart, frontend/appflowy_flutter/lib/plugins/base/drag_handler.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/mobile_select_option_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/moile_select_option_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/select_option_cell.dart, frontend/appflowy_flutter/lib/workspace/application/settings/appearance/mobile_appearance.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart, frontend/resources/flowy_icons/16x/m_checkbox_checked.svg, frontend/resources/flowy_icons/16x/m_checkbox_uncheck.svg
**How to integrate** 
```dart
showMobileBottomSheet(
context: context,
shape: const RoundedRectangleBorder(
borderRadius: BorderRadius.vertical(
top: Corners.s12Radius,
),
),
builder: (context) {
return MobileSelectOptionEditor(
cellController: cellController,
);
},
);
```
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/d66e5a61-0302-4ac2-9494-61656ed68868
---
=> feat: support select / multi select option

frontend/appflowy_flutter/lib/startup/deps_resolver.dart, frontend/appflowy_flutter/lib/startup/startup.dart, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/lib/startup/tasks/appflowy_cloud_task.dart, frontend/appflowy_flutter/lib/user/application/auth/af_cloud_auth_service.dart, frontend/appflowy_flutter/lib/user/application/sign_in_bloc.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-user/src/event_handler.rs, frontend/rust-lib/flowy-user/src/event_map.rs, frontend/rust-lib/flowy-user/src/manager.rs
=> feat: open appflowy from admin web

frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart, frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_buttons.dart
- Improve the logo color in dark mode, center the icon and text
- Improve the UI when there is no cloud service
---
=> chore: improve UI in MobileSignInScreen

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/.cargo/config.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml
=> Fix macos open crash

frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart, frontend/appflowy_flutter/lib/plugins/database_view/tab_bar/mobile/mobile_tab_bar_header.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
=> feat: support editing database icon

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/personal_info/edit_username_bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/personal_info/personal_info_setting_group.dart, frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_paginated_bottom_sheet.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/select_option_cell.dart, frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
=> feat: hide tabbar when pushing to view page

frontend/.vscode/tasks.json, frontend/appflowy_flutter/lib/env/cloud_env.dart, frontend/appflowy_flutter/lib/env/env.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_appflowy_cloud.dart
=> chore: enable debug with localhost

frontend/appflowy_flutter/env.cloud.test, frontend/appflowy_flutter/integration_test/util/base.dart, frontend/appflowy_flutter/lib/env/cloud_env_test.dart, frontend/appflowy_flutter/lib/startup/deps_resolver.dart, frontend/appflowy_flutter/lib/startup/tasks/rust_sdk.dart
=> ci: cloud integration test

frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/mobile_row_property_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_home_recent_views.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/row/mobile_row.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/select_option_cell.dart, frontend/appflowy_flutter/lib/workspace/application/settings/appearance/mobile_appearance.dart
follow the commits. Grid cell padding will be adjusted in a future pr
---
=> chore: misc mobile UI improvements

frontend/appflowy_flutter/lib/env/cloud_env.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/database/util.rs, frontend/rust-lib/flowy-database2/src/services/field_settings/entities.rs, frontend/rust-lib/flowy-database2/tests/database/field_settings_test/script.rs, frontend/rust-lib/flowy-database2/tests/database/field_settings_test/test.rs, frontend/rust-lib/flowy-server/Cargo.toml
=> chore: bump up yrs to 0.17.1

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-user/src/migrations/document_empty_content.rs
No need to do migration  if the document can open
=> chore: fix migrate empty document

frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/_field_options_eidtor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/mobile_row_property_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/row/cells/mobile_checklist_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/grid_header.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cell_builder.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/checklist_cell.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/checklist_cell_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/checklist_progress_bar.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/mobile_checklist_cell_editor.dart, frontend/appflowy_flutter/lib/util/field_type_extension.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/b5fedafb-53d8-4308-b510-76387f48c8ef
---
=> feat: mobile checklist

frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/application/grid_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/mobile_grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/mobile_fab.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/ced6fc5b-e0ed-486e-9f6c-fcad2864e860
---
=> feat: mobile grid fab

frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/extension.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/select_option_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/select_option_editor_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_property.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/f0c34b2c-b68f-4e73-822a-0b713eeca8dc
---
=> fix: double click to select / unselect options

frontend/appflowy_flutter/lib/plugins/document/application/doc_bloc.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-document2/src/event_handler.rs, frontend/rust-lib/flowy-error/src/impl_from/collab.rs, frontend/rust-lib/flowy-user/src/migrations/document_empty_content.rs, frontend/rust-lib/flowy-user/src/migrations/util.rs, frontend/rust-lib/flowy-user/src/services/database.rs
=> chore: bump collab rev

frontend/rust-lib/flowy-server/src/af_cloud/impls/user/dto.rs
=> fix: url icon

frontend/appflowy_flutter/lib/mobile/presentation/setting/cloud/appflowy_cloud_page.dart
=> fix: nav title of cloud setting on mobile

frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/_field_options.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/application/grid_bloc.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/layout/layout.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/mobile_grid_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/grid_header.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/checklist_cell/mobile_checklist_cell_editor.dart, frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_anonymous_button.dart, frontend/appflowy_flutter/lib/workspace/application/settings/appearance/mobile_appearance.dart
=> chore: fix grid width update

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml
=> chore: bump client api

.github/workflows/build_android_apk.yaml, frontend/Makefile.toml, frontend/appflowy_flutter/android/app/src/main/CMakeLists.txt, frontend/scripts/makefile/flutter.toml, frontend/scripts/makefile/mobile.toml
=> feat: support building apk on github action

frontend/resources/translations/pt-BR.json
Updated the latest pt-BR translations.
=> Update pt-BR translations

frontend/appflowy_flutter/lib/mobile/presentation/database/board/mobile_board_content.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/card/card.dart, frontend/appflowy_flutter/lib/workspace/application/settings/appearance/mobile_appearance.dart
- Improve the splash color on the outlined button
- Improve the card border and color in dark mode
---
=> fix: mobile UI

frontend/appflowy_flutter/lib/workspace/application/settings/appearance/desktop_appearance.dart, frontend/appflowy_flutter/lib/workspace/application/settings/appearance/mobile_appearance.dart
=> chore: disable material3

frontend/.vscode/launch.json, frontend/appflowy_flutter/lib/plugins/database_view/application/field/type_option/type_option_data_controller.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/presentation/board_page.dart, frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/toolbar/calendar_layout_setting.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/choicechip/select_option/option_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/choicechip/select_option/select_option.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/create_filter_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_type_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/grid_header.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/date.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/number.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/select_option_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/row/action.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/sort/create_sort_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/tab_bar/desktop/tab_bar_header.dart, frontend/appflowy_flutter/lib/plugins/database_view/tab_bar/tab_bar_view.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/date_cell/date_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/setting/database_layout_selector.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/setting/database_settings_list.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/setting/mobile_calendar_settings.dart, frontend/appflowy_flutter/lib/plugins/trash/trash_page.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/color_picker.dart
=> fix: database memory leaks

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml
=> chore: bump up client api

frontend/.vscode/launch.json
=> chore: revert flutterMode

frontend/resources/translations/zh-CN.json
=> fix Chinese translation error

frontend/appflowy_flutter/lib/mobile/presentation/home/personal_folder/mobile_home_personal_folder.dart, frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart, frontend/appflowy_flutter/lib/user/presentation/screens/splash_screen.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/4afe7132-1f5e-4f08-8f41-1f7bab978af8
---
=> fix: unable to sync the folder data

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-folder2/src/lib.rs, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-folder2/src/manager_init.rs, frontend/rust-lib/flowy-folder2/src/manager_observer.rs, frontend/rust-lib/flowy-folder2/src/util.rs
=> chore: open local folder when fail to init with remote server data

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-folder2/src/manager.rs, frontend/rust-lib/flowy-folder2/src/manager_init.rs
=> chore: bump client api and collab

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
- set text scaler factor as 1.0 to disable the system font size setting.
- support customizing the drag handler ball size.
- support customizing the magnifier size.
- add more padding between toolbar and cursor.
- support moving the cursor by long press gesture.
---
=> feat: mobile UI improvement

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_shortcut_event.dart
=> fix: exclude hyphen in code block

frontend/resources/translations/pt-BR.json
=> fix: translation into the wrong language

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_editor.dart, frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/select/select_option.dart
=> fix: select field type option editor overflow

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
=> fix: remove italic in inlined code

frontend/appflowy_flutter/lib/plugins/trash/application/trash_service.dart, frontend/appflowy_flutter/lib/workspace/application/home/home_service.dart, frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart, frontend/appflowy_tauri/src/appflowy_app/components/database/application/database_view/database_view_service.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/workspace/page/page_bd_svc.ts, frontend/appflowy_tauri/src/appflowy_app/stores/effects/workspace/trash/bd_svc.ts, frontend/rust-lib/event-integration/src/folder_event.rs, frontend/rust-lib/event-integration/tests/folder/local_test/script.rs, frontend/rust-lib/event-integration/tests/folder/local_test/test.rs, frontend/rust-lib/flowy-folder2/src/event_map.rs
=> chore: rename folder event

frontend/resources/translations/ru-RU.json
=> sync russian translation

frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/option_text_field.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/date_picker/mobile_date_picker_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_type_grid.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_type_option_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_field_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_quick_actions.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/edit_database_view_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_option_tile.dart, frontend/appflowy_flutter/lib/plugins/database_view/tab_bar/mobile/mobile_tab_bar_header.dart, frontend/appflowy_flutter/lib/plugins/database_view/tab_bar/tab_bar_view.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_property.dart, frontend/appflowy_flutter/lib/plugins/database_view/widgets/setting/mobile_database_controls.dart, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
=> fix: mobile launch review

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_align_items.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_bius_items.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_block_items.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_color_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_color_list.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_font_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_heading_and_text_items.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_indent_items.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_menu_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_popup_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_toolbar_theme.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/undo_redo_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/util.dart, frontend/appflowy_flutter/lib/workspace/application/settings/appearance/mobile_appearance.dart
**The colors for the dark mode were generated by AI.**
---
=> feat: improve toolbar dark mode

frontend/resources/translations/de-DE.json
Hi,
this is my first PR here. I hope it is fine, if not please ping me to improve my PR.
some better translations for the German UI
=> fix:Better wording for German i18n

frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/mobile_block_action_buttons.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_selection_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_indent_items.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/keyboard_height_observer.dart, frontend/appflowy_flutter/lib/startup/startup.dart, frontend/appflowy_flutter/lib/startup/tasks/device_info_task.dart, frontend/appflowy_flutter/lib/startup/tasks/prelude.dart
=> feat: add image block on mobile

frontend/appflowy_flutter/android/app/build.gradle, frontend/appflowy_flutter/packages/appflowy_backend/example/android/app/build.gradle
=> chore: adjust configuration for google play console

frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/group_card_header.dart, frontend/appflowy_flutter/lib/plugins/database_view/board/application/board_bloc.dart
When the user taps outside the text field, the keyboard will disappear.
https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/416387e3-357d-4dc7-9674-cf428d74721c
---
=> fix: group name edit issue in mobile

frontend/appflowy_flutter/pubspec.yaml
Update the board package ref version to fix the scroll card issue around groups
---
=> chore: update board package ref version

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_edit_link_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_item/utils.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_block_items.dart, frontend/appflowy_flutter/pubspec.lock
=> fix: unable to see the text of link menu in dark mode

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/emoji_picker_button.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_align_items.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_color_list.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_font_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
=> fix: disable unsupported buttons

frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_edit_field_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_type_option_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart
=> fix: field editor bugs

frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/mobile_board_trailing.dart, frontend/appflowy_flutter/lib/workspace/application/settings/appearance/mobile_appearance.dart
Set the text style on the elevated button to the theme font.
---
=> chore: unify the text font in elevated button

frontend/resources/translations/de-DE.json
follow-up of #4227
more labels are now translated to German.
More will follow in the next days/weeks.
=> fix:More labels to German translated and improved (part 2)

CHANGELOG.md, frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart
=> chore: bump version 0.4.0

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/clipboard_service.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> chore: upgrade flutter dependencies

frontend/Makefile.toml, frontend/scripts/code_generation/freezed/generate_freezed.cmd
=> chore: adjust flutter windows release path

frontend/Makefile.toml, frontend/scripts/makefile/flutter.toml
=> fix: windows package output path

frontend/resources/translations/de-DE.json
follow-up of #4248
more labels are now translated to German.
More translated text will follow in the next days/weeks. 2/3 is done.
=> fix: more labels translated to German and improved (part 3)

frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/type_option/number.dart
=> fix: number field editor full height

frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/type_option/select/select_option.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/row/cells/select_option_cell/extension.dart
=> fix: adjust select option button hover and padding

frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
- Redesign the touch gesture system.
- Add `HapticFeedback` when moving cursor and extending selection.
- Support selecting a word by long pressing, and add `HapticFeedback` too.
- Extend the drag handle hit test area.
- New UI design for drag handle.
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/d45bd7d8-84fa-4111-b758-88dfa1d63342
- Redesign the touch gesture system.
- Extend the drag handle hit test area.
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/d7ed7f01-4449-4d51-b953-bb9a2e39c822
---
=> feat: improve mobile touch gesture experience

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/event-integration/tests/user/af_cloud_test/import_af_data_folder_test.rs, frontend/rust-lib/flowy-ai/tests/util/mod.rs, frontend/rust-lib/flowy-document/src/manager.rs, frontend/rust-lib/flowy-user/src/services/data_import/appflowy_data_import.rs
=> fix: create offline document

frontend/resources/translations/zh-TW.json
Improve current zh-TW Traditional Chinese translation :taiwan:
=> Improve current zh-TW Traditional Chinese translation

frontend/appflowy_flutter/lib/plugins/database/application/defines.dart, frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/mobile_grid_page.dart, frontend/appflowy_flutter/lib/startup/tasks/device_info_task.dart, frontend/appflowy_flutter/lib/user/application/encrypt_secret_bloc.dart, frontend/appflowy_flutter/lib/user/presentation/screens/encrypt_secret_screen.dart, frontend/appflowy_flutter/lib/user/presentation/screens/workspace_error_screen.dart, frontend/appflowy_flutter/lib/workspace/application/settings/setting_file_importer_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_file_import_appflowy_data_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_supabase_cloud.dart
=> feat: show indicator when importing appflowy data

frontend/appflowy_flutter/lib/startup/startup.dart, frontend/appflowy_flutter/lib/startup/tasks/device_info_task.dart
=> fix: unable to get the device info in test mode

frontend/Makefile.toml, frontend/scripts/makefile/flutter.toml
=> chore: reduce package size

frontend/appflowy_flutter/lib/env/cloud_env.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_appflowy_cloud.dart
=> feat: using appflowy cloud as the default cloud type

frontend/appflowy_flutter/macos/Runner/Configs/AppInfo.xcconfig, frontend/appflowy_flutter/windows/runner/Runner.rc, frontend/appflowy_tauri/src/appflowy_app/components/layout/FooterPanel.tsx
fix copyright year from 2023 to 2024 in issue #4378 
---
=> fix: change copyright year to 2024

.github/workflows/flutter_ci.yaml, .github/workflows/rust_ci.yaml, frontend/appflowy_flutter/integration_test/util/base.dart, frontend/appflowy_flutter/lib/env/cloud_env.dart, frontend/appflowy_flutter/lib/env/env.dart, frontend/appflowy_flutter/lib/startup/deps_resolver.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_appflowy_cloud.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_cloud.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_file_import_appflowy_data_view.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/resources/translations/en.json, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/event-integration/src/user_event.rs, frontend/rust-lib/event-integration/tests/user/af_cloud_test/auth_test.rs, frontend/rust-lib/flowy-document/src/manager.rs, frontend/rust-lib/flowy-server/src/local_server/impls/user.rs, frontend/rust-lib/flowy-server/src/supabase/api/user.rs, frontend/rust-lib/flowy-user/src/services/data_import/appflowy_data_import.rs, frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs, frontend/scripts/docker-buildfiles/Dockerfile
=> chore: support localhost and development mode

frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> chore: update editor version

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/keyboard_height_observer.dart
=> fix: unable to use slide gesture to close keyboard

frontend/scripts/install_dev_env/install_linux.sh
---
- [ N/A ] I've listed at least one issue that this PR fixes in the description above.
=> fix: Print correct package name

frontend/resources/translations/fr-FR.json
---
Added all french translations usin inlang
=> Update french translations 

frontend/resources/translations/hu-HU.json
The Hungarian translation was inconsistent, sometimes it is used informal tense, instead of the more common formal tense. There was a couple missing labels, and also some very misleading translation was picked - for example "property" translated as "estate" or "landholding"
---
=> Fix Hungarian translations

.github/workflows/build_android_apk.yaml, .github/workflows/release.yml, frontend/appflowy_flutter/lib/env/cloud_env.dart, frontend/scripts/makefile/flutter.toml
- set appflowy cloud as default cloud type value in debug mode too.
---
=> fix: mobile sign-in issue

frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_setting_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/about/about_setting_group.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/user_session_setting_group.dart, frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart, frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_or_logout_button.dart, frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_buttons.dart
- Enable anonymous sign-in on mobile.
- If a user signs in with an anonymous session, third-party sign-in buttons and a logout button will be displayed on the settings page.
- If a user signs in with third-party services, only the logout button will be shown.
---
=> feat: enable anonymous sign in on mobile

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-server/src/af_cloud/server.rs
=> chore: bump client api to fix user session issue

frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_home_recent_views.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4283
---
=> feat: keep the offset of the recent section

frontend/appflowy_flutter/ios/Podfile.lock, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_edit_field_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_type_option_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/mobile_calendar_events_empty.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/mobile_calendar_events_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_setting_page.dart, frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notifications_hub_empty.dart, frontend/resources/translations/en.json
Closes: #4347
Closes: #4433 
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/18051c83-d985-452c-a141-76d48a37042d
=> Fix: mobile improvements

frontend/appflowy_flutter/integration_test/document/document_alignment_test.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/mobile_hidden_groups_column.dart, frontend/appflowy_flutter/lib/plugins/database/application/cell/select_option_cell_service.dart, frontend/appflowy_flutter/lib/plugins/database/application/defines.dart, frontend/appflowy_flutter/lib/plugins/database/application/field/field_service.dart, frontend/appflowy_flutter/lib/plugins/database/application/row/row_cache.dart, frontend/appflowy_flutter/lib/plugins/database/application/row/row_controller.dart, frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart, frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_event_editor_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/grid/application/row/row_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/grid/application/row/row_detail_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/mobile_row.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/row.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/card/card_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/row/cells/select_option_cell/select_option_editor_bloc.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/align_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/custom_text_align_command.dart
=> chore: code cleanup

frontend/appflowy_flutter/lib/mobile/presentation/favorite/mobile_favorite_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/example/lib/main.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/flowy_overlay.dart
=> chore: optimize android UI

frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart
=> fix: mobile row detail title not being updated

frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_home_recent_views.dart
=> feat: update recentViews list to only keep the first 20 items

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_block_action_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/mobile_block_action_buttons.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart
=> fix: unable to delete image and refactor image actions menu

frontend/appflowy_flutter/ios/Podfile.lock, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_create_field_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_edit_field_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_type_grid.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_type_option_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_field_list.dart
- field type option data not getting updated during field editing
- back navigation gesture not saving field updates during field editing
- changing field type when creating a new field always changes the name of the field.
---
=> fix: mobile field editing related bugs

frontend/appflowy_flutter/lib/mobile/presentation/base/flowy_search_text_field.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_type_option_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_option_tile.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart, frontend/resources/flowy_icons/16x/m_blue_check.svg
=> feat: new UI design for number format list

frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/date_picker.dart
Closes: #4540 
Some languages have one character for their Day of Week (E).
=> fix: idiomatic dow can be 1 character

frontend/appflowy_flutter/ios/Podfile.lock, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu.dart, frontend/appflowy_flutter/lib/shared/appflowy_network_image.dart, frontend/appflowy_flutter/lib/util/file_extension.dart, frontend/appflowy_flutter/lib/util/string_extension.dart, frontend/resources/translations/en.json
- limit maximum image upload size to 10MB
- disable copy link option for the image saved in cloud server
---
=> feat: optimize image block

frontend/appflowy_flutter/ios/Podfile.lock, frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/mobile_hidden_groups_column.dart, frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_trash_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/user_session_setting_group.dart, frontend/appflowy_flutter/lib/mobile/presentation/widgets/show_flowy_mobile_confirm_dialog.dart
=> feat: add signout dialog

frontend/rust-lib/flowy-core/src/integrate/user.rs, frontend/rust-lib/flowy-database2/src/manager.rs, frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs, frontend/rust-lib/flowy-server/src/local_server/impls/user.rs, frontend/rust-lib/flowy-server/tests/supabase_test/user_test.rs, frontend/rust-lib/flowy-user-pub/src/entities.rs, frontend/rust-lib/flowy-user-pub/src/session.rs, frontend/rust-lib/flowy-user/src/anon_user/migrate_anon_user_collab.rs, frontend/rust-lib/flowy-user/src/anon_user/sync_supabase_user_collab.rs, frontend/rust-lib/flowy-user/src/services/data_import/appflowy_data_import.rs, frontend/rust-lib/flowy-user/src/services/sqlite_sql/workspace_sql.rs
=> chore: rename

frontend/appflowy_flutter/ios/Podfile.lock, frontend/appflowy_flutter/lib/mobile/presentation/setting/launch_settings_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/support_setting_group.dart, frontend/appflowy_flutter/lib/util/share_log_files.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/resources/translations/en.json
=> feat: support exporting log files

frontend/appflowy_flutter/assets/template/readme.json
=> chore: get rid of space in code block of readme

frontend/appflowy_flutter/lib/mobile/presentation/base/type_option_menu_item.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/ba97fdd3-9576-4665-8625-a644b35b7fbf
---
=> feat: reafactor add block menu

frontend/resources/translations/zh-TW.json
This is a follow up of #4345, to continue improve the translation quality, as the original translation was more Simplified-Chinese, and there are also some new strings need to be translated.
=> chore: further improve and update zh-TW translation

.github/workflows/release.yml, frontend/scripts/code_generation/flowy_icons/generate_flowy_icons.sh, frontend/scripts/code_generation/language_files/generate_language_files.sh, frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml, frontend/scripts/linux_distribution/appimage/build_appimage.sh
https://github.com/LucasXu0/appflowy_package_builder/actions/runs/7741396546
---
=> fix: appimage build

frontend/appflowy_flutter/lib/env/cloud_env.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_appflowy_cloud.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_web/wasm-libs/Cargo.lock, frontend/appflowy_web/wasm-libs/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml
=> chore: fix ws conn

frontend/appflowy_flutter/integration_test/database/database_sort_test.dart, frontend/appflowy_flutter/integration_test/util/database_test_op.dart, frontend/appflowy_flutter/lib/plugins/database/application/field/field_controller.dart, frontend/appflowy_flutter/lib/plugins/database/application/sort/sort_service.dart, frontend/appflowy_flutter/lib/plugins/database/grid/application/sort/sort_editor_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/sort/sort_editor.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/sort/sort_menu.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/setting/setting_property_list.dart, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_tauri/src/appflowy_app/application/database/sort/sort_listeners.ts, frontend/appflowy_web/wasm-libs/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/flowy-database2/src/entities/filter_entities/util.rs, frontend/rust-lib/flowy-database2/src/entities/mod.rs, frontend/rust-lib/flowy-database2/src/entities/setting_entities.rs, frontend/rust-lib/flowy-database2/src/entities/sort_entities.rs, frontend/rust-lib/flowy-database2/src/event_handler.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_operation.rs, frontend/rust-lib/flowy-database2/src/services/sort/controller.rs, frontend/rust-lib/flowy-database2/src/services/sort/entities.rs, frontend/rust-lib/flowy-database2/tests/database/sort_test/multi_sort_test.rs, frontend/rust-lib/flowy-database2/tests/database/sort_test/script.rs, frontend/rust-lib/flowy-database2/tests/database/sort_test/single_sort_test.rs, frontend/rust-lib/lib-infra/src/validator_fn.rs
requires https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/156
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/3442
https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/5b7005b6-9e86-40bd-b822-d9f2bda3f2ff
=> feat: reorder sort precedence

frontend/appflowy_flutter/lib/plugins/database/application/field/field_info.dart, frontend/appflowy_flutter/packages/appflowy_backend/ios/Classes/binding.h, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs, frontend/rust-lib/flowy-database2/src/services/sort/controller.rs
=> feat: sort by last modified time or created time

frontend/appflowy_flutter/lib/shared/appflowy_network_image.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4591
---
=> fix: application will raise an error when selecting unsplash image inl ocal mode

frontend/appflowy_flutter/lib/plugins/database/widgets/setting/setting_property_list.dart
=> chore: add spacing between field buttons in setting popover

frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_user.dart
Closes: #4613 
Can open/close the settings dialog using `CMD + ,`/ `CTRL + ,` - Let me know if another binding is preferred.
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/e5051bd1-d086-469d-8ec6-e819b49df611
=> feat: hotkey to open settings dialog

frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_top_menu.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart
=> fix: use cmd+. to toggle sidebar on macOS

frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/grid_header.dart
=> fix: unequal grid header and body widths

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_rename_widget.dart
Closes: #4337 
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/ea4c173b-be32-42fd-97d4-80115ab1b315
=> fix: select name by default

.github/workflows/mobile_ci.yaml
=> chore: remove additionally unused tools

frontend/appflowy_flutter/integration_test/emoji_shortcut_test.dart, frontend/appflowy_flutter/integration_test/runner.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_menu_item.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_picker.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_shortcut_event.dart
---
https://github.com/AppFlowy-IO/AppFlowy/assets/35934427/61498e2b-4b77-476f-b4a0-217109e42bd1
Closes #2038 
Open the emoji selection menu with ctr/cmd+alt+e
=> feat: Open emoji selection menu with keyboard short

frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_shortcut_event.dart
=> fix: build regression

frontend/appflowy_flutter/integration_test/database/database_filter_test.dart, frontend/appflowy_flutter/lib/plugins/database/application/field/field_info.dart, frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/number_filter_editor_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/number.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/option_list.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/filter_info.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/filter_menu_item.dart, frontend/resources/translations/en.json
=> chore: enable number filter

frontend/resources/translations/ar-SA.json, frontend/resources/translations/ca-ES.json, frontend/resources/translations/de-DE.json, frontend/resources/translations/es-VE.json, frontend/resources/translations/eu-ES.json, frontend/resources/translations/fa.json, frontend/resources/translations/fr-CA.json, frontend/resources/translations/fr-FR.json, frontend/resources/translations/hu-HU.json, frontend/resources/translations/id-ID.json, frontend/resources/translations/it-IT.json, frontend/resources/translations/ja-JP.json, frontend/resources/translations/ko-KR.json, frontend/resources/translations/pl-PL.json, frontend/resources/translations/pt-BR.json, frontend/resources/translations/pt-PT.json, frontend/resources/translations/ru-RU.json, frontend/resources/translations/tr-TR.json, frontend/resources/translations/vi-VN.json, frontend/resources/translations/zh-CN.json, frontend/resources/translations/zh-TW.json
Update some missing translate for ENG to FR
=> chore: Update translations ENG to FR

.github/workflows/build_bot.yaml, .github/workflows/commit_lint.yml, .github/workflows/docker_ci.yml, .github/workflows/flutter_ci.yaml, .github/workflows/mobile_ci.yaml, .github/workflows/release.yml, .github/workflows/rust_ci.yaml, .github/workflows/rust_coverage.yml, .github/workflows/tauri_ci.yaml, .github/workflows/web_ci.yaml, frontend/resources/translations/en.json
=> fix: tauri build

frontend/resources/translations/fr-CA.json, frontend/resources/translations/fr-FR.json
Completes #4664
Improve translation for Toggle Lists.
=> Update fr-FR and fr-CA translations

frontend/appflowy_flutter/lib/startup/startup.dart
=> fix: dispose of previous applaunch tasks

frontend/rust-lib/flowy-database2/src/services/database_view/notifier.rs, frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs, frontend/rust-lib/flowy-database2/src/services/sort/controller.rs, frontend/rust-lib/flowy-database2/src/services/sort/entities.rs, frontend/rust-lib/flowy-database2/tests/database/sort_test/script.rs, frontend/rust-lib/flowy-database2/tests/database/sort_test/single_sort_test.rs
=> fix: newly-created rows aren't being automatically sorted

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_web/wasm-libs/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/collab-integrate/src/native/plugin_provider.rs, frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs, frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs, frontend/rust-lib/flowy-document/tests/document/util.rs, frontend/rust-lib/flowy-folder/src/manager.rs, frontend/rust-lib/flowy-user/src/user_manager/manager_user_awareness.rs
requires https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/158
for more information, please refer to that PR. I move the logic to find the first filter whose `field_id` matches here in `flowy_database2` so that it's clear that the `field_id` is defined in `flowy_database2::Filter`
---
=> chore: re-implement get_filter_by_field_id function

frontend/appflowy_flutter/lib/core/config/kv_keys.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/appearance/appearance_setting_group.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/appearance/text_scale_setting.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/more/cubit/document_appearance_cubit.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/more/font_size_slider.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/more/more_button.dart, frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart, frontend/appflowy_flutter/lib/workspace/application/settings/appearance/appearance_cubit.dart, frontend/appflowy_flutter/packages/flowy_svg/lib/src/flowy_svg.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml, frontend/resources/translations/en.json
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4685
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/d6eb9fbb-b4f0-488d-97ab-2e5532d92a1e
Known issue: the icon widgets dont support scaling. the icon widgets should be replaced with svg widgets.
---
=> feat: support scaling text on mobile

frontend/appflowy_flutter/android/app/src/main/Classes/binding.h, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_transition_bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_full_field_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_field_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_quick_actions.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/edit_database_view_screen.dart, frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/setting/mobile_database_controls.dart, frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> feat: bottom sheets with transition

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart
=> fix: the keyboard blocked the content of bottom sheet

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_menu.dart
=> chore: optimize image block actions menu

frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_quick_actions.dart, frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_mobile_quick_action_button.dart
=> fix: show database view options for inline as disabled

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option_action.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart, frontend/resources/translations/en.json
**no headings**
**no matching headings**
**matching headings**
- set the maximum visible depth to 6
---
=> feat: improve outline block

frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_editor.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/4715
---
=> fix: cjk input in calendar and row detail

frontend/appflowy_flutter/lib/plugins/document/presentation/more/cubit/document_appearance_cubit.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4709
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/bd3e6c2f-09e4-45bd-a71a-e096c17bd22a
---
=> fix: unable to click the items in a long list

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/block_menu/block_menu_button.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/custom_link_preview.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/link_preview_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/shared.dart, frontend/resources/translations/en.json
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4708
**desktop**
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/b2907bfd-bc61-432e-8ce8-8f07ae649393
**mobile**
---
=> feat: convert link preview block to url text

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_block_component.dart
Fixed part of https://github.com/AppFlowy-IO/AppFlowy/issues/4736
---
=> fix: the button sizes in math equation input field are not same

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_shortcut_event.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4487
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4492
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/e1cff78e-0da1-4c0c-979b-157fdedc0621
---
=> fix: unable to redo/undo in lists and data loss issues

frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/mobile_create_field_button.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/option_text_field.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_edit_field_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_full_field_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_field_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_quick_actions.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/mobile_field_button.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/mobile_grid_header.dart, frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart
- no autofocus on name of field editor
- tapping icon allows changing the type of the field
- applies to both the bottom sheet popup and the full screen editor.
- reduce spacing between toolbar and grid header
- fix a bug where users can't update the name of a database view
screen recording TBD
---
=> fix: some mobile database bugs

frontend/appflowy_flutter/android/app/src/main/Classes/binding.h, frontend/appflowy_flutter/lib/startup/tasks/rust_sdk.dart, frontend/appflowy_flutter/linux/flutter/dart_ffi/binding.h, frontend/appflowy_flutter/packages/appflowy_backend/ios/Classes/binding.h, frontend/appflowy_flutter/packages/appflowy_backend/lib/ffi.dart, frontend/appflowy_flutter/packages/appflowy_backend/lib/log.dart, frontend/appflowy_flutter/packages/appflowy_backend/linux/Classes/binding.h, frontend/appflowy_flutter/packages/appflowy_backend/macos/Classes/binding.h, frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_web/wasm-libs/Cargo.lock, frontend/appflowy_web/wasm-libs/Cargo.toml, frontend/rust-lib/Cargo.lock, frontend/rust-lib/Cargo.toml, frontend/rust-lib/dart-ffi/binding.h, frontend/rust-lib/dart-ffi/src/lib.rs, frontend/rust-lib/flowy-core/Cargo.toml, frontend/rust-lib/flowy-core/src/lib.rs, frontend/rust-lib/flowy-document/src/manager.rs, frontend/rust-lib/flowy-server/src/af_cloud/server.rs, frontend/rust-lib/lib-log/src/layer.rs, frontend/rust-lib/lib-log/src/lib.rs
=> chore: fix log

frontend/appflowy_flutter/lib/mobile/presentation/setting/about/about_setting_group.dart
=> chore: update privacy and terms link

frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
=> fix: mobile regression

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_menu.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/resizeable_image.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4749
---
=> fix: unable to resize the image

.github/workflows/mobile_ci.yaml
=> chore: cleanup disk space before running mobile ci

frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_block.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/migration/editor_migration.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_item/utils.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_bius_items.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_block_items.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_color_list.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/biuc_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/checkbox_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/more_toolbar_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/undo_redo_toolbar_item.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
=> fix: mobile UI regression

frontend/appflowy_tauri/src/appflowy_app/components/database/Database.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/database/Database.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/database_settings/DatabaseCollection.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/filter/Filter.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/filter/Filters.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/filter/date_filter/DateFilter.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/filter/date_filter/DateFilterValue.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/filter/number_filter/NumberFilterValue.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/filter/select_filter/SelectFilterValue.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/filter/text_filter/TextFilterValue.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/property/Property.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/database.scss, frontend/appflowy_tauri/src/appflowy_app/components/editor/command/formula.ts, frontend/appflowy_tauri/src/appflowy_app/components/editor/command/index.ts, frontend/appflowy_tauri/src/appflowy_app/components/editor/command/mark.ts, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/bulleted_list/BulletedListIcon.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/numbered_list/NumberListIcon.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/inline_nodes/inline_formula/InlineFormula.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/SelectionToolbar.hooks.ts, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/bold/Bold.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/formula/Formula.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/provider/utils/action.ts, frontend/appflowy_tauri/src/appflowy_app/components/editor/provider/utils/convert.ts, frontend/appflowy_tauri/src/appflowy_app/components/editor/stores/inline_node.ts, frontend/resources/translations/en.json
https://github.com/AppFlowy-IO/AppFlowy/assets/108015703/d4d554ed-7af0-417b-978a-509c257f33fe
https://github.com/AppFlowy-IO/AppFlowy/assets/108015703/c7296771-0c5a-45c3-9735-5bd126fc2635
---
=> feat: support to show condition in filter chip label

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_bius_items.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_color_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_color_list.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_font_item.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/util.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4762
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/3d398328-765e-4206-8f0e-15b177c8a09a
---
=> feat: support customizing font and color before typing

frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/view_meta_info.dart
=> fix: add time to view meta info

frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart, frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
=> fix: symmetric padding in mobile database header

frontend/resources/translations/ar-SA.json, frontend/resources/translations/ca-ES.json, frontend/resources/translations/de-DE.json, frontend/resources/translations/es-VE.json, frontend/resources/translations/eu-ES.json, frontend/resources/translations/fa.json, frontend/resources/translations/hu-HU.json, frontend/resources/translations/id-ID.json, frontend/resources/translations/it-IT.json, frontend/resources/translations/ja-JP.json, frontend/resources/translations/ko-KR.json, frontend/resources/translations/pl-PL.json, frontend/resources/translations/pt-BR.json, frontend/resources/translations/pt-PT.json, frontend/resources/translations/ru-RU.json, frontend/resources/translations/tr-TR.json, frontend/resources/translations/vi-VN.json, frontend/resources/translations/zh-CN.json, frontend/resources/translations/zh-TW.json
I translated parts of the text into Italian with the help of the translator (but, being Italian and therefore having Italian as my native language) I checked the syntax.
regards
Preview the messages on https://inlang.com/github.com/domenicodome/AppFlowy .
=> Update translations - partial Italian translation

frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/layout/sizes.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/layout/layout.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/layout/sizes.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/mobile_grid_page.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/grid_header.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/mobile_grid_header.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/mobile_row.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/row.dart, frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/setting_menu.dart, frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/tab_bar_header.dart, frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart, frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
1. adjust the padding in mobile grid, 16px on either side
2. reordering fields on mobile not working
---
=> fix: mobile ui fixes

frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/checklist_type_option/checklist.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/relation_type_option/relation.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/multi_select_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/single_select_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/timestamp_type_option/timestamp_type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option_cell.rs, frontend/rust-lib/flowy-database2/src/services/field/type_options/url_type_option/url_type_option.rs
=> chore: type option handler cleanup

.github/workflows/flutter_ci.yaml
The [flutter-action@2.13.0](https://github.com/subosito/flutter-action/releases/tag/v2.13.0) release came out and as a result our Flutter CI broke due to the following error:
```
Git error. Command: `git clone --mirror https://github.com/richardshiue/modal_bottom_sheet /c/Users/runneradmin/.pub-cache\git\cache\modal_bottom_sheet-c8bd9add1d9a97d898a12bad7d8e2e5ff759af5c`
stdout: 
stderr: fatal: destination path '/c/Users/runneradmin/.pub-cache\git\cache\modal_bottom_sheet-c8bd9add1d9a97d898a12bad7d8e2e5ff759af5c' already exists and is not an empty directory.
exit code: 128
```
- enable `flutter-action`'s cache feature (EDIT: cache isn't the same as pub cache)
- perform `dart pub cache clean` (EDIT: error)
```
No pub cache at /c/Users/runneradmin/.pub-cache.
```
- use the PR ref instead of …
=> fix: flutter_ci

frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
resolves https://github.com/AppFlowy-IO/AppFlowy/pull/4791
---
=> fix: reorder field updating all views

frontend/resources/translations/ru-RU.json
Preview the messages on https://inlang.com/github.com/dadyarri/appflowy
=> Update russian translations

frontend/appflowy_flutter/lib/core/helpers/url_launcher.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/about/about_setting_group.dart, frontend/appflowy_flutter/lib/mobile/presentation/setting/support_setting_group.dart, frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_mobile_state_container.dart, frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_cache.dart, frontend/appflowy_flutter/lib/plugins/database/application/row/row_cache.dart, frontend/appflowy_flutter/lib/plugins/database/application/view/view_cache.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_url_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_url_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_url_cell.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/custom_link_preview.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/util/learn_more_action.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart, frontend/appflowy_flutter/lib/user/application/auth/af_cloud_auth_service.dart, frontend/appflowy_flutter/lib/user/presentation/screens/skip_log_in_screen.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/errors/workspace_failed_screen.dart, frontend/appflowy_flutter/lib/workspace/presentation/home/toast.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_appflowy_cloud.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_file_import_appflowy_data_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_supabase_cloud.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_customize_location_view.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/theme_upload/theme_upload_learn_more_button.dart, frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart, frontend/resources/translations/en.json
Closes: #3060 
---
I haven't been able to test that this will work on Fedora / running AF in Flatpak.
Previously we used a helper function imported via appflowy_editor, this helper function should made private and only be used in the editor itself. It's `safeLaunchUrl`.
=> fix: launch url on all platforms

frontend/appflowy_flutter/integration_test/database/database_calendar_test.dart, frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_bloc.dart, frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_card.dart, frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_editor.dart
Closes: #4800 
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/f4a54e56-f037-439b-b078-9f46129ee28b
=> feat: duplicate calendar event

frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/link_to_page_widget.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/page_reference_commands.dart, frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/date_reference.dart, frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/inline_page_reference.dart, frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/reminder_reference.dart, frontend/appflowy_flutter/lib/plugins/inline_actions/inline_actions_command.dart, frontend/appflowy_flutter/lib/plugins/inline_actions/inline_actions_service.dart, frontend/appflowy_flutter/lib/plugins/inline_actions/service_handler.dart, frontend/appflowy_flutter/lib/plugins/inline_actions/widgets/inline_actions_handler.dart, frontend/rust-lib/flowy-folder/src/manager.rs
Closes: #3641 
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/38b56061-9437-47a4-b358-45130e0f3da5
=> fix: inline page reference update on workspace changes

frontend/appflowy_flutter/lib/mobile/presentation/base/option_color_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_transition_bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/date_picker/mobile_date_picker_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_full_field_editor.dart, frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_checklist_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_date_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_checklist_cell_editor.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_select_option_editor.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/setting/mobile_database_controls.dart, frontend/appflowy_flutter/lib/util/field_type_extension.dart, frontend/appflowy_flutter/lib/workspace/application/settings/appearance/mobile_appearance.dart
Title says all. Github doesn't allow me to upload this recording
---
=> chore: mobile grid dark mode improvements

frontend/appflowy_tauri/src-tauri/Cargo.lock, frontend/appflowy_tauri/src-tauri/Cargo.toml, frontend/appflowy_tauri/src-tauri/tauri.conf.json, frontend/appflowy_tauri/src/appflowy_app/application/document/document.types.ts, frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/LocalImage.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/UploadImage.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/UploadTabs.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/index.ts, frontend/appflowy_tauri/src/appflowy_app/components/_shared/view_title/cover/CoverPopover.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/view_title/cover/ViewCover.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageEmpty.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageRender.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageResizer.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/UploadPopover.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/math_equation/MathEquation.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/editor.scss, frontend/appflowy_tauri/src/appflowy_app/utils/mui.ts, frontend/appflowy_tauri/src/appflowy_app/utils/upload_image.ts, frontend/resources/translations/en.json
https://github.com/AppFlowy-IO/AppFlowy/assets/108015703/59f416e8-d309-4138-8b94-05bc3c51ff15
---
=> feat: support uploading local image

frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/option_text_field.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_select_option_editor.dart
=> fix: some mobile ui bugs

frontend/rust-lib/event-integration/tests/user/af_cloud_test/workspace_test.rs, frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
- delete local workspace after deleting workspace from cloud
=> fix: delete workspace after deleting from remote

frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_page.dart
=> fix: uninitialized error in members setting page

frontend/appflowy_flutter/lib/core/config/kv_keys.dart, frontend/appflowy_flutter/lib/shared/appflowy_cache_manager.dart, frontend/appflowy_flutter/lib/shared/feature_flags.dart, frontend/appflowy_flutter/lib/startup/deps_resolver.dart, frontend/appflowy_flutter/lib/startup/startup.dart, frontend/appflowy_flutter/lib/startup/tasks/feature_flag_task.dart, frontend/appflowy_flutter/lib/workspace/application/settings/settings_dialog_bloc.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/feature_flags/feature_flag_page.dart, frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/separated_flex.dart
=> feat: enable feature flag settings in debug mode

frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/field_type_list.dart
=> chore: enable relation

frontend/rust-lib/flowy-database2/src/services/field/type_options/relation_type_option/relation.rs
=> fix: relation hotfix

frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_sort_bottom_sheet.dart
=> fix: mobile grid launch review

frontend/.vscode/tasks.json, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/calculations/calculation_selector.dart, frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/field_editor.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart, frontend/appflowy_flutter/pubspec.lock
=> fix: desktop grid launch review

frontend/appflowy_flutter/lib/mobile/presentation/setting/support_setting_group.dart, frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart, frontend/resources/translations/en.json
- improve clear cache hint text.
- remove color tab in image picker.
---
=> fix: v0.5.1 issues

frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_item_body.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_page.dart, frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/default_mobile_action_pane.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_sort_bottom_sheet.dart, frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_list.dart, frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_option_tile.dart, frontend/appflowy_flutter/lib/plugins/database/application/field/field_controller.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/setting/mobile_database_controls.dart, frontend/resources/translations/en.json
- certain bottom sheets have the wrong color
- sort editor improvements
---
=> chore: some more mobile fixes

frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/EmbedLink.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/LocalImage.tsx, frontend/appflowy_tauri/src/appflowy_app/components/_shared/keyboard_navigation/KeyboardNavigation.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/checklist/AddNewOption.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/checklist/ChecklistCellActions.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/checklist/ChecklistItem.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/select/SelectOptionModifyMenu.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/select/select_cell_actions/SelectCellActions.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/text/EditTextCellInput.tsx, frontend/appflowy_tauri/src/appflowy_app/components/database/database.scss, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageRender.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageResizer.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/components/inline_nodes/link/LinkEditContent.tsx, frontend/appflowy_tauri/src/appflowy_app/components/editor/editor.scss, frontend/appflowy_tauri/src/appflowy_app/utils/upload_image.ts, frontend/resources/translations/en.json
=> fix: support upload and render image(.git, .webp, .svg)

frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/field_type_list.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart, frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart, frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart
=> fix: resort to using more conventional keyboard tab navigation

.github/workflows/rust_ci.yaml, frontend/rust-lib/flowy-server/src/af_cloud/server.rs
give me back my green checkmark.
---
=> ci: fix rust ci

frontend/appflowy_flutter/lib/core/helpers/url_launcher.dart, frontend/appflowy_flutter/pubspec.lock, frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4853
closes https://github.com/AppFlowy-IO/AppFlowy/issues/2801
- disable the shortcut for converting to numbered list when the block is a heading.
- Other shortcuts, such as converting a heading block to bulleted list still work.
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/e38bac4e-5a3f-4d43-8fa7-eb23e7de5bb9
---
=> disable the shortcut for converting to numbered list when the block is a heading

frontend/appflowy_flutter/integration_test/desktop/database/database_calendar_test.dart, frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart, frontend/appflowy_flutter/integration_test/shared/common_operations.dart
=> chore: try to fix flakiness
