AppFlowy-IO/AppFlowy

- .github/workflows/release.yml
> fix: release windows ci

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> fix: version bump sheet package

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/event-integration/src/folder_event.rs
- frontend/rust-lib/flowy-database2/tests/database/share_test/export_test.rs
- frontend/rust-lib/flowy-server/Cargo.toml
- frontend/rust-lib/flowy-server/src/af_cloud/server.rs
- frontend/rust-lib/lib-dispatch/src/module/module.rs
> chore: fix database test

- frontend/appflowy_flutter/lib/core/helpers/url_launcher.dart
- frontend/appflowy_flutter/lib/startup/tasks/appflowy_cloud_task.dart
- frontend/appflowy_flutter/lib/user/application/auth/af_cloud_auth_service.dart
- frontend/appflowy_flutter/lib/user/application/auth/auth_error.dart
> fix: sign in toast issue

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
> chore: bump client api that adding constraints for init sync

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> fix: mobile keyboard issues

- frontend/appflowy_flutter/integration_test/cloud/cloud_runner.dart
- frontend/appflowy_flutter/integration_test/cloud/workspace/change_name_and_icon_test.dart
- frontend/appflowy_flutter/integration_test/cloud/workspace/collaborative_workspace_test.dart
- frontend/appflowy_flutter/integration_test/shared/workspace.dart
- frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
- frontend/resources/translations/en.json
- frontend/rust-lib/event-integration/src/user_event.rs
- frontend/rust-lib/event-integration/tests/user/af_cloud_test/workspace_test.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
> feat: support changing the workspace icon

- frontend/resources/translations/el-GR.json
Opened new PR as requested @richardshiue
> feat: support el-GR language

- frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
- frontend/appflowy_flutter/packages/flowy_infra/lib/language.dart
- project.inlang.json
https://github.com/AppFlowy-IO/AppFlowy/pull/4920
---
> feat: support el_GR language

- frontend/rust-lib/flowy-database2/src/entities/filter_entities/checklist_filter.rs
- frontend/rust-lib/flowy-database2/src/entities/filter_entities/relation_filter.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_filter.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_filter.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/checklist_type_option/checklist_filter.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_filter.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_filter.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_filter.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_filter.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs
- frontend/rust-lib/flowy-database2/src/services/filter/controller.rs
- frontend/rust-lib/flowy-database2/src/services/filter/entities.rs
- frontend/rust-lib/flowy-database2/src/services/sort/controller.rs
- frontend/rust-lib/flowy-database2/tests/database/database_editor.rs
- frontend/rust-lib/flowy-database2/tests/database/field_test/test.rs
- frontend/rust-lib/flowy-database2/tests/database/filter_test/select_option_filter_test.rs
- frontend/rust-lib/flowy-database2/tests/database/mock_data/grid_mock_data.rs
- frontend/rust-lib/flowy-database2/tests/database/mod.rs
- frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/mod.rs
- frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/pre_fill_row_according_to_filter_test.rs
- frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/pre_fill_row_with_payload_test.rs
- frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/script.rs
a tech design write up is in the gantt
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/4468
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/4330
---
> feat: pre-fill row cells with filter data before row creation

- frontend/appflowy_flutter/android/app/src/main/CMakeLists.txt
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/scripts/makefile/mobile.toml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4624
Report from Google Play Console: some users were unable to install or launch AppFlowy on 32-bit devices.
**apk**
**apk**
**aab**
---
> feat: support 32-bit android devices

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/event-integration/src/document_event.rs
- frontend/rust-lib/event-integration/tests/database/supabase_test/helper.rs
- frontend/rust-lib/event-integration/tests/folder/supabase_test/helper.rs
- frontend/rust-lib/flowy-document/src/manager.rs
- frontend/rust-lib/flowy-server/src/supabase/api/user.rs
- frontend/rust-lib/flowy-server/tests/supabase_test/util.rs
- frontend/rust-lib/flowy-user/src/anon_user/migrate_anon_user_collab.rs
- frontend/rust-lib/flowy-user/src/anon_user/sync_supabase_user_collab.rs
- frontend/rust-lib/flowy-user/src/migrations/document_empty_content.rs
- frontend/rust-lib/flowy-user/src/migrations/util.rs
- frontend/rust-lib/flowy-user/src/services/data_import/appflowy_data_import.rs
- frontend/rust-lib/flowy-user/src/services/data_import/importer.rs
> chore: support skip gc

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_url_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_url_cell.dart
> fix: use bg color for mobile url bottom sheet

- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/feature_flags/feature_flag_page.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
- enable feature flags in setting during v0.5.3 launch review.
---
> chore: enable feature flags in settings

- .github/actions/flutter_build/action.yml
- .github/workflows/flutter_ci.yaml
- .github/workflows/release.yml
An upstream fix was merged recently that allows us to move away from this workaround https://github.com/subosito/flutter-action/pull/280
---
> ci: remove workaround for windows flutter ci

- frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/url_cell_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/condition_list.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/type_option/relation.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/relation_cell_editor.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/18c918a6-5e6a-4f24-9ef9-6dcd298545ac
---
> fix: launch review issues

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-core/src/integrate/log.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-document/src/manager.rs
- frontend/rust-lib/flowy-folder/src/event_handler.rs
- frontend/rust-lib/lib-dispatch/src/dispatcher.rs
> chore: bump client api that deduplicate sync message

- .github/workflows/release.yml
- Fixed issues with the AppImage build process.
- Resolved notification problems with Discord integration.
---
> fix: discord notify ci

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_editor.dart
- frontend/resources/translations/en.json
> chore: adjust select option editor

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
> chore: bump collab that fixs database row sync issue

- frontend/appflowy_flutter/lib/mobile/presentation/favorite/mobile_favorite_folder.dart
- frontend/appflowy_flutter/lib/mobile/presentation/favorite/mobile_favorite_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/favorite_folder/mobile_home_favorite_folder.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder_header.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
- frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
- frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_option_tile.dart
- frontend/appflowy_flutter/lib/workspace/application/favorite/favorite_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/favorite/favorite_listener.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
the collaboration feature flag is turned off. it's okay to merge into the main branch.
---
> feat: show member count on mobile

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
> fix: workspace names align issue

- frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
- frontend/rust-lib/flowy-folder/src/manager_observer.rs
> chore: remove repetitive words

- frontend/appflowy_flutter/lib/shared/af_role_pb_extension.dart
- frontend/appflowy_flutter/lib/user/application/user_service.dart
- frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
- frontend/resources/translations/en.json
> feat: support leaving workspace

- frontend/appflowy_flutter/lib/plugins/document/application/doc_collab_adapter.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/document_collaborators.dart
- frontend/appflowy_flutter/lib/shared/feature_flags.dart
- frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
> feat: enable collab workspace features

- frontend/appflowy_flutter/lib/plugins/document/application/doc_collab_adapter.dart
- frontend/appflowy_flutter/lib/shared/list_extension.dart
- frontend/rust-lib/flowy-core/src/integrate/log.rs
> fix: duplicated selections from remote

- frontend/appflowy_flutter/android/app/build.gradle
> chore: upgrade android min sdk version to 23 (android 6.0)

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/dart-ffi/Cargo.toml
- frontend/rust-lib/flowy-core/Cargo.toml
- frontend/rust-lib/flowy-document/Cargo.toml
- frontend/rust-lib/flowy-server/Cargo.toml
> feat: fetch missing updates

- .github/workflows/ios_ci.yaml
- frontend/appflowy_flutter/integration_test/desktop/uncategorized/switch_folder_test.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
- frontend/appflowy_flutter/lib/user/application/user_listener.dart
- frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
- frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
> fix: remove the deleted workspace from local storage

- frontend/appflowy_flutter/lib/plugins/document/application/doc_service.dart
> chore: replace close_document with close_view

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
> fix: the error of miss update yrs repo

- .github/workflows/web_ci.yaml
> chore: stop run web ci

- frontend/appflowy_flutter/lib/plugins/document/application/doc_sync_bloc.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/dart-ffi/Cargo.toml
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-document/src/document.rs
- frontend/rust-lib/flowy-document/src/manager.rs
> chore: start init sync when open document/database

- frontend/appflowy_flutter/lib/plugins/document/application/doc_collaborators_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/document_collaborators.dart
> fix: disable collaborators in local mode

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/event-integration/src/document/document_event.rs
- frontend/rust-lib/flowy-document/src/manager.rs
- frontend/rust-lib/flowy-server/src/local_server/impls/database.rs
- frontend/rust-lib/flowy-server/src/supabase/api/user.rs
- frontend/rust-lib/flowy-user/src/anon_user/sync_supabase_user_collab.rs
- frontend/rust-lib/flowy-user/src/migrations/document_empty_content.rs
- frontend/rust-lib/flowy-user/src/migrations/workspace_and_favorite_v1.rs
- frontend/rust-lib/flowy-user/src/migrations/workspace_trash_v1.rs
- frontend/rust-lib/flowy-user/src/services/data_import/appflowy_data_import.rs
> chore: bump collab

- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
- frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
> fix: workspaces empty error in local mode

- frontend/appflowy_flutter/integration_test/cloud/workspace/collaborative_workspace_test.dart
> fix: workspace integration test

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
> chore: bump client api 038

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
> chore: bump collab that do not emit awareness by default

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/dart-ffi/Cargo.toml
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
> chore: fix create workspace bugs

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> fix: delta insert assert

- frontend/appflowy_tauri/src-tauri/src/init.rs
- frontend/appflowy_web_app/src-tauri/src/init.rs
> fix: tauri ci error

- frontend/appflowy_flutter/lib/plugins/document/application/doc_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/application/doc_collab_adapter.dart
- frontend/appflowy_flutter/lib/util/throttle.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> fix: doc state refresh

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
> chore: update client api

- CHANGELOG.md
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> chore: update editor version & update CHANGELOG

- frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
- frontend/rust-lib/flowy-folder/src/event_handler.rs
- frontend/rust-lib/flowy-folder/src/event_map.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
> feat: get view ancestors

- frontend/appflowy_flutter/lib/shared/feature_flags.dart
> chore: disable team workspace

- frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
> fix: do not fetch reminders on resize window

- frontend/appflowy_flutter/lib/workspace/application/home/home_service.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart
> fix: hide menu resize when collapsed

- frontend/appflowy_flutter/lib/shared/feature_flags.dart
> chore: enable team workspace

- frontend/appflowy_flutter/lib/startup/tasks/app_window_size_manager.dart
- frontend/appflowy_flutter/lib/startup/tasks/windows.dart
> fix: windows size overflow

- .github/workflows/deploy_test_web.yaml
> fix: remove deploy web in main

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_cell_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_text_field.dart
> fix: regression selected options not scrolling automatically

- .github/workflows/ninja_i18n.yml
This PR adds the [Ninja i18n – GitHub action](https://inlang.com/m/3gk8n4n4/app-inlang-ninjaI18nAction)
This action will:
- remind you to fix new i18n issues in your pull requests
- notify you about new broken inlang projects
- create comments with an issue report
- provide Fink links to relevant messages
- stay silent if there is no need to act
https://github.com/opral/monorepo/assets/59048346/99049121-11db-4672-a7a8-e0d606426f4b
I'm the maintainer of Ninja i18n and the Fink localization editor. Since you are using inlang with Fink to manage your translations, you might want to try this. As this is the first published version, it is a beta version. So feel free to share your feedback in our [Discord channel](https://discord.gg/4G2QdvnQ) and [open issue …
> feat: Add Ninja i18n lint action

- .github/workflows/rust_ci.yaml
- frontend/appflowy_flutter/integration_test/desktop/uncategorized/share_markdown_test.dart
- frontend/appflowy_flutter/integration_test/mobile/home_page/create_new_page_test.dart
- frontend/appflowy_flutter/integration_test/mobile/sign_in/anonymous_sign_in_test.dart
- frontend/appflowy_flutter/integration_test/shared/auth_operation.dart
- frontend/rust-lib/event-integration/src/folder_event.rs
- frontend/rust-lib/event-integration/tests/user/af_cloud_test/member_test.rs
By default, secrets are not allowed to be shared in PRs.
---
> fix: rust ci

- frontend/resources/translations/fr-FR.json
> Update French translations

- .github/workflows/rust_ci.yaml
- frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/select_option_cell_editor_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_controller.dart
- frontend/rust-lib/event-integration/src/folder_event.rs
- frontend/rust-lib/event-integration/src/lib.rs
- frontend/rust-lib/event-integration/tests/database/local_test/test.rs
- frontend/rust-lib/flowy-database2/src/entities/type_option_entities/select_option_entities.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_option.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_type_option.rs
- frontend/rust-lib/flowy-search/src/folder/indexer.rs
> refactor: fetch all options from type option

- frontend/appflowy_tauri/src/appflowy_app/application/database/cell/cell_types.ts
- frontend/appflowy_tauri/src/appflowy_app/components/database/components/cell/URLCell.tsx
- frontend/rust-lib/flowy-database2/src/entities/type_option_entities/url_entities.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_type_option.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/url_type_option/url_tests.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/url_type_option/url_type_option.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/url_type_option/url_type_option_entities.rs
- frontend/rust-lib/flowy-database2/src/services/group/controller_impls/url_controller.rs
- frontend/rust-lib/flowy-database2/tests/database/cell_test/test.rs
> chore: move responsibility of url valdiation to front-frontend

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/src/entities/field_entities.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/field/field_builder.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs
- frontend/rust-lib/flowy-database2/src/template.rs
- frontend/rust-lib/flowy-database2/tests/database/field_test/util.rs
- frontend/rust-lib/flowy-database2/tests/database/mock_data/board_mock_data.rs
- frontend/rust-lib/flowy-database2/tests/database/mock_data/calendar_mock_data.rs
- frontend/rust-lib/flowy-database2/tests/database/mock_data/grid_mock_data.rs
depends on https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/199
---
> chore: remove field width and visibility

- frontend/resources/translations/es-VE.json
> Fink 🐦: update translations

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/resources/translations/en.json
> chore: update plugins package version

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
> fix: unable to open mentioned page on mobile

- frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/document_page.dart
If the user exits the app directly, there is no guarantee that the request will be sent successfully.
---
> fix: clear the collaborators when the app paused

- frontend/appflowy_flutter/lib/startup/plugin/plugin.dart
- frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/appearance/appearance_cubit.dart
fix some typos in comments
---
> chore: fix some typos in comments

- frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
- frontend/resources/translations/en.json
> chore: update translation text for wrap cell content

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_url_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/row/accessory/cell_accessory.dart
> fix: add an outline to accessory buttons

- frontend/appflowy_flutter/lib/user/application/sign_in_bloc.dart
- frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/magic_link_sign_in_buttons.dart
- frontend/appflowy_flutter/lib/workspace/application/sidebar/folder/folder_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_favorite_folder.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_section_folder.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
> feat: expand the view automatically upon opening

- frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
https://github.com/AppFlowy-IO/AppFlowy/issues/5186
---
> fix: use database sync bloc in database page

- .github/workflows/flutter_ci.yaml
- frontend/rust-lib/collab-integrate/Cargo.toml
- frontend/rust-lib/flowy-folder/src/event_handler.rs
- frontend/rust-lib/flowy-folder/src/event_map.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/flowy-folder/src/manager_init.rs
- frontend/rust-lib/flowy-folder/src/manager_observer.rs
- frontend/rust-lib/flowy-search-pub/src/entities.rs
- frontend/rust-lib/flowy-search/src/folder/indexer.rs
- frontend/rust-lib/flowy-user-pub/src/session.rs
- frontend/rust-lib/flowy-user/src/event_handler.rs
- frontend/rust-lib/flowy-user/src/services/authenticate_user.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
- frontend/rust-lib/lib-log/src/layer.rs
- frontend/rust-lib/lib-log/src/lib.rs
> chore: remove unused code & update log

- .github/workflows/rust_ci.yaml
- frontend/Makefile.toml
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/dart-ffi/Cargo.toml
- frontend/rust-lib/flowy-core/Cargo.toml
- frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/flowy-user/Cargo.toml
- frontend/rust-lib/flowy-user/src/user_manager/manager.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
- frontend/rust-lib/lib-log/Cargo.toml
- frontend/rust-lib/lib-log/src/layer.rs
- frontend/scripts/makefile/tests.toml
> chore: remove unused features

- .github/workflows/flutter_ci.yaml
- .github/workflows/rust_ci.yaml
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/dart-ffi/Cargo.toml
- frontend/rust-lib/event-integration/src/document/document_event.rs
- frontend/rust-lib/flowy-core/Cargo.toml
- frontend/rust-lib/flowy-document/src/event_handler.rs
- frontend/rust-lib/flowy-document/src/manager.rs
- frontend/rust-lib/flowy-error/src/code.rs
- frontend/rust-lib/flowy-error/src/errors.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/flowy-folder/src/manager_init.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/database.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/document.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/folder.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
- frontend/rust-lib/lib-log/src/lib.rs
> chore: check workspace id before write to disk

- frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option_cell.rs
> chore: update documentation for type option cell-related traits

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/toast.dart
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
support
resolves #5209
also fix another bug where all the toasts in the app aren't working.
---
> fix: some database bugs

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_observe.rs
- frontend/rust-lib/flowy-database2/src/services/database/mod.rs
> chore: update client api and collab

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_section_folder.dart
> chore: revert auto expand feature

- frontend/rust-lib/flowy-database2/src/services/share/csv/export.rs
- frontend/rust-lib/flowy-database2/tests/database/share_test/export_test.rs
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/5211
---
> fix: export created at and last modified cells to csv

- frontend/appflowy_flutter/lib/mobile/presentation/base/app_bar/app_bar.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/9f7580b5-e57e-4afa-a3c0-00212a916b31
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/a1c39636-38f5-4ce0-be76-41cc5757b79a
---
> feat: improve immersive cover style

- frontend/appflowy_flutter/lib/plugins/database/application/view/view_listener.dart
- frontend/appflowy_flutter/test/bloc_test/grid_test/util.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/src/notification.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_observe.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/notifier.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
- frontend/rust-lib/flowy-notification/Cargo.toml
- frontend/rust-lib/flowy-notification/src/builder.rs
- frontend/rust-lib/flowy-notification/src/debounce.rs
- frontend/rust-lib/flowy-notification/src/lib.rs
Using yrs observer as a trigger to send notification to the frontend. Using this approach, it can auto refresh the UI after receiving remote changes
TODO:
migrating all notification
> refactor: database row and cell notification

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
screen size width <= 340: 5
screen size width <= 384: 6
screen size width <= 430: 7
other screen size width : 8
---
> feat: adjust toolbar count based on the screen size

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> chore: upgrade editor version

- frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_recent_view.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/migration/editor_migration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
> fix: minor UI issues

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
fixes an issue where users cannot drag cards from one group to another on mobile
---
> chore: bump appflowy-board rev

- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_detail.dart
- frontend/resources/translations/en.json
- add a tooltip to the expand row as full page button
- icon constrast color
---
> fix: kanban related launch review issues

- frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
- frontend/appflowy_flutter/ios/Podfile
- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/ios/Runner.xcodeproj/project.pbxproj
- frontend/appflowy_flutter/lib/mobile/presentation/widgets/show_flowy_mobile_confirm_dialog.dart
- frontend/appflowy_flutter/lib/plugins/document/application/document_collab_adapter.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_cover_image.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_page.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/resources/translations/en.json
update:
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/c566d13a-7fff-4223-a1b6-d09efd4682ba
---
> feat: request permission again if the user denied the photo permission

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/Cargo.toml
- frontend/rust-lib/event-integration-test/Cargo.toml
- frontend/rust-lib/flowy-core/Cargo.toml
- frontend/rust-lib/flowy-database-pub/Cargo.toml
- frontend/rust-lib/flowy-database2/Cargo.toml
- frontend/rust-lib/flowy-document-pub/Cargo.toml
- frontend/rust-lib/flowy-document/Cargo.toml
- frontend/rust-lib/flowy-error/Cargo.toml
- frontend/rust-lib/flowy-folder-pub/Cargo.toml
- frontend/rust-lib/flowy-folder/Cargo.toml
- frontend/rust-lib/flowy-search-pub/Cargo.toml
- frontend/rust-lib/flowy-search/Cargo.toml
- frontend/rust-lib/flowy-server/Cargo.toml
- frontend/rust-lib/flowy-user-pub/Cargo.toml
- frontend/rust-lib/flowy-user/Cargo.toml
> chore: update yrs version

- frontend/appflowy_flutter/lib/plugins/document/application/document_collab_adapter.dart
> chore: remove debug print

- frontend/appflowy_flutter/integration_test/desktop/uncategorized/appearance_settings_test.dart
- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_picker_screen.dart
- frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_setting.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/service/openai_client.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_layout.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
- frontend/appflowy_flutter/test/bloc_test/home_test/trash_bloc_test.dart
- frontend/resources/translations/en.json
> fix: the cursor will jump up when creating a new document on desktop.

- frontend/appflowy_flutter/lib/mobile/application/mobile_router.dart
- frontend/appflowy_flutter/lib/mobile/presentation/favorite/mobile_favorite_folder.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/favorite_folder/mobile_home_favorite_folder.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_home_recent_views.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
- frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/setting/setting_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/emoji_picker_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_language_screen.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/font/customize_font_toolbar_item.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
- frontend/appflowy_flutter/lib/workspace/application/recent/cached_recent_service.dart
- frontend/appflowy_flutter/lib/workspace/application/recent/recent_views_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_favorite_folder.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_folder_header.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_folder.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_account_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/files/settings_file_exporter_widget.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_customize_shortcuts_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu_element.dart
- frontend/resources/translations/en.json
> fix: launch review improvements

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_file_widget.dart
> fix: assert on uploading image on macos

- frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_type_list.dart
> chore: disable ai summary

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-core/Cargo.toml
- frontend/rust-lib/flowy-error/Cargo.toml
- frontend/rust-lib/flowy-server/Cargo.toml
- frontend/rust-lib/flowy-server/src/af_cloud/server.rs
> fix: ws connect with invalid token

- frontend/appflowy_flutter/integration_test/desktop/uncategorized/appearance_settings_test.dart
- frontend/appflowy_flutter/lib/mobile/application/page_style/document_page_style_bloc.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_picker_screen.dart
- frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_setting.dart
- frontend/appflowy_flutter/lib/plugins/document/application/document_appearance_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_file_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_font_item.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_cover_image.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_layout.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
- frontend/appflowy_flutter/lib/shared/permission/permission_checker.dart
- frontend/appflowy_flutter/lib/util/font_family_extension.dart
- frontend/appflowy_flutter/lib/util/google_font_family_extension.dart
- frontend/appflowy_flutter/lib/workspace/application/appearance_defaults.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/appearance/base_appearance.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/appearance/desktop_appearance.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart
- frontend/appflowy_flutter/test/bloc_test/app_setting_test/appearance_test.dart
- frontend/appflowy_flutter/test/bloc_test/app_setting_test/document_appearance_test.dart
- frontend/appflowy_flutter/test/widget_test/theme_font_family_setting_test.dart
- frontend/rust-lib/flowy-user/src/entities/user_setting.rs
Using system default font instead of Poppins.
---
> feat: support system default font family on desktop

- .github/workflows/ios_ci.yaml
- frontend/appflowy_flutter/integration_test/mobile/page_style/document_page_style_test.dart
- frontend/appflowy_flutter/integration_test/mobile_runner.dart
- frontend/appflowy_flutter/integration_test/shared/common_operations.dart
- frontend/appflowy_flutter/integration_test/shared/expectation.dart
- frontend/appflowy_flutter/lib/mobile/application/base/mobile_view_page_bloc.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/app_bar_buttons.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/more_bottom_sheet.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
- Optimize the code logic for the mobile view page.
- Split the page widget into small widgets.
- Move the logic to the BLoC.
- Added more integration tests
---
> refactor: mobile view page

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
> chore: use patch to fix version issue

- frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/app_bar_buttons.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
- Remove the shadow color from the back button if not in immersive mode.
---
> fix: remove the shadow color from the back button if not in immersive mode.

- frontend/appflowy_flutter/lib/core/config/kv_keys.dart
- frontend/appflowy_flutter/lib/main.dart
- frontend/appflowy_flutter/lib/startup/startup.dart
- frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
- frontend/appflowy_flutter/lib/startup/tasks/app_window_size_manager.dart
- frontend/appflowy_flutter/lib/startup/tasks/windows.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
close https://github.com/AppFlowy-IO/AppFlowy/issues/5273
close https://github.com/AppFlowy-IO/AppFlowy/issues/5143
close https://github.com/AppFlowy-IO/AppFlowy/issues/363
close https://github.com/AppFlowy-IO/AppFlowy/issues/128
shortcut: `ctrl/cmd` + `+/-`
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/4af786c7-e4de-4d7b-bbe2-02dd686acb0e
Known issue: widget may overflow.
---
> feat: add support for scaling the application with a factor range of 0.5 to 2.0

- frontend/appflowy_flutter/lib/core/frameless_window.dart
- frontend/appflowy_flutter/lib/startup/entry_point.dart
- frontend/appflowy_flutter/lib/startup/tasks/windows.dart
- frontend/appflowy_flutter/lib/user/presentation/screens/splash_screen.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_top_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart
- frontend/appflowy_flutter/windows/flutter/CMakeLists.txt
Closes: #1995 
<details>
<summary>Dark Mode</summary>
</details>
<details>
<summary>Light Mode</summary>
</details>
---
There shouldn't be any changes to MacOS and Linux
> feat: custom windows title bar

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/number.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart
also improve appearance of empty text cells in kanban/calendar
---
> fix: ensure text update bug doesn't happen on number/url

- frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
> fix: view action not working

- frontend/appflowy_flutter/lib/shared/google_fonts_extension.dart
> fix: font family warning

- frontend/resources/translations/de-DE.json
- frontend/resources/translations/es-VE.json
Updated the German translation
> Update German translations

- frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
(Demo is done on Linux, but functions the same on Windows! The problem also occurred on Linux)
[Feature demo.webm](https://github.com/AppFlowy-IO/AppFlowy/assets/50213029/67db228a-2c53-4e6c-bf94-8a844706bf92)
[fixes](https://github.com/AppFlowy-IO/AppFlowy/issues/5304)
---
> fix: add space above logo on welcome screen

- frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_type_list.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_web/wasm-libs/Cargo.lock
> chore: enable ai summary

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
> fix: workspace icon displays incorrectly on Linux

- frontend/resources/translations/fr-FR.json
Fix minor typo in languages.
No test eligible.
- [x ] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x ] I've listed at least one issue that this PR fixes in the description above.
- [x ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x ] All existing tests are passing.
> Update fr-FR.json: fix typo

- frontend/rust-lib/flowy-database2/src/manager.rs
> chore: do not use the cell of given summary field

- project.inlang/settings.json
> Support Ukrainian language #5350

- frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web/wasm-libs/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
> fix: use full update states instead of patch update

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5361
---
> fix: range error raise if heading level >= 6

- frontend/rust-lib/event-integration-test/src/folder_event.rs
- frontend/rust-lib/event-integration-test/tests/folder/local_test/folder_test.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5372
---
> fix: infinite loop when getting ancestor for orphan view

- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_tauri/src-tauri/src/init.rs
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/src/init.rs
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/dart-ffi/Cargo.toml
- frontend/rust-lib/dart-ffi/src/lib.rs
- frontend/rust-lib/event-integration-test/Cargo.toml
- frontend/rust-lib/event-integration-test/src/lib.rs
- frontend/rust-lib/flowy-core/src/config.rs
- frontend/rust-lib/flowy-core/src/integrate/server.rs
- frontend/rust-lib/flowy-core/src/lib.rs
- frontend/rust-lib/flowy-server/Cargo.toml
- frontend/rust-lib/flowy-server/src/af_cloud/server.rs
- frontend/rust-lib/flowy-server/tests/af_cloud_test/util.rs
Curretnly there are some invalid version number. So set minimum version number to 0.8.5.
> chore: set min version number

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
- frontend/appflowy_flutter/test/widget_test/direction_setting_test.dart
> fix: default text direction not synced

- frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_new_page_button.dart
- frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart
> chore: improve hover and text colors in dark mode

- frontend/appflowy_flutter/integration_test/desktop/settings/notifications_settings_test.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_view_card.dart
- frontend/appflowy_flutter/lib/workspace/application/recent/cached_recent_service.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
> fix: notification test

- frontend/appflowy_flutter/lib/mobile/application/mobile_router.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/menu_shared_state.dart
- frontend/rust-lib/dart-ffi/src/lib.rs
> chore: call FolderEventSetLatestView when opening page on mobile

- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_add_new_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/default_mobile_action_pane.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_view_card.dart
- frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_related_question.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_welcome_page.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart
- frontend/resources/translations/en.json
> chore: add default questions

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
- frontend/appflowy_flutter/lib/shared/google_fonts_extension.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/appearance/appearance_cubit.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/appearance/base_appearance.dart
- frontend/appflowy_flutter/test/bloc_test/app_setting_test/appearance_test.dart
- frontend/appflowy_flutter/test/widget_test/direction_setting_test.dart
We're not using SF Mono as the code font anymore.
---
> fix: font not found error log

- frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_column_header.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_shortcut_container.dart
- frontend/appflowy_flutter/lib/plugins/shared/callback_shortcuts.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5451
---
> fix: some keys conflict with board shortcuts

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/header/sidebar_user.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/user_avatar.dart
> feat: change user avatar corner radius

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_ai_message.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_avatar.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_user_message.dart
> chore: fix ui color issue after merge main

- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_add_new_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_item_body.dart
- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/default_mobile_action_pane.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/favorite_folder/mobile_home_favorite_folder.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/recent_space.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder_header.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_view_card.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
- frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_slide_action_button.dart
- frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_folder.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/header/sidebar_top_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/flowy_tooltip.dart
> feat: support slide actions on mobile

- frontend/rust-lib/flowy-document/Cargo.toml
- frontend/rust-lib/flowy-document/tests/document/document_redo_undo_test.rs
- frontend/rust-lib/flowy-document/tests/document/document_test.rs
- frontend/rust-lib/flowy-document/tests/document/util.rs
> chore: fix document test

- frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
- frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
- frontend/appflowy_flutter/lib/plugins/database_document/database_document_page.dart
- frontend/appflowy_flutter/lib/plugins/document/document.dart
- frontend/appflowy_flutter/lib/plugins/document/document_page.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
> chore: disable sync indicator

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-document/src/manager.rs
- frontend/rust-lib/flowy-document/tests/document/document_redo_undo_test.rs
- frontend/rust-lib/flowy-document/tests/document/document_test.rs
- frontend/rust-lib/flowy-document/tests/document/util.rs
- frontend/rust-lib/flowy-user/src/migrations/document_empty_content.rs
> fix: generate default document data from document id

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/af_dropdown_menu_entry.dart
Closes: #5389
Closes: #5489
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/fcf914df-3dca-4f85-a3b1-41ef161997fc
> fix: custom font dropdown

- frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
Remove the member request on launch to prevent blocking the UI display.
---
> fix: remove member request on launch

- frontend/resources/translations/tr-TR.json
Describe the changes you have conducted here
Preview the messages on https://inlang.com/github.com/muratmirgun/AppFlowy .
> Update translations for tr_TR

- frontend/appflowy_flutter/lib/plugins/database/application/field/type_option/translate_type_option_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_summary_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_translate_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_summary_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/destop_row_detail_translate_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_summary_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_translate_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_summary_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_translate_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/translate.dart
- frontend/rust-lib/event-integration-test/tests/folder/local_test/script.rs
- frontend/rust-lib/flowy-database2/src/entities/type_option_entities/translate_entities.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/translate_type_option/translate.rs
- frontend/rust-lib/flowy-database2/tests/database/mock_data/grid_mock_data.rs
> chore: support more language

- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/action.dart
- frontend/resources/translations/en.json
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-chat/Cargo.toml
- frontend/rust-lib/flowy-database2/Cargo.toml
- frontend/rust-lib/flowy-error/Cargo.toml
- frontend/rust-lib/flowy-folder/Cargo.toml
- frontend/rust-lib/flowy-sqlite/migrations/2024-06-14-020242_workspace_member/down.sql
- frontend/rust-lib/flowy-sqlite/migrations/2024-06-14-020242_workspace_member/up.sql
- frontend/rust-lib/flowy-sqlite/src/schema.rs
- frontend/rust-lib/flowy-user-pub/src/entities.rs
- frontend/rust-lib/flowy-user/Cargo.toml
- frontend/rust-lib/flowy-user/src/services/sqlite_sql/member_sql.rs
- frontend/rust-lib/flowy-user/src/services/sqlite_sql/mod.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
- frontend/rust-lib/lib-dispatch/Cargo.toml
- frontend/rust-lib/lib-infra/Cargo.toml
> chore: save workspace member info to disk

- frontend/appflowy_flutter/lib/shared/feature_flags.dart
> chore: enable billing system

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/selectable_highlight.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> chore: highlight code block

- frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
When upgrading the space, skip this step if the private views for the current user are empty.
---
> fix: migrate the private views only if they are not empty

- frontend/appflowy_flutter/lib/shared/feature_flags.dart
> chore: turn off the billing feature

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/extension.dart
- frontend/appflowy_web/wasm-libs/Cargo.lock
> chore: adjust height

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
- frontend/rust-lib/lib-infra/src/priority_task/queue.rs
- frontend/rust-lib/lib-infra/src/priority_task/store.rs
> chore: fix checklist potential panic

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_textfield.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/6b633a79-c2ae-4ce3-88ef-a6b4c8ad090d
---
> fix: cursor jump randomly in check list item

- frontend/appflowy_flutter/integration_test/desktop/board/board_row_test.dart
> chore: fix flutter test

- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
> fix: automatically open page after switching space

- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/event-integration-test/src/folder_event.rs
- frontend/rust-lib/event-integration-test/tests/document/af_cloud_test/file_upload_test.rs
- frontend/rust-lib/event-integration-test/tests/user/af_cloud_test/member_test.rs
- frontend/rust-lib/event-integration-test/tests/user/af_cloud_test/workspace_test.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
- frontend/rust-lib/flowy-sqlite/src/schema.rs
- frontend/rust-lib/flowy-storage/src/manager.rs
- frontend/rust-lib/flowy-storage/tests/multiple_part_upload_test.rs
- frontend/rust-lib/flowy-user-pub/src/cloud.rs
- frontend/rust-lib/flowy-user/src/entities/workspace.rs
- frontend/rust-lib/flowy-user/src/event_handler.rs
- frontend/rust-lib/flowy-user/src/event_map.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
- Remove adding member directly
- Replacing add member in tests to use invite and accept invitation
> Remove deprecated add member

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/loading.dart
> fix: infinite loading

- frontend/appflowy_flutter/lib/workspace/application/sidebar/folder/folder_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_search_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/move_to/move_page_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
- frontend/resources/flowy_icons/16x/magnifier.svg
https://github.com/AppFlowy-IO/AppFlowy/issues/5578
---
> feat: support moving page across spaces

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5609
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5607
space menu
favorite menu
---
> fix: prevent overfow of space name and view name

- frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
- frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/import/import_panel.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_new_page_button.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
- Support creating the database page or AI chat page and importing page at the first level of space.
---
> feat: support creating database at the first level

- frontend/appflowy_flutter/lib/startup/tasks/windows.dart
> fix: macos fullscreen window position

- frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
- frontend/rust-lib/flowy-folder/src/entities/view.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
Open the duplicated space once the duplicate is completed.
---
> feat: open the duplicated space by default

- frontend/rust-lib/flowy-search/src/document/handler.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/search.rs
> fix: score filter

- frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
Simply postpone fetching the workspace member until after the workspace has been fetched, to render the sidebar with the minimum delay possible.
> fix: postpone fetching member

- frontend/appflowy_flutter/lib/plugins/ai_chat/chat.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_welcome_page.dart
- frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_ai_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_shortcuts_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_body.dart
https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/82b345b5-8327-48a8-9568-a8269b3c0392
---
> fix: settings changes + ai layout improvements

- frontend/rust-lib/flowy-chat/src/local_ai/chat_plugin.rs
- frontend/rust-lib/flowy-chat/tests/util.rs
> chore: fix rustfmt ci test

- frontend/.vscode/launch.json
- frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
- frontend/rust-lib/event-integration-test/src/folder_event.rs
- frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-folder/src/entities/view.rs
- frontend/rust-lib/flowy-folder/src/event_handler.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/flowy-folder/src/test_helper.rs
- frontend/rust-lib/flowy-folder/src/view_operation.rs
> feat: sync the created view after duplicating

- .github/workflows/release.yml
https://github.com/actions/runner-images/issues/9255
---
> chore: use latest macos runner to build the release package

- frontend/appflowy_flutter/integration_test/desktop/uncategorized/empty_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
- frontend/appflowy_flutter/lib/workspace/application/home/home_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/menu/sidebar_sections_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
> fix: take the max value of the keyboard height and the view insets bottom to make the toolbar visible 

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-server/src/local_server/impls/database.rs
- frontend/rust-lib/flowy-server/src/supabase/api/collab_storage.rs
- frontend/rust-lib/flowy-server/src/supabase/api/folder.rs
- frontend/rust-lib/flowy-server/src/supabase/api/request.rs
Companion PR to https://github.com/AppFlowy-IO/AppFlowy-Cloud/pull/677 and https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/227
> chore: update yrs and appflowy collab dependencies

- frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
- frontend/rust-lib/flowy-user-pub/src/cloud.rs
- frontend/rust-lib/flowy-user/src/entities/workspace.rs
- frontend/rust-lib/flowy-user/src/event_handler.rs
- frontend/rust-lib/flowy-user/src/event_map.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
- add subscription info for a workspace
> feat: add api for workspace subscription info

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
- frontend/resources/translations/de-DE.json
- frontend/resources/translations/en.json
Remove the dollar syntax in translation files. It will cause the flutter generation to throw an error.
```log
This builder requires Dart inputs without syntax errors.
However, package:appflowy/generated/codegen_loader.g.dart (or an existing part) contains the following errors.
codegen_loader.g.dart:11865:23: Expected an identifier.
codegen_loader.g.dart:11937:20: Expected an identifier.
codegen_loader.g.dart:11943:20: Expected an identifier.
And 2 more...
```
related issue: https://github.com/aissat/easy_localization/issues/392
---
> fix: syntax error when generating translation files

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/ai_message_bubble.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_copy_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/markdown_code_parser.dart
- frontend/appflowy_flutter/lib/shared/markdown_to_document.dart
- frontend/appflowy_flutter/lib/startup/tasks/app_window_size_manager.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/import/import_panel.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/document_color_setting_button.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> fix: ai chat result contains html escape text

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_progress_bar.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
> chore: improve popup menu color

- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
- frontend/rust-lib/flowy-user-pub/src/cloud.rs
- frontend/rust-lib/flowy-user/src/entities/workspace.rs
- frontend/rust-lib/flowy-user/src/event_handler.rs
- frontend/rust-lib/flowy-user/src/event_map.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
- use blocking option when canceling plan
- add method to set subscription period
> chore: update api for billing

- CHANGELOG.md
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
- Enhanced the message style on the AI chat page.
- Added the ability to choose cursor color and selection color from a palette in settings page.
- Optimized the performance for loading recent pages.
- Fixed an issue where the cursor would jump randomly when typing in the document title on mobile.
> chore: bump version 0.6.4

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/event-integration-test/src/user_event.rs
- frontend/rust-lib/flowy-chat/src/local_ai/local_llm_chat.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
> chore: update build config

- frontend/appflowy_flutter/lib/plugins/database/application/field/field_controller.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
- frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_item.dart
- frontend/appflowy_flutter/packages/appflowy_result/lib/src/async_result.dart
> fix: integration test - grid row detail page: hide and show hidden fields

- frontend/appflowy_web_app/src/application/services/js-services/cache/index.ts
- frontend/appflowy_web_app/src/components/app/AppTheme.tsx
- frontend/appflowy_web_app/src/components/database/board/Board.tsx
- frontend/appflowy_web_app/src/components/database/calendar/Calendar.tsx
- frontend/appflowy_web_app/src/components/database/calendar/calendar.scss
- frontend/appflowy_web_app/src/components/database/components/board/column/Column.tsx
- frontend/appflowy_web_app/src/components/database/components/calendar/toolbar/NoDate.tsx
- frontend/appflowy_web_app/src/components/database/components/calendar/toolbar/Toolbar.tsx
- frontend/appflowy_web_app/src/components/database/components/cell/checkbox/CheckboxCell.tsx
- frontend/appflowy_web_app/src/components/database/components/grid/grid-cell/GridCell.tsx
- frontend/appflowy_web_app/src/components/database/components/grid/grid-column/GridColumn.tsx
- frontend/appflowy_web_app/src/components/database/components/grid/grid-table/GridTable.tsx
- frontend/appflowy_web_app/src/components/database/components/tabs/ViewTabs.tsx
- frontend/appflowy_web_app/src/components/editor/components/leaf/mention/MentionPage.tsx
- frontend/appflowy_web_app/src/pages/AfterPaymentPage.tsx
- frontend/resources/translations/en.json
> fix: some style issues

- frontend/rust-lib/flowy-core/assets/read_me.json
Empty string edit causes issues with yrs version beofre 0.19.2, and it's safe to be removed.
---
> fix: Remove empty edit from read me json

- .github/workflows/rust_ci.yaml
1. Cargo make  is not necessary in rust CI as we do not invoke any Cargo make command at this stage. Similarly, we don't need duck script.
2. Cache on failure will help subsequent test run to be faster if it fails.
3. Add a step to show appflowy cloud container log in the event of CI failure to facilitate debugging.
4. Allow CI to be triggered on PR if rust_ci.yaml file changes.
---
> chore: remove unused step in rust CI, allow cache on failure, show container logs

- .github/workflows/docker_ci.yml
- .github/workflows/ios_ci.yaml
- .github/workflows/rust_ci.yaml
- .github/workflows/tauri2_ci.yaml
- .github/workflows/tauri_ci.yaml
> CI: use self-hosted runner if developer can create a branch in the up-stream repo

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5765
---
> fix: delete reference databases in toggle list

- .github/workflows/flutter_ci.yaml
- .github/workflows/rust_ci.yaml
- frontend/appflowy_flutter/integration_test/cloud/appflowy_cloud_auth_test.dart
- frontend/appflowy_flutter/integration_test/cloud/user_setting_sync_test.dart
- frontend/appflowy_flutter/lib/user/application/auth/af_cloud_mock_auth_service.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_account_view.dart
> chore: only run appflowy cloud if it's not exist

- frontend/appflowy_flutter/integration_test/shared/auth_operation.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_account_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_manage_data_view.dart
> fix: integration test (reset to default location)

- frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5805
---
> fix: the action menu is blocked by the navigation bar on Android

- frontend/appflowy_flutter/lib/startup/tasks/app_window_size_manager.dart
> fix: defaultWindowSize is out of scope (#5795)

- frontend/appflowy_flutter/lib/plugins/document/document_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_image.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- Drag and drop one or more images to the editor
- Ability to exclude some type of nodes from drop target, since we have custom drop logic implemented on all image nodes.
https://github.com/user-attachments/assets/45c75aa0-4a71-471f-8c1d-772bbb42ab68
---
> feat: drop images into editor

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_ai_message_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_file_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_related_question.dart
- frontend/appflowy_flutter/lib/shared/feature_flags.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/settings_ai_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_billing_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
- frontend/resources/translations/en.json
- frontend/rust-lib/flowy-chat/src/event_handler.rs
- frontend/rust-lib/flowy-chat/src/local_ai/local_llm_chat.rs
- frontend/rust-lib/flowy-document/src/manager.rs
- frontend/rust-lib/flowy-error/src/code.rs
> chore: chat with pdf ui

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/interactive_image_toolbar.dart
https://github.com/user-attachments/assets/9e952723-15b9-48a4-aa6d-bf27ffe1eb3e
---
> fix: chat messaage color doesn't update when switching theme

- .github/workflows/release.yml
> chore: notify in release build

- frontend/appflowy_flutter/lib/shared/feature_flags.dart
> chore: enable billing

- frontend/resources/translations/zh-CN.json
Fix an input error in Chinese translation
> chore: update simplified Chinese translate

- frontend/appflowy_flutter/integration_test/shared/editor_test_operations.dart
- frontend/appflowy_flutter/integration_test/shared/settings.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_font_item.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_account_view.dart
> fix: missing system font display

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
> chore: update collab

- CHANGELOG.md
> chore: bump version 0.6.6

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/settings_ai_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_billing_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
> chore: remove local ai

- frontend/appflowy_flutter/lib/mobile/presentation/base/gesture.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/tab/_tab_bar.dart
> chore: use light haptic feedback

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/plugin_state.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/settings_ai_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_billing_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
- frontend/rust-lib/flowy-chat/src/chat_manager.rs
- frontend/rust-lib/flowy-chat/src/local_ai/local_llm_chat.rs
- frontend/rust-lib/flowy-chat/src/local_ai/local_llm_resource.rs
- frontend/rust-lib/flowy-chat/src/local_ai/mod.rs
- frontend/rust-lib/flowy-chat/src/local_ai/path.rs
- frontend/rust-lib/flowy-chat/src/local_ai/watch.rs
> chore: switch to appflowy ai if local ai is not enable

- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_with_file_test.dart
- frontend/appflowy_flutter/integration_test/shared/editor_test_operations.dart
- frontend/appflowy_flutter/lib/plugins/document/document_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_drop_manager.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_file.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_menu.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_selection_menu.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_upload_menu.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_util.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/settings_dialog_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
- frontend/resources/translations/en.json
Relates: #5486 #5258 #2237 
TBD
> feat: upload file in document

- frontend/appflowy_web_app/src/components/global-comment/actions/ReactAction.tsx
> fix: react action bugs

- frontend/appflowy_web_app/src/components/_shared/notify/InfoSnackbar.tsx
- frontend/appflowy_web_app/src/components/global-comment/add-comment/AddComment.tsx
- frontend/appflowy_web_app/src/components/global-comment/add-comment/AddCommentWrapper.tsx
- frontend/resources/translations/en.json
> fix: add comment tip

- frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
> chore: optimize emoji align on mobile

- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/notifications/mobile_notifications_screen.dart
- frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/shared.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
- frontend/appflowy_flutter/lib/user/application/reminder/reminder_bloc.dart
- frontend/appflowy_flutter/lib/user/application/reminder/reminder_extension.dart
Improve reminder color in notification page
- past: grey
- upcoming: red
- others: black
---
> feat: improve reminder color in notification page

- frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/select_option_cell_editor_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/domain/select_option_cell_service.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_select_option_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_cell_editor.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
- frontend/appflowy_flutter/test/bloc_test/grid_test/cell/select_option_cell_test.dart
> fix: select option chip size

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
> chore: optimzie emoji align on desktop

- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder_header.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart
- frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
> fix: + button in the navigation bar doesn't work when the space is not initialized

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
> chore: optimize the workspace menu hover status

- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
- frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/inline_page_reference.dart
- frontend/appflowy_flutter/lib/plugins/inline_actions/widgets/inline_actions_handler.dart
- frontend/appflowy_flutter/lib/plugins/inline_actions/widgets/inline_actions_menu_group.dart
> chore: expand inline menu width

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
> feat: support pasting image from Slack

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5876
https://github.com/user-attachments/assets/5e3bed9f-cb6e-4924-aae3-e517716551c0
---
> fix: prevent shaking in nested lists deeper in AI message

- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_action_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_action_control.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_input.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input_action_menu.dart
- frontend/rust-lib/flowy-ai/src/local_ai/stream_util.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/flowy-folder/src/notification.rs
> chore: polish ui

- frontend/appflowy_flutter/lib/shared/icon_emoji_picker/flowy_icon_emoji_picker.dart
- frontend/appflowy_flutter/pubspec.lock
> fix: remove unused expanded widget

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon_popup.dart
> chore: adjust legacy space icon

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_action_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_action_control.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_member_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_service.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_user_message_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_avatar.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_input.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_metadata.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/other_user_message_bubble.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/user_message_bubble.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/ai/local_ai_on_boarding_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/ai/settings_ai_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/settings_ai_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/resources/translations/en.json
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-ai/src/entities.rs
- frontend/rust-lib/flowy-ai/src/event_handler.rs
- frontend/rust-lib/flowy-error/src/code.rs
- frontend/rust-lib/flowy-error/src/impl_from/cloud.rs
> chore: chat UI poblish

- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_action_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_input.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mobile_page_selector_sheet.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
> chore: optimize mobile ai chat page

- frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space_header.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space_menu.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_input.dart
- frontend/appflowy_flutter/lib/plugins/base/emoji/emoji_picker_header.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/string_extension.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/heading/heading_toolbar_item.dart
- frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/create_space_popup.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/manage_space_popup.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon_popup.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/flowy_tooltip.dart
- frontend/resources/translations/en.json
> fix: launch review issues 067

- frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/flowy_tab.dart
> chore: update tabbar icon

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_ai_message_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_entity.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_service.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_stream.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_user_message_bubble_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_message_bubble.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_text_message.dart
- frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
- frontend/rust-lib/flowy-ai/src/stream_message.rs
> chore: show attachment on local ai

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/upload_image_menu.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/widgets/embed_image_url_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
> chore: polish upload image menu

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_service.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_user_message_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_metadata.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/ai/download_model_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/downloading_model.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/resources/translations/en.json
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-ai-pub/src/cloud.rs
- frontend/rust-lib/flowy-ai/src/chat.rs
- frontend/rust-lib/flowy-ai/src/local_ai/local_llm_chat.rs
- frontend/rust-lib/flowy-ai/src/local_ai/local_llm_resource.rs
- frontend/rust-lib/flowy-ai/src/local_ai/stream_util.rs
- frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
- frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/chat.rs
- frontend/rust-lib/flowy-server/src/default_impl.rs
> chore: show reference sources on local ai response

- frontend/rust-lib/flowy-folder/src/manager.rs
> chore: using write lock to fix acquire lock error

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_user_message_bloc.dart
- frontend/rust-lib/flowy-folder/src/manager.rs
> chore: fix message id

- CHANGELOG.md
- frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
- frontend/appflowy_flutter/lib/shared/red_dot.dart
- frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_button.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_awareness.rs
- Redesigned the icon picker design on Desktop.
- Redesigned the notification page on Mobile.
- Enhance the toolbar tooltip functionality on Desktop.
- Enhance the slash menu user experience on Desktop.
- Fixed the issue where list style overrides occurred during text pasting.
- Fixed the issue where linking multiple databases in the same document could cause random loss of focus.
---
> chore: bump version 0.6.7

- frontend/appflowy_flutter/packages/appflowy_backend/pubspec.yaml
- frontend/appflowy_flutter/packages/appflowy_result/pubspec.yaml
- frontend/appflowy_flutter/packages/flowy_infra/pubspec.yaml
- frontend/appflowy_flutter/packages/flowy_infra_ui/pubspec.yaml
- frontend/appflowy_flutter/packages/flowy_svg/analysis_options.yaml
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/scripts/code_generation/flowy_icons/generate_flowy_icons.sh
- frontend/scripts/code_generation/freezed/generate_freezed.sh
- frontend/scripts/code_generation/generate.sh
- frontend/scripts/code_generation/language_files/generate_language_files.sh
- frontend/scripts/makefile/flutter.toml
The cost time for clean build reduced from 160s to 110s.
The cost time for incremental build reduced from 130s to 43s. (change one freezed file, one svg and one translation)
---
> chore: optimize generation speed

- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_rename_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_block.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/mobile_appflowy_date_picker.dart
> feat: optimize date picker & mention block

- frontend/appflowy_tauri/src-tauri/src/request.rs
- frontend/appflowy_web_app/src-tauri/src/request.rs
- frontend/rust-lib/flowy-ai-pub/src/cloud.rs
- frontend/rust-lib/flowy-ai/src/event_handler.rs
- frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
- frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
- frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs
- frontend/rust-lib/flowy-core/src/integrate/user.rs
- frontend/rust-lib/flowy-folder/src/view_operation.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/chat.rs
- frontend/rust-lib/flowy-server/src/default_impl.rs
- frontend/rust-lib/flowy-user/src/event_map.rs
- frontend/rust-lib/flowy-user/src/services/data_import/importer.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
> chore: rm fut

- frontend/rust-lib/flowy-ai/src/ai_manager.rs
- frontend/rust-lib/flowy-ai/src/chat.rs
- frontend/rust-lib/flowy-ai/src/event_handler.rs
- frontend/rust-lib/flowy-ai/src/local_ai/local_llm_chat.rs
- frontend/rust-lib/flowy-core/src/integrate/user.rs
> fix: refresh local ai state when opening workspace

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/settings_ai_view.dart
- frontend/rust-lib/flowy-ai/src/local_ai/local_llm_chat.rs
> fix: local ai toggle

- frontend/scripts/code_generation/freezed/generate_freezed.sh
https://github.com/user-attachments/assets/5ddea62d-06ef-46f4-8c96-975473501465
---
> chore: add loading indicator when generating freezed file

- frontend/appflowy_flutter/integration_test/desktop/document/document_with_database_test.dart
- frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
- frontend/appflowy_flutter/lib/startup/tasks/sentry.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/resources/translations/en.json
close https://github.com/AppFlowy-IO/AppFlowy/issues/5970
---
> fix: unable to insert todo list via slash menu

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/clipboard_service.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_image.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_floating_toolbar/custom_mobile_floating_toolbar.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5965
https://github.com/user-attachments/assets/8aadf314-b100-420f-8550-d7562fe4c178
---
> fix: support pasting web image on mobile

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_util.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_util.dart
- frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/UploadImage.tsx
> chore: remove file size limit

- frontend/appflowy_flutter/lib/plugins/database/application/row/related_row_detail_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/application/row/row_cache.dart
- frontend/appflowy_flutter/lib/plugins/database/application/row/row_controller.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_event_editor_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/application/row/row_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/application/row/row_detail_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/mobile_row.dart
- frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/setting_menu.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_observe.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_filter.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_group.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_operation.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_sort.rs
- frontend/rust-lib/flowy-database2/tests/database/database_editor.rs
- frontend/rust-lib/flowy-database2/tests/database/field_test/script.rs
- frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/script.rs
- frontend/rust-lib/flowy-database2/tests/database/share_test/export_test.rs
- frontend/rust-lib/flowy-database2/tests/database/sort_test/script.rs
> chore: lazy load database row

- frontend/appflowy_flutter/lib/plugins/database/application/view/view_cache.dart
- frontend/appflowy_flutter/lib/plugins/database/application/view/view_listener.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/Cargo.toml
- frontend/rust-lib/flowy-database2/src/entities/row_entities.rs
- frontend/rust-lib/flowy-database2/src/event_handler.rs
- frontend/rust-lib/flowy-database2/src/event_map.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/notification.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_observe.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
- frontend/rust-lib/flowy-database2/src/services/filter/controller.rs
> chore: fix database filter

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_tauri/src-tauri/src/init.rs
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/src/init.rs
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/dart-ffi/Cargo.toml
- frontend/rust-lib/dart-ffi/src/lib.rs
- frontend/rust-lib/event-integration-test/src/event_builder.rs
- frontend/rust-lib/event-integration-test/src/lib.rs
- frontend/rust-lib/event-integration-test/src/user_event.rs
- frontend/rust-lib/flowy-core/src/lib.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/lib-dispatch/Cargo.toml
- frontend/rust-lib/lib-dispatch/src/dispatcher.rs
- frontend/rust-lib/lib-dispatch/src/module/container.rs
- frontend/rust-lib/lib-dispatch/src/module/data.rs
- frontend/rust-lib/lib-dispatch/src/module/module.rs
- frontend/rust-lib/lib-dispatch/src/request/request.rs
- frontend/rust-lib/lib-dispatch/src/runtime.rs
- frontend/rust-lib/lib-dispatch/tests/api/module.rs
> chore: fix lib dispatch

- frontend/rust-lib/dart-ffi/src/lib.rs
- frontend/rust-lib/event-integration-test/src/event_builder.rs
- frontend/rust-lib/event-integration-test/src/lib.rs
- frontend/rust-lib/event-integration-test/src/user_event.rs
- frontend/rust-lib/flowy-database2/src/event_handler.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/lib-dispatch/src/dispatcher.rs
- frontend/rust-lib/lib-dispatch/tests/api/module.rs
> chore: spawn task on local set

- frontend/rust-lib/event-integration-test/tests/document/af_cloud_test/file_upload_test.rs
- frontend/rust-lib/flowy-document/tests/document/util.rs
- frontend/rust-lib/flowy-sqlite/migrations/2024-08-20-061727_file_upload_finish/down.sql
- frontend/rust-lib/flowy-sqlite/migrations/2024-08-20-061727_file_upload_finish/up.sql
- frontend/rust-lib/flowy-sqlite/src/schema.rs
- frontend/rust-lib/flowy-storage-pub/src/chunked_byte.rs
- frontend/rust-lib/flowy-storage-pub/src/storage.rs
- frontend/rust-lib/flowy-storage/src/manager.rs
- frontend/rust-lib/flowy-storage/src/sqlite_sql.rs
- frontend/rust-lib/flowy-storage/src/uploader.rs
- frontend/rust-lib/flowy-storage/tests/multiple_part_upload_test.rs
> chore: fix file upload test

- frontend/rust-lib/dart-ffi/src/lib.rs
- frontend/rust-lib/event-integration-test/src/lib.rs
- frontend/rust-lib/flowy-core/src/lib.rs
- frontend/rust-lib/lib-dispatch/src/module/module.rs
- frontend/rust-lib/lib-dispatch/tests/api/module.rs
> chore: calm clippy wanring when using non send with Arc

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-core/Cargo.toml
- frontend/rust-lib/flowy-database2/src/services/calculations/entities.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/timestamp_type_option/timestamp_type_option.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/translate_type_option/translate.rs
- frontend/rust-lib/flowy-database2/src/services/field_settings/entities.rs
- frontend/rust-lib/flowy-database2/src/services/field_settings/field_settings_builder.rs
- frontend/rust-lib/flowy-database2/src/services/filter/entities.rs
- frontend/rust-lib/flowy-database2/src/services/group/entities.rs
- frontend/rust-lib/flowy-database2/src/services/setting/entities.rs
- frontend/rust-lib/flowy-database2/src/services/sort/entities.rs
> chore: explicit using any int64

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/event-integration-test/tests/user/migration_test/version_test.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-document/src/manager.rs
- frontend/rust-lib/flowy-server/Cargo.toml
- frontend/rust-lib/flowy-server/src/local_server/impls/database.rs
- frontend/rust-lib/flowy-user/src/migrations/document_empty_content.rs
- frontend/rust-lib/flowy-user/src/migrations/workspace_and_favorite_v1.rs
- frontend/rust-lib/flowy-user/src/migrations/workspace_trash_v1.rs
> chore: write collab to disk if it's not exist

- frontend/resources/translations/fr-FR.json
> Update translations - FR-FR

- frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/invite_members_screen.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart
- frontend/resources/translations/en.json
> chore: update member exceeded hint text

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/single_setting_action.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/primary_rounded_button.dart
> fix: ai writer generate button color

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
> chore: upgrade collab version

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
> chore: Enable document undo redo

- frontend/appflowy_flutter/lib/plugins/database/application/row/row_controller.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/card/card_bloc.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
> chore: fix board row

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
> chore: upgrade collab verison

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
> chore: async load database row

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_observe.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option_cell.rs
- frontend/rust-lib/flowy-database2/src/services/share/csv/import.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/flowy-folder/src/view_operation.rs
> fix: upload all imported csv rows

- frontend/appflowy_web_app/src/application/services/js-services/cache/index.ts
- frontend/appflowy_web_app/src/application/slate-yjs/utils/convert.ts
- frontend/appflowy_web_app/src/application/slate-yjs/utils/table.ts
- frontend/appflowy_web_app/src/components/editor/components/blocks/table/TableCell.tsx
> fix: table cells order on publish

- frontend/appflowy_web_app/src/components/publish/CollabView.tsx
- frontend/appflowy_web_app/src/components/publish/DatabaseView.tsx
- frontend/appflowy_web_app/src/components/publish/useViewMeta.ts
> fix: calendar style issues

- frontend/appflowy_web_app/src/components/as-template/AsTemplateButton.tsx
- frontend/appflowy_web_app/src/components/as-template/AsTemplateForm.tsx
- frontend/appflowy_web_app/src/components/as-template/related-template/TemplateItem.tsx
- frontend/appflowy_web_app/src/components/database/components/tabs/DatabaseTabs.tsx
- frontend/appflowy_web_app/src/components/publish/DatabaseView.tsx
- frontend/appflowy_web_app/src/components/publish/header/duplicate/Duplicate.tsx
> fix: database tabs

- frontend/appflowy_web_app/src/components/as-template/AsTemplate.tsx
- frontend/appflowy_web_app/src/components/database/components/tabs/DatabaseTabs.tsx
- frontend/appflowy_web_app/src/components/publish/CollabView.tsx
> fix: document issues

- frontend/appflowy_flutter/lib/mobile/presentation/home/setting/settings_popup_menu.dart
- frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/invite_members_screen.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
> fix: update settings menu color

- frontend/appflowy_web_app/src/application/slate-yjs/utils/convert.ts
- frontend/appflowy_web_app/src/components/as-template/AsTemplate.tsx
- frontend/appflowy_web_app/src/components/as-template/related-template/TemplateItem.tsx
- frontend/appflowy_web_app/src/components/database/components/board/card/Card.tsx
> fix: table issues

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_option_transform.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_type_option.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/type_option_transform.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/url_type_option/url_type_option.rs
- frontend/rust-lib/flowy-database2/src/services/filter/controller.rs
- frontend/rust-lib/flowy-database2/src/services/sort/controller.rs
> chore: replace cell content when import from csv

- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_item.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/setting/settings_popup_menu.dart
- frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/settings_popup_menu.dart
- frontend/appflowy_flutter/lib/shared/popup_menu/appflowy_popup_menu.dart
- frontend/resources/translations/en.json
https://github.com/user-attachments/assets/333f6e79-cd81-44ed-b2c0-4c4d9d3429ef
---
> feat: customize transition animation for popup menu

- frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_controller.dart
- frontend/appflowy_flutter/lib/plugins/database/application/row/row_controller.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/event-integration-test/tests/document/af_cloud_test/edit_test.rs
- frontend/rust-lib/flowy-core/Cargo.toml
- frontend/rust-lib/flowy-database2/src/entities/row_entities.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/notification.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/database.rs
- frontend/rust-lib/flowy-user/src/services/data_import/importer.rs
> chore: fix database row meta

- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/shared/empty_placeholder.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
Transaction order may affect data consistency.
---
> fix: table render error

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs
- frontend/rust-lib/flowy-core/src/integrate/user.rs
- frontend/rust-lib/flowy-error/src/code.rs
- frontend/rust-lib/flowy-error/src/errors.rs
- frontend/rust-lib/flowy-error/src/impl_from/cloud.rs
- frontend/rust-lib/flowy-storage/src/manager.rs
> chore: enable upload when switching workspace

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
> chore: upgrade client api that fix initfine sync

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/import/import_type.dart
> chore: remove old import type

- frontend/appflowy_web_app/src/components/editor/components/blocks/file/FileBlock.tsx
> fix: some file block issues

- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
> fix: expand the icon to be the same size as the text in the heading block

- frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_page_test.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/board/mobile_board_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/mobile_grid_page.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/mobile_row.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_text_cell.dart
- frontend/appflowy_flutter/lib/plugins/document/document_page.dart
- frontend/appflowy_flutter/lib/shared/flowy_error_page.dart
- frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
> fix: reset first page when switching space

- frontend/scripts/docker-buildfiles/Dockerfile
---
Fixes : #4349 
This PR addresses two errors that occur in the "Building with the repository installed" process using Docker Compose.
- https://docs.appflowy.io/docs/appflowy/install-appflowy/installation-methods/installing-with-docker#building-with-the-repository-installed
---
**Error 1 :** 
This is mentioned in issue #4349 .
```
./AppFlowy: error while loading libraries: libnotify.so.4: cannot open shared object file:no such file or directory
```
Added the `libnotify` package to the `App` side.
**Error 2 :**
After resolving Error 1, I confirmed that the following error occurs.
```
Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': librocksdb.so.9.4: cannot open shared object file: No such file or directory
```
Therefore, `rocksdb` was also …
> fix: Modified to launch the app from docker-compose.

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart
- frontend/resources/translations/en.json
- frontend/rust-lib/flowy-ai/src/local_ai/watch.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
> chore: update plan desc

- frontend/appflowy_flutter/lib/workspace/application/settings/date_time/date_format_ext.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
> fix: add leading zeros to day & month in date format

- frontend/appflowy_flutter/lib/core/frameless_window.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
Moves the title bar on windows on top of tabs.
> fix: move title bar on top of tabs on Windows

- frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/tabs_manager.dart
> fix: lose focus when changing tabs

- frontend/resources/translations/de-DE.json
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/6125
---
> fix: typo in german translation

- frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart
- frontend/appflowy_flutter/lib/plugins/database/application/row/related_row_detail_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/application/row/row_controller.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_event_editor_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/application/row/row_detail_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/card/card_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database_document/presentation/database_document_title_bloc.dart
> fix: init database row init

- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/member_list.dart
- frontend/appflowy_flutter/lib/shared/popup_menu/appflowy_popup_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
background color and button color
---
> fix: android toast style

- .github/workflows/flutter_ci.yaml
- .github/workflows/rust_ci.yaml
- frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/text_cell_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_controller.dart
- frontend/appflowy_flutter/lib/plugins/database/application/row/row_cache.dart
- frontend/appflowy_flutter/lib/plugins/database/application/row/row_list.dart
- frontend/appflowy_flutter/lib/plugins/database/application/row/row_service.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/application/unschedule_event_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_text_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_text_cell.dart
- frontend/appflowy_tauri/src/appflowy_app/application/database/row/row_service.ts
- frontend/rust-lib/event-integration-test/src/database_event.rs
- frontend/rust-lib/event-integration-test/tests/database/local_test/test.rs
- frontend/rust-lib/event-integration-test/tests/document/af_cloud_test/edit_test.rs
- frontend/rust-lib/event-integration-test/tests/user/af_cloud_test/anon_user_test.rs
- frontend/rust-lib/event-integration-test/tests/user/af_cloud_test/import_af_data_folder_test.rs
- frontend/rust-lib/event-integration-test/tests/user/af_cloud_test/workspace_test.rs
- frontend/rust-lib/flowy-database2/src/entities/row_entities.rs
- frontend/rust-lib/flowy-database2/src/event_handler.rs
- frontend/rust-lib/flowy-database2/src/event_map.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
> chore: show document icon or emoji

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_textfield.dart
> fix: wrap checklist item text

- .github/workflows/flutter_ci.yaml
- .github/workflows/rust_ci.yaml
- frontend/rust-lib/flowy-ai-pub/src/cloud.rs
- frontend/rust-lib/flowy-ai/src/ai_manager.rs
- frontend/rust-lib/flowy-ai/src/local_ai/local_llm_chat.rs
- frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
- frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs
- frontend/rust-lib/flowy-core/src/integrate/user.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/chat.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
- frontend/rust-lib/flowy-server/src/default_impl.rs
> fix: local ai enable/disable

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
- frontend/resources/translations/en.json
> chore: remove unused translation

- .github/workflows/flutter_ci.yaml
- .github/workflows/rust_ci.yaml
- frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/text_cell_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/application/field/field_editor_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/domain/field_service.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/desktop_field_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_property.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/setting/setting_property_list.dart
- frontend/appflowy_flutter/test/bloc_test/board_test/create_or_edit_field_test.dart
- frontend/appflowy_flutter/test/bloc_test/board_test/util.dart
- frontend/appflowy_flutter/test/bloc_test/grid_test/field/edit_field_test.dart
- frontend/appflowy_flutter/test/bloc_test/grid_test/util.dart
- frontend/rust-lib/event-integration-test/src/database_event.rs
- frontend/rust-lib/flowy-database2/src/entities/field_entities.rs
- frontend/rust-lib/flowy-database2/src/event_handler.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/tests/database/field_test/script.rs
> chore: auto update field title when creating a new field

- frontend/resources/translations/en.json
- frontend/resources/translations/fr-FR.json
- frontend/resources/translations/vi-VN.json
Added missing french translations.
> chore: update FR-fr translations 

- frontend/appflowy_web_app/src/components/as-template/AsTemplate.tsx
- frontend/appflowy_web_app/src/components/as-template/creator/CreatorAvatar.tsx
- frontend/appflowy_web_app/src/components/as-template/related-template/TemplateItem.tsx
- frontend/appflowy_web_app/src/components/database/components/calendar/event/Event.tsx
- frontend/appflowy_web_app/src/components/publish/header/PublishViewHeader.tsx
- frontend/appflowy_web_app/src/components/publish/header/duplicate/Duplicate.tsx
- frontend/appflowy_web_app/src/utils/color.ts
- frontend/resources/translations/en.json
> fix: display duplicate entry

- frontend/appflowy_web_app/src/application/services/js-services/index.ts
- frontend/appflowy_web_app/src/components/_shared/emoji-picker/EmojiPicker.hooks.ts
- frontend/appflowy_web_app/src/components/_shared/emoji-picker/EmojiPicker.tsx
- frontend/appflowy_web_app/src/components/as-template/AsTemplate.tsx
- frontend/appflowy_web_app/src/components/as-template/utils.ts
- frontend/appflowy_web_app/src/components/publish/header/duplicate/Duplicate.tsx
- frontend/appflowy_web_app/src/components/publish/header/duplicate/DuplicateModal.tsx
- frontend/appflowy_web_app/src/components/publish/header/duplicate/useDuplicate.ts
> fix: some duplicate issues

- .github/workflows/ios_ci.yaml
- frontend/scripts/makefile/mobile.toml
> chore: downgrade macOS version in iOS CI to avoid "no space left" error

- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
- frontend/rust-lib/flowy-user-pub/src/cloud.rs
- frontend/rust-lib/flowy-user/src/event_handler.rs
- frontend/rust-lib/flowy-user/src/event_map.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager.rs
- Added backend cloud API for account deletion
> feat: added delete account functionality

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> fix: incorrect right-lick menu position on Desktop

- frontend/appflowy_flutter/macos/.gitignore
- frontend/appflowy_flutter/macos/Podfile.lock
> chore: podfile.lock should not be ignored

- frontend/appflowy_flutter/android/app/build.gradle
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar_item.dart
- frontend/scripts/makefile/mobile.toml
> feat: exclude ARMv7 architecture for Android builds

- frontend/appflowy_flutter/ios/Runner/Info.plist
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/error/error_block_component_builder.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/resources/translations/en.json
> feat: auto-fix table block data when duplicating it

- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/lib/workspace/application/sidebar/billing/sidebar_plan_bloc.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_observe.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_filter.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_group.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_operation.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_sort.rs
- frontend/rust-lib/flowy-database2/tests/database/group_test/script.rs
- frontend/rust-lib/flowy-storage/src/uploader.rs
> chore: Observe database row event

- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_document.dart
- frontend/appflowy_flutter/lib/plugins/database_document/database_document_page.dart
> feat: optimize error page in database row page and remove unused code

- frontend/appflowy_flutter/integration_test/desktop/board/board_field_test.dart
- frontend/appflowy_flutter/integration_test/desktop/database/database_cell_test.dart
- frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart
- frontend/appflowy_flutter/integration_test/desktop/database/database_row_page_test.dart
- frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/application/field/field_editor_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/application/row/row_detail_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/desktop_field_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/grid_header.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_checklist_cell_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/relation_cell_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_property.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/setting/setting_property_list.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/test/bloc_test/board_test/create_or_edit_field_test.dart
- frontend/appflowy_flutter/test/bloc_test/board_test/group_by_unsupport_field_test.dart
- frontend/appflowy_flutter/test/bloc_test/board_test/util.dart
- frontend/appflowy_flutter/test/bloc_test/grid_test/field/edit_field_test.dart
- frontend/appflowy_flutter/test/bloc_test/grid_test/util.dart
- frontend/resources/translations/en.json
- frontend/scripts/code_generation/freezed/generate_freezed.sh
1. fix this monstrosity
3. On desktop, make enter on checklist items end editing, only allow shift + enter to go to a new line
4. don't animate the wrap text toggle when opening it
5. add integration test for when changing field type during creation
6. allow opening a related database from the popover
https://github.com/user-attachments/assets/31e94760-de5d-40a4-a2c0-0db0838e9c40
---
> fix(flutter): various grid ui issues

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/date_card_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
resolves #6055
resolves #6112
---
> fix(flutter_desktop): board ui bugs

- frontend/resources/translations/fr-FR.json
- frontend/resources/translations/zh-CN.json
Added missing translations for "Continue with..." texts into zh-CN.
> Add translations to zh-CN

- frontend/resources/translations/en.json
> chore: update translation

- frontend/appflowy_flutter/lib/plugins/database/board/application/board_bloc.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/flowy-database2/Cargo.toml
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-storage-pub/src/storage.rs
- frontend/rust-lib/flowy-storage/src/manager.rs
- frontend/rust-lib/flowy-storage/src/uploader.rs
> fix: open duplicated database

- frontend/appflowy_web_app/src/components/app/AppConfig.tsx
- frontend/appflowy_web_app/src/components/app/withAppWrapper.tsx
- frontend/appflowy_web_app/src/styles/variables/light.variables.css
- frontend/appflowy_web_app/tailwind/box-shadow.cjs
- frontend/appflowy_web_app/tailwind/colors.cjs
> fix: toast issues

- frontend/appflowy_web_app/src/components/app/AppConfig.tsx
> fix: hide toast

- frontend/appflowy_web_app/src/application/types.ts
- frontend/appflowy_web_app/src/assets/login/apple.svg
- frontend/appflowy_web_app/src/components/login/LoginProvider.tsx
- frontend/appflowy_web_app/src/components/publish/outline/OutlineItem.tsx
- frontend/resources/translations/en.json
> fix: apple login on web

- frontend/appflowy_flutter/lib/plugins/database/board/application/board_bloc.dart
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/5525
relates https://github.com/AppFlowy-IO/AppFlowy/issues/5786
---
> fix(flutter_desktop): cannot drag newly-created board cards

- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart
> fix: flowy hover isselected check

- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
- frontend/rust-lib/flowy-database2/src/services/group/action.rs
- frontend/rust-lib/flowy-database2/src/services/group/controller.rs
- frontend/rust-lib/flowy-database2/src/services/group/controller_impls/default_controller.rs
- frontend/rust-lib/flowy-database2/src/services/group/entities.rs
- frontend/rust-lib/flowy-database2/tests/database/group_test/script.rs
- frontend/rust-lib/flowy-database2/tests/database/group_test/test.rs
https://github.com/user-attachments/assets/d7c9a1ba-c7f3-4f4d-984a-90f86f848465
---
> fix: newly-created group rows appear out of order

- frontend/appflowy_flutter/lib/plugins/database/board/application/board_bloc.dart
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/6160
---
> fix(flutter): unhiding group throws exception

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart
https://github.com/user-attachments/assets/64c5ec8f-0de9-44f4-adee-a354c6da0a9c
> fix: space button rebuild issue

- frontend/appflowy_flutter/lib/mobile/presentation/setting/user_session_setting_group.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/loading.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_deletion.dart
> fix: redirect to login page after deleting account on Android

- frontend/appflowy_web_app/src/application/publish/context.tsx
- frontend/appflowy_web_app/src/components/global-comment/index.ts
- frontend/appflowy_web_app/src/components/publish/PublishView.tsx
- frontend/appflowy_web_app/src/styles/variables/light.variables.css
> fix: modified some behavior of template

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_setting.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
- frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_button.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_bloc.dart
- frontend/appflowy_flutter/macos/Podfile.lock
Before:
|Theme|Light|Dark
|---|---|---|
| Default | ![Screenshot 2024-09-07 at 6 03 28 PM](https://github.com/user-attachments/assets/acde5602-8655-4a67-8d98-055a374ded1e) | ![Screenshot 2024-09-07 at 6 03 39 PM](https://github.com/user-attachments/assets/f01fd1ec-8264-441c-9be0-b687f670771a) |
| Dandelion | ![Screenshot 2024-09-07 at 6 04 12 PM](https://github.com/user-attachments/assets/6cc0b0ce-44f5-4060-a3d4-0f5ff2b30bcd) | ![Screenshot 2024-09-07 at 6 03 56 PM](https://github.com/user-attachments/assets/4d603770-60ff-48ed-b5b8-8b91ef3f9b53) |
After:
|Theme|Light|Dark|
|---|---|---|
|Default| ![Screenshot 2024-09-07 at 6 02 25 PM](https://github.com/user-attachments/assets/0c6f1eeb-532e-419b-bb46-c05ec22cb848) | ![Screenshot 2024-09-07 at 6 01 …
> fix(flutter_desktop): incorrect colors for switch workspace button

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_add_button.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart
https://github.com/user-attachments/assets/b1de525f-36e1-4059-979e-3bcf789e47bf
---
> fix: hover color in different color schemes

- frontend/appflowy_flutter/android/app/build.gradle
- frontend/appflowy_flutter/lib/mobile/presentation/home/setting/settings_popup_menu.dart
- frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
- frontend/appflowy_flutter/lib/plugins/base/emoji/emoji_text.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart
- frontend/appflowy_flutter/lib/shared/popup_menu/appflowy_popup_menu.dart
- frontend/appflowy_flutter/lib/util/share_log_files.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> fix: android share log file permission

- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/resources/translations/en.json
> feat: file block on mobile

- CHANGELOG.md
> Chore: Update CHANGELOG.md incl v0.6.9

- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-server/Cargo.toml
- frontend/rust-lib/flowy-server/src/local_server/impls/database.rs
- frontend/rust-lib/flowy-server/src/local_server/impls/user.rs
- frontend/rust-lib/flowy-user/src/services/data_import/appflowy_data_import.rs
> chore: check collab before saving collab to disk

- frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/6263
```log
flutter: [debug] apply transaction begin 834941874
flutter: [debug] [editor_transaction_adapter] apply transaction cost: total 23 ms, converter action 5 ms, apply action 18 ms
flutter: [debug] apply transaction end 834941874
flutter: [debug] apply transaction begin 362845249
flutter: [debug] [editor_transaction_adapter] apply transaction cost: total 19 ms, converter action 14 ms, apply action 5 ms
flutter: [debug] apply transaction end 362845249
flutter: [debug] apply transaction begin 752253174
flutter: [debug] [editor_transaction_adapter] apply transaction cost: total 2 ms, converter action 0 ms, apply action 2 ms
flutter: [debug] apply transaction end 752253174
flutter: [debug] apply transaction begin 428933228
flutter: …
```
> fix: the last block of a doc is randomly moved to the first position of the doc

- README.md
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> feat: support moving cursor using keyboard gesture on mobile

- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/rust-lib/flowy-database2/src/services/filter/controller.rs
> fix: filter rows sometime not working

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/unsplash_image_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_node_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_toolbar_item.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/appflowy_flutter/pubspec.lock
> feat: ai writer on multi-lines of text

- frontend/appflowy_flutter/lib/plugins/database/application/row/row_controller.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/flowy-database2/src/entities/row_entities.rs
- frontend/rust-lib/flowy-database2/src/event_handler.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/tests/database/database_editor.rs
> chore: adjust num of preload rows

- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart
Before:
https://github.com/user-attachments/assets/27c68517-94c5-41a9-a0af-5ec21ca236f3
> fix: card rebuild issue

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
> chore: bump collab that removes timeout when loading row

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/collab-integrate/src/collab_builder.rs
- frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
- frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs
- frontend/rust-lib/flowy-database-pub/src/cloud.rs
- frontend/rust-lib/flowy-database2/src/event_handler.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
- frontend/rust-lib/flowy-database2/tests/database/database_editor.rs
- frontend/rust-lib/flowy-document-pub/src/cloud.rs
- frontend/rust-lib/flowy-document/src/manager.rs
- frontend/rust-lib/flowy-document/tests/document/util.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/flowy-folder/src/manager_init.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/database.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/document.rs
- frontend/rust-lib/flowy-server/src/local_server/impls/database.rs
- frontend/rust-lib/flowy-server/src/local_server/impls/document.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_awareness.rs
1. Save document to cloud after create a new document
2. batch load database rows instead of load them one by one from server
3. reduce related to performance issue
> fix: write/load database/document collab

- frontend/appflowy_web_app/deploy/server.ts
- frontend/appflowy_web_app/src/application/services/js-services/http/http_api.ts
- frontend/appflowy_web_app/src/application/services/js-services/index.ts
- frontend/appflowy_web_app/src/application/services/services.type.ts
- frontend/appflowy_web_app/src/application/services/tauri-services/index.ts
- frontend/appflowy_web_app/src/application/session/sign_in.ts
- frontend/appflowy_web_app/src/application/types.ts
- frontend/appflowy_web_app/src/components/_shared/modal/NormalModal.tsx
- frontend/appflowy_web_app/src/components/app/App.tsx
- frontend/appflowy_web_app/src/components/app/AppConfig.tsx
- frontend/appflowy_web_app/src/components/login/LinearBuffer.tsx
- frontend/appflowy_web_app/src/components/login/LoginAuth.tsx
- frontend/appflowy_web_app/src/components/publish/header/PublishViewHeader.tsx
- frontend/appflowy_web_app/src/components/publish/header/utils.ts
- frontend/appflowy_web_app/src/pages/AcceptInvitationPage.tsx
- frontend/appflowy_web_app/src/utils/open_schema.ts
- frontend/resources/translations/en.json
> feat: support invitation page

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-core/Cargo.toml
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/filter/controller.rs
- frontend/rust-lib/flowy-database2/src/services/share/csv/export.rs
- frontend/rust-lib/flowy-database2/tests/database/filter_test/advanced_filter_test.rs
using original row roders to apply sort when there are no sorts
> fix: sort with original row orders

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/model_selection.dart
- frontend/rust-lib/flowy-user/src/entities/workspace.rs
> chore: update ai model name

- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_checkbox_column_header.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_column_header.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_editable_column_header.dart
> chore: show full name of groups on hover

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
> fix: view title doesn't update after renaming from 'more' button

- frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml
> chore: downgrade appimage builder

- frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/row_page_button.dart
- frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/text_cell_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/text.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
- frontend/appflowy_flutter/lib/plugins/database_document/presentation/database_document_title.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-core/Cargo.toml
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
1. replace onEditing callback with onComplete callback
2. fix  the title of row detail page is overwritten with untitled text
> fix: untitled override the true value in row details page

- frontend/appflowy_web_app/src/components/database/components/cell/primary/PrimaryCell.tsx
- frontend/appflowy_web_app/src/styles/app.scss
> fix: modified primary cell

- frontend/appflowy_flutter/packages/appflowy_backend/lib/log.dart
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/group/controller.rs
- frontend/rust-lib/flowy-database2/src/services/group/entities.rs
- frontend/rust-lib/flowy-database2/src/services/group/group_builder.rs
> chore: remove cancel get rows

- frontend/appflowy_flutter/lib/mobile/presentation/database/card/mobile_card_content.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/media_card_cell.dart
> fix: show count of files on card per column

- frontend/appflowy_web_app/src/components/database/components/cell/file-media/PreviewImage.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/table/Table.tsx
> fix: fixed image size for media cell

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_text_cell.dart
> fix: make icon of primary cells align to top

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/backtick_character_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5299
closes https://github.com/AppFlowy-IO/AppFlowy/issues/4431
---
> fix: inputting backtick will crash when using French IME

- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/lib/core/config/kv_keys.dart
- frontend/appflowy_flutter/lib/plugins/database_document/database_document_page.dart
- frontend/appflowy_flutter/lib/plugins/document/application/document_appearance_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/document_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/setting_list_tile.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/resources/translations/en.json
closes https://github.com/AppFlowy-IO/AppFlowy/issues/6312
update:
https://github.com/user-attachments/assets/49d4f951-12ce-4833-9dff-c7804a1bd0ae
---
> feat: support adjusting document width

- frontend/appflowy_flutter/integration_test/shared/common_operations.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
- frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/move_to/move_page_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/font_size_action.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/view_meta_info.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> feat: support moveTo feature in more action menu

- frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/setting_menu.dart
- frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
> fix(flutter_desktop): alignment on filter and sort menu

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart
> fix: image upload loading

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
In some cases, when the editor initialization is not finished, retrieving the offset returns 0 always.
before
after
---
> fix: icon doesn't align to the editor if the editor is not initialized

- frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/primary_rounded_button.dart
- frontend/resources/translations/en.json
> fix: settings page minor issues

- CHANGELOG.md
> chore: add changelog for 0.7.0

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-core/Cargo.toml
- frontend/rust-lib/flowy-document/src/manager.rs
- frontend/rust-lib/flowy-storage/Cargo.toml
- frontend/rust-lib/flowy-storage/src/manager.rs
- frontend/rust-lib/flowy-storage/tests/multiple_part_upload_test.rs
- frontend/rust-lib/flowy-user/src/services/data_import/appflowy_data_import.rs
> chore: bump collab version

- frontend/appflowy_flutter/integration_test/desktop/board/board_row_test.dart
- frontend/appflowy_flutter/packages/appflowy_backend/lib/log.dart
- frontend/rust-lib/flowy-core/Cargo.toml
- frontend/rust-lib/flowy-database2/src/services/database/database_observe.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
- frontend/rust-lib/flowy-database2/src/services/group/controller_impls/default_controller.rs
> fix: delete duplicate test in board

- frontend/appflowy_web_app/src/components/database/calendar/Calendar.tsx
- frontend/appflowy_web_app/src/components/database/components/board/column/ListItem.tsx
- frontend/appflowy_web_app/src/components/database/components/cell/useMeasure.ts
- frontend/appflowy_web_app/src/components/database/components/grid/grid-table/GridTable.tsx
- frontend/appflowy_web_app/src/components/document/Document.tsx
> fix: adjust margin bottom

- frontend/appflowy_web_app/src/components/document/Document.tsx
- frontend/appflowy_web_app/src/components/editor/Editable.tsx
> fix: adjust editor's margin bottom

- frontend/appflowy_web_app/src/components/database/components/database-row/DatabaseRowSubDocument.tsx
> fix: adjust row page skeleton

- frontend/appflowy_web_app/src/components/database/components/header/DatabaseRowHeader.tsx
> fix: modified row page cover

- frontend/appflowy_web_app/src/components/database/components/cell/relation/RelationItems.tsx
> fix: fix jump error issue

- frontend/appflowy_flutter/integration_test/cloud/anon_user_continue_test.dart
- frontend/appflowy_flutter/integration_test/shared/common_operations.dart
- frontend/appflowy_flutter/packages/appflowy_backend/lib/log.dart
> chore: fix anon test

- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_checkbox_column_header.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_column_header.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_editable_column_header.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/card/container/card_container.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_cell_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/media.dart
> fix: launch review issues 0.7.0

- frontend/appflowy_flutter/integration_test/cloud/cloud_runner.dart
- frontend/appflowy_flutter/integration_test/cloud/sidebar/sidebar_move_page_test.dart
- frontend/appflowy_flutter/integration_test/cloud/workspace/workspace_settings_test.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/move_to/move_page_menu.dart
- frontend/appflowy_flutter/pubspec.lock
> fix: sidebar move page test

- frontend/appflowy_flutter/integration_test/desktop/uncategorized/zoom_in_out_test.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_3.dart
- frontend/appflowy_flutter/integration_test/shared/common_operations.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/6311
---
> feat: add numpadSubtract as zoom out keycode

- frontend/appflowy_flutter/integration_test/desktop/settings/settings_runner.dart
- frontend/appflowy_flutter/integration_test/desktop/settings/sign_in_page_settings_test.dart
- frontend/appflowy_flutter/lib/flutter/af_dropdown_menu.dart
- frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_dropdown.dart
self-hosted
appflowy cloud
---
> feat: support appflowy cloud in sign-in settings page

- frontend/appflowy_flutter/integration_test/desktop/board/board_group_test.dart
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
Caused by a regression of https://github.com/AppFlowy-IO/AppFlowy/pull/6156
---
> fix(flutter_desktop): select option kanban groups not updating

- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
> fix: hover bug in row banner

- frontend/appflowy_flutter/integration_test/cloud/appflowy_cloud_auth_test.dart
- frontend/appflowy_flutter/integration_test/cloud/document/document_delete_block_test.dart
- frontend/appflowy_flutter/integration_test/cloud/document/document_drag_block_test.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
- frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_image.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_node_widget.dart
- frontend/appflowy_flutter/test/bloc_test/smart_edit_test/smart_editor_bloc_test.dart
> fix: potential ai_repository not init

- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_detail.dart
https://github.com/user-attachments/assets/2d0c355c-0d64-4ee6-b37c-eb3717fdf457
---
> fix: offset row actions by cover height

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/src/manager.rs
> chore: detect field type when import csv

- frontend/appflowy_flutter/integration_test/desktop/database/database_filter_test.dart
- frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
- frontend/appflowy_flutter/lib/plugins/database/application/field/filter_entities.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/filter_editor_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/date.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/appflowy_date_picker.dart
- frontend/resources/translations/en.json
- frontend/rust-lib/flowy-database2/src/entities/filter_entities/date_filter.rs
- frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_filter.rs
- frontend/rust-lib/flowy-database2/src/services/group/controller_impls/date_controller.rs
- frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/util.rs
- frontend/rust-lib/flowy-database2/tests/database/filter_test/advanced_filter_test.rs
- frontend/rust-lib/flowy-database2/tests/database/filter_test/date_filter_test.rs
- frontend/rust-lib/flowy-database2/tests/database/group_test/script.rs
- frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/pre_fill_row_according_to_filter_test.rs
> feat: allow filtering by date end

- frontend/appflowy_flutter/lib/mobile/presentation/database/board/mobile_board_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/group_card_header.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_bottom_sheet.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_bottom_sheet_cubit.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_condition_list.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_sort_bottom_sheet.dart
- frontend/appflowy_flutter/lib/plugins/database/application/field/filter_entities.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_column_header.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/filter_editor_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/checklist.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/date.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/number.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/select_option.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/text.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/url.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/field_type_extension.dart
- frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/extension.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_select_option_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/setting/mobile_database_controls.dart
- frontend/appflowy_flutter/lib/util/field_type_extension.dart
- frontend/appflowy_web_app/src/components/database/__tests__/DatabaseWithFilter.cy.tsx
- frontend/resources/translations/en.json
Supports filtering on mobile grid and kanban
resovles https://github.com/AppFlowy-IO/AppFlowy/issues/5849
I recorded a video but it's larger than 10mb
---
> feat(mobile): add database filters

- .github/workflows/docker_ci.yml
- frontend/appflowy_flutter/integration_test/desktop/document/document_customer_test.dart
- frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/keyboard_interceptor/keyboard_interceptor.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/6394
https://github.com/user-attachments/assets/d874d93a-4628-49e8-acac-dffd9c9649c4
https://github.com/user-attachments/assets/b2af05c3-43a1-4297-bc17-40a1b11ec856
---
> fix: backtick issue in French IME

- frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
- frontend/appflowy_flutter/macos/Runner/MainFlutterWindow.swift
https://github.com/user-attachments/assets/cd95551e-0978-4686-ae9d-9a07b8ace464
---
> feat: support window tiling on macOS

- frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_in_app_json.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/custom_image_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/image_menu.dart
- frontend/appflowy_flutter/lib/util/default_extensions.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
> fix: paste doesn't work sometimes in the first try

- frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/card/card_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/card/container/card_container.dart
- frontend/appflowy_flutter/pubspec.lock
> fix(flutter_desktop): board card rebuild issue

- frontend/appflowy_web_app/src/application/comment.type.ts
- frontend/appflowy_web_app/src/application/services/js-services/http/http_api.ts
- frontend/appflowy_web_app/src/application/services/js-services/index.ts
- frontend/appflowy_web_app/src/application/services/services.type.ts
- frontend/appflowy_web_app/src/application/services/tauri-services/index.ts
- frontend/appflowy_web_app/src/application/types.ts
- frontend/appflowy_web_app/src/assets/arrow.svg
- frontend/appflowy_web_app/src/components/app/AppRouter.tsx
- frontend/appflowy_web_app/src/components/app/SideBar.tsx
- frontend/appflowy_web_app/src/components/app/app.hooks.tsx
- frontend/appflowy_web_app/src/components/app/header/AppHeader.tsx
- frontend/appflowy_web_app/src/components/app/header/RightMenu.tsx
- frontend/appflowy_web_app/src/components/app/landing-pages/ApproveRequestPage.tsx
- frontend/appflowy_web_app/src/components/app/landing-pages/RequestAccess.tsx
- frontend/appflowy_web_app/src/components/app/share/ShareTabs.tsx
- frontend/appflowy_web_app/src/components/app/workspaces/Workspaces.tsx
- frontend/appflowy_web_app/src/components/global-comment/GlobalComment.hooks.tsx
- frontend/appflowy_web_app/src/pages/AcceptInvitationPage.tsx
- frontend/appflowy_web_app/src/pages/AppPage.tsx
- frontend/appflowy_web_app/src/utils/open_schema.ts
- frontend/resources/translations/en.json
> fix: support approve

- frontend/appflowy_flutter/integration_test/desktop/document/document_shortcuts_test.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_copy_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_cut_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/character_shortcuts.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/shortcuts/settings_shortcuts_cubit.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/shortcuts/settings_shortcuts_service.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/appflowy_flutter/test/bloc_test/shortcuts_test/shortcuts_cubit_test.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/6425
https://github.com/user-attachments/assets/94bde038-dc3a-4812-88a5-b1e44a1440b8
---
> feat: support copy/cut command when the selection is collapsed

- frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_column_header.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_day.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_page.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/toolbar/calendar_layout_setting.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/calculations/calculation_type_item.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/calculations/remove_calculation_button.dart
- frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/tab_bar_add_button.dart
- frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_relation_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_text_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_date_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_media_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_relation_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_timestamp_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_timestamp_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_select_option_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_property.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/appearance/base_appearance.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
> feat(flutter_desktop): use regular rather than medium font weight by default

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
https://github.com/AppFlowy-IO/AppFlowy/issues/6436
clear the document selection if the cover title is in focus.
---
> fix: double cursor show in title and doc sometimes

- frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
- frontend/appflowy_flutter/integration_test/shared/document_test_operations.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_in_app_json.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/6440
---
> fix: insert the pasted nodes after current selection if they start with a non-delta node

- frontend/appflowy_flutter/integration_test/desktop/document/document_selection_test.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/6433
For more details, refer to this PR. https://github.com/AppFlowy-IO/appflowy-editor/pull/909
---
> feat: optimize selection gesture in editor

- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_card.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/card/container/accessory.dart
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/5773
---
> fix(flutter_desktop): fix calendar event bugs

- frontend/appflowy_flutter/integration_test/desktop/database/database_field_settings_test.dart
- frontend/appflowy_flutter/integration_test/desktop/grid/grid_edit_row_test.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_3.dart
- frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
- frontend/appflowy_flutter/test/bloc_test/grid_test/filter/filter_menu_test.dart
> test: add grid bloc and integration tests

- frontend/appflowy_flutter/integration_test/desktop/database/database_cell_test.dart
- frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart
- frontend/appflowy_flutter/integration_test/desktop/database/database_share_test.dart
- frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
- frontend/rust-lib/flowy-database2/src/event_handler.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/type_option_transform.rs
Before
https://github.com/user-attachments/assets/5d50e8de-c813-4469-9b12-8bffb3b6549f
After
https://github.com/user-attachments/assets/a2972ef3-4fd7-4571-b9c0-1b5b97176afa
---
> fix: field type option transform

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
> fix: hide border on icon in callout

- frontend/appflowy_flutter/integration_test/desktop/document/document_with_file_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_selection_menu.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_selection_menu.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
> feat: show file popover automatically

- frontend/appflowy_flutter/integration_test/desktop/document/document_with_database_test.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/link_to_page_widget.dart
- frontend/appflowy_flutter/lib/plugins/inline_actions/inline_actions_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
Update the workspace icon style on desktop.
---
> feat: update workspace icon style on desktop

- frontend/appflowy_flutter/lib/plugins/trash/trash_page.dart
- frontend/resources/translations/en.json
> fix: new dialog style in trash actions

- frontend/appflowy_flutter/integration_test/desktop/document/document_sub_page_test.dart
> test: amend test after merge

- frontend/appflowy_web_app/src/components/_shared/modal/ChangeAccount.tsx
- frontend/appflowy_web_app/src/components/_shared/view-icon/ViewIcon.tsx
- frontend/appflowy_web_app/src/components/app/app.hooks.tsx
- frontend/appflowy_web_app/src/components/app/landing-pages/ApproveRequestPage.tsx
- frontend/appflowy_web_app/src/components/app/landing-pages/RequestAccess.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/toggle-list/ToggleIcon.tsx
- frontend/appflowy_web_app/src/pages/AcceptInvitationPage.tsx
> fix: share link issues

- frontend/appflowy_web_app/src/components/app/MainLayout.tsx
- frontend/appflowy_web_app/src/components/app/SideBar.tsx
- frontend/appflowy_web_app/src/components/app/app.hooks.tsx
- frontend/appflowy_web_app/src/components/editor/Editable.tsx
- frontend/appflowy_web_app/src/components/error/PageHasBeenDeleted.tsx
- frontend/appflowy_web_app/src/components/error/RecordNotFound.tsx
- frontend/appflowy_web_app/src/pages/TrashPage.tsx
> fix: add some placeholder for deleted and not found

- frontend/appflowy_web_app/src/components/app/app.hooks.tsx
> fix: not found page issues

- frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_option_actions_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
Disable the 'Copy Link to Block' feature. It's not included in the upcoming version.
---
> chore: disable copy link to block feature

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
> Unable to add test because it's not possible to mock resizing in the test env.
https://github.com/user-attachments/assets/e84ad830-1167-4f03-b0dc-419379f070d2
https://github.com/user-attachments/assets/6ca54f18-3196-48af-af09-0e0a0049fd60
---
> fix: title flash when resizing

- frontend/appflowy_flutter/integration_test/desktop/document/document_sub_page_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/block_transaction_handler.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_block_component.dart
- frontend/resources/translations/en.json
- frontend/rust-lib/flowy-folder/src/manager.rs
> fix: sub page block review fixes

- frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_icon_test.dart
- frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_test_runner.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_title_test.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_with_cover_image_test.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
- frontend/appflowy_flutter/integration_test/shared/document_test_operations.dart
- frontend/appflowy_flutter/lib/mobile/application/page_style/document_page_style_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/exit_edit_mode_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/undo_redo/custom_undo_redo_commands.dart
- frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-user/src/services/data_import/appflowy_data_import.rs
> fix: ignore same workspace icon update

- .github/actions/flutter_integration_test/action.yml
- .github/workflows/flutter_ci.yaml
- .github/workflows/release.yml
- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_1.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_2.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_1.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_3.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_4.dart
- frontend/appflowy_flutter/integration_test/mobile/document/document_test_runner.dart
- frontend/appflowy_flutter/integration_test/mobile/document/title_test.dart
- frontend/appflowy_flutter/integration_test/runner.dart
- frontend/appflowy_flutter/integration_test/shared/common_operations.dart
- frontend/appflowy_flutter/integration_test/shared/document_test_operations.dart
- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/default_mobile_action_pane.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart
- frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
- frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
- frontend/appflowy_flutter/lib/plugins/document/document_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
- frontend/resources/translations/en.json
- frontend/resources/translations/ja-JP.json
- frontend/resources/translations/tr-TR.json
- frontend/resources/translations/uk-UA.json
- frontend/resources/translations/vi-VN.json
https://github.com/user-attachments/assets/ce9b7b44-31aa-4682-93f0-98df0979f7fc
---
> feat: support editing name when creating a new page on mobile

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/test/bloc_test/grid_test/sort/sort_editor_bloc_test.dart
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/6503
---
> test: fix flaky sort test

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_node_widget.dart
- frontend/appflowy_flutter/test/bloc_test/smart_edit_test/smart_editor_bloc_test.dart
> fix: show AI limit error toast if exceeding the AI response

- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-ai/src/entities.rs
- frontend/rust-lib/flowy-database2/src/entities/calculation/calculation_changeset.rs
- frontend/rust-lib/flowy-database2/src/entities/database_entities.rs
- frontend/rust-lib/flowy-database2/src/entities/field_entities.rs
- frontend/rust-lib/flowy-database2/src/entities/field_settings_entities.rs
- frontend/rust-lib/flowy-database2/src/entities/filter_entities/util.rs
- frontend/rust-lib/flowy-database2/src/entities/group_entities/group.rs
- frontend/rust-lib/flowy-database2/src/entities/row_entities.rs
- frontend/rust-lib/flowy-database2/src/entities/setting_entities.rs
- frontend/rust-lib/flowy-database2/src/entities/sort_entities.rs
- frontend/rust-lib/flowy-document/Cargo.toml
- frontend/rust-lib/flowy-document/src/entities.rs
- frontend/rust-lib/flowy-document/src/parser/parser_entities.rs
- frontend/rust-lib/flowy-folder/src/entities/import.rs
- frontend/rust-lib/flowy-search/Cargo.toml
- frontend/rust-lib/flowy-user/src/entities/import_data.rs
- frontend/rust-lib/flowy-user/src/entities/parser/user_email.rs
- frontend/rust-lib/flowy-user/src/entities/user_profile.rs
- frontend/rust-lib/flowy-user/src/entities/workspace.rs
- frontend/rust-lib/lib-dispatch/Cargo.toml
- frontend/rust-lib/lib-dispatch/src/data.rs
- frontend/rust-lib/lib-infra/Cargo.toml
> chore: bump validator crate ver

- frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_icon_test.dart
- frontend/appflowy_flutter/lib/main.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/select/select_option.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_button.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/time_text_field.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/pop_up_action.dart
- frontend/appflowy_flutter/packages/appflowy_popover/analysis_options.yaml
- frontend/appflowy_flutter/packages/appflowy_popover/example/analysis_options.yaml
- frontend/appflowy_flutter/packages/appflowy_popover/example/ios/Flutter/AppFrameworkInfo.plist
- frontend/appflowy_flutter/packages/appflowy_popover/example/ios/Runner.xcodeproj/project.pbxproj
- frontend/appflowy_flutter/packages/appflowy_popover/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- frontend/appflowy_flutter/packages/appflowy_popover/example/ios/Runner/Info.plist
- frontend/appflowy_flutter/packages/appflowy_popover/example/lib/example_button.dart
- frontend/appflowy_flutter/packages/appflowy_popover/example/lib/main.dart
- frontend/appflowy_flutter/packages/appflowy_popover/example/macos/Runner.xcodeproj/project.pbxproj
- frontend/appflowy_flutter/packages/appflowy_popover/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- frontend/appflowy_flutter/packages/appflowy_popover/example/pubspec.yaml
- frontend/appflowy_flutter/packages/appflowy_popover/lib/src/follower.dart
- frontend/appflowy_flutter/packages/appflowy_popover/lib/src/layout.dart
- frontend/appflowy_flutter/packages/appflowy_popover/lib/src/mask.dart
- frontend/appflowy_flutter/packages/appflowy_popover/lib/src/mutex.dart
- frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart
- frontend/appflowy_flutter/packages/appflowy_popover/pubspec.yaml
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
- frontend/appflowy_flutter/pubspec.lock
For better visual effect, add fade and scale animation to the popover component.
> By default, the animation is disabled. Enable it by setting an animation duration.
https://github.com/user-attachments/assets/d02b0276-80ce-48d3-8d6d-02907977bf75
---
> feat: customize animation for popover

- frontend/appflowy_flutter/test/bloc_test/grid_test/sort/sort_editor_bloc_test.dart
https://github.com/AppFlowy-IO/AppFlowy/actions/runs/11255922422/job/31297124026
---
> test: fix flaky sort editor bloc test

- frontend/appflowy_flutter/integration_test/desktop/database/database_calendar_test.dart
- frontend/appflowy_flutter/integration_test/desktop/database/database_filter_test.dart
- frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
- frontend/appflowy_flutter/lib/plugins/database/application/defines.dart
- frontend/appflowy_flutter/lib/plugins/database/application/row/row_cache.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_page.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/toolbar/calendar_setting_bar.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
- frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/5303
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/3345
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/6234
---
> feat: calendar filters

- README.md
Corrected "Acknowledgements" to "Acknowledgments" in [README.md].
This pull request addresses a minor typo found in the repository. The typo has been corrected to improve clarity and maintain the quality of the documentation.
This change is purely cosmetic and does not affect functionality.
---
> Update README.md fixed a typo

- frontend/appflowy_web_app/deploy/server.ts
- frontend/appflowy_web_app/src/application/services/js-services/http/http_api.ts
- frontend/appflowy_web_app/src/components/_shared/file-dropzone/FileDropzone.tsx
- frontend/appflowy_web_app/src/components/_shared/more-actions/MoreActions.tsx
- frontend/appflowy_web_app/src/components/_shared/more-actions/importer/Import.tsx
- frontend/appflowy_web_app/src/components/_shared/more-actions/importer/ImporterDialogContent.tsx
- frontend/appflowy_web_app/src/components/_shared/more-actions/importer/ImporterModal.tsx
- frontend/appflowy_web_app/src/components/_shared/more-actions/importer/useImport.hook.ts
- frontend/appflowy_web_app/src/components/app/app.hooks.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/gallery/carousel.scss
- frontend/appflowy_web_app/src/components/main/App.tsx
- frontend/appflowy_web_app/src/pages/ImportPage.tsx
- frontend/resources/translations/en.json
> feat: support import notion

- frontend/rust-lib/flowy-database2/tests/database/calculations_test/calculation_test.rs
- frontend/rust-lib/flowy-database2/tests/database/calculations_test/script.rs
- frontend/rust-lib/flowy-database2/tests/database/database_editor.rs
> chore: add calculation rust test

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
- frontend/resources/translations/en.json
> chore: add tooltip when import notion file

- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/toolbar/calendar_layout_setting.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/date_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/media.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/timestamp.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/group/database_group.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/local_ai_chat_setting.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/local_ai_setting.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_appflowy_cloud.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_notifications_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/date_picker_dialog.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/toggle/toggle.dart
…e.toggle
pass the new value instead of the old value into the callback
---
> chore: adjust Toggle widget's onChanged callback

- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
> fix: text button

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_import_notion.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/rust-lib/flowy-server/src/af_cloud/server.rs
> chore: show import error

- frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_copy_link_to_block_test.dart
- frontend/appflowy_flutter/lib/plugins/document/document.dart
- frontend/appflowy_flutter/lib/plugins/document/document_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
- frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
- frontend/appflowy_flutter/lib/workspace/application/action_navigation/navigation_action.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_deletion.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
https://github.com/user-attachments/assets/d00e0555-e491-498d-9398-235dc4170a53
---
> feat: observe mention block change and support block navigation

- frontend/appflowy_flutter/integration_test/desktop/database/database_calendar_test.dart
- frontend/appflowy_flutter/integration_test/desktop/database/database_filter_test.dart
- frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_bottom_sheet.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_condition_list.dart
- frontend/appflowy_flutter/lib/plugins/database/application/field/filter_entities.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_page.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/select_option_loader.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/condition_list.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/option_list.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/select_option.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
- frontend/appflowy_flutter/test/bloc_test/grid_test/filter/filter_entities_test.dart
- frontend/rust-lib/flowy-database2/src/entities/filter_entities/select_option_filter.rs
- frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_filter.rs
- frontend/rust-lib/flowy-database2/src/services/filter/entities.rs
- frontend/rust-lib/flowy-database2/tests/database/filter_test/select_option_filter_test.rs
- frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/pre_fill_row_according_to_filter_test.rs
> fix(flutter-desktop): launch review issues for 0.7.2

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/5772
https://github.com/user-attachments/assets/f446aaf6-62d5-4cbe-8aea-37abf856a7e8
---
> fix: bring back the board scrollbar

- frontend/appflowy_flutter/integration_test/desktop/document/document_option_action_test.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_1.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button_feedback.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/option_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/cover_title_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_toolbar_item.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/test/unit_test/document/turn_into/turn_into_test.dart
- frontend/resources/translations/en.json
> fix: turn into issues

- frontend/appflowy_flutter/lib/workspace/presentation/command_palette/command_palette.dart
> fix: notifier disposed but in use

- frontend/appflowy_flutter/lib/plugins/database_document/database_document_page.dart
> fix: drag and drop row document full page

- frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
> fix: trash breadcrumb line height

- frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/option_text_field.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_full_field_editor.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_field_list.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/row/cells/mobile_cell_container.dart
https://github.com/user-attachments/assets/154685b1-a8ba-4132-98de-e762fb43406c
Also disable changing the field type of the primary field
---
> fix(flutter-mobile): edit primary field from database controls

- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs
- frontend/rust-lib/flowy-error/src/code.rs
- frontend/rust-lib/flowy-folder-pub/Cargo.toml
- frontend/rust-lib/flowy-folder-pub/src/cloud.rs
- frontend/rust-lib/flowy-folder-pub/src/entities.rs
- frontend/rust-lib/flowy-folder/Cargo.toml
- frontend/rust-lib/flowy-folder/src/entities/icon.rs
- frontend/rust-lib/flowy-folder/src/entities/publish.rs
- frontend/rust-lib/flowy-folder/src/entities/view.rs
- frontend/rust-lib/flowy-folder/src/event_handler.rs
- frontend/rust-lib/flowy-folder/src/event_map.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/chat.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/folder.rs
- frontend/rust-lib/flowy-server/src/local_server/impls/folder.rs
- frontend/rust-lib/flowy-server/src/supabase/api/folder.rs
This reverts commit 73e8b476fbfe25dda69d0e430376473012202b7e.
---
> Revert "feat: custom domain (#6518)"

- frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/date_cell_editor_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/board/application/board_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/appflowy_date_picker.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/mobile_appflowy_date_picker.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/test/bloc_test/grid_test/cell/date_cell_bloc_test.dart
- frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option.rs
> fix: date picker code improvements and regressions

- frontend/appflowy_web_app/src/application/services/js-services/http/http_api.ts
- frontend/appflowy_web_app/src/application/services/js-services/index.ts
- frontend/appflowy_web_app/src/application/services/services.type.ts
- frontend/appflowy_web_app/src/application/services/tauri-services/index.ts
- frontend/appflowy_web_app/src/components/_shared/more-actions/importer/ImporterDialogContent.tsx
> fix: import interfaces and error message

- .github/workflows/flutter_ci.yaml
- .github/workflows/ios_ci.yaml
- .github/workflows/rust_ci.yaml
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/database.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/folder.rs
> chore: bump client api that includes upload large zip file

- frontend/appflowy_flutter/macos/Runner.xcodeproj/project.pbxproj
- Embed libbz2.tbd on macOS
---
> fix: macos arm64 build

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/event-integration-test/src/folder_event.rs
- frontend/rust-lib/event-integration-test/tests/database/af_cloud/util.rs
- frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/share/csv/import.rs
- frontend/rust-lib/flowy-database2/src/template.rs
- frontend/rust-lib/flowy-database2/tests/database/mock_data/board_mock_data.rs
- frontend/rust-lib/flowy-database2/tests/database/mock_data/calendar_mock_data.rs
- frontend/rust-lib/flowy-database2/tests/database/mock_data/grid_mock_data.rs
- frontend/rust-lib/flowy-folder/src/entities/view.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/flowy-folder/src/test_helper.rs
- frontend/rust-lib/flowy-folder/src/view_operation.rs
- frontend/rust-lib/flowy-server/src/local_server/impls/database.rs
1. upgrade yrs to 0.21.3
2. refactor database inline view
> chore: bump appflowy collab

- .github/workflows/flutter_ci.yaml
- frontend/appflowy_flutter/integration_test/desktop/database/database_test_runner_1.dart
- frontend/appflowy_flutter/integration_test/desktop/database/database_test_runner_2.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_1.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_2.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_3.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_4.dart
- frontend/appflowy_flutter/integration_test/desktop/first_test/first_test.dart
- frontend/appflowy_flutter/integration_test/desktop/grid/grid_test_runner_1.dart
- frontend/appflowy_flutter/integration_test/desktop/uncategorized/uncategorized_test_runner_1.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_1.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_2.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_3.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_4.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_5.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_6.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_7.dart
- frontend/appflowy_flutter/integration_test/desktop_runner_8.dart
- frontend/appflowy_flutter/integration_test/runner.dart
- frontend/appflowy_flutter/macos/Runner.xcodeproj/project.pbxproj
- frontend/appflowy_flutter/pubspec.lock
Use 8 runners temporarily, as adding more runners will increase the total cost.
---
> feat: run integration tests on multiple runners

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-user/src/services/data_import/appflowy_data_import.rs
> chore: ignore invalid database when import appflowy data

- frontend/appflowy_flutter/integration_test/desktop/document/document_with_date_reminder_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> chore: update appflowy_editor version

- .github/workflows/flutter_ci.yaml
- .github/workflows/rust_ci.yaml
> test: fix ci

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
> chore(flutter_desktop): improve title and heading appearance

- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
> fix(flutter_desktop): add forgotten call to update text cell

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/af_dropdown_menu_entry.dart
> chore: drop down menu conforms to design

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
- frontend/appflowy_flutter/test/widget_test/confirm_dialog_test.dart
- frontend/appflowy_flutter/test/widget_test/date_picker_test.dart
- frontend/appflowy_flutter/test/widget_test/test_material_app.dart
on supports the primary action for now, does not support keyboard navigation with arrow keys and tab
---
> feat(flutter_desktop): press enter to confirm a dialog

- frontend/appflowy_flutter/lib/mobile/application/mobile_router.dart
- frontend/appflowy_flutter/lib/mobile/application/notification/notification_reminder_bloc.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart
- frontend/appflowy_flutter/lib/mobile/presentation/editor/mobile_editor_screen.dart
- frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/notification_item.dart
- frontend/appflowy_flutter/lib/plugins/document/document.dart
- frontend/appflowy_flutter/lib/plugins/document/document_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
- frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
https://github.com/user-attachments/assets/9c509b21-2bfc-4d1b-ac96-dc5079c4d3ff
---
> feat: scroll to block after selecting notification item

- frontend/appflowy_flutter/integration_test/desktop/document/document_inline_page_reference_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/link_to_page_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/referenced_database_menu_item.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
~~- [ ] tests~~
https://github.com/user-attachments/assets/7a0d1666-749d-439e-9973-a19ec1ffadca
---
> feat: enable link to database in slash menu

- frontend/appflowy_flutter/lib/mobile/presentation/notifications/mobile_notifications_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/child_page_transaction_handler.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/editor_transaction_service.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/mention_transaction_handler.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
- frontend/appflowy_flutter/lib/workspace/presentation/notifications/notification_dialog.dart
- frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_button.dart
- frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_item.dart
- frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_view.dart
> fix: reminder bugs/changes

- frontend/appflowy_flutter/integration_test/desktop/document/document_with_date_reminder_test.dart
Use `find.descendant` to find the text field instead of using specific time.
---
> fix: date reminder test

- frontend/appflowy_flutter/lib/workspace/application/menu/sidebar_sections_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
- frontend/appflowy_flutter/lib/workspace/application/workspace/workspace_service.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-ai-pub/src/cloud.rs
- frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
- frontend/rust-lib/flowy-folder/src/entities/view.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/flowy-folder/src/view_operation.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/chat.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/folder.rs
> chore: remove view desc

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/turn_into_option_action.dart
- frontend/appflowy_flutter/pubspec.lock
> fix: do not rely on getIt in turnIntoBlock

- frontend/appflowy_flutter/test/widget_test/date_picker_test.dart
> test: fix date picker tests

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/Cargo.toml
- frontend/rust-lib/flowy-database2/src/services/database/database_observe.rs
> chore: fix database view event

- frontend/appflowy_flutter/integration_test/desktop/database/database_cell_test.dart
- frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_with_date_reminder_test.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/date_picker/mobile_date_picker_screen.dart
- frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/date_cell_editor_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_day.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/date.dart
- frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/tab_bar_header.dart
- frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_style_maps/desktop_board_card_cell_style.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_text_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/date_cell_editor.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/appflowy_date_picker_base.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/desktop_date_picker.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/mobile_date_picker.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/date_picker_dialog.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/date_time_text_field.dart
- frontend/appflowy_flutter/test/bloc_test/grid_test/cell/date_cell_bloc_test.dart
- frontend/appflowy_flutter/test/widget_test/date_picker_test.dart
- date picker refactor
- automatically select current time
- add hint text
- row card icon alignment issue
- untitled database view issue
- calendar new event radius
- tests
---
> chore: launch review 0.7.3

- frontend/rust-lib/flowy-ai/Cargo.toml
- frontend/rust-lib/flowy-ai/src/local_ai/local_llm_resource.rs
- frontend/rust-lib/flowy-core/Cargo.toml
> chore: remove local ai watch on windows and linux

- frontend/appflowy_web_app/cypress.config.ts
- frontend/appflowy_web_app/src/application/slate-yjs/command/index.ts
- frontend/appflowy_web_app/src/application/slate-yjs/utils/applyToSlate.ts
- frontend/appflowy_web_app/src/application/slate-yjs/utils/slateUtils.tsx
- frontend/appflowy_web_app/src/application/slate-yjs/utils/yjsOperations.ts
- frontend/appflowy_web_app/src/application/types.ts
- frontend/appflowy_web_app/src/components/editor/__tests__/behavior/TabBehavior.cy.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/toggle-list/ToggleList.tsx
- frontend/appflowy_web_app/src/components/editor/components/leaf/formula/FormulaLeaf.tsx
- frontend/appflowy_web_app/src/components/editor/components/leaf/mention/MentionPage.tsx
- frontend/appflowy_web_app/src/components/editor/components/toolbar/selection-toolbar/actions/Align.tsx
- frontend/appflowy_web_app/src/components/editor/components/toolbar/selection-toolbar/actions/Heading.tsx
- frontend/appflowy_web_app/src/components/editor/shortcut.hooks.ts
- frontend/appflowy_web_app/src/components/error/NotFound.tsx
- frontend/appflowy_web_app/src/components/view-meta/ViewMetaPreview.tsx
> feat: support tab and shift+tab on range

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
- frontend/appflowy_flutter/lib/workspace/application/sidebar/billing/sidebar_plan_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
- frontend/resources/translations/en.json
> fix: 0.7.3 improvements

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_shortcuts.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/domain/domain_item.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/appflowy_flutter/test/unit_test/document/shortcuts/toggle_list_shortcut_test.dart
- frontend/resources/translations/en.json
> fix: align the namespace and toggle shortcuts

- frontend/appflowy_web_app/src/pages/AcceptInvitationPage.tsx
> fix: modified invitation page text

- frontend/appflowy_flutter/lib/startup/tasks/file_storage_task.dart
- frontend/rust-lib/flowy-ai/src/local_ai/local_llm_resource.rs
- frontend/rust-lib/flowy-storage-pub/src/storage.rs
- frontend/rust-lib/flowy-storage/src/manager.rs
- frontend/rust-lib/flowy-storage/src/sqlite_sql.rs
- frontend/rust-lib/flowy-storage/tests/multiple_part_upload_test.rs
> chore: send notification for file upload state

- frontend/appflowy_flutter/integration_test/desktop/document/document_block_option_test.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_4.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/option_button.dart
> fix: block option interceptor

- frontend/appflowy_flutter/windows/runner/flutter_window.cpp
- frontend/appflowy_flutter/windows/runner/main.cpp
- frontend/appflowy_flutter/windows/runner/win32_window.cpp
- frontend/appflowy_flutter/windows/runner/win32_window.h
https://github.com/AppFlowy-IO/AppFlowy/issues/6677
---
> fix: application window is not visible on Windows

- frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/date_cell_editor_bloc.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_textfield.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/appearance/desktop_appearance.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/appflowy_date_picker_base.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/desktop_date_picker.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/reminder_selector.dart
- frontend/appflowy_flutter/test/bloc_test/grid_test/cell/date_cell_bloc_test.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_awareness.rs
requires https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/336
- When toggling end date aka is range option, the focused day of the calendar doesn't immediately change to the selected date. (no tests)
- Checklist item alignment issue due to visual density changes (no tests)
- Fix reminders not working at all (tests added)
- Fix reminder not being able to be updated twice (tests added), see collab PR and date_cell_bloc_test.dart
https://github.com/user-attachments/assets/ec5e88f3-c083-4a0d-9e2a-21af31a8d1b4
- fix a small ui mishap where the date time text field gets updated too quickly
---
> fix: v0.7.3 additional launch review session issues

- CHANGELOG.md
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart
- frontend/resources/translations/en.json
> chore: bump version 0.7.3

- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart
> fix: hidden group name overflow

- .github/workflows/mobile_ci.yml
- frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
- frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/6768
---
> Support uploading webp

- .github/workflows/rust_ci.yaml
- frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/collaborative_workspace_test.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
**before**
https://github.com/user-attachments/assets/96e55982-64bc-4343-af14-d12fe2a3e6e0
**after**
https://github.com/user-attachments/assets/28238fbe-e26f-4d71-9481-22e0569e710d
---
> feat: optimize the workspace menu loading speed

- frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_4.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_toolbar_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/font/customize_font_toolbar_item.dart
> feat: optimize the font menu speed

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_upload_menu.dart
> fix: mobile file upload menu

- frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/mobile_date_picker.dart
> fix(mobile): selecting date from cupertino date widget resets time

- frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/change_name_and_icon_test.dart
- frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/collaborative_workspace_test.dart
- frontend/appflowy_flutter/integration_test/mobile_runner_1.dart
- frontend/appflowy_flutter/integration_test/shared/workspace.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
- frontend/rust-lib/flowy-ai/src/local_ai/watch.rs
> fix: launch 0.7.4 review issues on desktop

- frontend/appflowy_web_app/src/components/_shared/more-actions/MoreActions.tsx
- frontend/appflowy_web_app/src/components/publish/header/RightMenu.tsx
> fix: add template button to publish page

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_user_invalid_message.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
> fix: ai chat error message background color

- frontend/appflowy_flutter/integration_test/mobile/cloud/document/publish_test.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/more_bottom_sheet.dart
- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space_menu.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/create_workspace_menu.dart
- frontend/appflowy_flutter/lib/plugins/shared/share/share_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
- frontend/resources/translations/en.json
https://github.com/user-attachments/assets/30175f77-139d-4617-96e4-853d3262f547
---
> feat: support editing path name on mobile

- frontend/appflowy_flutter/integration_test/desktop/document/document_title_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
> fix: cannot paste text into the title of the doc

- frontend/appflowy_web_app/src/application/database-yjs/selector.ts
- frontend/appflowy_web_app/src/application/types.ts
- frontend/appflowy_web_app/src/assets/date.svg
- frontend/appflowy_web_app/src/assets/reminder_clock.svg
- frontend/appflowy_web_app/src/components/_shared/image-render/ImageRender.tsx
- frontend/appflowy_web_app/src/components/database/components/board/card/Card.tsx
- frontend/appflowy_web_app/src/components/database/components/header/DatabaseRowHeader.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/callout/CalloutIcon.tsx
- frontend/appflowy_web_app/src/components/editor/components/leaf/mention/MentionDate.tsx
> fix: add new row cover

- frontend/appflowy_flutter/lib/workspace/application/settings/file_storage/file_storage_listener.dart
- frontend/appflowy_flutter/lib/workspace/application/sidebar/billing/sidebar_plan_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_toast.dart
- frontend/resources/translations/en.json
- frontend/rust-lib/flowy-document/tests/document/util.rs
- frontend/rust-lib/flowy-error/src/code.rs
- frontend/rust-lib/flowy-error/src/errors.rs
- frontend/rust-lib/flowy-storage-pub/src/chunked_byte.rs
- frontend/rust-lib/flowy-storage-pub/src/storage.rs
- frontend/rust-lib/flowy-storage/src/file_cache.rs
- frontend/rust-lib/flowy-storage/src/manager.rs
- frontend/rust-lib/flowy-storage/src/notification.rs
- frontend/rust-lib/flowy-storage/src/uploader.rs
- frontend/rust-lib/flowy-storage/tests/multiple_part_upload_test.rs
> chore: fix upload file limit

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_editor_style.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
accompanying pr: https://github.com/AppFlowy-IO/AppFlowy-Plugins/pull/24
NOTE: this pr doesnt work with the line number feature. trying to do so will raise an assertion
---
> feat: wrap code block code

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/event-integration-test/src/lib.rs
- frontend/rust-lib/event-integration-test/src/user_event.rs
- frontend/rust-lib/event-integration-test/tests/document/af_cloud_test/file_upload_test.rs
- frontend/rust-lib/flowy-core/src/config.rs
- frontend/rust-lib/flowy-core/src/integrate/server.rs
- frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs
- frontend/rust-lib/flowy-core/src/integrate/user.rs
- frontend/rust-lib/flowy-document/src/event_handler.rs
- frontend/rust-lib/flowy-document/src/manager.rs
- frontend/rust-lib/flowy-document/tests/document/util.rs
- frontend/rust-lib/flowy-server-pub/src/native/af_cloud_config.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/file_storage.rs
- frontend/rust-lib/flowy-server/src/af_cloud/server.rs
- frontend/rust-lib/flowy-storage-pub/src/chunked_byte.rs
- frontend/rust-lib/flowy-storage-pub/src/cloud.rs
- frontend/rust-lib/flowy-storage-pub/src/storage.rs
- frontend/rust-lib/flowy-storage/src/manager.rs
- frontend/rust-lib/flowy-storage/src/sqlite_sql.rs
- frontend/rust-lib/flowy-storage/src/uploader.rs
- frontend/rust-lib/flowy-storage/tests/multiple_part_upload_test.rs
> chore: delete upload task when upload size exceed limit

- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_bloc.dart
> chore: only fetch billing info when current user is the workspace owner

- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/animated_chat_list.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
> chore: re-add chat message animations

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
closes #6796 
If the URL block is a local file path, open it using OpenFilex.
---
> fix: macOS error 50 on uploading files

- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_loading.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
pulls commits out of #6851
---
> chore: minor ai chat improvements

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_ai_message_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_stream.dart
> fix: loading message hot fix

- frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_full_field_editor.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/text_robot.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart
- frontend/appflowy_flutter/lib/startup/tasks/app_window_size_manager.dart
- frontend/appflowy_flutter/test/unit_test/document/text_robot/text_robot_test.dart
> fix: multiple select menu display issue

- frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/built_in_page_widget.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
> fix: built in database height issue

- frontend/appflowy_flutter/ios/Runner/Info.plist
> fix: add camera permission for iOS

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/ai_writer_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/ask_ai_action_bloc.dart
- frontend/appflowy_flutter/test/unit_test/document/text_robot/markdown_text_robot_test.dart
> fix: unable to render code block in ai writer block

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_welcome_page.dart
> fix(mobile): lost initial scroll position on welcome page

- frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_attachment_item.dart
> fix: mobile camera android permission

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_list.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/_shared_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_shortcuts.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/appflowy_flutter/test/unit_test/document/shortcuts/toggle_list_shortcut_test.dart
- frontend/scripts/code_generation/language_files/generate_language_files.cmd
closes https://github.com/AppFlowy-IO/AppFlowy/issues/6881
---
> fix: pressing enter on a collapsible list toggle adds an additional new line

- frontend/appflowy_web_app/src/application/types.ts
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/SimpleTable.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/SimpleTableCell.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/SimpleTableRow.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/index.ts
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/simple-table.scss
- frontend/appflowy_web_app/src/components/editor/components/element/Element.tsx
- frontend/appflowy_web_app/src/components/editor/components/table-container/TableContainer.tsx
- frontend/appflowy_web_app/src/components/editor/editor.scss
- frontend/appflowy_web_app/src/components/editor/editor.type.ts
> feat: support simple table

- CHANGELOG.md
- frontend/appflowy_flutter/integration_test/desktop/document/document_with_simple_table_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_style_operation.dart
- frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_delete_operation_test.dart
- frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_duplicate_operation_test.dart
- frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_insert_operation_test.dart
- frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_style_operation_test.dart
- Revamped the simple table UI
- Added support for capturing images from camera on mobile
- Improved markdown rendering capabilities in AI writer
- Fixed an issue where pressing Enter on a collapsed toggle list would add an unnecessary new line
- Fixed an issue where creating a document from slash menu could insert content at incorrect position
> chore: release version 0.7.6

- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_metadata.dart
> feat: open ai response url source in browser

- .github/workflows/docker_ci.yml
- .github/workflows/tauri2_ci.yaml
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/SimpleTableCell.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/SimpleTableRow.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/simple-table.scss
> fix: simple table width

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
> fix: initial ai chat load

- frontend/appflowy_flutter/lib/core/helpers/url_launcher.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/more_bottom_sheet.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_media_cell.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_media_cell.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_util.dart
- frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
- frontend/appflowy_flutter/lib/user/application/auth/af_cloud_auth_service.dart
- frontend/appflowy_flutter/lib/util/share_log_files.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/ai/plugin_state_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_manage_data_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/theme_upload/theme_upload_learn_more_button.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/interactive_image_toolbar.dart
- frontend/appflowy_flutter/test/unit_test/url_launcher/url_launcher_test.dart
- frontend/resources/translations/en.json
> fix: unable to open local file using afLaunchUrl function

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/src/manager.rs
- frontend/rust-lib/flowy-database2/src/services/calculations/controller.rs
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
- frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
- frontend/rust-lib/flowy-database2/src/services/share/csv/export.rs
> chore: fetch rows by chunk size

- frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
Don't use forEach to test the widgets, as it may cause random failures.
---
> fix: image tests

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_mention_page_bottom_sheet.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_mention_page_menu.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
> feat(flutter_mobile): improve appearance of mention page selector

- frontend/resources/translations/de-DE.json
Describe the changes you have conducted here
Preview the messages on https://inlang.com/github.com/uxadax/AppFlowy .
Translated sentences from English to German
> Update translations german

- frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/color_option_action.dart
- frontend/appflowy_flutter/test/unit_test/document/option_menu/block_action_option_cubit_test.dart
> feat: support multiple blocks operation

- frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart
> test: attempt to fix flaky test

- frontend/appflowy_flutter/integration_test/desktop/document/document_find_menu_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/find_and_replace/find_and_replace_menu.dart
solves #6955
https://github.com/user-attachments/assets/cca77a69-2cb3-4f53-8c9b-9b28104d7aec
---
> fix: Esc not working for Find-Replace menu(#6955)

- frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
- frontend/appflowy_flutter/ios/Runner/Runner.entitlements
Register deep links for appflowy.io/appflowy.com domains to enable opening app from the website, or redirect to the google play store or app store.
---
> feat: support universal link / app link on mobile

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
> fix(flutter_desktop): cannot copy ai response with ctrl c

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_control_cubit.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_mention_page_bottom_sheet.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_mention_page_menu.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
- frontend/appflowy_flutter/lib/workspace/application/view_title/view_title_bar_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
- mention popup height match design
- adding while scrolling through mention page popup
- don't add @ and restart creating mention when already in the middle of one
- hide orphan views from mention page
- arrow navigation wrap mention page popup breaks bloc
---
> fix: launch review issues 0.7.8

- frontend/appflowy_web_app/src/application/types.ts
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/SimpleTable.hooks.ts
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/SimpleTable.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/SimpleTableCell.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/SimpleTableRow.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/const.ts
- frontend/appflowy_web_app/src/components/editor/components/blocks/simple-table/simple-table.scss
> fix: simple table bugs

- frontend/rust-lib/flowy-core/src/deps_resolve/chat_deps.rs
- frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
- frontend/rust-lib/flowy-folder-pub/src/query.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
@LucasXu0, this doesn't affect anything on existing features so I'm merging this.
---
> fix: AI chat initial rag_ids

- frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_math_equation_test.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_page_test.dart
- frontend/appflowy_flutter/integration_test/desktop/document/document_with_simple_table_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/visual_drag_area.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/option_actions.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/numbered_list/numbered_list_icon.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_more_action.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_map_operation.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_style_operation.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_row_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_backspace_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_command_extension.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_enter_command.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> fix: simple table issues

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_control_cubit.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
chatting with spaces currently not supported, hence this PR
---
> chore: filter out spaces from mention page

- frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_image.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/inline_math_equation/inline_math_equation.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_border_builder.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/image_provider.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/interactive_image_toolbar.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> feat: support readonly table

- .github/workflows/android_ci.yaml.bak
- .github/workflows/ios_ci.yaml
- .github/workflows/release.yml
- .github/workflows/rust_coverage.yml
- .github/workflows/tauri_ci.yaml
- .github/workflows/tauri_release.yml
- CHANGELOG.md
- codemagic.yaml
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/scripts/docker-buildfiles/Dockerfile
- frontend/scripts/install_dev_env/install_ios.sh
- frontend/scripts/install_dev_env/install_linux.sh
- frontend/scripts/install_dev_env/install_macos.sh
- frontend/scripts/install_dev_env/install_windows.sh
- frontend/scripts/makefile/env.toml
- update version 0.7.8
- update appflowy editor and appflowy editor plugin version
---
> chore: bump version 0.7.8

- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/build-tool/flowy-codegen/src/dart_event/dart_event.rs
- frontend/rust-lib/dart-ffi/src/lib.rs
- frontend/rust-lib/flowy-database2/src/services/group/group_builder.rs
- frontend/rust-lib/flowy-folder/src/entities/parser/trash/trash_id.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
- frontend/rust-lib/lib-dispatch/src/module/module.rs
- frontend/rust-lib/rust-toolchain.toml
> chore: bump client api 088

- frontend/rust-lib/flowy-database2/src/services/filter/entities.rs
- frontend/rust-lib/flowy-database2/src/services/group/configuration.rs
- frontend/rust-lib/flowy-user/src/migrations/workspace_and_favorite_v1.rs
> chore: fix clippy

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_tauri/src-tauri/Cargo.lock
- frontend/appflowy_tauri/src-tauri/Cargo.toml
- frontend/appflowy_web_app/src-tauri/Cargo.lock
- frontend/appflowy_web_app/src-tauri/Cargo.toml
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/event-integration-test/src/folder_event.rs
- frontend/rust-lib/event-integration-test/tests/folder/local_test/publish_database_test.rs
- frontend/rust-lib/event-integration-test/tests/folder/local_test/publish_document_test.rs
- frontend/rust-lib/flowy-ai/src/ai_manager.rs
- frontend/rust-lib/flowy-ai/src/notification.rs
- frontend/rust-lib/flowy-core/src/deps_resolve/chat_deps.rs
- frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
- frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs
- frontend/rust-lib/flowy-core/src/integrate/user.rs
- frontend/rust-lib/flowy-core/src/lib.rs
- frontend/rust-lib/flowy-folder-pub/src/cloud.rs
- frontend/rust-lib/flowy-folder-pub/src/query.rs
- frontend/rust-lib/flowy-folder/src/manager.rs
- frontend/rust-lib/flowy-folder/src/view_operation.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/folder.rs
- frontend/rust-lib/flowy-server/src/local_server/impls/folder.rs
1. sync selected sources when open chat
2. sync selected sources after updating selected sources
3. use first message as chat title when current title is empty
> chore: sync chat document when open chat

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
> chore: regenerate response improvements

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_select_sources_cubit.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_bottom_sheet.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_menu.dart
- frontend/rust-lib/flowy-ai/src/ai_manager.rs
> chore: adjust select sources

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_menu.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/layout_define.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
adjust input area ui
bump up ai response action button size
---
> chore(flutter_desktop): ai chat ui improvements

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
- frontend/rust-lib/flowy-ai/src/ai_manager.rs
> fix: update rag_ids not saving to local store

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_menu.dart
- frontend/rust-lib/flowy-core/src/deps_resolve/chat_deps.rs
- frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
- frontend/rust-lib/flowy-folder-pub/src/query.rs
no i18n because this is temporary
---
> chore: include parent view id in initial chat settings

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
> fix: regenerating the last answer doesn't work

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_entity.dart
> chore: remove unused ai prompt response state

- frontend/appflowy_flutter/integration_test/mobile/document/document_test_runner.dart
- frontend/appflowy_flutter/integration_test/mobile/document/simple_table_test.dart
- frontend/appflowy_flutter/integration_test/shared/common_operations.dart
- frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/shared.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_more_action.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_action_sheet.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_border_builder.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_feedback.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_reorder_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
> feat: reordering table columns and rows on mobile

- frontend/appflowy_flutter/integration_test/desktop/document/document_with_simple_table_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/align_option_action.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/option_actions.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_style_operation.dart
- frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_style_operation_test.dart
> feat: support table align on desktop

- frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_math_equation_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/inline_math_equation/inline_math_equation.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
> fix: do not wrap the inline math equation in a new line

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_drop_handler.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/draggable_view_item.dart
Relates: #6334 
https://github.com/user-attachments/assets/9808d244-7c20-41f9-b10b-bdeba9c395ee
> feat: drag view into document to link to view

- frontend/appflowy_flutter/integration_test/desktop/database/database_row_page_test.dart
- frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart
> fix(flutter_desktop): row detail checklist cell "create new" text field doesn't clear after clicking on create button

- .github/workflows/release.yml
- .github/workflows/rust_coverage.yml
- .github/workflows/tauri_ci.yaml
- .github/workflows/tauri_release.yml
> Fix build issue

- frontend/resources/translations/de-DE.json
Hi guys,
I am German native speaker and updated the translations for lang de-DE. Would appreciate a review or merge!
> Update translations de-DE

- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/align_option_action.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_more_action.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_content_operation.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_arrow_down_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_commands.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_navigation_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/_simple_table_bottom_sheet_actions.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_action_sheet.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_add_column_and_row_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_add_column_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_add_row_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_bottom_sheet.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_command.dart
> fix: simple table issues on mobile

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
> fix: try to fix message regeneration being appended instead of replaced

- frontend/appflowy_web_app/src/components/_shared/notify/InfoSnackbar.tsx
- frontend/appflowy_web_app/src/components/editor/components/blocks/database/DatabaseBlock.tsx
- frontend/appflowy_web_app/src/pages/AppPage.tsx
> fix: add tip for database page

- frontend/appflowy_web_app/src/components/editor/components/table-container/TableContainer.tsx
> fix: hover controls position

- frontend/appflowy_flutter/integration_test/desktop/settings/sign_in_page_settings_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_map_operation.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_more_action_popup.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_delete_operation_test.dart
- frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_duplicate_operation_test.dart
- frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_insert_operation_test.dart
> feat: auto-dismiss collapsed handle on Android if no interaction occurs

- frontend/appflowy_flutter/integration_test/desktop/settings/sign_in_page_settings_test.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
- frontend/appflowy_flutter/macos/Podfile.lock
> test: fix change server integration test

- frontend/appflowy_flutter/integration_test/mobile/document/document_test_runner.dart
- frontend/appflowy_flutter/integration_test/mobile/document/toolbar_test.dart
complete the test code for #7060
> chore: complete the test code for #7060

- frontend/appflowy_flutter/integration_test/mobile/document/simple_table_test.dart
- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_block_component.dart
- frontend/appflowy_flutter/macos/Podfile.lock
> fix: simple tests on mobile

- frontend/appflowy_web_app/src/application/services/js-services/http/http_api.ts
- frontend/appflowy_web_app/src/application/services/js-services/index.ts
- frontend/appflowy_web_app/src/application/services/services.type.ts
- frontend/appflowy_web_app/src/application/types.ts
- frontend/appflowy_web_app/src/components/app/workspaces/CreateWorkspace.tsx
- frontend/appflowy_web_app/src/components/app/workspaces/Workspaces.tsx
- frontend/appflowy_web_app/src/components/editor/components/toolbar/block-controls/utils.ts
- frontend/resources/translations/en.json
> feat: support create workspace on web

- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_progress_bar.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/row/accessory/cell_accessory.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/test/bloc_test/board_test/group_by_date_test.dart
helps fix ci errors that are affecting open PRs
---
> chore: bump dependencies

- frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart
> feat(flutter_desktop): add button to expand side peek

- frontend/resources/translations/ar-SA.json
Preview the messages on https://inlang.com/github.com/FakhriAz/AppFlowy .
> chore: update ar-SA translations

- frontend/appflowy_flutter/integration_test/desktop/cloud/cloud_runner.dart
- frontend/appflowy_flutter/integration_test/desktop/cloud/sidebar/sidebar_icon_test.dart
- frontend/appflowy_flutter/integration_test/shared/emoji.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_page_card.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart
- frontend/appflowy_flutter/lib/shared/icon_emoji_picker/recent_icons.dart
- frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
> fix: recent icon doesn't work in space icon (#7133)

- frontend/appflowy_flutter/lib/plugins/document/application/document_collaborators_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_drop_handler.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/visual_drag_area.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_more_action.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_more_action_popup.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart
- frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/date_reference.dart
- frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/reminder_reference.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/date_time/date_format_ext.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/draggable_item/draggable_item.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
closes #7119 
closes #5221 
---
> fix: simple table issues and locale issues

- frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/tabs_test.dart
- frontend/appflowy_flutter/lib/workspace/application/home/home_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/7148
---
> fix: filter out the space when opening new tab

- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/mobile_grid_page.dart
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/7070
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/7143
resolves https://github.com/AppFlowy-IO/AppFlowy/issues/7156
---
> fix(flutter_mobile): linked grid cannot be displayed in document

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/backspace_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-folder/src/manager.rs
> chore: bump collab commit id

- frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_settings_test.dart
- frontend/appflowy_flutter/integration_test/desktop/settings/shortcuts_settings_test.dart
- frontend/appflowy_flutter/integration_test/mobile/document/simple_table_test.dart
- frontend/appflowy_flutter/lib/workspace/application/command_palette/command_palette_bloc.dart
> fix: filter the search results by duplicate ids

- frontend/resources/translations/ja-JP.json
Our company, which is one of the Japanese companies, has added Japanese to help spread the word about this project.
> chore: update ja-JP translations

- frontend/resources/translations/ko-KR.json
Added some ko-KR translations
Preview the messages on https://inlang.com/github.com/hoyaaaa/AppFlowy .
> Update translations for ko-KR

- frontend/appflowy_flutter/integration_test/mobile/document/simple_table_test.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_style_operation.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_column_resize_handle.dart
> feat: resize table column width on mobile

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_stream.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
> fix: remove error message when sending a new message

- frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_favorites_test.dart
- frontend/appflowy_flutter/integration_test/shared/common_operations.dart
- frontend/appflowy_flutter/lib/workspace/application/favorite/favorite_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/favorite/favorite_service.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_folder.dart
Dealing with #4879
Reordering the favorites by dragging and dropping
https://github.com/user-attachments/assets/ffdcb645-3c8a-47ad-b870-b1bc3926ffcf
> feat: enable to reorder favorites

- frontend/appflowy_flutter/lib/ai/ai_client.dart
- frontend/appflowy_flutter/lib/ai/appflowy_ai_service.dart
- frontend/appflowy_flutter/lib/ai/openai_client.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/ai_writer_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/ask_ai_action_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/ask_ai_block_component.dart
- frontend/appflowy_flutter/lib/shared/appflowy_network_image.dart
- frontend/appflowy_flutter/test/bloc_test/ask_ai_test/ask_ai_action_bloc_test.dart
- frontend/resources/translations/en.json
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/event-integration-test/src/chat_event.rs
- frontend/rust-lib/flowy-ai-pub/src/cloud.rs
- frontend/rust-lib/flowy-ai/src/completion.rs
- frontend/rust-lib/flowy-ai/src/entities.rs
- frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
- frontend/rust-lib/flowy-core/src/deps_resolve/cloud_service_impl.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/chat.rs
- frontend/rust-lib/flowy-server/src/default_impl.rs
- frontend/rust-lib/flowy-user/src/services/sqlite_sql/workspace_sql.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
> chore: ai block with context

- frontend/appflowy_flutter/integration_test/desktop/command_palette/folder_search_test.dart
- frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_recent_icon_test.dart
- frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_test_runner.dart
- frontend/appflowy_flutter/integration_test/shared/emoji.dart
- frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
- frontend/appflowy_flutter/lib/shared/icon_emoji_picker/recent_icons.dart
- frontend/appflowy_flutter/lib/workspace/application/command_palette/search_result_ext.dart
- frontend/appflowy_flutter/test/unit_test/util/recent_icons_test.dart
- Fix: icons not display in search results
- Fix: skip dirty data in recent icons
> fix: icons not display in search results

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_row_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/_desktop_simple_table_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/_mobile_simple_table_widget.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_widget.dart
> chore: allow customize that forces distribute column widths

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/animated_chat_list.dart
> fix: message scrolling

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_edit_document_service.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_member_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_select_message_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_avatar.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_chat_input.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_message_selector_banner.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/message_util.dart
- frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
- frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
- frontend/resources/flowy_icons/16x/checkbox_ai_empty.svg
- frontend/resources/flowy_icons/16x/checkbox_ai_minus.svg
- frontend/resources/flowy_icons/16x/checkbox_ai_selected.svg
- frontend/resources/translations/en.json
> feat: save multiple messages to a page

- frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/share_menu_test.dart
- frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_settings_test.dart
- frontend/appflowy_flutter/lib/plugins/document/document_page.dart
- frontend/appflowy_flutter/lib/plugins/shared/share/constants.dart
The homepage url now contains an 'app' in the path. It should directly point to the published page without 'app'.
---
> fix: remove app from homepage url

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
- frontend/rust-lib/flowy-ai/src/chat.rs
> chore: trim markdown text

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_edit_document_service.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/markdown_simple_table_parser.dart
- frontend/appflowy_flutter/lib/shared/markdown_to_document.dart
- frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_markdown_test.dart
> chore: bump table column width when saving chat message to page

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
Update editor version to fix the issue of the cursor constantly blinking on Android
---
> fix: the cursor constantly blinking on Android

- frontend/appflowy_flutter/integration_test/mobile/settings/scale_factor_test.dart
- frontend/appflowy_flutter/integration_test/shared/base.dart
- frontend/appflowy_flutter/lib/mobile/presentation/setting/appearance/text_scale_setting.dart
> fix: use scale factor to zoom mobile(#7201)

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_html.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/appflowy_flutter/test/unit_test/document/html/_html_samples.dart
- frontend/appflowy_flutter/test/unit_test/document/html/paste_from_html_test.dart
> feat: support pasting table from notion, google docs and google sheet

- frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/application/document_collab_adapter.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_html.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/keyboard_interceptor/keyboard_interceptor.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/appflowy_flutter/test/unit_test/document/html/_html_samples.dart
- frontend/appflowy_flutter/test/unit_test/document/html/paste_from_html_test.dart
> chore: only enable document integrity check when enableDocumentInternalLog is on

- frontend/appflowy_flutter/lib/plugins/ai_chat/chat.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/resources/translations/en.json
> fix: launch review issues 0.8.2

- frontend/resources/translations/ar-SA.json
- frontend/resources/translations/de-DE.json
- frontend/resources/translations/en.json
- frontend/resources/translations/fr-FR.json
- frontend/resources/translations/ja-JP.json
- frontend/resources/translations/ru-RU.json
- frontend/resources/translations/th-TH.json
- frontend/resources/translations/tr-TR.json
- frontend/resources/translations/uk-UA.json
- frontend/resources/translations/vi-VN.json
> Update plan desc

- frontend/appflowy_flutter/lib/ai/service/appflowy_ai_service.dart
- frontend/appflowy_flutter/lib/ai/service/error.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_ai_message_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_stream.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
- frontend/resources/translations/en.json
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-ai/src/chat.rs
- frontend/rust-lib/flowy-ai/src/completion.rs
- frontend/rust-lib/flowy-error/src/code.rs
- frontend/rust-lib/flowy-error/src/errors.rs
- frontend/rust-lib/flowy-error/src/impl_from/cloud.rs
> chore: return ai image error

- frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
- frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
Note to reviewers:
It will be easier to review this PR going commit by commit.
The git diff for the test file looks messed up, but the only change in the most recent commit is to move some ungrouped tests into the group.
---
> chore: support pasting image links that have no file extension

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_html.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_in_app_json.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/custom_delete_command.dart
- frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
- frontend/appflowy_flutter/test/unit_test/document/html/_html_samples.dart
- frontend/appflowy_flutter/test/unit_test/document/html/paste_from_html_test.dart
~~- [ ] support copy action in block action menu~~
---
> fix: v0.8.2 launch review issues

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
- frontend/appflowy_flutter/lib/util/default_extensions.dart
> chore: restrict uploadable image types

- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_chat_input.dart
> fix(flutter_mobile): drop focus on tap outside

- frontend/appflowy_flutter/lib/workspace/application/settings/ai/settings_ai_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/model_selection.dart
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-ai-pub/src/cloud.rs
- frontend/rust-lib/flowy-ai/src/ai_manager.rs
- frontend/rust-lib/flowy-ai/src/entities.rs
- frontend/rust-lib/flowy-ai/src/event_handler.rs
- frontend/rust-lib/flowy-ai/src/event_map.rs
- frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
- frontend/rust-lib/flowy-core/src/deps_resolve/cloud_service_impl.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/chat.rs
- frontend/rust-lib/flowy-server/src/af_cloud/server.rs
- frontend/rust-lib/flowy-server/src/default_impl.rs
- frontend/rust-lib/flowy-user/src/entities/user_profile.rs
- frontend/rust-lib/flowy-user/src/entities/workspace.rs
- frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
> chore: fetch model list

- frontend/resources/translations/id-ID.json
- Update translations in `id-ID.json` to improve naturalness and accuracy.
- Adjusted 'themeMode' label to better reflect its meaning in Indonesian.
- Refined 'fontFamily' text to align with common Indonesian usage.
- Updated 'layoutDirection' and 'textDirection' translations for better clarity.
---
> i18n: Update Indonesia translation

- frontend/appflowy_flutter/lib/workspace/application/settings/ai/settings_ai_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
- frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
- frontend/rust-lib/flowy-user/src/entities/workspace.rs
> chore: fix ai page user profile refresh

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/7315
This issue is caused by the file_picker package. Do not upgrade file_picker until the issue is fixed.
https://github.com/miguelpruivo/flutter_file_picker/issues/1652
---
> fix: unable to upload file on Android devices

- frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
- frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_card.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_page.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/row/relation_row_detail.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/image_menu.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/layouts/image_browser_layout.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/resizeable_image.dart
Spaghetti code
follow up to https://github.com/AppFlowy-IO/AppFlowy/issues/7310
---
> fix: row document images

- frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
> test: fix image integration test

- frontend/resources/translations/tr-TR.json
- Added complete Turkish (tr-TR) language translation
- Complete Turkish language translation for AppFlowy
- Refined terminology and UI string consistency
- Covers all UI elements and user-facing strings
- Improves localization support for Turkish users
- Carefully reviewed and consistent terminology
- Maintained original meaning of UI strings
- Enhanced readability for Turkish users
---
> feat(i18n): Add Turkish (tr-TR) language translation

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/clipboard_service.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
To fix #7284 and #7283
https://github.com/user-attachments/assets/d19a9353-cb80-4ac6-b913-5f8a6e657f2b
---
> fix: pasting a link on iOS results in incorrect behavior

- frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
> chore: disable impeller on android

- frontend/appflowy_flutter/lib/ai/widgets/prompt_input/predefined_format_buttons.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_entity.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_change_format_bottom_sheet.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
> chore: rename predefined format enum variant

- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/ios/Runner/AppDelegate.swift
- frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/app_bar_buttons.dart
- frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/more_bottom_sheet.dart
- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_item_body.dart
- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/default_mobile_action_pane.dart
- frontend/appflowy_flutter/lib/mobile/presentation/database/board/mobile_board_page.dart
- frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_mobile_quick_action_button.dart
- frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_option_tile.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_page.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/mobile_grid_page.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/mobile_grid_header.dart
- frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> feat: lock page on mobile

- frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
- frontend/appflowy_flutter/ios/Podfile.lock
- frontend/appflowy_flutter/ios/Runner/Info.plist
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/custom_image_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
- frontend/appflowy_flutter/lib/shared/permission/permission_checker.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
closes https://github.com/AppFlowy-IO/AppFlowy/issues/7369
---
> fix: save image should not copy the image

- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
Update collab version to the latest on main branch.
---
> chore: update collab version

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_header_operation.dart
Clear the previous background color if the enable header row / header column again
---
> fix: clear background color of header row & header column

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart
- frontend/resources/translations/en.json
Added AI image label in settings plan page.
---
> chore: add ai images label

- frontend/appflowy_flutter/lib/shared/version_checker/version_checker.dart
> fix: auto updater issue on Windows

- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_message_bubble.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_text_message.dart
> chore(flutter): move other user message to end

- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_message_bubble.dart
> fix: adjust other user message alignment

- frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_detail.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/multi_image_menu.dart
> fix: error display when showing SnackBar with dialog

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/simple_columns_item.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- hide the improve writing button in the toolbar
- update appflowy_editor version
---
> fix: hide the improve writing button

- frontend/appflowy_flutter/lib/ai/service/ai_prompt_input_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_related_question.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_toolbar_item.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_entities.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
- frontend/rust-lib/flowy-ai/src/completion.rs
> Fix/launch review 0.8.5

- frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/recent_view_tile.dart
> fix(flutter_desktop): page name overflow in search

- frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
- Give a selected effect after Icon was tapped
- Hide the color picker after scrolling or an outside tapping
Before: 
https://github.com/user-attachments/assets/a0b6a333-7974-4f18-8058-2276cfb08ab6
After: 
https://github.com/user-attachments/assets/8e48cf53-ae0f-4123-81fe-ab033cdef961
---
> fix: improve the experience of using icon color picker

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_toolbar_item.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/markdown_simple_table_parser.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
> fix: ai writer issues

- frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
**light mode**
**dark mode**
---
> fix: update locked page button background color

- frontend/appflowy_flutter/lib/plugins/database/board/presentation/toolbar/board_setting_bar.dart
- frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/toolbar/calendar_setting_bar.dart
- frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/toolbar/grid_setting_bar.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/setting/database_layout_selector.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/toggle/toggle.dart
- Board: missing fullscreen icon
- Calendar: missing fullscreen icon 
---
> fix: complete the missing icons in the database

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/format_arrow_character.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/character_shortcuts.dart
- frontend/appflowy_flutter/test/unit_test/document/shortcuts/format_shortcut_test.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/7456
https://github.com/user-attachments/assets/63400a27-d032-49e0-97d4-b7a59fe1496a
---
> feat: use undo to revert the autotypograph

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/selectable_item_list_menu.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_language_selector.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
Fix #7460 
The error is caused by this issue : https://github.com/google/flutter.widgets/issues/468
---
> fix: error caused by ScrollablePositionedList(#7460)

- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- avoid infinite recusion due to cyclic dependency
---
> chore: bump collab version 45239d2

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/toolbar_extension.dart
- frontend/appflowy_flutter/pubspec.lock
> fix: consider simple table in exclude table types

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/emoji_picker_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
> feat: support custom icons for callout

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
- Import the missing header caused by the merge conflict.
---
> fix: callout block build error

- frontend/appflowy_flutter/lib/plugins/document/application/document_rules.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_column_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_column_block_width_resizer.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_column_node_extension.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_columns_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_columns_block_constant.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/custom_image_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/simple_columns_item.dart
https://github.com/AppFlowy-IO/AppFlowy/issues/7476
https://github.com/user-attachments/assets/af8322e9-1de1-45c8-8e3b-6dfba509bc8b
Debug Mode
https://github.com/user-attachments/assets/6238ef96-8ee4-4788-84d9-4f95bad37366
---
> feat: make the columns block same width width the editor

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
Increase the scroll edge offset to ensure the AI writer is visible when generating results.
https://github.com/user-attachments/assets/262a7276-7ac5-4115-a4fd-844de1dc3142
---
> feat: ensure the ai writer block visible when generating result

- frontend/appflowy_flutter/lib/ai/widgets/loading_indicator.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_related_question.dart
> fix: don't allow selection of text in related questions or loading

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/settings_ai_view.dart
- frontend/rust-lib/flowy-ai/src/local_ai/watch.rs
> chore: fix ios build

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_columns_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/quote/quote_block_component.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- Remove the layout builder in the quote block to avoid layout errors in AI Chat.
- Fix selection area color in quote block
- Fix quote block layout on mobile
---
> fix: remove layout builder in quote block

- frontend/appflowy_flutter/lib/mobile/presentation/selection_menu/mobile_selection_menu.dart
- frontend/appflowy_flutter/lib/mobile/presentation/selection_menu/mobile_selection_menu_item_widget.dart
- frontend/appflowy_flutter/lib/mobile/presentation/selection_menu/mobile_selection_menu_widget.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- slash menu unexpectedly overflows the screen
- the style of no result doesn’t match the design
- unexpected flashing effect on 2nd level menu item
- can not back to last level through backspace
---
> fix: some slash menu issues

- frontend/appflowy_flutter/lib/ai/service/ai_prompt_input_bloc.dart
- frontend/appflowy_flutter/lib/ai/widgets/prompt_input/desktop_prompt_text_field.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_ai_message_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_stream.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/ai/local_ai_setting_panel_bloc.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/ai/local_llm_listener.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/ai/plugin_state_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/local_ai_setting.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/settings_ai_view.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-ai/src/chat.rs
- frontend/rust-lib/flowy-ai/src/local_ai/controller.rs
- frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
- frontend/rust-lib/flowy-error/src/code.rs
- frontend/rust-lib/flowy-error/src/errors.rs
> chore: disable input when local ai is initializing

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_column_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/callout_node_parser.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/quote/quote_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/quote/quote_block_shortcuts.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_enter_command.dart
- frontend/appflowy_flutter/lib/startup/tasks/rust_sdk.dart
- frontend/appflowy_flutter/test/unit_test/document/turn_into/turn_into_test.dart
- support indent and outdent in quote block
- add slash menu support in callout block
- icon overlay issue in quote block
- enter key issue in callout block within table
- image block layout issue in column block
- turn nested list into callout / quote block
- quote block in table layout
- quote icon height is too short on mobile
- remove debug print
---
> fix: nested list issue in quote/callout block

- frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_select_message_bloc.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_message_selector_banner.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
> chore: disable add messages to page when chat is empty

- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-ai-pub/src/cloud.rs
- frontend/rust-lib/flowy-ai/src/chat.rs
- frontend/rust-lib/flowy-ai/src/local_ai/controller.rs
- frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
- frontend/rust-lib/flowy-core/src/deps_resolve/cloud_service_impl.rs
- frontend/rust-lib/flowy-server/src/af_cloud/impls/chat.rs
- frontend/rust-lib/flowy-server/src/default_impl.rs
> chore: support response format

- frontend/appflowy_flutter/lib/ai/widgets/prompt_input/send_button.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/resources/translations/en.json
> fix: stop generating in ai chat and writer

- frontend/appflowy_flutter/lib/plugins/ai_chat/chat.dart
- frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
- frontend/resources/translations/en.json
> chore: add tooltip for disabled select messages

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_related_question.dart
> chore: use tooltip instead of multi line for related questions

- frontend/appflowy_flutter/lib/ai/widgets/prompt_input/predefined_format_buttons.dart
> fix(mobile): image formats not shown

- frontend/appflowy_flutter/lib/ai/service/ai_prompt_input_bloc.dart
- frontend/rust-lib/flowy-ai/src/chat.rs
- frontend/rust-lib/flowy-ai/src/local_ai/controller.rs
> chore: disable chat with file

- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/init_local_ai.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/ollma_setting.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/plugin_state.dart
- frontend/resources/translations/en.json
> chore: replace guide url

- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
The new Unsplash API may not return the user info. Update the Unsplash client to resolve this issue.
---
> chore: update unsplash client

- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-ai/src/ai_manager.rs
- frontend/rust-lib/flowy-ai/src/local_ai/controller.rs
- frontend/rust-lib/flowy-ai/src/local_ai/resource.rs
- frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
> chore: local ai embed file

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_related_question.dart
- frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
> chore: set releated question height

- frontend/appflowy_flutter/lib/env/cloud_env.dart
- frontend/appflowy_flutter/lib/mobile/presentation/setting/cloud/appflowy_cloud_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/undo_redo/custom_undo_redo_commands.dart
- frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart
- frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/anonymous_sign_in_button.dart
- frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_agreement.dart
- frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_anonymous_button.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/resources/translations/en.json
closes https://github.com/AppFlowy-IO/AppFlowy/issues/7529
- fix: the workflow of switching to Local in app
- fix: unable to redo undo when the selection is null
---
> fix: the workflow of switching to Local in app

- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
> fix: message hover action flashing

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover_bloc.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
- get the latest cover information after adding the new cover.
---
> fix: first added cover might be invisible

- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_footer.dart
- Update template link URL from appflowy.io to appflowy.com
---
> chore: update template link url

- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
> chore: update commit

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
> fix: continue writing empty text case

- frontend/appflowy_flutter/lib/ai/widgets/prompt_input/desktop_prompt_text_field.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
- frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_chat_input.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_block_operations.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_entities.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_prompt_input_more_button.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_scroll_wrapper.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
- frontend/appflowy_flutter/macos/Podfile.lock
> chore: pass ai writer context

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
> chore: replace ai response every time

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
> fix: pass response format in ai writer

- frontend/appflowy_flutter/lib/ai/widgets/prompt_input/desktop_prompt_text_field.dart
- frontend/appflowy_flutter/lib/mobile/presentation/setting/ai/ai_settings_group.dart
- frontend/appflowy_flutter/lib/workspace/application/settings/ai/settings_ai_bloc.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/model_selection.dart
- frontend/appflowy_flutter/macos/Podfile.lock
- frontend/resources/translations/en.json
- frontend/rust-lib/flowy-ai/src/ai_manager.rs
- frontend/rust-lib/flowy-ai/src/entities.rs
- frontend/rust-lib/flowy-ai/src/event_handler.rs
- frontend/rust-lib/flowy-user/src/entities/user_profile.rs
> chore: remove default model name

- frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/number_cell_bloc.dart
> fix: number cell update flashes with old content

- frontend/appflowy_flutter/lib/ai/service/ai_input_control.dart
- frontend/appflowy_flutter/lib/startup/tasks/device_info_task.dart
> chore: fix incorrect local ai state

- frontend/resources/translations/uk-UA.json
> fix: correct translation inconsistencies

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_block_operations.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_scroll_wrapper.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
> fix: ai text insertion

- frontend/appflowy_flutter/lib/workspace/application/settings/ai/settings_ai_bloc.dart
> fix(mobile): settings page crashes

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
> chore: adjust ai writer popover content area

- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
To include https://github.com/AppFlowy-IO/appflowy-editor/pull/1079
---
> chore: bump editor ref

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
> fix: undo not working for toggle heading

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_prompt_input_more_button.dart
- frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
> chore: adjust popover shadows

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/desktop_floating_toolbar.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
https://github.com/user-attachments/assets/33b3397a-cdcd-42f9-ac19-e791440b0e4d
---
> fix: add animation for floating toolbar

- frontend/appflowy_flutter/integration_test/shared/settings.dart
- frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_page_card.dart
- frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/invite_members_screen.dart
- frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/workspace_setting_group.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
- frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_textfield.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/backtick_character_command.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/custom_delete_command.dart
- frontend/appflowy_flutter/lib/user/application/password/password_http_service.dart
- frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/set_new_password.dart
- frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/password/change_password.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/password/setup_password.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_shortcuts_view.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_input_field.dart
- frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/inivitation/m_invite_member_by_link.dart
- frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/textfield/textfield.dart
- frontend/appflowy_flutter/pubspec.lock
- frontend/appflowy_flutter/pubspec.yaml
- frontend/resources/translations/en.json
- frontend/rust-lib/flowy-error/src/code.rs
> fix: paste issue with the nested image

- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_drop_handler.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_drop_manager.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
- frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart
> fix: drop files duplicates

- frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart
- frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
- frontend/rust-lib/Cargo.lock
- frontend/rust-lib/Cargo.toml
- frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
requires: https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/386
---
> fix: clear cells not working
